### ISSUE TITLE
Filter for aborting the upload for whatever reason

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-s3-and-cloudfront#110]
We should add a filter to `wp_update_attachment_metadata()` for aborting the upload to S3 for whatever reason. Requested in https://wordpress.org/support/topic/excluding-a-subfolder?replies=1.

**Comment by evok3d** [comment]
Hi. has there been any progress on this?

Cheers.

**Comment by A5hleyRich** [comment]
See the `as3cf_pre_upload_attachment` filter.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L762
