### ISSUE TITLE
Plugin breaks custom header feature

### ISSUE THREAD

**Issue by fadookie** [deliciousbrains/wp-amazon-s3-and-cloudfront#129]
After installing this plugin, I was having a lot of trouble getting the custom header feature in WP 4.0 to work (under Appearance -> Header.) I went the "Or choose an image from your media library:" route. First of all, the preview image shown to crop media was a broken link. I got through the crop stage by disabling the plugin, but I re-enabled the plugin before submitting my crop so it would be uploaded to s3. Everything went wonky after this, with a broken link showing in my site's header. I finally fixed it by clearing my theme_mod options in my database and then re-selecting the header image radio button in the admin panel with the s3 plugin active.

**Comment by psorowka** [comment]
Hi, just played around with the current master and have to confirm the feature is still broken. Although the cropped image seems to be uploaded (= is on S3), the database table contains the path to the (non-existent) image in the local wp-uploads directory.

Same behaviour is for the image rotating/mirroring/cropping feature from the media library

(wordpress version 4.1)

**Comment by A5hleyRich** [comment]
Fix in version 0.9.4.
