### ISSUE TITLE
Replace media functionality

### ISSUE THREAD

**Issue by gtrout** [deliciousbrains/wp-amazon-s3-and-cloudfront#136]
We used to use the [Enable Media Replace](https://wordpress.org/plugins/enable-media-replace/) plugin and when we first migrated to Amazon S3 & Cloudfront it seemed to work, so long as versioning was enabled we chose the "Replace the file, use new filename, and update all links" option (vs. just "Replace the File"). For some reason, it no longer appears to work.  I suspect it might have to do with enabling the "Remove uploaded file from local filesystem" as we're now serving our site from multiple ec2 instances. Is there a configuration that will interoperate with the Media Replace plugin again? 

Alternatively, perhaps it would be possible to add a "Replace File on Cloudfront" functionality to this plugin that would replace a file, and attachment links, with a new version? The new file would probably have to be versioned, although incorporating automatic invalidation of the original file might allow the reuse of filenames, which might be convenient for some users.

**Comment by A5hleyRich** [comment]
We have a compatibility addon for Enable Media Replace.

https://deliciousbrains.com/wp-offload-s3/doc/enable-media-replace-addon/
