### ISSUE TITLE
Incompatibilities with WooCommerce Dynamic Gallery PRO

### ISSUE THREAD

**Issue by annoyedatanother** [deliciousbrains/wp-amazon-s3-and-cloudfront#14]
There are several issues with this plugin

1) it is not compatible with WooCommerce Dynamic Gallery PRO and image uploads fail (no error) they just fail

2) sometimes image upload simply sticks at 100% , closing window and opening media window shows the image did upload

3) when inserting an image into blog using shortcode or plugins the image always scales to full size rather than selecting correct size image

4) Periodically it fails when trying to insert image directly from S3, interface just closes for no apparent reason

I love the plugin but these issues and minor possible bugs need ironing out

I have tested it on 3 sites running different themes and versions of woocommerce and WP same issues repeat

http://wordpress.org/extend/plugins/amazon-s3-and-cloudfront/

one final note, i would rather have support via wordpress as it is easier for newbies to see and fix what issues others have, as it makes the plugin look bad if none of the support threads are answered, I for one usually ignore plugins if the support threads go unanswered as this gives the impression the plugin developer does not care, it was only after posting the support thread I noticed yo prefer github, but that means I have yet another support forum to join adding to the extensive list I have to remember if there is a problem :)

**Comment by aaemnnosttv** [comment]
Closing this one due to the age and we have had no other reports of it.
