### ISSUE TITLE
 Empty Space Used in network subsite dashboard

### ISSUE THREAD

**Issue by gofas** [deliciousbrains/wp-amazon-s3-and-cloudfront#167]
I installed, configured and migrated all images successfully to aws s3.
How do i view the space used in subsites wp dashboard at a network, based on the space used in s3?

![captura de tela 2014-12-03 as 22 06 14](https://cloud.githubusercontent.com/assets/7539811/5293841/addc433e-7b60-11e4-9d61-49179dfea029.png)

**Comment by A5hleyRich** [comment]
Fixed in version 0.9.7.

**Comment by gofas** [comment]
Very cool!
Actually i use yas3fs for mount virtual uploads directory, this update made me to look again to WP Offload S3.
Thanks!
