### ISSUE TITLE
Error: Local File System

### ISSUE THREAD

**Issue by plmwebdev** [deliciousbrains/wp-amazon-s3-and-cloudfront#195]
When I save, i get this error.

There was an error attempting to access the local file system whilst checking the bucket permissions.

Any clues, please?

**Comment by sethrubenstein** [comment]
Getting the same thing in the settings panel for the plugin. Running on multsiite. Any ideas?

**Comment by polevaultweb** [comment]
Duplicate of https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/185 - is fixed in next version
