### ISSUE TITLE
NextGen media library 

### ISSUE THREAD

**Issue by soyguille** [deliciousbrains/wp-amazon-s3-and-cloudfront#199]
Hello
Your plug is working fine for me on default wordpress media library, but only with media files added with default WordPress tools.

I have discovered NextGen , sure you know is one of the most used plugins by photographers , it has lot of useful things for us , but it lacks for uploading to S3 or CDN and deleting origin files , I use a Cloud Host VPS and space is expensive.

I though that job could be done by your plug , but even if I change default galleries form NextGen to match WordPress system galleries , looks like all NextGen galleries are hidden to your plug.

It could be grate to add support compatibility to external galleries plugging , I think NextGen is the most used.

**Comment by bradt** [comment]
Have you looked at Envira Gallery? https://wordpress.org/plugins/envira-gallery-lite/

**Comment by soyguille** [comment]
Thanks for comment 
It works perfect with your plug !! 

But .....
-NO ecomerce option available , photographers need to show an sell  with download options
-NO ability to proof galleries for clients
-No multilingual , at least on lite version ( I need to sell - rent - to photographers and scalable spanish - wordpress - ecomerce solution )
-Envira needs Addon Modules even for right protect button, some modules are free like NexGen import but others need at least purchase Gold plan , thats logical but without ecomerce features or proof options, I don't thing thats a profesional target product.

I have purchased for my own pictures  business ( Sytist ) , but it is not a wordpress add-on.
Also I have purchased NextGen pro for wordpress but without plugs like yours it is not a solution by now.

Envira Gallery can be a nice tool , sure is much better coded and works nice , but is not what I need.

**Comment by soyguille** [comment]
I have asked envira to the possibility of working with external plugs , I will inform with response .

Multi language options is posible in other versions ( PO. MO )

**Comment by soyguille** [comment]
Imposible to find  e commerce photo gallery compatible with S3 Amazon, every one makes its own media folder.
I have found some woo commerce, convert photos to woo commerce products.
[Lunar](http://www.sakuraplugins.com/products-list/lunar-sell-photos-online-wordpress-photography-plugin/)

May be your next Woocommerce compatible Pro-plug could do job ?

**Comment by aaemnnosttv** [comment]
Closing this one out as this would require an integration for the pro version of Offload S3 due to the architectural changes needed to support offloading files outside the media library.
