### ISSUE TITLE
Upgraded legacy Multisite URLs do not have subsite number in them

### ISSUE THREAD

**Issue by polevaultweb** [deliciousbrains/wp-amazon-s3-and-cloudfront#200]
If a MS install created pre 3.5 has been upgraded to 3.5+, the base upload path derived from the option 'upload_path' still contains the the full site path for files, e.g `wp-content/blogs.dir/2/files`. This means that when it is removed from the `wp_upload_dir` path it will remove the subsite identifier, resulting in a generic prefix across all the sites in the network.

**Comment by bradt** [comment]
Is there an easy way to reproduce this? Can I just change the value of my 'upload_path'? I assume I need to make changes to my .htaccess as well?

**Comment by polevaultweb** [comment]
Actually you would need to install 3.4, create network then upgrade. 

> Can I just change the value of my 'upload_path'? I assume I need to make changes to my .htaccess as well?

It could work...

**Comment by bradt** [comment]
Meh, I'll stop being lazy. :)
