### ISSUE TITLE
Call to undefined method WP_Error::get() in amazon-s3-and-cloudfront.php on line 1063

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-s3-and-cloudfront#208]
To reproduce, remove AWS keys and load the settings page.

**Comment by dskvr** [comment]
I am getting this error in my nginx logs after upgrading Wordpress ... Solution was to remove this plugin from the plugins directory, force deactivating it (workaround) ... When activating again, it causes a Redirect Loop.
