### ISSUE TITLE
Replace use of key & secret key with IAM system

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-s3-and-cloudfront#21]

**Comment by arabold** [comment]
I was wondering the same thing. It would be better to use IAM roles as hard coding keys anywhere is not a good practice for production systems.

**Comment by polevaultweb** [comment]
We have added a filter to the next version currently in development that allows you to indicate IAM roles are being used, so you don't need to add your keys

**Comment by tkellen** [comment]
:+1:

**Comment by MattSurabian** [comment]
Is master stable enough to run on if one wanted to use IAM roles now?

**Comment by polevaultweb** [comment]
Not currently, but we are testing the latest release very shortly.

**Comment by MattSurabian** [comment]
Sounds great, thanks for the quick reply! Looking forward to the latest release.

**Comment by qwcode** [comment]
was this ever released?  it's unclear how to bypass configuring the keys and fallback to the role on the server?

**Comment by qwcode** [comment]
ok, I found this:   https://deliciousbrains.com/wp-offload-s3/doc/iam-roles/
