### ISSUE TITLE
Manual Image Crop Not working

### ISSUE THREAD

**Issue by dream2live** [deliciousbrains/wp-amazon-s3-and-cloudfront#210]
Hi,

I've managed to find the problem why Manual image crop doesn't seem to work, I've deactivated the S3 plug in, and it worked after.

May I ask if there's some settings i can tweak or a workaround to this?

Our company needs both plug ins to work on WP.

Our website is hk-stage.localiiz.com

**Comment by polevaultweb** [comment]
@dream2live hi, could you post a screenshot of your plugin settings and let me know steps to recreate

**Comment by polevaultweb** [comment]
Thanks for the details @dream2live, just to be clear is it this plugin you are using? https://wordpress.org/plugins/manual-image-crop/

**Comment by dream2live** [comment]
@polevaultweb yup that's correct! If i disable the S3 plug in, the manual crop works fine,

**Comment by noreabu** [comment]
Hope this helps: https://github.com/tomaszsita/wp-manual-image-crop/pull/55

If not, please give me feedback :)

**Comment by aaemnnosttv** [comment]
Closing this one out for now as [Manual Image Crop](https://wordpress.org/plugins/manual-image-crop/) has not been updated in over 2 years, and is currently only tested up to WP 4.3.
