### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-s3-and-cloudfront#213]
- [x] Grunt for assets
- [x] Update .pot file
- [x] Bump version in readme.txt, 
- [x] Bump version in php file header
- [x] Bump version in AWS meta global
- [x] Update required version of Amazon Web Services (`$aws_plugin_version_required`) where necessary 
- [x] Update version of supported addons where necessary in AWS meta global
- [x] Update changelog with commits for this version

**Comment by bradt** [comment]
@polevaultweb Can you take care of this please?

**Comment by polevaultweb** [comment]
NA:

- [] Update required version of Amazon Web Services (`$aws_plugin_version_required`) where necessary 
- [] Update version of supported addons where necessary in AWS meta global
