### ISSUE TITLE
Styling issue - White lines appearing in WordPress admin navigation 

### ISSUE THREAD

**Issue by s3w47m88** [deliciousbrains/wp-amazon-s3-and-cloudfront#217]
![screen shot 2015-01-11 at 10 52 56 am](https://cloud.githubusercontent.com/assets/656776/5696307/065d6b2c-9980-11e4-9a94-374bfafa737a.png)

When the Plugin is enabled it seems to load administrative wide styling (when it should only load the styles on it's own administrative page) causing white lines to appear in the navigation area on the left of the WordPress admin.

**Comment by polevaultweb** [comment]
hey @s3w47m88 that isn't actually this plugin, you have installed https://wordpress.org/plugins/aws-for-wp/. I recommend contacting the developers of that plugin.

**Comment by s3w47m88** [comment]
Bizarre! Somehow it linked me here? Must have been a bad fork. Sorry!
