### ISSUE TITLE
Wordpress Error

### ISSUE THREAD

**Issue by brandonlucius** [deliciousbrains/wp-amazon-s3-and-cloudfront#219]
Hello, I created a test cdn site before I started incorporating cdn technology into my clients' websites. The url is cdntest.brandonluciusdesigns.com. I'm getting an error stating:

"Warning: strtolower() expects parameter 1 to be string, object given in /home/content/p3pnexwpnas05_data03/83/2396483/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php on line 1132".

How can this be fixes?

Thanks

**Comment by polevaultweb** [comment]
@brandonlucius what region is your bucket in? Could you post a screenshot of your plugin settings please?

**Comment by polevaultweb** [comment]
@brandonlucius when do you see the issue, when you are visiting the plugin settings or uploading media?

**Comment by brandonlucius** [comment]
My bucket is currently in the US East region.

I've uploaded a picture of the error.

![screenshot 2015-01-14 13 15 11](https://cloud.githubusercontent.com/assets/10528061/5745570/705ab54a-9bef-11e4-8dc7-592a0daa1bc5.png)

The site is currently hosted on Wordpress under GoDaddy Managed Wordpress.

I only see the issue in the backend. Everything shows up fine on the front-end of things.

**Comment by polevaultweb** [comment]
@brandonlucius thanks for the details. Would you mind testing these versions of the plugins (AWS & AS3CF) to see if they fix your issues?

http://cl.ly/3b1W0q2d2A1W
http://cl.ly/3g1Q303M1215

**Comment by brandonlucius** [comment]
Sure, no problem.

On Thu, Jan 15, 2015 at 10:19 AM, Iain Poulson <notifications@github.com>
wrote:

> @brandonlucius <https://github.com/brandonlucius> thanks for the details.
> Would you mind testing these versions of the plugins (AWS & AS3CF) to see
> if they fix your issues?
>
> http://cl.ly/3b1W0q2d2A1W
> http://cl.ly/3g1Q303M1215
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/219#issuecomment-70111642>
> .
>



-- 

*Brandon Lucius,*
*Brandon Lucius Designs*
*1-888-470-0572*
*www.brandonluciusdesigns.com <http://www.brandonluciusdesigns.com/>*

*Partnerships & Memberships*
Bing Ads Accredited Professionals | Verify
<http://advertise.bingads.microsoft.com/en-us/training-accreditation-find-a-pro-directory?CompanyID=15319>
Constant Contact Partner | Verify
<http://www.constantcontact.com/index.jsp?pn=brandonluciusdesigns>
GoDaddy Affiliate
Google Domains Beta Tester
Google Partners Program of North America
Inbox by Gmail Beta Tester
PayPal Partner | Verify
<https://www.paypal-marketing.com/paypal/html/hosted/emarketing/partner/directory/v2/>
Spreadshirt Partner
Vendeavor Certified Partner
Vistaprint Pro Advantage Designer

*Certifications*
Bing Ads Accredited Professional | Verify
<http://advertise.bingads.microsoft.com/en-us/training-accreditation-find-a-pro-directory?MemberID=680350f1-f1c0-46f7-8779-e0e9c533ab04>
Certified Adobe Photoshop CS4 Associate
Certified Google Adwords Specialist | Verify
<https://www.google.com/partners/?hl=en-US#i_profile;idtf=106141776004128815900;>
Certified Microsoft Excel 2007 Application Specialist
Certified Microsoft PowerPoint 2007 Application Specialist
Certified Microsoft Word 2007 Application Specialist

*This email and the information it contains are confidential and may be
privileged. If you have received this email in error please notify us
immediately. You should not copy it for any purpose, or disclose its
contents to any other person. Internet communications are not secure and,
therefore, Brandon Lucius Designs does not accept legal responsibility for
the contents of this message as it has been transmitted over a public
network. If you suspect the message may have been intercepted or amended
please contact us.*

*© 2014 Brandon Lucius Designs*

**Comment by A5hleyRich** [comment]
Fixed in version 0.8.1.
