### ISSUE TITLE
Error in table prefixes in cron task to update bucket region in S3 metadata

### ISSUE THREAD

**Issue by theclue** [deliciousbrains/wp-amazon-s3-and-cloudfront#220]
I've just updated to the most up-to-date version and I now I ended up with these errors ino the log:

[14-Jan-2015 09:33:23 UTC] WordPress database error Table 'openanalytics.gb_1_7_postmeta' doesn't exist for query SELECT `post_id` as `ID`, `meta_value` AS 's3object'
AND `meta_value` NOT LIKE '%"region"%'
LIMIT 428 made by do_action_ref_array, call_user_func_array, AS3CF_Upgrade->cron_update_meta_with_region, AS3CF_Upgrade->get_attachments_without_region
FROM `gb_1_7_postmeta`
AND `meta_value` NOT LIKE '%"region"%'
WHERE `meta_key` = 'amazonS3_info'

Since 'gb_' is my table prefix, I've 7 blogs into my multisite install and I got seven of those (referring to gb_1_1_, gb1_2_, gb_1_3 and so on), I guess there is something wrong with the table prefixes.

best regards,
gabriele

**Comment by polevaultweb** [comment]
@theclue what is the value of `$table_prefix` in wp-config.php?

**Comment by theclue** [comment]
here's the line:

$table_prefix  = 'gb_';

regards,
gabriele

**Comment by bradt** [comment]
@polevaultweb Looks like this code might be running on a subsite, but only should be running at the network admin level?

**Comment by polevaultweb** [comment]
@bradt thanks for that, I was a bit stumped! Will try to recreate...

**Comment by theclue** [comment]
Sorry, I forgot to mention that the plugin is actually network activated

**Comment by polevaultweb** [comment]
@theclue yes correct, the plugin is - but I think some of our upgrade routine can be mistakenly run when visiting the dashboard of a subsite, am investigating now

**Comment by polevaultweb** [comment]
@theclue this will be fixed in the next release

**Comment by theclue** [comment]
tnx, it works like a charm!
