### ISSUE TITLE
Plugin seems to force requirement of read/write access to all buckets

### ISSUE THREAD

**Issue by jamesblackwell** [deliciousbrains/wp-amazon-s3-and-cloudfront#222]
I've tried several user policies and the only way I can get this plugin to work is when full read/write access is given to all buckets. What's wrong with a user policy like below?

```
{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets"
      ],
      "Resource": "arn:aws:s3:::*"
    },
    {
	  "Effect": "Allow",
	  "Action": "s3:*",
	  "Resource": "arn:aws:s3:::my-files"
    }
  ]
}
```

I have allowed access to list the buckets and full read/write to just a single bucket "my-files" but I receive the "S3 Policy is Read-Only" error. 

There's no way we can allow full access to all buckets, its far too insecure. Maybe I've got something wrong? But after trying a few combinations of Allow/Deny statements as well it seems that the only working solution is to give the plugin full access.  Thanks in advance for any assistance.

**Comment by polevaultweb** [comment]
Can you try
```
{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets"
      ],
      "Resource": "arn:aws:s3:::*"
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::my-files","arn:aws:s3:::my-files/*"
    }
  ]
}
```

**Comment by jamesblackwell** [comment]
Thanks, I think this looks like it's working fine now: 

```
{
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets"
      ],
      "Resource": "arn:aws:s3:::*"
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "arn:aws:s3:::my-files/*"
    }
  ]
}
```

So the difference being the trailing slash and asterisk.
