### ISSUE TITLE
get_attached_file in upload_attachment_to_s3 returning empty string when W3 Total Cache database cache is enabled.

### ISSUE THREAD

**Issue by tmoitie** [deliciousbrains/wp-amazon-s3-and-cloudfront#224]
For some reason `$file_path = get_attached_file( $post_id, true );` is returning nothing when the database cache is on and the upload is initiated from a non ajax script (specifically `acf_form` in ACF pro).

**Comment by tmoitie** [comment]
This is the line in question https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L405

**Comment by duvanmonsa** [comment]
Hello i am having same problem did you solve the error? Thank you.

**Comment by aaemnnosttv** [comment]
Closing for now as this does not appear to be a bug in Offload S3 but a consequence of using a database cache.

If W3TC-specific support is needed for this to work, it would be added in the form of an integration on the pro plugin if there was enough demand for it.
