### ISSUE TITLE
IAM Policy Scope

### ISSUE THREAD

**Issue by fritcher** [deliciousbrains/wp-amazon-s3-and-cloudfront#225]
Your IAM policy is scoped wider than it needs to be.  Recommend narrowing it down to better fit amazon accounts that have more than one site running.

i.e. I got this error:
![amazon_s3_and_cloudfront_wordpress](https://cloud.githubusercontent.com/assets/222284/6094992/5ac8166e-aefa-11e4-924b-3bd3704024b4.jpg)

but my policy is broken down into 3 pieces:  
- List All Buckets & Get bucket regions
- Allow behaviors for the bucket.
- Allow behaviors for the contents of the bucket

**Comment by polevaultweb** [comment]
Thanks @fritcher, this will be fixed in the next release

**Comment by A5hleyRich** [comment]
This issue has been rectified and will be available in the next update.
