### ISSUE TITLE
Incompatible with Axis for WordPress 1.0.2

### ISSUE THREAD

**Issue by aendrew** [deliciousbrains/wp-amazon-s3-and-cloudfront#226]
Hi there!

I'm the developer of Axis for WordPress, an interface for easily creating a multitude of charts for WordPress. We're using `wp-amazon-s3-and-cloudfront` to serve static assets, which include my Axis charts. Alas, I'm running into a weird bug wherein only the second most-recent version of a chart is uploaded to S3.

Essentially: in Axis, you create a chart in a modal window spawned via TinyMCE toolbar button, and then click a button once finished. Some AJAX stuff goes on in the background that saves the chart as a PNG on a new attachment in the media library, and an image tag is dropped into TinyMCE. The relevant bits of the AJAX callback are [here](https://github.com/times/Axis/blob/master/Axis.php#L166). 

Oddly, it seems to only update the attachment filename on the next edit/save of the chart, causing wp-amazon-s3-and-cloudfront to then push it to S3. Even more oddly, this behaviour doesn't exist locally.

Any thoughts? I'm a bit at my wit's end with this and any feedback you could give would be massively appreciated. :smile: 

Thanks!

**Comment by bradt** [comment]
Have you tried enabling the Object Versioning option in the plugin's settings?

**Comment by aendrew** [comment]
Yep, just did. Same behaviour.

**Comment by aendrew** [comment]
Let's put this a different way — as a plugin developer, how do I leverage your plugin to update images in the media library? There isn't any developer documentation AFAICT...

**Comment by aendrew** [comment]
Just reading through a few more issues — as per #7, does this mean there is currently no way for outside plugins to leverage `wp-amazon-s3-and-cloudfront`? If so, this should be clearly stated on the WP.org plugin page because the likelihood of breaking other code as a result of this is fairly substantial.

**Comment by aendrew** [comment]
The issue is [here](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L405) — instead of using the new filename supplied via the `$data` function argument, it throws that all away and grabs the existing filename from the database.

Working on a PR now...

**Comment by aendrew** [comment]
I've created a hacky workaround for the issue (replaces existing image on server and adds a timestamp to the url in TinyMCE as a cache buster) but am leaving this open in case there's a not-hacky way of leveraging `wp-amazon-s3-and-cloudfront` that I've missed.

**Comment by aaemnnosttv** [comment]
Closing this one due to the age and lack of activity. WP Offload S3 does not have it's own plugin API at this time (other than a few filters) because it is designed to interact with the core WordPress APIs as much as possible to provide the most compatible and transparent experience.

Please re-open if there is a bug with the current version of Offload S3.
