### ISSUE TITLE
Breaks EDD FES File Upload

### ISSUE THREAD

**Issue by jdriselvato** [deliciousbrains/wp-amazon-s3-and-cloudfront#229]
Seems like this works perfectly with EDD FES except if you use the File Upload field.

I've reported this to Easy Digital Download here: https://easydigitaldownloads.com/support/topic/fes-file-upload-field-not-saving-input/

We've concluded that it's this plug in is stopping the File Upload field to not save it's field. Not sure if this is a EDD issue to fix or this plug-ins issue. but wanted to report it.

To test:
1. Add the File Upload field your submission form with this plugin active.
2. Save the submission form after adding a file to the File Upload Field
3. see that the File Upload field is missing the file just uploaded (the file shows up in media library)
4. Deactivate this plugin
3. Do steps 1-3
4. The File Upload field now has the added file

**Comment by aaemnnosttv** [comment]
Closing this one out as this is an addition to our existing EDD integration that is a pro-only feature of Offload S3.
