### ISSUE TITLE
Setting the ACL Bucket?

### ISSUE THREAD

**Issue by jeffesonmaia** [deliciousbrains/wp-amazon-s3-and-cloudfront#230]
The panel has no way to set the type of acl I want to use, and I need to use private. Its remedy this?

**Comment by A5hleyRich** [comment]
Hey @jeffesonmaia, what's the need for setting the ACL to private?

**Comment by jeffesonmaia** [comment]
Hey @A5hleyRich Thanks for Reply, 
Looking after the infrastructure requested that the images were placed as private, but not explained to me why only asked.

**Comment by A5hleyRich** [comment]
Ok. It just seems strange, as the Media Library items by nature are public. For example, you can visit any item using the direct URL but you shouldn't be able to index the uploads directory (which is the behaviour we have implemented in Amazon S3 and CloudFront). Therefore, this isn't possible at the moment, and I'm not sure whether it is something we plan on adding.

**Comment by A5hleyRich** [comment]
Hey @jeffesonmaia, I've just been looking into this further and although you can't specify the ACL on bucket creation, you can specify the ACL for each individual upload.

Check out this filter: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L409

**Comment by jeffesonmaia** [comment]
Thanks, helped a lot

2015-03-24 5:23 GMT-03:00 Ashley Rich <notifications@github.com>:

> Hey @jeffesonmaia <https://github.com/jeffesonmaia>, I've just been
> looking into this further and although you can't specify the ACL on bucket
> creation, you can specify the ACL for each individual upload.
>
> Check out this filter:
> https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L409
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/230#issuecomment-85393201>
> .
>



-- 
Jeffeson Pinheiro - Programador Web
jeffeson.maia.pinheiro@hotmail.com/jeffeson.maia.pinheiro@gmail.com
+55 8589085517/+55 8597859025

**Comment by tamsky** [comment]
> Check out this filter: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L409

Here's a date-anchored link to `master` branch that reflects the intended line:

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master@%7B%22Mar%2024,%202015%22%7D/classes/amazon-s3-and-cloudfront.php#L409

**Comment by ianmjones** [comment]
You might find the example for how to use the `as3cf_upload_acl` filter in our Tweaks plugin helpful too.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/3e83234e96f67b823ae94d27385cf9603d149c0b/amazon-s3-and-cloudfront-tweaks.php#L115
