### ISSUE TITLE
Issue with plugin interfering with wp-admin/customize.php background image functionality

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#231]
When a user attempts to modify their background image they can do so no problem. After the initial upload they will see the thumbnail for the background and see the options to remove the background or change the background. In addition the theme will save the background upon viewing in a live mode.

However when returning to the customize -> background image control, instead of the the thumbnail and "remove background" being present they are not even though the background is reflected in the theme that was previously selected. ![screen shot 2015-03-20 at 2 09 08 pm](https://cloud.githubusercontent.com/assets/391043/6764068/4d46c7e8-cf5b-11e4-8ade-333b81f224d7.png)

Disabling your S3 plugins causes the issue to go away.

Not sure if this happened on the new release of your plugins or if this happened with wordpress being updated. At one point there was no issues and it worked great.

Any quick fixes to this issue? This effects all themes with the background image controls enabled.

**Comment by mrbm** [comment]
Anybody there....?

**Comment by A5hleyRich** [comment]
@mrbm This is being looked into.

**Comment by A5hleyRich** [comment]
This has been fixed in the latest development branch and will be included in the next release.

**Comment by mrbm** [comment]
I would love to test it, but when i am on github i'm seeing a development branch that is older than the master, is there a place I could try your changes out?

**Comment by A5hleyRich** [comment]
This repo is only used for issue reporting by the public. Since work on the Pro version has begun we use a private repo, which is only accessible to the development team.

**Comment by A5hleyRich** [comment]
Fixed in version 0.9.
