### ISSUE TITLE
Not working with WP Retina 2x

### ISSUE THREAD

**Issue by aidanlane** [deliciousbrains/wp-amazon-s3-and-cloudfront#233]
Hi,

WP Retina 2x and Amazon S3 and CloudFront don’t seem to be playing nicely together (even though the latter has a "Copy HiDPI (@2x) Images” option which explicitly links to WP Retina 2x).

The issue seems to stem from file versioning, which we need.

Any ideas? See below:

Retina Details

This screen displays all the image sizes set-up by your WordPress configuration with the Retina details.

Title: The Arguello Inc. Harvest Oil Platform
Full-size: 600×480
Image URL: https://www.example.com/wp-content/uploads/Oil_platform.jpeg
Image Path: https://www.example.com/wp-content/uploads/20150402123901/Oil_platform.jpeg

Size: thumbnail

The image created by WordPress is missing. The plugin will only create a retina image if the base image exists.

Normal (150×150)	Retina 2x (300×300)
	
Image URL: https://www.example.com/wp-content/uploads/./Oil_platform-150x150.jpeg
Retina URL: 
Image Path: https://www.example.com/wp-content/uploads/20150402123901/Oil_platform-150x150.jpeg
Retina Path: 

Size: medium

The image created by WordPress is missing. The plugin will only create a retina image if the base image exists.

Normal (300×240)	Retina 2x (600×480)
	
Image URL: https://www.example.com/wp-content/uploads/./Oil_platform-300x240.jpeg
Retina URL: 
Image Path: https://www.example.com/wp-content/uploads/20150402123901/Oil_platform-300x240.jpeg
Retina Path: 

Size: large

The image size 'large' could not be found. You probably changed your image sizes but this specific image was not re-build. This is not related to the retina plugin. You should probably use a plugin to re-generate the missing metadata and images.

Normal (×)	Retina 2x (0×0)
	
Image URL: 
Retina URL: 
Image Path: 
Retina Path: 

Size: post-thumbnail

The image created by WordPress is missing. The plugin will only create a retina image if the base image exists.

Normal (600×270)	Retina 2x (1200×540)
	
Image URL: https://www.example.com/wp-content/uploads/./Oil_platform-600x270.jpeg
Retina URL: 
Image Path: https://www.example.com/wp-content/uploads/20150402123901/Oil_platform-600x270.jpeg
Retina Path:

**Comment by polevaultweb** [comment]
Have you enabled the 'Remove Files From Server' option?

**Comment by aidanlane** [comment]
Yes I have, was that a mistake?



--

Aidan Lane

Director, Education Technology Lab




Faculty of Information Technology

Monash University, Room H6.80, Caulfield Campus

900 Dandenong Road, Caulfield East, VIC 3145, Australia

+61 3 9905 8471

https://www.alexandriarepository.org




CRICOS Provider: Monash University 00008C

**Comment by aidanlane** [comment]
Thanks!

**Comment by aidanlane** [comment]
Hi @polevaultweb, have you any updates? we really need to resolve this and are more than happy to donate!

**Comment by polevaultweb** [comment]
@aidanlane after investigation it looks like there would need quite a bit of work done to the WP Retina plugin to add hooks and filters so our plugin can fully integrate with it, when using the 'remove from server' option.

**Comment by aidanlane** [comment]
Really? Wouldn't correcting the Image URL to include the version go a long way to resolving the issue?
>Image URL: https://www.example.com/wp-content/uploads/Oil_platform.jpeg
>Image Path: https://www.example.com/wp-content/uploads/20150402123901/Oil_platform.jpeg

There are some `file_exists` checks that could be fixed in WP Retina though.

Btw, the 'remove from server' is kind of implicit from our system architecture anyway, as we have an ephemeral filesystem and a scalable set of nodes in the web tier.

**Comment by A5hleyRich** [comment]
No further reports. Closing

**Comment by aidanlane** [comment]
I guess the plugin has been (virtually?) rewritten since then.
I haven't dug into this again of late, but I haven't noticed any particular issues either.
Thanks :)

**Comment by noreabu** [comment]
Issue still exist for me, suggest reopening. Will put some time into it, during the next days. Any hints are welcome

**Comment by jingari** [comment]
https://deliciousbrains.com/wp-offload-s3/doc/copy-hidpi-2x-images-support/ is giving a 404, is there another place I can get information on how to continue copying @2x images to S3?

**Comment by A5hleyRich** [comment]
We retired that article because the steps outlined no longer work. It's still possible to copy the @2x images to S3, but they won't get included in srcset.

```
function wpos3_hipdi_add_hidpi_file_paths( $paths ) {
	global $as3cf;

	foreach ( $paths as $path ) {
		$paths[] = $as3cf->apply_file_suffix( $path, '@2x' );
	}

	return $paths;
}
add_filter( 'as3cf_attachment_file_paths', 'wpos3_hipdi_add_hidpi_file_paths' );
```

**Comment by ondoheer** [comment]
A5hleyRich is there a way to use the plugin with the native srcset functionality? or should we just build our own? We could help with it if needed. What is the main reason the srcset attribute is not being generated?

**Comment by A5hleyRich** [comment]
WP Offload S3 already supports native WordPress srcset. If you want to use the file sizes generated by WP Retina you will need to hook into `wp_calculate_image_srcset` and `wp_calculate_image_srcset_meta`.

**Comment by ondoheer** [comment]
Hello A5hleyRich, thanks for the quick response,

I discovered the images that had the add_image_size crop parameter set to true aren't generating the srcset attribute, it wasn't the plugin, sorry for that. It's logical, and I didn't know about it!

**Comment by avishai** [comment]
I was having a similar problem. It turns out that to get your images in WooCommerce to look great on retina displays, all you have to do is change your thumbnail settings in `WooCommerce > Settings > Products > Display` to double the intended logical resolution. For example, if your theme displays the `shop_catalog` thumbnail as `200x200`, set the dimensions in WC to `400x400`.

**Comment by ondoheer** [comment]
Yes @avishai , doing tome experiments I realised I really didin't need the retina 2x plugin, it helps, it organizes the image requirements, and it uses the @2x sintax, but wordpress can handle different density images automatically by just creating other copies of the same images on those resolutions. This solved our problem and made the template one more plugin thiner, which we love!  Thanks for the comment.
