### ISSUE TITLE
Redirecting featured image not working

### ISSUE THREAD

**Issue by SupremeMark** [deliciousbrains/wp-amazon-s3-and-cloudfront#234]
I've run into a strange issue when using this. 

I'm having no problems at all redirecting media within posts through S3 but when it comes to the featured image it doesn't seem to work.

I've set it up to remove media from the local server so I'm left with no image.

I've tried inspecting the element with Firefox and it looks like the source isn't loading.

The code where the problem lies is:

			
			
			<?php if(has_post_thumbnail()) { ?>					
				<div class="post-thumbnail<?php if($gp_settings['image_wrap'] == "Disable") { ?> thumbnail-no-wrap<?php } ?>">
					<?php if($gp_settings['post_type'] == "Video") { ?><span class="video-icon"></span><?php } ?>
					<a href="<?php the_permalink(); ?>" title="<?php the_title_attribute(); ?>">
						<?php $image = vt_resize(get_post_thumbnail_id(), '', $gp_settings['image_width'], $gp_settings['image_height'], true); ?>
						<img src="<?php echo $image['url']; ?>" width="<?php echo $image['width']; ?>" height="<?php if($image['height'] != "0") { echo $image['height']; } ?>" alt="<?php if(get_post_meta(get_post_thumbnail_id(), '_wp_attachment_image_alt', true)) { echo get_post_meta(get_post_thumbnail_id(), '_wp_attachment_image_alt', true); } else { the_title_attribute(); } ?>" />		
					</a>				
				</div><?php if($gp_settings['image_wrap'] == "Disable") { ?><div class="clear"></div><?php } ?>					
			<?php } ?>
			
			

I'm using a commercial theme so maybe it's a problem with conflicting code?

Appreciate any help. Many thanks.

**Comment by machomacho** [comment]
Hey @SupremeMark, it seems that the images need to be in your uploads folder (same disk as your app) for the image to be resized. At least that's what I'm running into with Wordpress + AquaResizer + S3 (https://github.com/syamilmj/Aqua-Resizer)

**Comment by polevaultweb** [comment]
@SupremeMark it shouldn't matter that the image has been removed from the local server. The issue I suspect is coming from the custom function `vt_resize()`. Our plugin hooks into the WordPress filter 'wp_get_attachment_url', which is used by WordPress built in functions when retrieving images and featured image. Without looking at the code for `vt_resize()` I would assume it doesn't use that filter. If that is part of your theme, I recommend talking the the theme developers.
