### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by simplyianm** [deliciousbrains/wp-amazon-s3-and-cloudfront#236]
I'm getting the following error in my console whenever I try to refresh my buckets:

```
Uncaught TypeError: undefined is not a function
```

I can't see any of my buckets either.

Thanks!

**Comment by polevaultweb** [comment]
@simplyianm are you using an IAM user to connect to AWS S3? What permissions/policy are you using?

**Comment by polevaultweb** [comment]
@simplyianm is this still happening on the latest version 0.9?

**Comment by A5hleyRich** [comment]
Fixed in version 0.9.
