### ISSUE TITLE
Dealing with private directories

### ISSUE THREAD

**Issue by enricodeleo** [deliciousbrains/wp-amazon-s3-and-cloudfront#237]
Hi everyone!
I'm (happily) using this plugin to store both private (via a Bucket Policy) and public uploads on S3. Something I noticed is that even if the plugin uploads files correctly into private directories it throws an error when it tries to retrieve it for thumbnails regeneration (of course you don't see even thumbnails but it's not a problem on my end).
Digging into the plugin itself I found that it copies files back with 
```php
// download the file from S3
$temp_file = download_url( $url  ); 
```
that is good for public files (since download_url is a download via http) but fails with private directories. What I'm suggesting here is to use the SDK to have something that works in both scenarios (private and public directories), like
```php
$temp_path = '/tmp/' . $attachment_id;
try {
  $this->get_s3client( $s3object['region'] )->getObject(
    array(
      'Bucket' => $s3object['bucket'],
      'Key' => $s3object['key'],
      'SaveAs' => $temp_path
    )
  );
}
catch ( Exception $e ) {
  return new WP_Error( 'exception', $e->getMessage() );
}
// copy the temp file to the attachments location
if ( ! $wp_filesystem->copy( $temp_path, $file ) ) {
  // fallback to url
  $file = $url;
}
// clear up temp file
@unlink( $temp_path );
```

Is it applicable? What do you think about it ?

**Comment by polevaultweb** [comment]
@enricodeleo thanks for raising this, we will investigate.

**Comment by polevaultweb** [comment]
@enricodeleo what policy are you using to make the files private? Is this not done with the plugin's ACL filter?

**Comment by enricodeleo** [comment]
@polevaultweb as I mentioned above I have a _Bucket Policy_ that recursively makes unaccessible a directory. This is the snippet:

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "DenyPublicRead",
			"Effect": "Deny",
			"NotPrincipal": {
				"AWS": "arn:aws:iam::MY_IAM_USER"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::MY_BUCKET/PATH_TO_PROTECT/*"
		},
		{
			"Sid": "AllowEverythingElse",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::MY_IAM_USER"
			},
			"Action": "s3:*",
			"Resource": "arn:aws:s3:::MY_BUCKET/*"
		}
	]
}
```

**Comment by polevaultweb** [comment]
@enricodeleo thanks for the info!

**Comment by polevaultweb** [comment]
By the way, are you not seeing issues with URLs broken in the admin area for those images?

**Comment by enricodeleo** [comment]
@polevaultweb  yes, I do, but this is not actually a problem for my purposes (using it for WooCommerce digital downloads).

**Comment by polevaultweb** [comment]
Ah ok cool - in that case you will be very interested in this https://deliciousbrains.com/preview-woocommerce-addon-amazon-s3-and-cloudfront-pro/ :)

**Comment by enricodeleo** [comment]
Yes, I am and I subscribed some weeks ago, but I was running out of time and I had to solve with the method above and apparently it works fine :)
Hopefully I'll switch to the pro version once it'll ready!

**Comment by polevaultweb** [comment]
This will be fixed in the next version, thanks for your help

**Comment by enricodeleo** [comment]
My pleasure :)
