### ISSUE TITLE
Wrong path for woocommerce uploads 

### ISSUE THREAD

**Issue by enricodeleo** [deliciousbrains/wp-amazon-s3-and-cloudfront#239]
Hi,
I just found a strange behaviour: when I upload a file as downloadable product on woocommerce everything works as expected but the file path on S3 becomes woocommerce_uploads/wooc/mm instead of woocommerce_uploads/2015/04.

Any ideas?

**Comment by A5hleyRich** [comment]
Hi enricodeleo,

This has been fixed in the latest development branch. It will be available in the next release.

**Comment by enricodeleo** [comment]
Thank you! 
Can I ask you another question? The development branch you're referring to is that here on github? Can I contribute to it? I think it could be nice to introduce the [stream wrapper](http://docs.aws.amazon.com/aws-sdk-php/guide/latest/feature-s3-stream-wrapper.html) in order to have a more transparent implementation of object saving/retrieving..
