### ISSUE TITLE
Breaks WP Import Functionality

### ISSUE THREAD

**Issue by dpegasusm** [deliciousbrains/wp-amazon-s3-and-cloudfront#240]
When using the WordPress import tool with the option to "Remove Files From Server" tuned on, the uploaded XML file is moved to the AWS S3 bucket and removed from the server preventing the import from completing because the file cannot be found to be used in subsequent steps. 

A cheap workaround is to disable the "Remove Files From Server" option when an import needs to be done but it should work without having to do this.

**Comment by polevaultweb** [comment]
@dpegasusm thanks for the heads up, we will take a look

**Comment by polevaultweb** [comment]
Thanks for the heads up, we will be addressing this in a later release

**Comment by ianmjones** [comment]
Hi @dpegasusm,

We've been trying to replicate the issue with the current version of WP Offload S3 Lite, and with WP Offload S3, but not having any luck.

Do you still see the problem with the latest version?

**Comment by A5hleyRich** [comment]
Unable to replicate. Closing
