### ISSUE TITLE
Using this plugin with WPMU Dev Upfront themes

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#241]
I have been trying to use the wpmu dev upfront theme ( please try the demo for more context its really cool: http://spirit.upfront.pro/?editmode=true )

It all works fine...until trying to add an image. The theme will attempt to resize images. Your plugin doesn't seem to play nice. I'm wondering if the fix for using cropping and resizing images will also fix the issues occurring with this group of themes.

**Comment by polevaultweb** [comment]
@mrbm have you got the setting 'Remove file from server' enabled?

**Comment by mrbm** [comment]
Yes

**Comment by polevaultweb** [comment]
In that case this issue will be fixed in the next version of the plugin in development at the moment

**Comment by mrbm** [comment]
Will the fix also be available in the free release? Also is there a basic timeline on the next release or can there be a pre-release for the issue? If you guys are having trouble with the issue i have a possible solution. 

Also I wanted to do a workaround for the theme to temporarily get around your bug, but there is no way to disable the plugin for a single sub-site in a multi-site environment, can you think of a possible workaround I can use immediately?

**Comment by polevaultweb** [comment]
@mrbm thanks for the offer but we have it covered. It will be in the free release and available soon
