### ISSUE TITLE
Is it supposed to redirect to amazon s3 when accessing the old wp-content/uploads/ urls?

### ISSUE THREAD

**Issue by andrewchen5678** [deliciousbrains/wp-amazon-s3-and-cloudfront#242]
Is it supposed to redirect from http://domain.com/wp-content/uploads/image.jpg to https://s3.amazonaws.com/bucket/wp‑content/uploads/image.jpg? Right now I am getting 404. It would be great help that I don't need to update all urls in my posts if it has such feature.

**Comment by A5hleyRich** [comment]
No, the assets aren't automatically redirected. The pro version will however automatically update the URLs within your content.
