### ISSUE TITLE
Url still using subdirectory even if set to use subdomain

### ISSUE THREAD

**Issue by andrewchen5678** [deliciousbrains/wp-amazon-s3-and-cloudfront#243]
![screenshot 2015-05-21 17 49 40](https://cloud.githubusercontent.com/assets/2096114/7762028/f0700bf2-ffe2-11e4-8e69-3d7da0434443.png)
When domain is set to "Bucket name as subdomain", it is still showing https://s3.amazonaws.com/bucket-name/wp‑content/uploads/photo.jpg instead of http://bucket-name.s3.amazon.com/…

**Comment by A5hleyRich** [comment]
Unable to replicate this. Please could you provided us with your full settings screen and any active plugins that you have installed.

**Comment by andrewchen5678** [comment]
Working now.
