### ISSUE TITLE
How to Get S3 URL Right Away

### ISSUE THREAD

**Issue by icecast** [deliciousbrains/wp-amazon-s3-and-cloudfront#244]
I can display images in posts because they use attachments, but cannot display images that are stored in post meta fields.

Does Amazon S3 plugin RETURN the S3 URL after upload? How can I get the S3 URL right away?

**Comment by polevaultweb** [comment]
Once you upload an image via the media uploader, if you then edit the image the S3 URL is displayed.

**Comment by mikejolley** [comment]
@polevaultweb what about with a call to `wp_handle_upload`?

**Comment by polevaultweb** [comment]
Hi @mikejolley, if you are programatically doing the upload and you know the attachment ID of the newly created attachment, you would need to first update the meta data (to trigger our hooks) and then you can do something like this:

```php
$data = array( 'whatever...' );
wp_update_attachment_metadata( $attach_id, $data );

global $as3cf;
$s3_url = $as3cf->get_attachment_url( $attach_id );
```

Out of curiosity, what is your use case for this?

**Comment by mikejolley** [comment]
@polevaultweb  We have an 'file' type field in our custom forms which uploads the image via wp_handle_upload and then stores the URL to the resource as postmeta. We don't use attachments.

When the user enables the option to delete the local resource when its transferred to S3, this causes 404's as we stored the original URL.

**Comment by aaemnnosttv** [comment]
Closing this one due to the age and lack of activity. A lot has changed in Offload S3 over the past few years. Feel free to re-open If you believe there to be a related bug with the current version of the plugin.
