### ISSUE TITLE
File uploaded with same name if using "wp_handle_sideload" function

### ISSUE THREAD

**Issue by thomascharbit** [deliciousbrains/wp-amazon-s3-and-cloudfront#245]
If medias are uploaded using the media_handle_sideload function, the prefilter that checks if a file with same name already exists is not run, therefore file with same name are overwitten on amazon s3.

I think both wp_handle_upload_prefilter and wp_handle_sideload_prefilter filters should be used instead.

**Comment by polevaultweb** [comment]
Thanks for the heads up, we will be addressing this in a later release

**Comment by aaemnnosttv** [comment]
Resolved in [1.1.6](https://wordpress.org/plugins/amazon-s3-and-cloudfront/#developers)
