### ISSUE TITLE
S3 Policy is Read-Only Error

### ISSUE THREAD

**Issue by awall25** [deliciousbrains/wp-amazon-s3-and-cloudfront#246]
I've tried everything I can to get this setup and am completely stuck.

The user for the account has Administrator access and everything tests out in the policy simulator.

I can manually upload a file into the bucket and then view it on Cloudfront, but for whatever reason I can't get the plugin to work.

Any help would be much appreciated!

**Comment by polevaultweb** [comment]
@awall25 are you using an IAM user? If so, can you post the policy you are using. Could you also post a screenshot of the settings screen for the plugin?

**Comment by A5hleyRich** [comment]
No further reports. Closing
