### ISSUE TITLE
Not working anymore with current version of Amazon Webservices

### ISSUE THREAD

**Issue by FlorianZy** [deliciousbrains/wp-amazon-s3-and-cloudfront#247]
Hello,

I got the following Error after installing it by today.

"Amazon S3 and CloudFront has been disabled because it will not work with the version of the Amazon Web Services plugin installed. Amazon S3 and CloudFront 0.9 or later is required. Update Amazon S3 and CloudFront to the latest version
You can deactivate the Amazon S3 and CloudFront plugin to get rid of this notice."

Any Suggestions?

**Comment by polevaultweb** [comment]
@FlorianZy version 0.9 is being released very soon, apologies for this.

**Comment by polevaultweb** [comment]
@FlorianZy you can manually fix that for now by editing line 28 of amazon-web-services.php and setting the version 0.9 back to 0.8.2

**Comment by A5hleyRich** [comment]
@FlorianZy The update has been pushed.
