### ISSUE TITLE
US Standard shows blank image

### ISSUE THREAD

**Issue by gerikg** [deliciousbrains/wp-amazon-s3-and-cloudfront#248]
When you create a new bucket and pick US Standard as a location.  Then you upload an image to your Media section it comes up blank.

WordPress: 4.2.2
Web Server: Apache
PHP: 5.6.10
MySQL: 5.5.36-34.2-log
ext/mysqli: yes
WP Memory Limit: 128M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: No
WP Max Upload Size: 128 MB
PHP Time Limit: 120
PHP Error Log: php_errorlog
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1o 12 Jun 2015
cURL: Enabled
Zlib Compression: Enabled

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: On
Object Versioning: Off
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
WP Offload S3 (v0.9) by Brad Touesnard
Amazon Web Services (v0.3) by Brad Touesnard
Events Manager (v5.5.7.1) by Marcus Sykes
Functionality (v1.1) by Shea Bunge
Jetpack by WordPress.com (v3.6) by Automattic
Strictly Auto Tags (v2.9.8) by Rob Reid
Under Construction (v1.12) by Jeremy Massel

**Comment by polevaultweb** [comment]
Can you check a few things:

1. Have you got the 'Rewrite File URLs' turned on? If not, turn it on
1. Has the bucket been created
1. Does the file get created on S3

**Comment by polevaultweb** [comment]
Did you delete some info from the diagnostic log by the way?

**Comment by gerikg** [comment]
![image](https://cloud.githubusercontent.com/assets/8923164/8599767/f2fe350e-2627-11e5-8d6c-a48597d7478a.png)

Have you got the 'Rewrite File URLs' turned on? YES, it's been on.
Has the bucket been created? YES through your plugin, on Amazon too.
Does the file get created on S3? YES all sizes, like normal.
Did you delete some info from the diagnostic log by the way? YES

**Comment by polevaultweb** [comment]
@gerikg if you inspect the broken image, what is the URL of the img src?

**Comment by gerikg** [comment]
Hey sorry I've been traveling.  If I have time I'll adjust it back.  I had
to move forward for a client.
