### ISSUE TITLE
After save the bucket and options, it just go away

### ISSUE THREAD

**Issue by TiagoGouvea** [deliciousbrains/wp-amazon-s3-and-cloudfront#249]
After write the bucket name, and fill some options, I pressed "Save Changes" and it just back to the clear interface, with just the input asking me "Existing bucket name".
1) How can I know if it saved my data?
2) When will the plugin sync the files? I send a picture to gallery to check if it working and the file wasn't uploaded to s3. When it occurs?
Thanks

**Comment by TiagoGouvea** [comment]
Checking the "diagnostic info", I saw that is save the bucket name, but don't save the other configurations that I made, like "Custom Path". Diagnostic:

site_url(): http://181.224.138.135/~phormar9
home_url(): http://181.224.138.135/~phormar9
Database Name: phormar9_newsite
Table Prefix: wp_
WordPress: 4.2.2
Web Server: Apache
PHP: 5.3.29
MySQL: 5.5.32-31.0-log
ext/mysqli: no
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: pt_BR
Debug Mode: No
WP Max Upload Size: 128 MB
PHP Time Limit: 0
PHP Error Log: php_errorlog
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1m 19 Mar 2015
cURL: Enabled
Zlib Compression: Enabled

Bucket: 
Region: 
Copy Files to S3: Off
Rewrite File URLs: Off

URL Preview: http://.s3.amazonaws.com/~phormar9/wp‑content/uploads/2015/07/09191307/photo.jpg

Domain: subdomain
Enable Path: On
Custom Path: ~phormar9/wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: Off
Object Versioning: On
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
Advanced Custom Fields (v4.4.2) by Elliot Condon
Advanced Post Types Order (v2.5.4) by Nsp Code
AJAX Thumbnail Rebuild (v1.12) by junkcoder
WP Offload S3 (v0.9) by Brad Touesnard
Amazon Web Services (v0.3) by Brad Touesnard
Formulário de contato 7 (v4.2.1) by Takayuki Miyoshi
Facebook Page Promoter Lightbox (v3.2) by Arevico
Meta Box (v4.5.5) by Rilwis
Posts 2 Posts (v1.6.4) by scribu
Taxonomy Images (v0.8.0) by Michael Fields
Category Order and Taxonomy Terms Order (v1.4.4) by Nsp-Code
WordPress Related Posts (v3.5.4) by Zemanta Ltd.
WP Instagram Widget (v1.5.1) by Scott Evans

**Comment by A5hleyRich** [comment]
Are any errors logged to the console when saving the errors?

https://developer.chrome.com/devtools/docs/console#errors-and-warnings

Can you enable WP_DEBUG and WP_DEBUG_LOG to see if any errors are sent to the debug.log file?

https://codex.wordpress.org/Debugging_in_WordPress

**Comment by TiagoGouvea** [comment]
Sorry friend. After that I saw that all plugins was unable to save data...
I import the database again and all back to work.
Are a bug not related to your plugin. 
Thanks for reply!

**Comment by A5hleyRich** [comment]
Cheers for the heads up @TiagoGouvea
