### ISSUE TITLE
Not uploading custom image sizes

### ISSUE THREAD

**Issue by ezekg** [deliciousbrains/wp-amazon-s3-and-cloudfront#251]
I have ~5 custom image sizes added with `add_image_size()`, and none of them seem to get stored on S3. Only the full size image gets stored. I've attempted to regenerate thumbnails, but nothing seems to be working.

As it is right now, I can't use this plugin because we use these sizes for responsive images. It would be great if somebody could help me solve this issue, because I would really like to take advantage of S3.

Is there some setting that I'm missing? ETA on the pro version?

**Comment by polevaultweb** [comment]
Where are those `add_image_size()` being added, your theme or a plugin?

Can you paste the code, including surrounding function and hook so I can try to recreate please

**Comment by ezekg** [comment]
Just in the theme's `functions.php` file.

```php
add_image_size( "product-large", 900 );
add_image_size( "product-small", 200 );
```

Tried inside of the `after_setup_theme` as well. Everything works if I disable the plugin and regenerate the thumbnails, of course.

**Comment by ezekg** [comment]
Sorry, after digging in more, this was an issue with not having `php-gd` installed, so no images were being generated at all. Closing the issue. For future reference (for anybody else), this can be resolved by installing via:

```bash
sudo yum install gd gd-devel php-gd
sudo service httpd restart
```

**Comment by polevaultweb** [comment]
Thanks for the update @ezekg

**Comment by ezekg** [comment]
Np. Sorry for the issue. Should have dug in deeper first. Is there an ETA on the pro version? Or is it still up in the air?
