### ISSUE TITLE
Error fetching buckets: SyntaxError: Unexpected token N

### ISSUE THREAD

**Issue by nitin-patil-cm** [deliciousbrains/wp-amazon-s3-and-cloudfront#252]
S3 and cloudFront plugin was working fine previously. but when i uploaded files by  pasting new offloadS3 plugin folder it's not working. I'm continuously getting "Error fetching buckets: SyntaxError: Unexpected token N" while creating new bucket and also browsing existing buckets. 

![screenshot_1](https://cloud.githubusercontent.com/assets/13364306/8818131/cd8f545a-305a-11e5-8e74-54dd9ac532a7.png)

Now my previous version also not working please do suggest something to recover from this issue.
I have checked my S3 bucket and IAM user setting no issue from AWS side.
I have opened almost all port of Web servers.

**Comment by A5hleyRich** [comment]
If you enable WP_DEBUG_LOGS https://codex.wordpress.org/WP_DEBUG#WP_DEBUG_LOG are any errors logged?

**Comment by polevaultweb** [comment]
@nitin-patil-cm did [this](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/252#issuecomment-123712994) show any errors?

**Comment by nitin-patil-cm** [comment]
It was due to NAT instance, it was not well configured in my case. But the issue was WordPress server was not connected to internet and hence it was showing "Unexpected Token N"

**Comment by polevaultweb** [comment]
@nitin-patil-cm Thanks for the update
