### ISSUE TITLE
Setting end-point

### ISSUE THREAD

**Issue by TittoProof** [deliciousbrains/wp-amazon-s3-and-cloudfront#253]
hi, is possible to define different end-points?
actually it seem only default end points like s3.amazonaws.com is enabled, but i like to set up different endpoint.
Thanks

**Comment by A5hleyRich** [comment]
You can't change the default endpoints but you can add a custom domain. If you create a CNAME within your DNS control panel that points to S3, you can use a subdomain like so:

http://cdn.domain.com

**Comment by TittoProof** [comment]
Uhm interesting!... 
and how i can setup a custom domain inside the plugin?
Thank you!

**Comment by A5hleyRich** [comment]
![offload s3 site 1 wordpress](https://cloud.githubusercontent.com/assets/1422996/8848498/9c93dd64-312f-11e5-9072-3c7500148796.png)

**Comment by TittoProof** [comment]
I've not this screen! maybe wrong version? I need to obtain pro version?

**Comment by A5hleyRich** [comment]
No this functionality exists in the free version.

**Comment by TittoProof** [comment]
![screenshot 2015-07-23 12 54 33](https://cloud.githubusercontent.com/assets/13465885/8848736/098f3972-313a-11e5-8ba9-a3889fb0963e.png)
I see this..... i can't create or select any bucket because my storage service is in other endpoint

**Comment by A5hleyRich** [comment]
What do you mean by different storage provider?

**Comment by TittoProof** [comment]
my storage provider is Seeweb (with endpoint seewebstorage.it) and not Amazon directly. Here my problem with this plugin...

**Comment by A5hleyRich** [comment]
Does this service link to an S3 bucket?

**Comment by TittoProof** [comment]
yes I think.... I can reach buckets using cyberduck and i can use it by JetS3t Java API... both with endpoint customized

**Comment by A5hleyRich** [comment]
I'm not familiar with how Seeweb works, but if it's linked to an S3 bucket you should be able to select it within WP Offload S3 and then point the custom domain to seewebstorage.it.

However, as this is a non-default setup we can't provided further support.

**Comment by TittoProof** [comment]
thank you
