### ISSUE TITLE
Patch to make "Same as request" work for SSL and non SSL sites using relative URL's

### ISSUE THREAD

**Issue by darrenwwilliams** [deliciousbrains/wp-amazon-s3-and-cloudfront#257]
In `get_url_preview` lines 339-344 use this:

```php
if ( $this->get_setting( 'ssl' ) == 'request' ) {
    $url = '//' . $domain . '/' . $path . $suffix;
}
else {
    $url = $scheme . '://' . $domain . '/' . $path . $suffix;
}
```

And in `get_attachment_url`

lines 1124 to 1129:

```php
if ( $this->get_setting( 'ssl' ) == 'request' ) {
    $url = '//' . $domain_bucket . '/' . $file;
}
else {
    $url = $scheme . '://' . $domain_bucket . '/' . $file;
}
```

**Comment by polevaultweb** [comment]
@darrenwwilliams what version of the plugin are you using? As of 0.9, we have consolidated the SSL code to https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L924

**Comment by darrenwwilliams** [comment]
Using the latest version, and yes I saw this code. The problem is that it does not seem to inherit the request type correctly using this technique on sites with mixed SSL/Non SSL (for example when you have an online store) and with the global option:

define('FORCE_SSL_ADMIN', true);

Relative URL’s using this technique let Wordpress decide the protocol to server instead and makes sure that your SSL certificate does not warn you about mixed protocols when you land on SSL pages.

cheers, darren

________________________
Darren Williams, Ph.D.

**Comment by aaemnnosttv** [comment]
Sites with mixed content are becoming less and less common these days. It's better to go HTTPS site-wide where possible.

You can always strip the scheme from S3 URLs using the `as3cf_get_attachment_url` filter.
