### ISSUE TITLE
Editing on image not working on newly fresh wordpress set up. No plugins added

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#258]
Just spun up a new digital ocean wordpress droplet, have 0 other plugins enabled accept Amazon Web Services and WP Offload S3

Seems to work great except when I got edit the image it shows a missing image.

If I inspect the missing image, the file path is:

/wp-admin/admin-ajax.php?action=imgedit-preview&_ajax_nonce=e5aa67e277&postid=34&rand=69888

Which when I put into a url of browser with domain returns:  -1

I am running apache server and not sure what is causing me this problem...driving me crazy. What is weird is that I have your plugin working great on another multi-site however running NGINX. Perhaps there is another library I need to install on the server? Not seeing any error messages.

Thanks for the help.

Happy to private message you the server if you want to see for yourself. 

I have it working perfectly on another multi-site with nginx, so I am wondering perhaps if apache wasn't tested...?  I first tested this site as a single site set up, then a multi-site set up.

Database Name: wordpress
Table Prefix: wp_
WordPress: 4.2.3 Multisite
Web Server: Apache/2.4.7 (Ubuntu)
PHP: 5.5.9-1ubuntu4.11
MySQL: 5.5.44-0ubuntu0.14.04.1
ext/mysqli: yes
WP Memory Limit: 64M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: No
WP Max Upload Size: 1 MB
PHP Time Limit: 30
PHP Error Log: syslog
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled

Bucket: XXXXXX
Region:
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: http://XXXXXX.s3.amazonaws.com/wp‑content/uploads/2015/07/28074942/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
SSL: http
Remove Files From Server: On
Object Versioning: On
Far Future Expiration Header: On
Copy HiDPI (@2x) Images: On

Active Plugins:
WP Offload S3 (v0.9) by Brad Touesnard
Amazon Web Services (v0.3) by Brad Touesnard

**Comment by mrbm** [comment]
built another server in NGINX...and it works...so....I am wondering if you guys are testing are testing with apache....there might be an issue with the apache worth reviewing.

**Comment by A5hleyRich** [comment]
Yes we test on Apache and it works fine. Does editing an image work with the plugin disabled?

Does enabling WP_DEBUG show an error?

**Comment by mrbm** [comment]
yes editing without the plugin enabled works if the image was uploaded.

WP_DEBUG does not show an error. In my production server i use nginx so I don't really care about apache...but I have this vps spun up, would you like access to it before I kill it. Maybe it could help, perhaps there is a requirement that needs to be noted in the instructions that you aren't aware of at the moment. Let me know.

**Comment by A5hleyRich** [comment]
If you don't mind giving us access that would be appreciated. Could you send the login details to nom[ at ]deliciousbrains.com

**Comment by mrbm** [comment]
Happy to help, I'll send you an email right now.

**Comment by A5hleyRich** [comment]
Credentials received. I'll take a look this evening.

Cheers!

**Comment by A5hleyRich** [comment]
Issue due to not having the php5-gd module installed.

**Comment by mrbm** [comment]
Thanks ashley. So the amazon webservices plugin does a check for the cURL library. Perhaps an error message stating the php5-gd library is not installed would be good place where the broken image is. Thoughts?

**Comment by A5hleyRich** [comment]
I'm not sure this check is required. The php5-gd library is a requirement of WordPress core in order to use the image editing functionality. If you disable WP Offload S3 you still wouldn't be able to use the image editor.
