### ISSUE TITLE
Incorrect information about minimal WP version required

### ISSUE THREAD

**Issue by AlexeyDemidov** [deliciousbrains/wp-amazon-s3-and-cloudfront#259]
In readme it states that minimal Wordpress version required is 3.5 but actually it requires at least version 3.7 as it uses function wp_get_sites which was introduced in 3.7 according to documentation https://codex.wordpress.org/Function_Reference/wp_get_sites

**Comment by A5hleyRich** [comment]
Thanks for the heads up @AlexeyDemidov. We'll get that amended.

**Comment by polevaultweb** [comment]
@AlexeyDemidov of course we recommend using the most up to date version of WordPress as best practice :smile:
