### ISSUE TITLE
Debugging an error between your plugin and WPMU Dev Upfront Spirit Theme

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#260]
Been playing with this front-end editing capable theme:

http://premium.wpmudev.org/project/spirit/ 
http://demo.upfront.pro/spirit/?editmode=true (demo of it in use)

Trying to figure out where the problem is. I remember there was an issue with your plugin before version 0.9 that made the background image feature when customizing a theme break. Version .9 fixed it!

Wondering if a similar modification to your plugin needs to be made to make this work or if the issue is with the theme not properly using the wordpress methods, or if I could modify the theme to use your methods.

What is working:
When editing with the theme it works great for uploading photos and creating the thumbnails (try inserting an image on the demo site). 

With S3 enable, when inserting an image with this theme it seems to work but upon viewing it, it is looking to call on a file that it has modified the name for (appends the dimensions and an ID).  In addition it seems to attempt to process the image any time it needs to modify the name, size cropping ect.

There is a moment where this plugin "re-processes" the image. At which point I assume it grabs the original image, modifies it locally and then re-uploads the image back. And I am guessing that is where the issue is.

It works fine for inserting background in the theme which requires no re-processing.

The Wordpress S3 Plugin is working well with other themes and works for cropping and other image manipulations without issue just not this one.

Would love your input, thanks! 

PS: I have also set up a separate dedicated nginx server with only your amazon s3 plugin and this theme.

**Comment by aaemnnosttv** [comment]
Closing this one due to the age and lack of activity. Most theme and plugin compatibility issues are due to not using the correct core WordPress functions and methods.

A lot has changed in Offload S3 over the past few years. Feel free to re-open If you believe there to be a related bug with the current version of the plugin.
