### ISSUE TITLE
The path in url gets some random suffix value

### ISSUE THREAD

**Issue by shreychaturvedi123** [deliciousbrains/wp-amazon-s3-and-cloudfront#261]
Hi The url preview i am getting is 
http://propguide.s3‑ap‑southeast‑1.amazonaws.com/2015/08/05124231/photo.jpg
but it should be http://propguide.s3‑ap‑southeast‑1.amazonaws.com/2015/08/photo.jpg

why it is appending 05124231 or random path in url, is there any way i can disable it?

**Comment by ianmjones** [comment]
@shreychaturvedi123 That random number (which isn't actually random by the way) is added to the path when you have Object Versioning turned on (it's on by default). If you look in your settings you'll see a slider you can switch to "Off" and then save the settings if you don't need this feature.

It's worth reading the info that is linked to near the setting before turning it off though, it's quite a useful setting to have turned on.

**Comment by shreychaturvedi123** [comment]
Thanks
