### ISSUE TITLE
Uploads to S3 Don't Show as Storage Used 

### ISSUE THREAD

**Issue by MarcWoodyard** [deliciousbrains/wp-amazon-s3-and-cloudfront#262]
I have WP Offload S3 and Amazon s3 and CloudFront plugins network activated on my multisite network. I'm able to upload, edit, and delete files. But my upload quota stays at 0.00 MB no matter how much I upload. Is this normal?

**Comment by polevaultweb** [comment]
Hi @ModMarc this is being fixed for a future release

**Comment by ModMarc** [comment]
Glad to hear. Thanks

-----Original Message-----

**Comment by A5hleyRich** [comment]
Resolved in 0.9.7.
