### ISSUE TITLE
Does not work with Nginx! 

### ISSUE THREAD

**Issue by winnie-nz** [deliciousbrains/wp-amazon-s3-and-cloudfront#266]
I currently use Nginx Vps running on easyengine. 
i cant get s3offload working on it 

do you know what i should do ? to make it working on nginx ? 
i dont know how to access config files on nginx either to test .? 
will be great if you could help 
thankj you

**Comment by A5hleyRich** [comment]
WP Offload S3 is tested on Nginx, so this is more than likely a config issue. Please can you be more specific as to what exactly isn't working?

Can you try editing your wp-config.php file to replace this line -

define( 'WP_DEBUG', false );

With these lines -

define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false); 
This means that any errors are logged to `/wp-content/debug.log', because some errors are not visible on screen. Can you then try the process again and then post the debug.log?

More details about that at http://codex.wordpress.org/Editing_wp-config.php#Debug

**Comment by MattyLB** [comment]
I have the same problems on my EC2 server setup with nginx via easy engine
and the URL rewrites to s3 do not work.

I'll try the debug log when I'm near my computer, but it might be worth
your group creating a test site using EE from rtcamp.com and you'll see
what we mean.

Most likely it's in how the nginx or fast cache config defines rewrites or
caching.

**Comment by winnie-nz** [comment]
hi thank you for your update please let me know if your able to solve this
problem .
of using easy engine with s3 offload.

i also wanted to know how i can access wordpress sub directories in ee to
access wp-content or some php file .
i am new to nginx vps and ee all together .
thank you very much

**Comment by A5hleyRich** [comment]
I've tested this with EasyEngine and everything works as expected. All rewrites are performed at a PHP level, therefore using Nginx should have no adverse effects.

As mentioned above, please could you provide the diagnostic information found under the support tab.

Could you also take a look at this WordPress thread, which is the only issue we are currently aware of that results in broken images:

https://wordpress.org/support/topic/broken-images-41?replies=6

A fix for this issue will be available shortly.

**Comment by espellcaste** [comment]
Just to reinforce, I'm using the plugin on Nginx without any problem. Working normally.

**Comment by winnie-nz** [comment]
thank you for all your updates i tired this plugin but was not able to get
s3 with cloudfront working so i tried another one which does the same job
but i had to make some changed in nginx config file and after that i was
able to use it as well
i will test this plugin again and see if i could use it with nginx via
easyengine on ubuntu
my website which is working fine right now with nginx with cdn s3 for media
umakant.info

**Comment by A5hleyRich** [comment]
Thanks for the updates. I would be interested in knowing what Nginx directives you've changed if you get chance to test WP Offload S3 again.

**Comment by winnie-nz** [comment]
for now i am not using s3 offload plugin as i tired it and it did not work
so i tried this one its called "tcS3 " which also did not work so i asked a
developed what to do with nginx server running easyengine he asked me to do
the below and it was working fine

this is on ubuntu running easyengine ie nginx


/var/www/mywebsite/conf/nginx/

This can be done by using the following command:

nano /var/www/mywebsite/conf/nginx/aws.s3.conf

In that file, paste the code you need into it, save and run the following
command.

nginx -t

If it says the following, you're good to go.

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok

nginx: configuration file /etc/nginx/nginx.conf test is successful

Otherwise, feel free to reply with any errors and I'd be happy to help you
figure it out.


than “ee stack restart”

other things i have done extra i have made dns entry on cloudflare.com so i
take link from cloudfont aws into it with orange cloud enabled
so its running on back of two cdns now (only media)
and it works well and very fast



On Tue, Sep 22, 2015 at 7:19 PM, Ashley Rich <notifications@github.com>
wrote:
>
> Thanks for the updates. I would be interested in knowing what Nginx
directives you've changed if you get chance to test WP Offload S3 again.

**Comment by A5hleyRich** [comment]
Tested with both Nginx and EasyEngine, unable to replicate. No further reports, closing for now.
