### ISSUE TITLE
Error fetching buckets — SyntaxError: JSON Parse error: Unexpected identifier "Warning"

### ISSUE THREAD

**Issue by FranciscoCG** [deliciousbrains/wp-amazon-s3-and-cloudfront#269]
When clic Browse existing buckets,  enter it manually, or create a new one, got this error.

AWS credentials verified, I deactivated all plugins. but I got the same error.

site_url(): http://test.eshops.cl/beta
home_url(): http://test.eshops.cl/beta
Database Name: ********
Table Prefix: wp_
WordPress: 4.2.4
Web Server: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.11
PHP: 5.5.9-1ubuntu4.11
MySQL: 5.5.44-0ubuntu0.14.04.1-log
ext/mysqli: yes
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: Yes
WP Max Upload Size: 20 MB
PHP Time Limit: 600
PHP Error Log: 
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled

Bucket: 
Region: 
Copy Files to S3: Off
Rewrite File URLs: Off

URL Preview: http://.s3.amazonaws.com/beta/wp‑content/uploads/2015/08/20002831/photo.jpg

Domain: subdomain
Enable Path: On
Custom Path: beta/wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: Off
Object Versioning: On
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
WP Offload S3 (v0.9.3) by Brad Touesnard
Amazon Web Services (v0.3.1) by Brad Touesnard

**Comment by A5hleyRich** [comment]
The 'Unexpected identifier "Warning"' suggests that PHP is issuing a warning, which is being prepended to our AJAX requests.

If you disable the display of debug messages does this issue go away? Replace:

```
define('WP_DEBUG', true);
```

With:

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```

The debug.log file will also show what's causing the issue.

**Comment by polevaultweb** [comment]
@FranciscoCG is this still happening? Did you add the code to generate the debug log?

**Comment by A5hleyRich** [comment]
No further reports. Closing
