### ISSUE TITLE
PHP memory exhausted after 0.9.4 update

### ISSUE THREAD

**Issue by thomascharbit** [deliciousbrains/wp-amazon-s3-and-cloudfront#272]
Hi,

Since updating to 0.9.4 admin is unreachable, having PHP memory errors.

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 7 bytes)

It seems to be related to AS3CF_Upgrade_File_Sizes, when i comment it from Amazon_S3_And_CloudFront::init it works again.

For info I have more than 100,000 medias in library, all removed from the local server.

Anyway to fix this?

**Comment by A5hleyRich** [comment]
What's your WP_MEMORY limit currently set to?

**Comment by FreshFlesh** [comment]
128Mb.

I guess loading all attachments at once from DB leads to memory exhaustion

**Comment by A5hleyRich** [comment]
Is this a multisite install? If so, how many blogs do you have?

Can you try increasing the WP_MEMORY_LIMIT to 256?

**Comment by FreshFlesh** [comment]
No multisite, i raised the PHP limit to 256M and got same error:
> [28-Aug-2015 11:01:56 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /srv/www/purple.dev/current/web/wp/wp-includes/functions.php on line 4614

**Comment by FreshFlesh** [comment]
The issue seems to come from the foreach loop in `get_attachments_removed_from_server`.

```php
	function get_attachments_removed_from_server( $prefix, $count = false, $limit = null ) {
		$all_attachments = $this->get_s3_attachments( $prefix, $limit );
		$attachments     = array();

		foreach ( $all_attachments as $attachment ) {
			if ( ! file_exists( get_attached_file( $attachment->ID, true ) ) ) {
				$attachments[] = $attachment;
			}
		}

		if ( $count ) {
			return count( $attachments );
		}

		return $attachments;
	}
```

If i remove it and simply sets `$attachments = $all_attachments;` it works.

Can 115,000 `file_exists()` calls in a row be a problem?

**Comment by A5hleyRich** [comment]
Yep, you are right, we need to limit the amount of calls. If you change:

`$all_attachments = $this->get_s3_attachments( $prefix, $limit );`

to:

`$all_attachments = $this->get_s3_attachments( $prefix, 1000 );`

Does it resolve the issue?

**Comment by FreshFlesh** [comment]
Yes, it works.

**Comment by A5hleyRich** [comment]
Thanks for your assistance on this, I'll get a patch put together.

In the meantime if you leave the limit to `1000` it should allow the upgrade routine to run.

**Comment by FreshFlesh** [comment]
Thank YOU for your help, i will wait for the patch to deploy to our production server.

**Comment by FreshFlesh** [comment]
Any update for the patch?

**Comment by FreshFlesh** [comment]
Hi @A5hleyRich, do you know when a patch will be available? Thanks!

**Comment by polevaultweb** [comment]
Our patch is a little way off at the moment, so I recommend manually patching it on your prod site for speed.

**Comment by aaemnnosttv** [comment]
This is an old issue and should no longer be an issue with more recent versions of the plugin. If you're still experiencing problems, please reopen.
