### ISSUE TITLE
Related to #263 - initial crop results in broken image for customizer header controls

### ISSUE THREAD

**Issue by nerrad** [deliciousbrains/wp-amazon-s3-and-cloudfront#273]
The work done in #263 fixes the ability to get back the cropping stage when using the customizer header feature of WordPress.  However after the initial cropping action, the displayed selected header in the customizer control and the preview is broken (using the path to the image on the server which is no longer present).

Here's a short screencast demonstrating: https://monosnap.com/file/osf9CcGTcZJ4ru0e6kke8Q7oWTS8Zu

The video demonstrates the initial result after cropping.  However, if I reload the customizer the cropped image will display in the "previously uploaded" container and then I can select it and it will work as expected.

So it's just on the initial ajax response from the cropping action that the image isn't updating correctly in the dom.  Instead of the amazon url being used, the url to the wp-content/uploads directory for the image is being used (which is invalid because I have things set to automatically remove images from the local directory after upload to amazon).

**Comment by A5hleyRich** [comment]
This is an issue with WordPress core. We're submitted a patch to get this fixed but it can take some time to get them approved.

https://core.trac.wordpress.org/ticket/33319

**Comment by nerrad** [comment]
Yeah I figured.  I had done some preliminary investigation to see if I could implement a fix but noticed the same thing.  Was hoping you folks were aware of another method to get around that static url that I wasn't.  Nice to know about the trac ticket tho, I'll keep it on my radar.

**Comment by nerrad** [comment]
Hey just a heads up that it looks like @polevaultweb 's patch got committed to WP core for WP4.4 :)

**Comment by A5hleyRich** [comment]
:tada:

**Comment by polevaultweb** [comment]
hey, thanks for the pushing on that ticket @nerrad!

**Comment by nerrad** [comment]
Thanks for setting it up for easier pushing :)

**Comment by A5hleyRich** [comment]
Resolved in version 0.9.7.
