### ISSUE TITLE
Compatibility with WPML - Image URL not updated correctly for other languages

### ISSUE THREAD

**Issue by yesinternet** [deliciousbrains/wp-amazon-s3-and-cloudfront#279]
Hello

I am using Wordpress, WPML (incl. WPML Media translation plugin) and Offload S3 Free, all latest versions. I also have made all necesary configuraiton for Offload S3 (using custom CNAME method).

When I upload an image to the Media library, the image is properly uploaded to S3 and after upload, it is porperly shown to the MEdia Manager with correct S3 URL

However, when I switch to other languages via WPML language switcher, the image entyr is shown in the Media manager, but the thumbnails and full image are not showing. This is becasue the image URL is not updated to the S3 URL, but it keeps the original WP URL.

Please let me know if you need any further information on this issue.

**Comment by polevaultweb** [comment]
Hi @yesinternet, we have been working on this recently and will be releasing compatibilty with WPML / WPML media soon.

**Comment by yesinternet** [comment]
Ok, this is great.
Looking forward.
Thanks
