### ISSUE TITLE
Buddypress Avatars and Cover Photos

### ISSUE THREAD

**Issue by Grendel61** [deliciousbrains/wp-amazon-s3-and-cloudfront#281]
Hi,

Moving Buddypress custom profile and group avatars as well as profile and group cover photos is going to be important this year. In the next release or two you’ll be able to upload those multi-part files from IOS that have a little motion in them. Getting some of these more static files off the server and into S3 or another solution are going to be important. 

I’d like to suggest you take a new look at it. I was attempting to run down this problem with customizations to Upload-S3, but unfortunately that approach is not going to be stable enough for me. Buddypress rewrote all of the functions to move media attachments including avatars and cover photos for groups and profiles. 

You could probably code an add-on the way you did for EDD, and it would work fine. I'd buy it if you had it.

**Comment by polevaultweb** [comment]
@Grendel61 we will certainly add it to the todo list :)

**Comment by aaemnnosttv** [comment]
Closing this one out as it will eventually come as an integration for the pro version of Offload S3 due to the architectural changes needed to support it.

**Comment by diogonborges** [comment]
any timeline predicted for this?

**Comment by aaemnnosttv** [comment]
It's a bit of an unknown as there is some prerequisite architectural changes we need to make before we can add support for this. Sooner than later though ;)

**Comment by tkyser-rodeo** [comment]
Any update? it's been years... BuddyBoss would be nice to see as well
