### ISSUE TITLE
Image link error 404 on woocommerce product translated

### ISSUE THREAD

**Issue by pietroperona** [deliciousbrains/wp-amazon-s3-and-cloudfront#282]
Hi,
now on site http://www.mpcashmere.com language base is set to Italian in wpml. My problem occurs only on certain woo commerce products in their translated version is not showing the images properly (it seems they are not present) in the base product but the images are correct. 
A real example:
- Link product displayed correctly (Italian): http://www.mpcashmere.com/shop/scatola-regalo/
- Link product does not display properly (English): http://www.mpcashmere.com/shop/gift-box/?lang=en
  Link product image in the base language is correct (using s3) while that in the translated version seems to be a link of the file locally, but on the server are not present because I keep them all on s3 ... How can I fix?

**Comment by aaemnnosttv** [comment]
The pro version of [Offload S3](https://deliciousbrains.com/wp-offload-s3/) includes a WPML integration with a Gold license or higher.
