### ISSUE TITLE
upload gzipped version of content and serve it when appropriate

### ISSUE THREAD

**Issue by tkellen** [deliciousbrains/wp-amazon-s3-and-cloudfront#283]
Are there any plans to support something like this? If no, would you be willing to discuss the implementation so a PR could be made?

**Comment by A5hleyRich** [comment]
We will be implementing gzip compression into a future version. It's pretty high on our to-do list.

**Comment by tkellen** [comment]
Awesome! Is there an issue I can track for this?

**Comment by A5hleyRich** [comment]
It's actually raised on our private repo at the moment.

**Comment by tkellen** [comment]
Has any implementation work been done? Is there anything I can do to help this land publicly?

**Comment by grappler** [comment]
@tkellen I created a small plugin that does that for svg images. Feel free to use to code. https://gist.github.com/grappler/62626ff680edc5d03453

**Comment by A5hleyRich** [comment]
@tkellen No implementation has been carried out yet. Can you clarify which content you wish to Gzip?

**Comment by tkellen** [comment]
@A5hleyRich svg was my primary use case. I'll check out your code @grappler!

**Comment by A5hleyRich** [comment]
Thanks for clarification. Please let us know how you get on with @grappler's Gist.

**Comment by grappler** [comment]
FYI - Cloudfront now supports gzip. You can now request a compressed version of the file. http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

**Comment by tkellen** [comment]
Huzzah, I saw this a few weeks ago :D

**Comment by grappler** [comment]
@tkellen I think you should still keep the issue open as the plugin does not yet define `Accept-Encoding: gzip` in the request header yet.

**Comment by A5hleyRich** [comment]
We're still adding support for gzip with S3, but we have no plans to add the `Accept-Encoding` header. Instead we will always serve the gzipped version as almost all devices in the last 10 years support gzip. Adjusting request headers with WordPress isn't really feasible because of page caching plugins.

**Comment by A5hleyRich** [comment]
Gzip compression added for supported file types.

**Comment by grappler** [comment]
@A5hleyRich In which version was support added?

**Comment by A5hleyRich** [comment]
WP Offload S3 0.9.12
