### ISSUE TITLE
Support for WP-CLI media regenerate

### ISSUE THREAD

**Issue by grappler** [deliciousbrains/wp-amazon-s3-and-cloudfront#284]
Hello,

Could you add support for the wp cli command `wp media regenerate`? Thanks :smile: 
http://wp-cli.org/commands/media/regenerate/

**Comment by polevaultweb** [comment]
:+1:

**Comment by grappler** [comment]
I think the code that would be needed would look like this:
```
if ( defined('WP_CLI') && WP_CLI ) {
	if ( ( $file = $this->copy_s3_file_to_server( $s3_object, $file ) ) ) {
		// Return the file if successfully downloaded from S3
		return $file;
	};
}
```

**Comment by grappler** [comment]
Would you be open to a PR? I ask because it seems this repo is just the distribution files of the lite version.

**Comment by A5hleyRich** [comment]
@grappler sure

**Comment by popularsizzle** [comment]
Try this:

        add_filter('as3cf_get_attached_file_copy_back_to_local', function($copy) {
                if (defined('WP_CLI')) { 
                        return true; 
                }
 
                return $copy; 
        });

**Comment by throw-111** [comment]
Try this:

    add_filter('as3cf_get_attached_file_copy_back_to_local', function($copy) {
            if (defined('WP_CLI')) { 
                    return true; 
            }

            return $copy; 
    });

**Comment by aaemnnosttv** [comment]
Thanks everyone, this is already fixed in the next release.

This issue will close automatically as soon as it's available.

**Comment by throw-111** [comment]
@aaemnnosttv is there a commit?

**Comment by aaemnnosttv** [comment]
Not on this repository unfortunately as it is only used as a release mirror.  Your workaround looks like it should do just fine until the next release is out though :)

**Comment by throw-111** [comment]
No problem.

Also is that compatibility file going to hang around?

**Comment by aaemnnosttv** [comment]
Yeah, `as3cf-plugin-compatibility.php` isn't going anywhere.

**Comment by aaemnnosttv** [comment]
Support added in v1.2 🎉
