### ISSUE TITLE
Don't use old_s3object settings when uploading

### ISSUE THREAD

**Issue by zephod** [deliciousbrains/wp-amazon-s3-and-cloudfront#286]
Hi Ashley & team,

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/amazon-s3-and-cloudfront.php#L536

This line just cost me half a day of coding :-|
I am using the regenerate_thumbnails plugin to move all our existing assets to S3. However, changing the S3 bucket and regenerating thumbnails was not working; files were not being uploaded to the new bucket. I traced it back to this line of code, which ignores the settings if the file has already been moved to S3 before (eg. in staging, to a staging bucket). My solution was to comment out the entire block, forcing the plugin to use the real DB settings every time. 

Is this an optimisation or does it do something necessary? I can't work out why it would stick to the old bucket/old region for an upload.

To be clear, there's a definite bug anyway: It will upload to the old bucket but rewrite the URL to the new bucket, so there's inconsistency. 

Thanks for reading. Hope we can make sense of this :)

**Comment by grappler** [comment]
I came across a similar bug. I changed the bucket name as I changed aws account. The problem is that the previously uploaded files have the old bucket name in the database and not the new one. So when trying to download files to the server does not work.

**Comment by aaemnnosttv** [comment]
Thanks for the report guys, but this is not a bug.  Once uploaded to a bucket, an item will stay in that bucket until removed (pro feature). Your best bet to move buckets with this plugin is to move the assets manually on S3 and perform a search replace on the media's `amazonS3_info` post meta to rename the bucket name to the new bucket. Make sure to make a backup of the DB first of course.
