### ISSUE TITLE
Progress bar for the upgrade process

### ISSUE THREAD

**Issue by grappler** [deliciousbrains/wp-amazon-s3-and-cloudfront#287]
Please could you add a progress bar to the upgrade process?

I have 26 images for which the image sizes needed to be updated and it is still running an hour later.

**Comment by A5hleyRich** [comment]
Thanks for the feedback, it's in the pipeline.

**Comment by ianmjones** [comment]
All recent releases that required upgrades included a percentage complete in their notices on the WP Offload S3 settings page.
