### ISSUE TITLE
Latest update breaks URL with resize option.

### ISSUE THREAD

**Issue by B3nCr** [deliciousbrains/wp-amazon-s3-and-cloudfront#288]
Certain image urls are being double encoded so instead of the query string`?resize=256,256` it's adding `%3Fresize%3D256%252C256` which isn't being recognised as a query string by amazon and is assumed to be part of the file name.

I updated the S3 plugin and WooCommerce at the same time so can't be sure it's not WooCommerce doing this as some images still work. Although, on the other hand, my entire media library was broken so that's not a WooCommerce feature.

**Comment by B3nCr** [comment]
Someone on the wordpress.org forum has also noticed this behaviour but like me didn't read that this needs reporting here. https://wordpress.org/support/topic/update-breaks-images

**Comment by polevaultweb** [comment]
Hey @B3nCr thanks for posting on here. Can we get your diagnostic log  so we can recreate? Also do you know what is adding the query string?

**Comment by B3nCr** [comment]
@polevaultweb diagnostic log? Is that a plugin thing or a wordpress thing? I'm still feeling my way around wordpress. 

I've reverted my environment back to the previous version. I'll create a new branch and recreate.

I was seeing the issue on resized images, thumbnails in the media library and products on the catalog page. I'm not sure what was adding the query string.

**Comment by polevaultweb** [comment]
hey @B3nCr if you go to AWS > S3 and CloudFront > Support tab, you can download the diagnostic log and post it here. Cheers

**Comment by B3nCr** [comment]
site_url(): http://localhost:8059
    home_url(): http://localhost:8059
    Database Name: ebdb
    Table Prefix: wp_
    WordPress: 4.3.1
    Web Server: Microsoft-IIS/8.5
    PHP: 5.6.0
    MySQL: 5.6.23-log
    ext/mysqli: yes
    PHP Memory Limit: 256M
    WP Memory Limit: 40M
    Blocked External HTTP Requests: None
    WP Locale: en_GB
    Debug Mode: No
    WP Max Upload Size: 8 MB
    PHP Time Limit: 300
    PHP Error Log: C:\WINDOWS\temp\PHP56_errors.log
    WP Cron: Enabled
    fsockopen: Enabled
    OpenSSL: OpenSSL 1.0.1i 6 Aug 2014
    cURL: Enabled
    Zlib Compression: Enabled
    PHP GD: bundled (2.1.0 compatible)
    Imagick: Disabled
    
    Media Files: 4
    Media Files on S3: 4
    Number of Image Sizes: 10
    
    Bucket: andrewterrygolf-content
    Region: eu-west-1
    Copy Files to S3: On
    Rewrite File URLs: On
    
    URL Preview: http://andrewterrygolf‑content.s3‑eu‑west‑1.amazonaws.com/wp‑content/uploads/2015/10/27092339/photo.jpg
    
    Domain: subdomain
    Enable Path: On
    Custom Path: wp-content/uploads/
    Use Year/Month: On
    SSL: request
    Remove Files From Server: Off
    Object Versioning: On
    Far Future Expiration Header: Off
    Copy HiDPI (@2x) Images: Off
    
    Active Plugins:
    Amazon Web Services (v0.3.3) by Delicious Brains
    Enhanced Media Library (v2.0.4.8) by wpUXsolutions
    Jetpack by WordPress.com (v3.7.2) by Automattic
    Members (v1.1.0) by Justin Tadlock
    WP Offload S3 (v0.9.7) by Delicious Brains
    WooCommerce (v2.4.8) by WooThemes
    WooCommerce Bookings (v1.7.13) by WooThemes
    WooThemes Helper (v1.5.9) by WooThemes
    Woocommerce CSV Import (v3.0.5) by Allaerd Mensonides
    Woocommerce CSV import attributes (v3.1.0) by Allaerd Mensonides
    Woocommerce CSV import variable products (v3.1.0) by Allaerd Mensonides

**Comment by B3nCr** [comment]
@polevaultweb Very strange, now that I've re-installed the plugins one by one I'm not getting the same issue

**Comment by polevaultweb** [comment]
@B3nCr as well as 'Enhanced Media Library'?

**Comment by B3nCr** [comment]
@polevaultweb That didn't get an update. S3 Offload was working before the update with that installed. It adds categories to the media items in the DB, I don't think it changes how it handles the actual files.

**Comment by polevaultweb** [comment]
@B3nCr hmm, ok so it sounds like WooCommerce adds the query string. I will investigate and get back to you. Cheers.

**Comment by B3nCr** [comment]
@polevaultweb I've just had a look through the enhanced media library php and js files and I can't find the term `resize`.

Thanks for looking into this

**Comment by B3nCr** [comment]
Is there an easy way to reverse images back from the S3 bucket to the media library?

**Comment by polevaultweb** [comment]
@B3nCr as in copy them back, or don't serve them from S3?

**Comment by B3nCr** [comment]
copy them back

**Comment by polevaultweb** [comment]
That's actually a feature of the Pro upgrade - https://deliciousbrains.com/wp-offload-s3/upgrade/ :)

**Comment by B3nCr** [comment]
It was a small enough library that I can manage it manually and be more cost effective at the moment.

I might need pro soon enough for purchasable content though I'm a bit put off by the limit on the number of items though. I'll have to see how big the media library grows to.

Does the free version have such a limit on media items?

**Comment by polevaultweb** [comment]
No limit on the free version

**Comment by A5hleyRich** [comment]
Fixed in 0.9.8

**Comment by B3nCr** [comment]
Can I re-enable the jetpack caching feature then? Thanks

**Comment by polevaultweb** [comment]
@B3nCr yep, should be fine to.
