### ISSUE TITLE
Packagist is not updated

### ISSUE THREAD

**Issue by phh** [deliciousbrains/wp-amazon-s3-and-cloudfront#289]
0.9.7 was released 3 days ago:
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/releases/tag/0.9.7

But the now version is not available on packagist:
https://packagist.org/packages/deliciousbrains/wp-amazon-s3-and-cloudfront

You could add a github service hook to notify packagist that there is an update available:
https://packagist.org/about#how-to-update-packages

**Comment by A5hleyRich** [comment]
The packagist repo isn't maintained by us so we can't add the GitHook.

Please use http://wpackagist.org/search?q=amazon-s3-and-cloudfront&type=any&search=
