### ISSUE TITLE
Support for Responsive Images in WP 4.4

### ISSUE THREAD

**Issue by grappler** [deliciousbrains/wp-amazon-s3-and-cloudfront#290]
Please could you support responsive images in WP 4.4. At the moment the URL for the other image sizes is the local URL and not the amazon url.

**Comment by A5hleyRich** [comment]
It's in the pipeline.

**Comment by elyobo** [comment]
Implemented in 0.9.10?

**Comment by polevaultweb** [comment]
@elyobo correct :)
