### ISSUE TITLE
PHP Fatal error: Call to undefined function mysql_get_server_info() with "WP DB Driver" Plugin

### ISSUE THREAD

**Issue by tkywtnb** [deliciousbrains/wp-amazon-s3-and-cloudfront#294]
I use "WP DB Driver" plugin in order to connect to MySQL with SSL.
And also I use "PDO - MySQL" as DB driver.
I got a following error when I show "S3 and CloudFront" page in 0.9.9

```
PHP Fatal error:  Call to undefined function mysql_get_server_info() in /app/user/public/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php on line 2450
```

**Comment by A5hleyRich** [comment]
Thanks for the report and PR. We'll get it merged in a future release.

**Comment by A5hleyRich** [comment]
This will be available in the next release. Thanks!
