### ISSUE TITLE
Custom domain with path

### ISSUE THREAD

**Issue by gsf** [deliciousbrains/wp-amazon-s3-and-cloudfront#297]
Great plugin! With 0.9.6 and earlier we were able to set the custom domain to `example.com/media`. Our `example.com` server then proxies from `/media/` to `https://s3.amazonaws.com/media-bucket/`. With 0.9.7 and above the slash is no longer allowed in the custom domain, so if we want to continue serving media from `example.com/media` we need to set the custom domain to `example.com`, turn on the "Path" option with `media` as the value, move all media to `media-bucket/media`, and proxy to there instead.

It isn't a terrible workaround, but it does seem silly to put everything in a `media` folder of the media bucket. Is there a reason the custom domain no longer supports a path portion?

**Comment by nmarley** [comment]
There was a path option? Came here to open an issue, moving back to TanTan since I can't specify path after year/month. Why would a custom path option be removed? It seems like it would be the most useful feature.

**Comment by A5hleyRich** [comment]
You should be able to use the `as3cf_cloudfront_path_parts ` filter for this:

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/master/amazon-s3-and-cloudfront-tweaks.php#L42

**Comment by gsf** [comment]
Great to see a fix, thanks! @karissademi @michaelck
