### ISSUE TITLE
No Upload Link In Plugin Setting

### ISSUE THREAD

**Issue by wakamin** [deliciousbrains/wp-amazon-s3-and-cloudfront#298]
Hi, I am using Wordpress 4.4. And I didn't see the upload link. I see in the video that there is a link that noticed the library needs to be upload to S3. But in my Wordpress, there is no link like that.

I already set the bucket. What's the problem? I appreciate any help.

**Comment by polevaultweb** [comment]
Can you post your diagnostic log from AWS > S3 & CloudFront > Support please

**Comment by wakamin** [comment]
Here it is

site_url(): http://www.****.com
home_url(): http://www.****.com
Database Name: ****
Table Prefix: ****
WordPress: 4.4
Web Server: nginx/1.8.0
PHP: 5.6.4-4ubuntu6.4
MySQL: 5.6.27-0ubuntu0.15.04.1
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: No
WP Max Upload Size: 8 MB
PHP Time Limit: 30
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Disabled

Media Files: 1,822
Media Files on S3: 2
Number of Image Sizes: 5

Bucket: ****
Region: us-west-2
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: http://s3‑us‑west‑2.amazonaws.com/****/20151214104743/photo.jpg

Domain: path
Enable Path: Off
Custom Path: media
Use Year/Month: Off
SSL: request
Remove Files From Server: Off
Object Versioning: On
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
Akismet (v3.1.5) by Automattic
Amazon Web Services (v0.3.4) by Delicious Brains
Autoptimize (v1.9.4) by Frank Goossens (futtta)
Better Font Awesome (v1.4.3) by MIGHTYminnow & Mickey Kay
CloudFlare (v1.3.19) by Ian Pye, Jerome Chen, James Greene, Simon Moore, David Fritsch (CloudFlare Team)
Contact Form 7 (v4.3.1) by Takayuki Miyoshi
****(Custom Plugin)! (v1.2.0) by Me
Display Widgets (v2.05) by Strategy11
EWWW Image Optimizer (v2.5.4) by Shane Bishop
Facebook Widget (v3.1) by Milap Patel
Google Webfont Optimizer (v0.2.4) by Sigurdur Gudbrandsson
Hello Dolly (v1.6) by Matt Mullenweg
Hide My WP (v5.01) by AUB Media
Jetpack by WordPress.com (v3.8.1) by Automattic
Nav Menu Roles (v1.7.4) by Kathy Darling
Next Level Cache (v0.0.9) by VerySimple
Really Simple CAPTCHA (v1.8.0.1) by Takayuki Miyoshi
S3 Image Optimizer (v.2) by Shane Bishop
Single Post Template (v1.4.4) by Nathan Rice
UpdraftPlus - Backup/Restore (v1.11.18) by UpdraftPlus.Com, DavidAnderson
WP Offload S3 (v0.9.10) by Delicious Brains
WP Super Cache (v1.4.6) by Automattic
Yoast SEO (v3.0.6) by Team Yoast

**Comment by A5hleyRich** [comment]
You don't have the Pro version of WP Offload S3 installed. Mass upload is a Pro only feature.

**Comment by wakamin** [comment]
Ah sorry I don't know about it. That's really answer the question :) thank you.
