### ISSUE TITLE
I'm not able to regenerate thumbnails if original files are deleted from wp-content directory

### ISSUE THREAD

**Issue by wujekbogdan** [deliciousbrains/wp-amazon-s3-and-cloudfront#300]
Hi,

I have deleted all the images from the `/wp-content/uploads/ direcory`. All the files have been sent to S3.

Afterwards, I've registered several image sizes (with `add_image_size()`). I wanted to regenerate thumbnails. But regenerating thumbnails keeps failing - new sizes are not created. I believe it's not regenerate thumbnails plugin fault, because I tried several plugins and wp-cli. If amazon web services plugin is disabled, regenerating thumbnails works fine.

Is it a bug or is it the way the plugin is meant to work? Do I need original files to be placed in the `/wp-content/uploads/` directory in order to regenerate sizes? If so, is there any way to regenerate images except downloading original files from S3 into `wp-content/uploads/`?

**Comment by polevaultweb** [comment]
@wujekbogdan The Regenerate Thumbnails plugin is supported, in that if your files have been removed from the server, when you run the regen, WPOS downloads them from S3 so it can be processed, then removes them again. It sounds like there is a bug with this process on your site. Can you post the diagnostic info from S3 & CloudFront > Support please.

**Comment by wujekbogdan** [comment]
```
site_url(): http://mysecretdomainname.com
home_url(): http://mysecretdomainname.com
Database Name: my_secret_database_name
Table Prefix: wp_
WordPress: 4.4.1
Web Server: Apache
PHP: 5.6.14
MySQL: 5.6.19-log
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: Yes
WP Max Upload Size: 128 MB
PHP Time Limit: 60
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1k-fips 8 Jan 2015
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled

Media Files: 355
Media Files on S3: 355
Number of Image Sizes: 28

Bucket: my-secret-bucked-name
Region: eu-west-1
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: http://mysecretamazonappname.s3‑eu‑west‑1.amazonaws.com/NEW/data/wp‑content/uploads/2016/01/13131116/photo.jpg

Domain: subdomain
Enable Path: On
Custom Path: NEW/data/wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: Off
Object Versioning: On
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
Advanced Custom Fields Pro (v5.3.2.2) by elliot condon
Advanced Custom Fields: Nav Menu Field (v2.0.0) by Faison Zutavern
Amazon Web Services (v0.3.4) by Delicious Brains
Disqus Comment System (v2.84) by Disqus 
Enhanced Media Library (v2.1.4) by wpUXsolutions
Intuitive Custom Post Order (v3.0.7) by hijiri
Regenerate Thumbnails (v2.2.6) by Alex Mills (Viper007Bond)
WP Offload S3 (v0.9.11) by Delicious Brains
Yet Another Related Posts Plugin (v4.2.5) by Adknowledge
Yoast SEO (v3.0.7) by Team Yoast
```

**Comment by jhonaker-cap** [comment]
I had a similar issue which I was able to work around by manually creating the year/month directory structure in uploads.

**Comment by A5hleyRich** [comment]
Fixed in https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/9431f5a81d5650a045b83441472297288c5654e7/classes/as3cf-plugin-compatibility.php#L663
