### ISSUE TITLE
Shows PHP Strict Warning, Declaration of AS3CF_Stream_Wrapper::register() should be compatible with Aws\S3\StreamWrapper::register(Aws\S3\S3Client $client, $protocol = 's3', Aws\CacheInterface $cache = NULL)

### ISSUE THREAD

**Issue by adeubank** [deliciousbrains/wp-amazon-s3-and-cloudfront#303]
<table class="xdebug-error xe-strict-standards" dir="ltr" border="1" cellspacing="0" cellpadding="1">
<tbody><tr><th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> Strict standards: Declaration of AS3CF_Stream_Wrapper::register() should be compatible with Aws\S3\StreamWrapper::register(Aws\S3\S3Client $client, $protocol = 's3', Aws\CacheInterface $cache = NULL) in /home/vagrant/wordpress/wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-stream-wrapper.php on line <i>3</i></th></tr>
<tr><th align="left" bgcolor="#e9b96e" colspan="5">Call Stack</th></tr>
<tr><th align="center" bgcolor="#eeeeec">#</th><th align="left" bgcolor="#eeeeec">Time</th><th align="left" bgcolor="#eeeeec">Memory</th><th align="left" bgcolor="#eeeeec">Function</th><th align="left" bgcolor="#eeeeec">Location</th></tr>
<tr><td bgcolor="#eeeeec" align="center">1</td><td bgcolor="#eeeeec" align="center">0.0005</td><td bgcolor="#eeeeec" align="right">242816</td><td bgcolor="#eeeeec">{main}(  )</td><td title="/home/vagrant/wordpress/wp-admin/admin.php" bgcolor="#eeeeec">.../admin.php<b>:</b>0</td></tr>
<tr><td bgcolor="#eeeeec" align="center">2</td><td bgcolor="#eeeeec" align="center">0.0007</td><td bgcolor="#eeeeec" align="right">243344</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/home/vagrant/wordpress/wp-load.php'</font> )</td><td title="/home/vagrant/wordpress/wp-admin/admin.php" bgcolor="#eeeeec">.../admin.php<b>:</b>31</td></tr>
<tr><td bgcolor="#eeeeec" align="center">3</td><td bgcolor="#eeeeec" align="center">0.0010</td><td bgcolor="#eeeeec" align="right">244160</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/home/vagrant/wordpress/wp-config.php'</font> )</td><td title="/home/vagrant/wordpress/wp-load.php" bgcolor="#eeeeec">.../wp-load.php<b>:</b>37</td></tr>
<tr><td bgcolor="#eeeeec" align="center">4</td><td bgcolor="#eeeeec" align="center">0.0012</td><td bgcolor="#eeeeec" align="right">245928</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/home/vagrant/wordpress/wp-settings.php'</font> )</td><td title="/home/vagrant/wordpress/wp-config.php" bgcolor="#eeeeec">.../wp-config.php<b>:</b>59</td></tr>
<tr><td bgcolor="#eeeeec" align="center">5</td><td bgcolor="#eeeeec" align="center">0.2289</td><td bgcolor="#eeeeec" align="right">3236472</td><td bgcolor="#eeeeec">do_action(  )</td><td title="/home/vagrant/wordpress/wp-settings.php" bgcolor="#eeeeec">.../wp-settings.php<b>:</b>392</td></tr>
<tr><td bgcolor="#eeeeec" align="center">6</td><td bgcolor="#eeeeec" align="center">0.2518</td><td bgcolor="#eeeeec" align="right">3641512</td><td bgcolor="#eeeeec"><a href="http://www.php.net/function.call-user-func-array:{/home/vagrant/wordpress/wp-includes/plugin.php:525}" target="_new">call_user_func_array:{/home/vagrant/wordpress/wp-includes/plugin.php:525}</a>
(  )</td><td title="/home/vagrant/wordpress/wp-includes/plugin.php" bgcolor="#eeeeec">.../plugin.php<b>:</b>525</td></tr>
<tr><td bgcolor="#eeeeec" align="center">7</td><td bgcolor="#eeeeec" align="center">0.2518</td><td bgcolor="#eeeeec" align="right">3641576</td><td bgcolor="#eeeeec">amazon_web_services_init(  )</td><td title="/home/vagrant/wordpress/wp-includes/plugin.php" bgcolor="#eeeeec">.../plugin.php<b>:</b>525</td></tr>
<tr><td bgcolor="#eeeeec" align="center">8</td><td bgcolor="#eeeeec" align="center">0.2530</td><td bgcolor="#eeeeec" align="right">3916328</td><td bgcolor="#eeeeec">Amazon_Web_Services-&gt;__construct(  )</td><td title="/home/vagrant/wordpress/wp-content/plugins/amazon-web-services/amazon-web-services.php" bgcolor="#eeeeec">.../amazon-web-services.php<b>:</b>52</td></tr>
<tr><td bgcolor="#eeeeec" align="center">9</td><td bgcolor="#eeeeec" align="center">0.2530</td><td bgcolor="#eeeeec" align="right">3916784</td><td bgcolor="#eeeeec">do_action(  )</td><td title="/home/vagrant/wordpress/wp-content/plugins/amazon-web-services/classes/amazon-web-services.php" bgcolor="#eeeeec">.../amazon-web-services.php<b>:</b>36</td></tr>
<tr><td bgcolor="#eeeeec" align="center">10</td><td bgcolor="#eeeeec" align="center">0.2531</td><td bgcolor="#eeeeec" align="right">3918200</td><td bgcolor="#eeeeec"><a href="http://www.php.net/function.call-user-func-array:{/home/vagrant/wordpress/wp-includes/plugin.php:525}" target="_new">call_user_func_array:{/home/vagrant/wordpress/wp-includes/plugin.php:525}</a>
(  )</td><td title="/home/vagrant/wordpress/wp-includes/plugin.php" bgcolor="#eeeeec">.../plugin.php<b>:</b>525</td></tr>
<tr><td bgcolor="#eeeeec" align="center">11</td><td bgcolor="#eeeeec" align="center">0.2531</td><td bgcolor="#eeeeec" align="right">3918280</td><td bgcolor="#eeeeec">as3cf_init(  )</td><td title="/home/vagrant/wordpress/wp-includes/plugin.php" bgcolor="#eeeeec">.../plugin.php<b>:</b>525</td></tr>
<tr><td bgcolor="#eeeeec" align="center">12</td><td bgcolor="#eeeeec" align="center">0.2578</td><td bgcolor="#eeeeec" align="right">4000096</td><td bgcolor="#eeeeec">require_once( <font color="#00bb00">'/home/vagrant/wordpress/wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-stream-wrapper.php'</font> )</td><td title="/home/vagrant/wordpress/wp-content/plugins/amazon-s3-and-cloudfront/wordpress-s3.php" bgcolor="#eeeeec">.../wordpress-s3.php<b>:</b>62</td></tr>
</tbody></table>

```
site_url(): http://local.wordpress.com:8000
home_url(): http://local.wordpress.com:8000
Database Name: wordpress
Table Prefix: wp_
WordPress: 4.4
Web Server: nginx/1.8.0
PHP: 5.6.15-1+deb.sury.org~trusty+1
MySQL: 5.7.9
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Debug Mode: Yes
WP Max Upload Size: 100 MB
PHP Time Limit: 30
PHP Error Log: /home/vagrant/site/wp-content/debug.log
WP Cron: Enabled
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.2d 9 Jul 2015
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Disabled

Media Files: 0
Media Files on S3: 0
Number of Image Sizes: 4

Bucket: 
Region: 
Copy Files to S3: Off
Rewrite File URLs: Off

URL Preview: http://.s3.amazonaws.com/wp‑content/uploads/2016/01/21173723/photo.jpg

Domain: subdomain
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: Off
Object Versioning: On
Far Future Expiration Header: Off
Copy HiDPI (@2x) Images: Off

Active Plugins:
Amazon Web Services (v0.3.4) by Delicious Brains
Async Javascript (v1.15.08.21.1) by David Clough (cloughit)
Breadcrumb NavXT (v5.2.2) by John Havlik
Disable Comments (v1.3.2) by Samir Shah
Disable XML-RPC (v1.0.1) by Philip Erb
Multiple Roles (v1.0) by Michael Dance
WP Offload S3 (v0.9.11) by Delicious Brains
WP REST API (v2.0-beta5) by WP REST API Team
```

Changing the register declaration to include the cache interface seems to quiet the warning,

```
public static function register( Aws\S3\S3Client $client, $protocol = 's3', Aws\CacheInterface $cache = NULL ) {
```

**Comment by A5hleyRich** [comment]
Are you pulling in another version of the AWS SDK via composer, so some other method?

**Comment by adeubank** [comment]
Yep, that is exactly what I am doing. This is the version I have in my composer.json, `"aws/aws-sdk-php": "^3.2",`

What SDK version is this plugin using? Or what AWS API version should I use?

**Comment by A5hleyRich** [comment]
WP Offload S3 isn't compatible with version 3 of the SDK.

**Comment by adeubank** [comment]
That was it, downgrading to 2.* in the composer.json did the trick. thank you, sir.
