### ISSUE TITLE
wp_calculate_image_srcset always returns false when Object versioning is enabled

### ISSUE THREAD

**Issue by mcanever** [deliciousbrains/wp-amazon-s3-and-cloudfront#304]
Hello,
we're using this plugin on WordPress 4.4.1 with no issues so far, thanks for the great job.
At the moment we're willing to start implementing the native support for responsive images on WP 4.4.x on a responsive website, but we've noticed that `wp_calculate_image_srcset` is always returning `false`.
I've started digging and found a small issue in your code [which I highligted here](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/commit/05861fab4f0f84fa8ee1a45173ff81e35caec620#commitcomment-15826312) . 
After hotfixing the plugin, basically nothing changed so I digged more, and found out that this is caused by [how WP 4.4 matches the image src ](https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-includes/media.php#L1072) in `wp_calculate_image_srcset` : it checks the image url against `$dirname . $image['file']`, which doesn't work when media are uploaded to S3 with object versioning, which appends a unique ID to the final url. 
I didn't find a way to workaround this issue, and I think you're already aware of it 'cause I see @polevaultweb discussing this [here](https://core.trac.wordpress.org/ticket/35045#comment:21) ... Do you have any idea of how to handle this? Any hint from the wordpress team about providing a solution?

Thanks a lot in advance for your feedback
Matteo

**Comment by polevaultweb** [comment]
@mcanever we have been working on a fix for this and it will be released soon, will keep you posted.

**Comment by polevaultweb** [comment]
@mcanever this should be fixed in version 0.9.12 just released :)

**Comment by mcanever** [comment]
Awesome!!! Thanks
