### ISSUE TITLE
Cannot use a directory in an S3 bucket as the Origin for a CloudFront distribution with custom domain

### ISSUE THREAD

**Issue by tlpriest** [deliciousbrains/wp-amazon-s3-and-cloudfront#307]
Create an S3 bucket with the following example directories:

s3://mybucket/cloudformation
s3://mybucket/cloudfront
s3://mybucket/lambda
s3://mybucket/otherstuff...

Create a CloudFormation distribution with an origin of s3://mybucket/cloudformation and a custom domain of cloudfront.mydomain.com

In wp-amazon-s3-and-cloudfront, set Path to 'cloudfront/wordpress/wp-content/uploads/' so that when you upload a file, it goes to the right place in the bucket. Set domain to be "CloudFront or custom domain" and specify "cloudfront.mydomain.com" as the name.

At this point, wp-amazon-s3-and-cloudfront creates a URL:

http://cloudfront.mydomain.com/cloudfront/wordpress/wp-content/uploads/...

But that's wrong, because the Origin for the CloudFront distribution already contains '/cloudfront' in the path. This URL makes CloudFront look for a file named '/cloudfront/cloudfront/wordpress/wp-content/uploads/.." which fails.

**Comment by A5hleyRich** [comment]
Thanks for the heads up @tlpriest. I've raised an issue with the rest of the team so that we can look at supporting CloudFront origin paths.

**Comment by kevinsperrine** [comment]
+1

**Comment by ianmjones** [comment]
Hi @kevinsperrine,

The current release has a `as3cf_cloudfront_path_parts` filter that can be used to specify what's already handled by the distribution.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/master/amazon-s3-and-cloudfront-tweaks.php#L41

Look further down the file to find the `cloudfront_path_parts` function to see how you can drop the first part(s) of the path that are used in the distribution.
