### ISSUE TITLE
Compatibility with WPML Plugin

### ISSUE THREAD

**Issue by elend80** [deliciousbrains/wp-amazon-s3-and-cloudfront#308]
Hello.

I have installed S3 Offload and WPML.

but it serves only one language. if change language, media file's link is default site domain.

How to solve?

Refer...
https://wpml.org/forums/topic/compatibility-with-s3-offload/
https://wpml.org/forums/topic/compatibility-with-amazon-s3-and-cloudfront-plugin/
https://wpml.org/forums/topic/amazon-s3-and-cloudfront-and-wpml-compability/

**Comment by sampohaavisto** [comment]
I've noticed that this occurs when sharing the media between languages. It has been around since the I started using the offload plugin -- Jan 2015.

You can do a rewrite in server configuration. That's my solution. Works, but it's kind of hacky.

You must disable object versioning from the plug-in configurations and possibly copy all files from the object version dirs to /bucket/yyyy/mm/ in order for this to work.

Nginx:

```
  # Insert inside your server block
  # Rewrite wp-content GET requests to CloudFront / S3
  location  ~ "^/wp-content/uploads/[\d]{4}/[\d]{2}/" {
    if ($request_method = GET ) {
      rewrite ^/wp-content/uploads/(.*)/(.*)$ https://{{url-to-bucket}}/wp-content/uploads/$1/$2 break;
    }
  }
```

**Comment by polevaultweb** [comment]
@elend80 WPML and WPML Media plugin compatibility with WP Offload S3 is available using the [Pro upgrade](http://deliciousbrains.local/wp-offload-s3/) with our WPML addon http://deliciousbrains.local/wp-offload-s3/doc/wpml-addon/

**Comment by elend80** [comment]
@sampohaavisto @polevaultweb Thank you.
 
My Solution is modify s3 plugin file

amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php

`    function wp_get_attachment_url( $url, $post_id ) {

        global $sitepress;
            //get the original id
            $post_id= icl_object_id($post_id, 'page', true, $sitepress->get_default_language());
`

**Comment by sampohaavisto** [comment]
Thanks @elend80, looks good to me!

**Comment by napisal** [comment]
This solution does not work with thumbnails of attachments, am I right?
