### ISSUE TITLE
Empty Needle on Non-Image Media Uploads

### ISSUE THREAD

**Issue by shawnhooper** [deliciousbrains/wp-amazon-s3-and-cloudfront#309]
Looking at my media library,  non-image uploads that have been offloaded to Amazon S3 are getting an "empty needle" php error in the list above the thumbnail and post title. 

`Warning: strpos(): Empty needle in /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-plugin-compatibility.php on line 906`

Going to the Amazon S3 URL for these items loads them OK, so the objects are in the S3 bucket.  The two resources I'm seeing this on right now are a PPTX and PDF file.

WordPress 4.2.2 and and WP Offload S3 0.9.12

**Comment by A5hleyRich** [comment]
Hi Shawn,

This will be fixed in the next release. The error is related to compatibility with responsive images, which is why you're seeing it for those file types. It shouldn't cause any issue though, other than maybe filling your logs.

**Comment by shawnhooper** [comment]
Thanks for the update Ashley!

**Comment by A5hleyRich** [comment]
Fixed in the latest release.

https://wordpress.org/plugins/amazon-s3-and-cloudfront/changelog/
