### ISSUE TITLE
How do you setup this WP plugin to use a proxy to connect to s3?

### ISSUE THREAD

**Issue by ArcticSnowman** [deliciousbrains/wp-amazon-s3-and-cloudfront#310]
How do you setup this WP plugin to use a proxy to connect to s3?

I have WP_PROXY_* settings in my wp-config.php and I have the PROXY_HTTPS environment settings, but I seem unable to reach http://s3.amazonaws.com/

Any ideas?

**Comment by A5hleyRich** [comment]
You need to pass your proxy settings to the S3 client, which you can do using the `aws_get_client_args` filter.

https://blogs.aws.amazon.com/php/post/Tx9FZ2MY1XP7X6/Sending-requests-through-a-proxy

Something like this should work:

```
function dbi_proxy_config( $args ) {
	$proxy_auth = WP_PROXY_USERNAME . ':' . WP_PROXY_PASSWORD . '@';
	$proxy_address = WP_PROXY_HOST . ':' . WP_PROXY_PORT;

	$args['request.options']['proxy'] = $proxy_auth . $proxy_address;

	return $args;
}
add_filter( 'aws_get_client_args', 'dbi_proxy_config' );
```

**Comment by ArcticSnowman** [comment]
But there is code support for setting the proxy in your 'Amazon Web Services'  WP plugin, so why not provide some means to support that with the S3 plugin?

**Comment by A5hleyRich** [comment]
S3 uses the Amazon Web Services plugin to connect to S3, therefore the filter provided covers both. What code to you need to 'hack'?

**Comment by ArcticSnowman** [comment]
Where would I put that piece of code?

**Comment by A5hleyRich** [comment]
It's best to add it to another plugin. Check out our tweaks plugin, which demonstrates how to customize WP Offload S3.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks

**Comment by ArcticSnowman** [comment]
That's neat,   will take a look... I still think proxy support should be on your roadmap as most enterprise installs (internal at least) would live behind a proxy.

**Comment by A5hleyRich** [comment]
Thanks for the suggestion. I've raised an issue to get it included in a future version.
