### ISSUE TITLE
Cant edit image when plugin is enabled

### ISSUE THREAD

**Issue by nickcaus** [deliciousbrains/wp-amazon-s3-and-cloudfront#311]
Error message: 
"This image is from a different remote domain. To be able to resize it, upload the image on this domain!"

**Comment by A5hleyRich** [comment]
That doesn't sound like a native WordPress error message. Do you have any plugins installed which change the edit image functionality? WP Offload S3 is tested with the builtin image editor and it works just fine, including when the local image is removed from the server.

**Comment by noreabu** [comment]
Do you receive this error message in the logs or on screen?
I am probably experiencing the same problem with the builtin image editor, when the local image is removed (https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/317). Preview seems to work, but the edit view is missing the image. First it worked once, now not anymore...

**Comment by aaemnnosttv** [comment]
Better support for image editing has been added in v1.2, even when local images have been removed from the server.
