### ISSUE TITLE
Error Creating Bucket - Please Help

### ISSUE THREAD

**Issue by bisonbrah** [deliciousbrains/wp-amazon-s3-and-cloudfront#312]
I need to offload roughly 6GB's of media files from WordPress install to AWS. Tried following guide [here](https://premium.wpmudev.org/blog/moving-wordpress-media-to-amazon-s3/) but I keep getting error below.

Error creating bucket — SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data

**Comment by A5hleyRich** [comment]
Can you provide your diagnostic information found on the support tab?

**Comment by bisonbrah** [comment]
site_url(): http://keystonepuppies.com
home_url(): http://keystonepuppies.com
Database Name: wp_keystonepup
Table Prefix: wp_
WordPress: 4.4.2
Web Server: Apache
PHP: 5.5.9-1ubuntu4.14
MySQL: 5.6.28
ext/mysqli: no
PHP Memory Limit: 256M
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 50 MB
PHP Time Limit: 3600
PHP Error Log: /var/log/apache2/keystonepup.error.log
WP Cron: Enabled
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Enabled

Media Files: 32,125
Media Files on S3: 0
Number of Image Sizes: 4

Names and Dimensions of Image Sizes: 
thumbnail (178x118)
medium (300x300)
large (1000x700)

WP_CONTENT_DIR: /nas/content/live/keystonepup/wp-content
WP_CONTENT_URL: http://keystonepuppies.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /nas/content/live/keystonepup/wp-content/plugins
WP_PLUGIN_URL: http://keystonepuppies.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: 
Region: 
Copy Files to S3: Off
Rewrite File URLs: Off

URL Preview: http://s3.amazonaws.com//wp‑content/uploads/2016/03/14064134/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: Keysone Puppy Theme
Active Theme Folder: keystone

Active Plugins:
Amazon Web Services (v0.3.5) by Delicious Brains
Contact Form 7 (v3.2.1) by Takayuki Miyoshi
Keystone Pods Customizations (v1.0) by ParadoxLabs
Lightbox Plus (v2.4.6) by Dan Zappone
ManageWP - Worker (v4.1.28) by ManageWP
Pods CMS Framework (v1.14.2) by The Pods CMS Team
Scissors and Watermark (v3.0) by Ales Loziak
ShareThis (v5.2) by ShareThis,next2manu, Manu Mukerji 
WP Offload S3 Lite (v1.0.2) by Delicious Brains

Must-use Plugins:
Force Strong Passwords - WPE Edition (v1.6.4) by Jason Cosper
ManageWP - Worker Loader (v) by ManageWP
Stop long comments (v0.0.4) by WPEngine
WP Engine System (v2.2.7) by WP Engine

**Comment by A5hleyRich** [comment]
No response received. JSON errors usually occur when WP_DEBUG_DISPLAY is enabled and PHP notices are corrupting AJAX response.

**Comment by bisonbrah** [comment]
thank you
