### ISSUE TITLE
Not working with Wordpress responsive images?

### ISSUE THREAD

**Issue by elliotthill** [deliciousbrains/wp-amazon-s3-and-cloudfront#314]
Hi,

I have the plugin working, although the srcsets are pointing to non s3 urls.

The hooks, wp_get_attachment_url, wp_get_attachment_image_src are not affecting these URLS. All caches are cleared.

Is this a known issue?

**Comment by elliotthill** [comment]
It needs another hook into here no?

https://developer.wordpress.org/reference/functions/wp_calculate_image_srcset/

**Comment by polevaultweb** [comment]
Can you post your diagnostic info from the Support tab in the plugin settings please?

**Comment by A5hleyRich** [comment]
No response received. Responsive images should be fully supported since WP Offload S3 1.0.

**Comment by felixdorner** [comment]
Same problem for me. Before the images got replaced they used to be wrapped in srcset. When replaced by Offload S3 they are just img tags without the srcset information.

**Comment by ianmjones** [comment]
@felixdorner can you post your diagnostic info from the Support tab in the plugin settings please?

**Comment by felixdorner** [comment]
Okay, I have sent it.

**Comment by ianmjones** [comment]
Latest instance of this issue is due to a theme builder incompatibility rather than WordPress responsive images problem.

**Comment by felixdorner** [comment]
Okay, so it is not possible to solve the incompatibility? The theme builder is Fusion Builder by Avada which is used by many. Maybe it is possible to add compatibility for this builder?

**Comment by khalidahmada** [comment]
I have the same issue . I dont use Fusion Builder i have my clean theme( from scratch ) I think this is due to You plugin. 

Any help please ?

**Comment by ianmjones** [comment]
Hi @khalidahmada, this isn't a support forum, please submit a support request via WP Offload S3's built in support tab.

If you don't have a license then you could try the [community support forum](https://wordpress.org/support/plugin/amazon-s3-and-cloudfront).

You'll need to supply some information and what you've done so far to debug it in order for anyone to be able to try and help you. Diagnostic Info and debug.log files are also helpful.
