### ISSUE TITLE
Settings row in database overwritten if settings fail to load.

### ISSUE THREAD

**Issue by GiacoCorsiglia** [deliciousbrains/wp-amazon-s3-and-cloudfront#315]
Hello,

If the plugin ever fails to read the settings row from the database (via `get_site_option()`), it appears to destroy most of the saved settings.  Suppose in one request `get_site_option('tantan_wordpress_s3')` fails due to, say, a momentarily dropped MySQL connection.  In that same request, the `'tantan_wordpress_s3'` row is updated so it loses most (see list) of the saved values.  This means all subsequent requests will have incorrect Offload S3 settings.  My setup uses a custom cloudfront domain, so if this ever occurs, all generated image urls are incorrect until I manually update the settings in the WP Admin dashboard.

As far as I can tell, the deleted settings (keys in the serialized array) are:

- domain
- cloudfront
- object-prefix
- copy-to-s3
- serve-from-s3
- remove-local-file
- ssl
- object-versioning
- use-yearmonth-folders
- enable-object-prefix

This problem came to my attention following some issues with, as you may have guessed, dropped MySQL connections.  However, it can be reproduced by simply shorting out the call to `get_site_option('tantan_wordpress_s3')` with the following filter:

    add_filter('pre_site_option_tantan_wordpress_s3', function( $value, $key ) {
      return null;
    }, 1000, 2);

Observe the value of the `tantan_wordpress_s3` row before and after the first request following the addition of this filter.  It may be that the filter must be added before the plugin is initialized (I'm currently including the filter as a must-use plugin to ensure this happens).

(I'm currently using this filter as a stop-gap solution to the issue.  Instead of returning `null` I'm returning a hardcoded settings array, so database connection issues are never a problem.)

I'm running Amazon Web Services 0.3.5 and WP Offload S3 Lite 1.0.3 on WordPress 4.4.2.  It is a multisite setup, so the settings are saved in the `wp_sitemeta` table.

Please let me know if I can be of any help in resolving this.

Thank you.

**Comment by A5hleyRich** [comment]
Thanks for the report. However, this seems very edge case and more of an issue with your environment. As a workaround can you use the settings constant?

https://deliciousbrains.com/wp-offload-s3/doc/settings-constants/

Closing until we receive further reports.
