### ISSUE TITLE
error attempting to get the region of the bucket

### ISSUE THREAD

**Issue by sharadm-iprogrammer** [deliciousbrains/wp-amazon-s3-and-cloudfront#316]
I am using plugin Offload S3 Lite, I am not able to browse "Existing bucket". I am getting below error:

Error saving bucket — Error Getting Bucket Region —There was an error attempting to get the region of the bucket {{BUCKETAME}}: Access Denied

I even have tried setting mentioned @ https://wordpress.org/support/topic/error-saving-bucket-failed-to-retrieve-bucket-region but with no success

Please help me to solve this problem.

**Comment by A5hleyRich** [comment]
Do you have the `list` permissions as per this doc? https://deliciousbrains.com/wp-offload-s3/doc/quick-start-guide/

**Comment by sharadm-iprogrammer** [comment]
I have added s3:List permission as per doc but I am till facing same problem. Is there anything else needs to do in setting?

**Comment by A5hleyRich** [comment]
No that should be enough. The next thing to do would be to enable WP_DEBUG_LOG and try listing the buckets to see if a more informative error is generated in wp-content/debug.log.

**Comment by sharadm-iprogrammer** [comment]
I checked log and found below variables not defined so I added them in wp-config.php.

AWS_USE_EC2_IAM_ROLE
AS3CF_BUCKET
AS3CF_ASSETS_BUCKET
AS3CF_REGION

but till I am getting below arror

 Error Getting Bucket Region —There was an error attempting to get the region of the bucket BUCKET_NAME: Error retrieving credentials from the instance profile metadata server. When you are not running inside of Amazon EC2, you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object. (Client error response [status code] 404 [reason phrase] Not Found [url] http://169.254.169.254/latest/meta-data/iam/security-credentials/)

**Comment by polevaultweb** [comment]
@sharadm-iprogrammer those are constants that are not required to be set, and are only needed for certain scenarios. 

Can you revert those and let us know if anything is in the logs as per https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/316#issuecomment-209794958

**Comment by sharadm-iprogrammer** [comment]
I tried with as requested by A5hleyRich but there is no error in debug.log while accessing s3bucket (only PHP Notice were there which were for variable)

but after accessing page "/hotel/wp-admin/admin.php?page=amazon-s3-and-cloudfront" shows error 

Error Getting Bucket Region —There was an error attempting to get the region of the bucket BUCKET_NAME: Error retrieving credentials from the instance profile metadata server. When you are not running inside of Amazon EC2, you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object. (Client error response [status code] 404 [reason phrase] Not Found [url] http://169.254.169.254/latest/meta-data/iam/security-credentials/)

**Comment by polevaultweb** [comment]
@sharadm-iprogrammer are you running the site on EC2? If no, then you can remove the constant `AWS_USE_EC2_IAM_ROLE` from your wp-config.php file. Can you retry to see if the original error https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/316#issue-147991376 causes anything to show up in the logs.

**Comment by sharadm-iprogrammer** [comment]
No I am not running site on EC2. I have removed this variable from config file and till there are only PHP Notices in support.log file.

Wp admin panel shows error message:

Error Getting Bucket Region —There was an error attempting to get the region of the bucket BUCKET_NAME: Error retrieving credentials from the instance profile metadata server. When you are not running inside of Amazon EC2, you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object. (Client error response [status code] 404 [reason phrase] Not Found [url] http://169.254.169.254/latest/meta-data/iam/security-credentials/)

What is "you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object"?

**Comment by polevaultweb** [comment]
@sharadm-iprogrammer are you loading the AWS SDK by another means, eg. composer?

**Comment by sharadm-iprogrammer** [comment]
No I am not using composer or another means

**Comment by sharadm-iprogrammer** [comment]
Here are the current permissions for that user in IAM: 

{ 
"Statement": [ 
{ 
"Effect": "Allow", 
"Action": [ 
"s3:DeleteObject", 
"s3:Put*", 
"s3:Get*", 
"s3:List*" 
], 
"Resource": [ 
"arn:aws:s3:::BUCKET_NAME/", 
"arn:aws:s3:::BUCKET_NAME/*" 
] 
} 
] 
}

Please let me know if these settings are ok or we need to make any change in this?

Currently I am getting below error:
There was an error attempting to check the permissions of the bucket BUCKET_NAME: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "BUCKET_NAME.s3.amazonaws.com".

Please help

**Comment by A5hleyRich** [comment]
Can you provide your diagnostic info found on the support tab, remembering to blank out sensitive data?

**Comment by sharadm-iprogrammer** [comment]
Below is the detail:

WP_CONTENT_DIR: /home/dev/ABC/hotel/wp-content
WP_CONTENT_URL: http://ABC/hotel/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /home/dev/ABC/hotel/wp-content/plugins
WP_PLUGIN_URL: http://ABC/hotel/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: BUCKET_NAME
Region: 
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: http://s3.amazonaws.com/BUCKET_NAME/hotel/wp‑content/uploads/2016/04/18074109/photo.jpg

Domain: path
Enable Path: On
Custom Path: hotel/wp-content/uploads/
Use Year/Month: On
SSL: request
Remove Files From Server: Off
Object Versioning: On


Currently I am getting below error:
There was an error attempting to check the permissions of the bucket BUCKET_NAME: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "BUCKET_NAME.s3.amazonaws.com".

**Comment by AltJ** [comment]
I'm helping Sharad troubleshoot this issue and here's what I've done and ended up with the same error:
I've:

- uninstalled the plugin and removed the config settings from the DB
- added the proper AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY lines to wp-config.php
- followed the instructions here: https://deliciousbrains.com/wp-offload-s3/doc/quick-start-guide/ (same error)
- tried blowing the permissions wide open with allowing "Action" on "s3:*" with the resource "arn:aws:s3:::*" (same error)

The only thing that might be out of the ordinary is our bucket name.  It is of the format wps3.dev.yourdomain.com.  Is there any additional information that would help troubleshoot this problem?

**Comment by AltJ** [comment]
oh, I forgot to mention that I've verified that the credentials we have are working with s3cmd.

**Comment by AltJ** [comment]
I'm an idiot.  You can close this.  I've been wasting a bunch of time troubleshooting this with the wrong set of keys.

**Comment by Samyoul** [comment]
If it helps, this thread gave me the hint to check that the keys I was using had access. They didn't have access, saved myself hours of head scratching. Thank you.

**Comment by ianmjones** [comment]
Issue resolved by using correct access credentials for bucket, closing.

**Comment by keithpickering** [comment]
I'm having this exact issue but I'm 100% certain my credentials are correct. Any help?

**Comment by ianmjones** [comment]
@keithpickering Please check the policies on your account or buckets, and turn on WP_DEBUG, WP_DEBUG_LOG, turn off WP_DEBUG_DISPLAY, and then check /wp-content/debug.log after another attempt to browse buckets.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "License & Support" tab in the plugin.

**Comment by ianmjones** [comment]
@leandroruel For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.

**Comment by YMIndustries** [comment]
Sorry to necro this thread, but I also experienced this issue and I wanted to share my solution. People are suggesting adding s3:List* permissions, but that's not correct. This error appears if you are missing the s3:GetBucketLocation permission. Adding this permission resolved the error for me.

**Comment by allella** [comment]
I was able to resolve the following PHP log error by adding [s3:GetBucketLocation permission](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html) to a policy attached to the IAM Role used by the EC2 instance.

> AS3CF: There was an error attempting to get the region of the bucket covers-direct: Failed to instantiate the provider client.
