### ISSUE TITLE
Multisite: support for per-site settings

### ISSUE THREAD

**Issue by mirodanov** [deliciousbrains/wp-amazon-s3-and-cloudfront#32]
A great plugin first ... I was more than happy to see new version supporting multisite, etc.

Anyway I found something that missing with multisite addons. For example if you mapping domain names with http://wordpress.org/plugins/wordpress-mu-domain-mapping/ and want to have different bucket and CloudFront for every domain.

Example buckets:
domain1.s3.amazonaws.com
domain3.s3.amazonaws.com
domain2.s3.amazonaws.com

Then corresponding cloudfront distributions with their domain names:
cdn.domain1.com
cdn.domain2.com
cdn.domain3.com

Having this will have this plugin complete solution. I am also happy to contribute codding this if it's not planned or implemented yet.

**Comment by aaemnnosttv** [comment]
Closing this out as a possibility for the future, but will be pro-only.
