### ISSUE TITLE
Wordpress image editor wont work for certain jpeg images

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#320]
I thought this issue was random...but its not.

Various jpeg images in the word press image editor preview are showing up with a no image and if following the image preview path it returns a -1

I can confirm that all jpegs coming from my cell phone camera behave in this way in the image editor, otherwise they perform as expected. If i re-export an image with new compression via photoshop with the same dimensions and slightly smaller or larger compression the image will also act fine in preview.

If i turn off amazon s3 and re-upload the image, no issues with the image editing.

Attached is an image that is demonstrating the issue:
![img_20160511_123159594](https://cloud.githubusercontent.com/assets/391043/15197655/7d2fcdae-1787-11e6-9c65-b6f54b53abd7.jpg)

**Comment by polevaultweb** [comment]
Could you post your diagnostic info from the support tab in the settings please?

**Comment by mrbm** [comment]
I'd prefer not to post that data publicly, just sent it to the email address on your site. Please confirm receiving it. Thanks!

**Comment by A5hleyRich** [comment]
Got it. Looking into it now.

**Comment by mrbm** [comment]
Great thanks, let me know if I can help. 

To confirm are you seeing the same issue on your system with the image i sent?

**Comment by A5hleyRich** [comment]
I'm not able to replicate this locally with the image provided. What's strange is we've had another report of this today and I can't replicate with those images either.

Is there anything in the debug.log files?

**Comment by mrbm** [comment]
Just messaged you on the email. And regarding the debug.log, nothing hits it when gong to the going to edit it.

**Comment by mrbm** [comment]
Is your plugin hitting the exif data in any way?

**Comment by A5hleyRich** [comment]
Nope we don't touch the exif data.

**Comment by mrbm** [comment]
Been working with Ashley and it looks like he has narrowed it down to a bug reported here:

https://bugs.php.net/bug.php?id=69706

However that bug is referring to an issue found in aws-sdk-php version 2, in version 3 it appears that is was addressed. 

https://github.com/aws/aws-sdk-php/issues/587

wp-amazon-s3-and-cloudfront appears to be still using the aws-sdk-php 2.  For some situations Image Magic PHP library will solve the problem, but that doesn't seem to work in all scenarios that I'm testing.

Bump for plugin using aws-sdk-php 3!

**Comment by mrbm** [comment]
More debugging.

In the file amazon-web-services/vendor/aws/Aws/S3/StreamWrapper.php line 179

There is a function called public function stream_seek($offset, $whence = SEEK_SET)

Inside this function, I modified it to send me an email...that email gets sent only with the problem images in both the thumbnail editor (without imagick installed)

So this is indeed a problem area....in version 3 some additional code was added to address an issue:

```
        // We use CachingEntityBody for seekable streams, which can only seek on
        // bytes that have been read. If we are seeking ahead in the stream, we
        // need to read first.
        if ($this->getOption('seekable')) {
            switch ($whence) {
                case SEEK_SET:
                    $seek_position = $offset;
                    break;
                case SEEK_CUR:
                    $seek_position = $this->body->ftell() + $offset;
                    break;
                default:
                    throw new RuntimeException(__CLASS__ . ' supports only SEEK_SET and SEEK_CUR seek operations');
            }
            while ($this->body->ftell() < $seek_position && !$this->body->isConsumed()) {
                $this->body->read(8192);
            }
        }
```

In my testing $whence is set to 0, and $this->getOption('seekable') is set to nothing, so I think version 3 of the aws could possibly address this issue as something seems to be missing in this exact location.

Thanks guys

**Comment by leoxavier** [comment]
Seems like we are having the same issue. We run a site with a large amount of photos uploaded, and users have been having issues cropping images (we have our own image crop add-on). But further investigation shows that WP also doesn't allow editing images in the media manager.

We logged a lot of these events and the patterns *seems* ti be: if images are sRGB, they can't be read. It might also be some other EXIF data that usually comes from cameras that produce sRGB photos. We get the same -1, and the debug points us to an error in the getimagesize function, which seems to point to the same seek issue.

@mrbm we are trying to do a drop in replacement of AWS PHP SDK to bump it to V3, but it's not as easy as replacing the folder, so can't yet tell if that fixes it. We also tried by just forcing the "seekable" option to true, but that produces another error. Where do you see the code you mentioned?

We're using Image GD and HHVM.

**Comment by mrbm** [comment]
@leoxavier 

Try reviewing the discussion here: https://github.com/aws/aws-sdk-php/issues/587

That's where my conclusions were drawn from.

I believe it is important for this plugin to use the latest AWS PHP SDK as it is a major issue, and will continue to be. I realize that it requires a higher level of PHP and that by not using the latest SDK the plugin maintains a higher compatibility....but that philosophy is hindering progress and reliability. There is the workaround for installing the Image Magic PHP library...however that still leaves much functionality broken and also if they are on a shared server where they can't upgrade the PHP version, then they probably can't install Image magick either.

I think the time has come. Fingers crossed!

-Ben

**Comment by mrbm** [comment]
I am now finding that images generated by exporting from the "preview" program will sometimes and sometimes not export images out with poor EXIF ...causing problems.

So that said I would like to BUMP this issue to the top as very important.

The older S3 library your plugin is using is identified as failing in poor exif information conditions.
To address this issue:
#1) Updated the aws s3 library to the most current version! I realize the requirements from the server are the concern...but this is severely impacting the stability of this plugin! So perhaps have an option in the wordpress settings of this plugin to use the most current library or the older one you are using now.

#2) On upload, option to wipe EXIF data before moving file to S3

Thoughts...keep running into this problem more and more. Please advise.

Thanks!

**Comment by mrbm** [comment]
bump bump

**Comment by leoxavier** [comment]
Once we switched from HHVM to PHP7 this stopped happening, it seems. Can't guarantee that that's the reason though, since we changed multiple things.

**Comment by mrbm** [comment]
@leoxavier @A5hleyRich 

upgrading to PHP 7 (which was an ordeal i must say with my config) also seemed to fix the issue with certain images not being handled properly. So perhaps the issue is not confined to the amazon sdk but also the gd library in php 7 vs php 5.X. But this is good news that we have isolated the randomness a bit further.

@A5hleyRich if you want further details on my install and repositories that are working for the fix, DM me.

**Comment by aaemnnosttv** [comment]
Closing as support for editing images has been improved in v1.2.  Please re-open if this is still and issue for anyone.
