### ISSUE TITLE
Object versioning should auto disable if rewriting is off

### ISSUE THREAD

**Issue by pdufour** [deliciousbrains/wp-amazon-s3-and-cloudfront#321]
Hi sweet plugin! Super easy to install & use. One quirk I noticed, if you disable the automatic rewriting, but leave object versioning enabled, it will upload the file to a versioned url, but keep the non-versioned url displayed in the admin.

So it uploads to 2015/$version/foo.jpg, but in the admin it looks for 2015/foo.jpg (results in 404). I think it would be convenient if object versioning was automatically set to false with maybe a warning message if you disable the rewriting feature.

**Comment by A5hleyRich** [comment]
I think you may have the 'Rewrite File URLs' option confused, which allows you to toggle whether or not to serve files from S3. If you disable the option the local version will be used. It's useful if you want to backup your Media Library to S3, but continue serving the local versions.

**Comment by pdufour** [comment]
In our context, we have the files uploaded to s3, but we don't have this plugin do the rewriting. Instead we have a CDN plugin that rewrites all static files including uploads.

**Comment by pdufour** [comment]
I think I see what you mean though. Our case is probably an outlier. You could be backing up to S3 without rewriting like you said, which would mean object versioning being on or off would not break the images.

**Comment by A5hleyRich** [comment]
Is there any reason why you're using another plugin to perform the rewriting?

**Comment by pdufour** [comment]
We want files like theme assets to be served by the CDN as well.

**Comment by A5hleyRich** [comment]
Gotcha. That is a feature of our Pro version and the Assets addon.

Closing issue as it's very specific to your use case.
