### ISSUE TITLE
v1.0.4 does not change the image URL to the CDN

### ISSUE THREAD

**Issue by grappler** [deliciousbrains/wp-amazon-s3-and-cloudfront#324]
I just updated to WP Offload S3 Lite 1.0.4 and Amazon Web Services 0.3.6.

The media URL are pointing to the local files instead of the files on the CDN.

Also strangely the settings page has disappeared. The other two pages show up fine. 

There was no issue with the previous version. It is specifically this update as I was able to fix it be reverting the update.

```
WordPress: 4.5.2
Web Server: Apache
PHP: 7.0.7
MySQL: 5.6.28
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Blocked External HTTP Requests: None
WP Locale: de_CH
Organize uploads by month/year: Enabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 128 MB
PHP Time Limit: 120
WP Cron: Disabled
fsockopen: Enabled
OpenSSL: OpenSSL 1.0.2h  3 May 2016
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Disabled

Media Files: 87
Media Files on S3: 87
Number of Image Sizes: 9

Names and Dimensions of Image Sizes: 
thumbnail (none)
medium (320x320)
large (600x600)
wpzoo1024 (1024x0)
wpzoo1280 (1280x0)
wpzoo1680 (1680x0)
Penguin800X400 (800x400)
Penguin1200X600 (1200x600)

WP_CONTENT_DIR: /home/wpzoo587/public_html/prod/content
WP_CONTENT_URL: //wpzoo.ch/content
UPLOADS: Not defined
WP_PLUGIN_DIR: /home/wpzoo587/public_html/prod/content/plugins
WP_PLUGIN_URL: //wpzoo.ch/content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: wpzoo.ch2
Region: eu-central-1
Copy Files to S3: On
Rewrite File URLs: On

URL Preview: https://cdn.wpzoo.ch/uploads/2016/06/02213834/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: uploads/
Use Year/Month: On
SSL: https
Remove Files From Server: On
Object Versioning: On

Active Theme Name: WPZOO
Active Theme Folder: WPZOO
Parent Theme Folder: penguin-gold

Active Plugins:
Amazon Web Services (v0.3.5) by Delicious Brains
Antispam Bee (v2.6.8) by pluginkollektiv
Dequeue jQuery Migrate (v1.0.0) by Cedaro
Disable Emojis (v1.5.1) by Ryan Hellyer
EDD Language Packs (v0.1.0) by WPZOO, Ulrich Pogson
EDD Variable Pricing Descriptions (v1.0.2) by Andrew Munro - Sumobi
EDD WPZOO (v1.0.0) by wpzoo.ch
EU VAT for Easy Digital Downloads (v1.5.10) by Lyquidity Solutions
Easy Digital Downloads (v2.5.16) by Pippin Williamson and Company
Easy Digital Downloads - Auto Register (v1.3.5) by Andrew Munro, Pippin Williamson, and Chris Klosowski
Easy Digital Downloads - Fraud Monitor (v1.0.7) by Andrew Munro, Pippin Williamson, and Chris Klosowski
Easy Digital Downloads - Software Licenses (v3.4.7) by Pippin Williamson and Chris Klosowski
Easy Digital Downloads - Stripe Payment Gateway (v2.4.3) by Pippin Williamson
Easy Digital Downloads Polylang (v0.0.1) by Ulrich Pogson
Fragment Cache (v1.3) by Andrey "Rarst" Savchenko
GistPress (v3.0.1) by Blazer Six
If Menu (v0.4.1) by Andrei Igna
Jetpack by WordPress.com (v4.0.3) by Automattic
Log Out Shortcode (v1.0.4) by OM4
MailChimp für WordPress (v3.1.8) by ibericode
Menu Humility (v0.3) by Mark Jaquith
Ninja Forms (v2.9.47) by The WP Ninjas
Ninja Forms - Mail Chimp (v3.0.0) by The WP Ninjas
Polylang (v1.9.1) by Frédéric Demarle
Polylang Slug (v0.2.0) by Ulrich Pogson
Rock The Slackbot (v1.1.1) by Rachel Carden
SG CachePress (v2.3.4) by SiteGround
SearchWP (v2.7.2) by Jonathan Christopher
SearchWP Polylang Integration (v1.2) by Jonathan Christopher
Shortcake (Shortcode UI) (v0.6.2) by Fusion Engineering and community
WF Cookie Consent (v0.9.9) by wunderfarm
WP Comment Humility (v0.1.0) by John James Jacoby
WP Migrate DB Pro (v1.6) by Delicious Brains
WP Offload S3 Lite (v1.0.3) by Delicious Brains
WP Rocket (v2.8) by WP Rocket
WPZOO Docs (v1.0.1) by WPZOO
WPZOO Gravatar Shortcode (v1.0.0) by Ulrich Pogson
WPZOO Plugin (v1.0.0) by WPZOO
WPZOO SVG (v1.0.0) by WPZOO
WPZOO Simple Analytics (v0.1.0) by WPZOO, Ulrich Pogson
Yoast SEO (v3.2.5) by Team Yoast

Must-use Plugins:
Selective Loading (v0.1.0) by WPZOO, Ulrich Pogson
WP Migrate DB Pro Compatibility (v1.1) by Delicious Brains
disable-notification.php
register-theme-directory.php
```

**Comment by A5hleyRich** [comment]
Are there any errors when `WP_DEBUG_LOG` is enabled?

**Comment by matschaffer** [comment]
I also experienced similar issues. My images weren't replaced with s3 URLs. The "settings" link was also missing from the plugin list. I have WP_DEBUG enabled but nothing that I could see in the error logs about the plugin. For now I pinned back to 1.0.3

**Comment by A5hleyRich** [comment]
Do you have `curl_multi_exec` enabled?

**Comment by grappler** [comment]
The function exists on my site. My host is Siteground. There were no error messages in the debug log.

**Comment by A5hleyRich** [comment]
We're having a hard time replicating this. Do you a site where we could take a look?

**Comment by matschaffer** [comment]
If you clone https://github.com/matschaffer/s3test and run `docker-compose up` (may need some env or hosts tweaking for directs etc) it should get replicate what I'm seeing as far as the settings link not being present. Will require some media to see that the media links aren't getting replaced.

<img width="1225" alt="screen shot 2016-06-03 at 10 11 58 pm" src="https://cloud.githubusercontent.com/assets/690/15779658/80453534-29d8-11e6-90c8-777102e310be.png">

**Comment by grappler** [comment]
I think there may be an issue with wpackagist. I am using composer and it seems like it did not properly update amazon-web-services to version 0.3.6.

**Comment by matschaffer** [comment]
Yeah, I just noticed that as well. Composer reports 0.3.6, but the `amazon-web-services.php` it downloads says 0.3.5.

**Comment by A5hleyRich** [comment]
Awesome. Cheers for the heads up. Looking into it now.

**Comment by grappler** [comment]
After `composer clean-cache` and deleting the plugins it seems to working fine. The reason I did not realize the issue was that I do not have any update notifications on my staging and live site.

Perhaps a notice of incompatible versions would be helpful but this issue has been fixed.

**Comment by matschaffer** [comment]
clean-cache followed by removing the in-repo dir then re-running install seems to have gotten the right version for me as well. settings link is back too.

**Comment by BrandonShutter** [comment]
This didn't work for me.  I still have old versions of the plugins installed.

  ```
  {
      "type": "package",
      "package": {
        "name": "deliciousbrains/wp-migrate-db-pro",
        "type": "wordpress-plugin",
        "version": "1.6",
        "dist": {
          "type": "zip",
          "url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-latest.zip?licence_key=c7cd7bae-3ccf-4157-a859-920a62fa66ac&site_url=bs.dev"
        },
        "require": {
          "composer/installers": "v1.0.12"
        }
      }
    },
```

Locally, version 1.6 is installed, remotely version 1.5.5 is installed.

**Comment by BrandonShutter** [comment]
Downgrading to 1.0.3 brings back the setting menu.

**Comment by grappler** [comment]
@BrandonShutter This is not the repo or issue or Migrate DB Pro but for WP Offload S3 Lite

**Comment by BrandonShutter** [comment]
@grappler  Correct, and downgrading back a version of S3 Lite brings the settings back.  The newest version doesn't show it.

**Comment by grappler** [comment]
@BrandonShutter You added a composer snippet from Migrate DB Pro above. :smile: Make sure that amazon-web-services and WP Offload S3 Lite are updated to the latest version and then it should work.

**Comment by A5hleyRich** [comment]
The AWS plugin is now tagged in SVN, which should resolve this issue going forward.
