### ISSUE TITLE
Custom logo upload issue in customizer

### ISSUE THREAD

**Issue by topdown** [deliciousbrains/wp-amazon-s3-and-cloudfront#325]
In WP 4.5 custom logo support was added to customizer
https://make.wordpress.org/core/2016/03/10/custom-logo/

While building my SaaS app which has this feature I found out that the logo uploader breaks when the image crop mechanism is used and Remove Files From Server set on.
It works fine if no cropping is needed or Remove Files From Server is set to off.

Setting up locally I found out that the cropper outputs a WP notice
`There has been a error cropping your image.`

I think what is happening is the image is being uploaded to S3 first and removed on the server.
The URL the cropper uses is no longer good.

I believe the Twenty Sixteen theme has custom logo support built in if you want to test.

**Comment by A5hleyRich** [comment]
Custom logo support added in WP Offload S3 Lite 1.1.
