### ISSUE TITLE
Some images are automatically deleting from s3 buckets

### ISSUE THREAD

**Issue by Vipulalw** [deliciousbrains/wp-amazon-s3-and-cloudfront#326]
Some images are automatically deleting from s3 buckets and if I browse Image URL it shows XML error. For resolving this I'll have to regenerate thumbnail then image creates again on s3 bucket.
![s3_image_not_found](https://cloud.githubusercontent.com/assets/19647451/16332210/76463656-3a12-11e6-9e1c-d1468cbece3d.png)

**Comment by A5hleyRich** [comment]
This is the first report we've had of this, so it's more likely to be caused by a third party plugin. Please can you provide your diagnostic information from the support tab?

**Comment by A5hleyRich** [comment]
No response and no further reports. Closing issue.
