### ISSUE TITLE
AWS Bucket Access -- Restrict to path

### ISSUE THREAD

**Issue by mike-healy** [deliciousbrains/wp-amazon-s3-and-cloudfront#327]
The plugin reports an error "Access denied to bucket" when the IAM user is set to have S3 permissions to only a specific path within the bucket.

I don't want WordPress to have write access to the entire bucket.

My IAM Policy (snippet):
```
"Resource": [
                "arn:aws:s3:::mybucket",
                "arn:aws:s3:::mybucket/thisproject/*"
            ]
```
The allowed path matches the path that the plugin is configured to write to.

Plugin: 1.0.4 / WordPress 4.5.3

**Comment by A5hleyRich** [comment]
Can you confirm how you've configured your bucket path? WP Offload S3 should use the 'Path' option in the settings screen to test write permissions.

**Comment by mike-healy** [comment]
My mistake -- I had an error in the S3 path I wanted to use.
Missed the obvious :)
