### ISSUE TITLE
Missing Expires Headers on Uploaded Images

### ISSUE THREAD

**Issue by scottybo** [deliciousbrains/wp-amazon-s3-and-cloudfront#328]
Hi Guys,

Great plugin, but one small problem: Expires Headers are not set on the images.

Running a Pingdom test on a website, I noted that all S3 images have a short freshness lifetime. For improved caching and speed, the cache time on images should be at least a week.

It would be brilliant if either of these options could be implemented:

1) This option was set as a default in the core code
2) An option was added to allow us to specify the expiration time via the Wordpress admin

**Comment by A5hleyRich** [comment]
What version of WP Offload S3 are you using? Since version 1.0 (released 2016-03-07) `Expires` and `Cache-Control` headers have been added by default with a 1 year expiry. Prior to that release you could enable the 'Far Future Expiration' option.

**Comment by scottybo** [comment]
Thanks for the fast reply!

Version 1.0.4 for WP Offload and Version 0.3.6 for Amazon Web Services Plugin

The site in question is: http://www.webpager.co.uk

Pingdom test can be seen here: http://tools.pingdom.com/fpt/JfWav/http://www.webpager.co.uk

**Comment by scottybo** [comment]
Hold that thought - we're using a Lambda function to compress images as they're uploaded, just need to double check that the replaced file is keeping its headers

**Comment by scottybo** [comment]
Confirmed that it's not an issue wtih your plugin, cache-control was stripped by our Lambda function. Thanks again for your original response :)

**Comment by pkiula** [comment]
Where can I control the Cache-Control option in the plugin settings? Or is it fixed and inbuilt?
