### ISSUE TITLE
Deleting Images in Bulk

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#329]
In a multi-site environment, went to a subblog > media library > put it in list mode > selected the whole group of items > choose "delete permanently" 

Appears to be gone from blog...however visiting the path of one of thumbnail images reveals that it is still on my s3 server...I will email you direct an example of a image that wasn't deleted of of the s3

Love your thoughts

-MRBM

**Comment by A5hleyRich** [comment]
We've been unable to replicate this issue ourselves. Are you able to replicate this reliably? If so, do you have the exact steps?

**Comment by mrbm** [comment]
I am not, tried adding and deleting 3 images without issue.

Still haven't tested if me as the network admin deleting a subusers pics in bulk makes a difference, nor have I tested if having a mp3 and mp4 in combination with all the jpegs in a group delete caused the issue (perhaps it got tripped up looking to delete a thumbnail that didn't exist via the .mp3 or mp4)  

I should have pre-tested more and these other scenarios to do a better bug report.  A bit swamped so if you don't come across the issue i will do more testing.

**Comment by A5hleyRich** [comment]
No worries. We'll keep this open for now to see if someone else has the same issue.

**Comment by aaemnnosttv** [comment]
Closing for now as unable to replicate. Please re-open if this is still an issue for anyone.
