### ISSUE TITLE
Document how to use as3cf_pre_update_attachment_metadata

### ISSUE THREAD

**Issue by njbarrett** [deliciousbrains/wp-amazon-s3-and-cloudfront#330]
Hey,
FYI I am using the pro version of this plugin.

I am trying to prevent a certain folder from being uploaded to s3. I need the folder to remain on the server, but I need the "remove files from server" setting enabled for everything else. Basically I just want the default wordpress functionality for the folder I set.

From some digging it looks like I can use `as3cf_pre_update_attachment_metadata`, but its not documented anywhere as to how to use the hook. When I tried returning false from it it blocked the uploads all together (even to the local server, not just s3 like I thought it would).

Could someone please explain how to implement `as3cf_pre_update_attachment_metadata` correctly, and what the expected behaviour is?

**Comment by A5hleyRich** [comment]
This is how you would exclude the 2016/07 directory from being uploaded to S3 and retain the local files. All other files will be offloaded to S3 and the local files removed.

```
function pre_update_attachment_metadata( $pre_update, $data, $post_id ) {
	if ( false !== strpos( $data['file'], '2016/07' ) ) {
		return true; // Abort the upload
	}

	return false;
}
add_filter( 'as3cf_pre_update_attachment_metadata', 'pre_update_attachment_metadata', 10, 3 );
```

**Comment by njbarrett** [comment]
Awesome, thanks for this.
