### ISSUE TITLE
Links to docs in settings exit WordPress

### ISSUE THREAD

**Issue by Shelob9** [deliciousbrains/wp-amazon-s3-and-cloudfront#331]
The docs links in the settings are super useful, but I really wish they opened in new tab. I keep getting the error popup and then manually open them in new tab.

**Comment by polevaultweb** [comment]
>  I keep getting the error popup

Hey Josh, which error popup do you mean, got a screenshot? Cheers

**Comment by aaemnnosttv** [comment]
Closing this out as most in page links (if not all) use `target=_blank` now which will open the link in a new window/tab.
