### ISSUE TITLE
Cropping in the Customizer fails with ImageMagick

### ISSUE THREAD

**Issue by morganestes** [deliciousbrains/wp-amazon-s3-and-cloudfront#332]
I'm attempting to crop an image in the Customizer, but when ImageMagick is enabled in PHP 5.6 (`php-imagick` in Ubuntu), cropping fails with "There has been an error cropping your image."

Disabling ImageMagick (`phpdismod -v5.6 imagick`), ensuring PHP GD is active, and restarting php-fpm allows cropping to continue, not it's not fully successful (still looking into that part).

**Comment by polevaultweb** [comment]
hey @morganestes, does the cropping work as expected with the plugin disabled?

**Comment by morganestes** [comment]
Yep, it crops to the right size (we're using fixed sizes/ratios) and saves it to the media library as expected.

**Comment by mrbm** [comment]
@morganestes do you have this issue with all images...? Try an image from another source. You may be interested in reviewing my thread here:

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/320

**Comment by aaemnnosttv** [comment]
Closing as support for editing images has been improved in v1.2. Please re-open if this is still and issue for anyone.
