### ISSUE TITLE
Unable to browse to another s3 bucket

### ISSUE THREAD

**Issue by aaronjhoffman** [deliciousbrains/wp-amazon-s3-and-cloudfront#333]
We've been using the plugin successfully for number of months. Recently wanted to change the s3 bucket to a different bucket. When we click Browse to bucket and select it gives the following error:

Error saving bucket — Error Getting Bucket Region —There was an error attempting to get the region of the bucket newuploads: The specified bucket does not exist

The specific IAM user has full access and should be able to access the bucket just as we did initially. 

Any ideas why suddenly we cannot change buckets?

**Comment by aaemnnosttv** [comment]
Does this happen with any bucket you choose or just the one?

**Comment by aaemnnosttv** [comment]
Going to close this one for now as we haven't heard back from you and we have no other reports of this, nor can we reproduce. If you found out what it was, please share!
