### ISSUE TITLE
need to add images from aws s3 url without download/upload on local server upload directory.

### ISSUE THREAD

**Issue by ravibarnwal** [deliciousbrains/wp-amazon-s3-and-cloudfront#335]
I need to add images from aws s3 url without download/upload on upload directory. 
I have a site with woocommerce(main site) all images are uploaded and served by aws s3 cloud front using WP Offload S3 Lite. 
Now I am using Woocommerce REST API To import/create new product on another woocommerce site(sub site from main site). So i want to use main site images path as an attachment for sub site without uploading again on local server or on aws s3 bucket. Please help me how can use images as an attachment directly from external url.

**Comment by ravibarnwal** [comment]
@A5hleyRich please help me on above issue.

**Comment by aaemnnosttv** [comment]
This request is outside of the scope of the kind of support we can provide on the free tier.

For individualized premium support from a developer, please upgrade to Offload S3 pro and send us an email.
