### ISSUE TITLE
Issue with rewrites

### ISSUE THREAD

**Issue by pkmnct** [deliciousbrains/wp-amazon-s3-and-cloudfront#336]
We're getting a weird bug when we enable the "Rewrite File URLs" option. The URL appears correctly in the preview pane (http://files.kstatecollegian.com/2016/08/photo.jpg), but when enabled the URLs that the site gives are quite odd:

http://files.kst67720758-6210-4149-8883-d10199e25478-100x70.jpgtecollegi67720758-6210-4149-8883-d10199e25478-100x70.jpgn.com/67720758-6210-4149-8883-d10199e25478-100x70.jpg

when it should be

http://www.kstatecollegian.com/wp-content/uploads/2016/07/67720758-6210-4149-8883-d10199e25478-100x70.jpg

The plugin appears to be changing any instance of "a" in the URL to the photo's filename, and leaving out the path to the file.

**Comment by aaemnnosttv** [comment]
That is quite strange behavior! Can you confirm that this is still an issue for you with the latest version of the plugin? (Currently 1.2)

**Comment by ianmjones** [comment]
No further info provided, closing.
