### ISSUE TITLE
Plugin won't set up with AWS VPC S3 Endpoint - allow for defining region up front?

### ISSUE THREAD

**Issue by pbudzon** [deliciousbrains/wp-amazon-s3-and-cloudfront#339]
Hi!

First of all, thanks for the plugin, it's a must-have when deploying Wordpress to AWS.

I've been trying to deploy a fairly secure setup where the EC2 instance hosting Wordpress is located within a private subnet inside a VPC - that means, it does not have an internet gateway (ie. no access to the internet). This would normally mean no access to S3 either, but with VPC Endpoints for S3 it is now possible to add a route to S3 to a private VPC subnet.
So, running 
```
curl -v https://s3-eu-west-1.amazonaws.com/somebucket/somefile
```
will work, if your instance is in eu-west-1.
**Note, this only works for the region in which instance is located.**
That means, from the same instance, running:
```
curl -v http://s3.amazonaws.com/somebucket/somefile
```
**will not work** (different region, us central by default).

That posses a problem for the plugin, when setting up a new environment, because when you select a bucket for the plugin, it tries to detect the region (I'm guessing at this point the request goes to http://s3.amazonaws.com/, which as above, will not work).

I tried pre-setting the configuration as described here (https://deliciousbrains.com/wp-offload-s3/doc/settings-constants/), but that also doesn't have the info about the region.

After I added internet access for the instance, set up the plugin (let it detect the region), I removed the internet access and everything works perfectly (the plugin already knows the region, and uses correct s3 endpoint).
For me it seems like an option to pre-set the region of the bucket (instead of auto-detection), would solve the problem right away.

Thanks,
Paulina.

Info:
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html

**Comment by A5hleyRich** [comment]
You can use the `aws_get_client_args` filter to specify the region upfront. Please see:

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/master/amazon-s3-and-cloudfront-tweaks.php#L43
