### ISSUE TITLE
Attachments are not sent to S3 when they're inserted to the media library programmatically

### ISSUE THREAD

**Issue by wujekbogdan** [deliciousbrains/wp-amazon-s3-and-cloudfront#340]
When I insert attachments into the WP media library programmatically they're not sent to the S3 bucket. I use the `wp_upload_bits()` function together with the `wp_insert_attachment()` function. 

This is how I do this:
``` php
$filePath = '/file/path/on/the/server/myFile.zip';
$uploaded = wp_upload_bits('myFile.zip', null, file_get_contents($filePath));

if ($uploaded['error'] !== false) {
    wp_die('Upload failed');
}

$attachmentId = wp_insert_attachment([
    'post_mime_type' => wp_check_filetype(basename($filePath))['type'],
    'post_title' => 'myFile',
    'post_content' => '',
    'post_status' => 'inherit'
], $uploaded['file'], $post->ID);
```
The code is fine. Attachments are sent to the media library properly. I can see them on the list, but URLs still point to my localhost.

Is it a bug or am I doing something wrong? I suppose that WP Offload S3 relies on a hook that is not executed when attachments are inserted into the Media Library this way.

PS
The configuration is fine. Attachments added to the Media Library in a normal way are properly sent to the S3 bucket.

**Comment by A5hleyRich** [comment]
At present WP Offload S3 only hooks into `wp_update_attachment_metadata`. As a workaround can you call that function after inserting the attachment into the Media Library?

**Comment by wujekbogdan** [comment]
Thanks! It works fine.

``` php
$attachmentData = wp_generate_attachment_metadata( $attachmentId, $uploaded['file'] );
wp_update_attachment_metadata( $attachmentId,  $attachmentData );
```

But IMO it's still a workaround and it would be better if WP Offload S3 listened to the `wp_handle_upload` hook (if possible).

**Comment by A5hleyRich** [comment]
As per the Codex, `wp_insert_attachment` should be used in conjunction with `wp_update_attachment_metadata`.

https://codex.wordpress.org/Function_Reference/wp_insert_attachment

Closing issue

**Comment by martinr77** [comment]
Hi, I'm trying hours about hours but it will not work:

`

include_once ABSPATH . 'wp-admin/includes/media.php';
include_once ABSPATH . 'wp-admin/includes/file.php';
include_once ABSPATH . 'wp-admin/includes/image.php';

$url = content_url() . $filepath;
								//$url = 'https://s.w.org/style/images/wp-header-logo.png';
								
								$temp_file = download_url( $url );
								
								
								 // Array based on $_FILE as seen in PHP file uploads
									$file = array(
										'name'     => basename($url), // ex: wp-header-logo.png
										'type'     => 'image/png',
										'tmp_name' => $temp_file,
										'error'    => 0,
										'size'     => filesize($temp_file),
									);
								
								
								$overrides = array(
										// Tells WordPress to not look for the POST form
										// fields that would normally be present as
										// we downloaded the file from a remote server, so there
										// will be no form fields
										// Default is true
										'test_form' => false,
								
										// Setting this to false lets WordPress allow empty files, not recommended
										// Default is true
										'test_size' => true,
									);
								
									// Move the temporary file into the uploads directory
									$file_return = wp_handle_sideload( $file, $overrides );
								
								
								 $filename = $file_return['file'];
									
									// Prepare an array of post data for the attachment.
										  $attachment = array(
											  'post_mime_type' => $file_return['type'],
											  'post_title' => preg_replace( '/\.[^.]+$/', '', basename( $filename ) ),
											  'post_content' => '',
											  'post_status' => 'inherit',
											  'post_author' => $ID,
											  'guid' => $file_return['url']
										  );
										  
										  // Insert the attachment.
										  $attachment_id = wp_insert_attachment( $attachment, $file_return['url'] );
									 
									 // generates metadata for an image attachment. It also creates a thumbnail and other intermediate sizes of the image attachment based on the sizes defined on the Settings
									 // and update the database record.
										  $attachment_data = wp_generate_attachment_metadata( $attachment_id, $filename );
										  
										  wp_update_attachment_metadata( $attachment_id, $attachment_data );`


then I tried the solution above but it is also not working because there is missing the size and the type:

$filePath = content_url() . $fotopath;
									
									
							header('Content-Type: image/jpeg');
    						
	
									$uploaded = wp_upload_bits(basename($filePath), null, file_get_contents($filePath));
									
									if ($uploaded['error'] !== false) {
										error_log("copypic - upload failed - " . $filePath . ' - '. date( 'G:i:s' ) .PHP_EOL, 3, dirname( __FILE__ ) .  '/logs/copyimages-logs-' . date( 'Y-m-d' ) . '.log');
									}
									
									$wp_filetype = wp_check_filetype( basename( $filePath['file'] ), null );
									
									
									$wp_upload_dir = wp_upload_dir();
									
									
									$attachment_id = wp_insert_attachment([
										'post_mime_type' => $wp_filetype['type'],
										'post_title' => preg_replace( '/\.[^.]+$/', '', basename( $uploaded['file'] ) ),
										'post_content' => '',
										'post_author' => $ID,
										'post_status' => 'inherit',
										'guid' => $wp_upload_dir['baseurl'] . _wp_relative_upload_path( $uploaded['file'] )
									], $uploaded['url']);


$attachmentData = wp_generate_attachment_metadata( $attachment_id, $uploaded['file'] );
wp_update_attachment_metadata( $attachment_id,  $attachmentData );

**Comment by wujekbogdan** [comment]
In order to call `wp_update_attachment_metadata` the `wp-admin/includes/image.php`  file have to be included (see the [documentation](https://codex.wordpress.org/Function_Reference/wp_insert_attachment)). It seems to be a very bad practice. 

So even if WP Codex recommends to do it this way it doesn't mean it's a good practice. It's overcomplicated and messy.

**Comment by ravibarnwal** [comment]
I am also uploading images on s3 using wp-amazon-s3-and-cloudfront and trying to regenerate thumbnails on another plugin it is not working but same code working in regenerate thumbnail plugin https://wordpress.org/plugins/regenerate-thumbnails/. So nay help on that.

**Comment by wujekbogdan** [comment]
@ravibarnwal 
I've posted a solution [here](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/340#issuecomment-247953986). So if the plugin that regenerates thumbnails calls `wp_update_attachment_metadata()` function then images will be pushed to S3, otherwise you have to call it manually.

**Comment by ravibarnwal** [comment]
Thank you for your response. I am able to upload the files on s3. my concern is when I am trying to regenerate the metadate in my plugin using function `wp_generate_attachment_metadata` it is not working means not generate the metadata of image. I am doing same as https://wordpress.org/plugins/regenerate-thumbnails/ this plugin is doing. please help me.

**Comment by ianmjones** [comment]
@ravibarnwal Regenerate Thumbnails calls `wp_update_attachment_metadata` after `wp_generate_attachment_metadata`, does your code?

**Comment by ravibarnwal** [comment]
I have uploaded the image using custom code to s3. and now I am try to regenerate the metadata for that image. But it is not working.
```
<?php
$image = get_post( $attachment_id );
$fullsizepath = get_attached_file( $image->ID );
$metadata = wp_generate_attachment_metadata( $image->ID, $fullsizepath ); // It is not generating metadata.
wp_update_attachment_metadata( $image->ID, $metadata );
```

Same like above code in regenerate thumbnail plugin are using but there it is working. What is the issue I don't no. 


Note: My attachement on s3 only not on local server.

Main I am fixing this problem. https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/335

**Comment by ianmjones** [comment]
> `$metadata = wp_generate_attachment_metadata( $image->ID, $fullsizepath ); // It is not generating metadata.`

That is your problem.

You should put some error checking into your code and check the result of that call.

I suspect you're heading for a world of hurt because you're not using local files for generating the metadata.

**Comment by ravibarnwal** [comment]
@ianmjones , thanks,

 I am checking in my complete code. yes that code throw the file_not exit.
My question is when I am using this code it is giving s3 url of image.  
$fullsizepath = get_attached_file( $image->ID );

And same code in regenrate thumbnail plugin giving local file url. 

When I am using this code and getting local file url 
$fullsizepath = get_attached_file(  $image->ID, TRUE  );
using this code throwing the file does not exit error I don't know why it is not working in my plugin 
$metadata = wp_generate_attachment_metadata( $image->ID, $fullsizepath );

same code working  https://github.com/Viper007Bond/regenerate-thumbnails/blob/master/regenerate-thumbnails.php#L351.

Can you suggest me any solution for above problem. your help would be very helpful for me.

**Comment by ianmjones** [comment]
@ravibarnwal Regenerate Thumbnails works because it is working with attachments that already have good metadata that points to S3. WP Offload S3 knows about the S3 object and temporarily pulls down the original if it doesn't exist locally or in other scenarios sets up a stream wrapper.

You're doing the opposite, you're trying to generate the metadata for a file for the first time without local access to the file.

If you were to debug the call stack you'll notice that WP Offload S3 does not know about the file and is not even involved in the `get_attached_file` call chain apart from saying "we don't know about this attachment so skip doing anything with its URL".

WP Offload S3 isn't involved, you're blowing up on standard WordPress functionality because you don't have a local file.

**Comment by ravibarnwal** [comment]
Now I understood. @ianmjones thanks lots. Great explanation.

**Comment by scarpelini** [comment]
Hey guys, I'm getting some issues when I'm trying to send video files programmatically to the bucket. I'm almost the same routines described above, however, using the method '**wp_handle_upload**'(I also tested with '**wp_handle_sideload**'). Both of them are uploading the video file, but only saving to the HD not to the S3. Using the very same approach with images, they are being saved correctly into the S3. It's specifically an issue around video files(larger files, maybe).

The video files uploaded are available in the Media Gallery but with the local path.

Guys, do you have any clue about that? Did you face any troubles around uploading videos with **WP Offload Media Lite**?
@A5hleyRich do you know anything about this problem?

**Comment by scarpelini** [comment]
Guys, I've just found the solution. I'm using W3 Total Cache plugin and the problem was in the Database cache. Considering the WP Offload Media updates the file path after saving the file into the S3 Bucket, probably W3 Total Cache was blocking the action. What I did was disable this action into the cache plugin. Now it's all working fine.
