### ISSUE TITLE
1.2 Upgrade of Local Content

### ISSUE THREAD

**Issue by jesseheap** [deliciousbrains/wp-amazon-s3-and-cloudfront#342]
After upgrading to the newest version it appears the upgrade routine to replace all S3 urls is stuck at 0% after several hours.  

I want to diagnose further but I have a few questions:

1) What are you replacing the S3 URL with?  A relative URL (i.e. https://images.pinkcakebox.com/imagename.jpg to /imagename.jpg) or an absolute (i.e. https://images.pinkcakebox.com/imagename.jpg to https://www.pinkcakebox.com/imagename.jpg)
1. If an image was not included as an attachment (but merely added to the post via a url like: `<img src="https://images.pinkcakebox.com/first-birthday-creative-cakes-950x633.jpg" alt="Creative 1st Birthday Cakes " width="950" height="633" class="aligncenter size-large wp-image-6650" />`)) will it upgrade these as well?

Thanks for your help and for continuing to maintain this plugin.

Jesse

**Comment by A5hleyRich** [comment]
Hi,

Could you provide the diagnostic information found on the support tab?

**Comment by jesseheap** [comment]
Sure:

site_url(): http://maintest.pinkcakebox.com
home_url(): http://maintest.pinkcakebox.com
Database Name: pinkcakeboxtest
Table Prefix: wp_
WordPress: 4.7
Web Server: Apache
PHP: 7.0.12
MySQL: 5.6.25
ext/mysqli: yes
PHP Memory Limit: 90M
WP Memory Limit: 40M
Memory Usage: 18 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Disabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 64 MB
PHP Time Limit: 30
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1 14 Mar 2012
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Enabled
Proxy: Disabled

Media Files: 2,646
Media Files on S3: 2,571
Number of Image Sizes: 5

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (950x900)
wp_rp_thumbnail (150x150)

WP_CONTENT_DIR: /home/pinkcakebox/maintest.pinkcakebox.com/wp-content
WP_CONTENT_URL: http://maintest.pinkcakebox.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /home/pinkcakebox/maintest.pinkcakebox.com/wp-content/plugins
WP_PLUGIN_URL: http://maintest.pinkcakebox.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: images.pinkcakebox.com
Region: 
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://maintest.pinkcakebox.com/wp‑content/uploads/photo.jpg
S3 URL:
https://images.pinkcakebox.com/photo.jpg

Domain: cloudfront
Enable Path: Off
Custom Path: wp-content/uploads/
Use Year/Month: Off
Force HTTPS: On
Remove Files From Server: Off
Object Versioning: Off

Active Theme Name: PinkCakeBox.com
Active Theme Folder: pinkcakebox

Active Plugins:
AMP (v0.4.2) by Automattic
Akismet (v3.2) by Automattic
Amazon Web Services (v1.0.1) by Delicious Brains
Custom Google Maps (v1.0) by Jesse Heap
Custom Post Type UI (v1.4.3) by WebDevStudios
Custom Posts Per Page (v1.7.1) by Jeremy Felt
Customizable Post Listings (v1.2) by Scott Reilly
Daily Top 10 Posts (v0.4) by Andrew dela Serna
Disable Embeds (v1.3.0) by Pascal Birchler
Disable Emojis (v1.5.3) by Ryan Hellyer
Disable XML-RPC (v1.0.1) by Philip Erb
FooBox HTML & Media Lightbox (v2.3.2.37) by FooPlugins
Glue for Yoast SEO & AMP (v0.3.3) by Joost de Valk
Google XML Sitemap for Videos (v2.6.1) by Amit Agarwal
Instant Articles for WP (v3.2.2) by Automattic, Dekode, Facebook
Limit Login Attempts (v1.7.1) by Johan Eenfeldt
Mobile Smart (vv1.3.16) by Dan Smart
Pagebar2 (v2.65) by Lutz Schröer
PinkCakeBox Search (v1.0) by Gabriel Franco
Related Posts (v3.6) by Zemanta
Scroll Triggered Box (v2.3) by Dreamgrow Digital
Search Meter (v2.13.2) by Bennett McElwee
Smart Youtube PRO (v4.3) by Vladimir Prelovac
Ultimate Social (v6.0.7) by WPSmarter
Varnish HTTP Purge (v4.0.2) by Mika Epstein
Velvet Blues Update URLs (v3.2.7) by VelvetBlues.com
WP Offload S3 Lite (v1.1.4) by Delicious Brains
WP Retina 2x (v4.7.5) by Jordy Meow
WordPress Database Backup (v2.3.1) by Austin Matzko
Yoast Breadcrumbs (v0.8.5 Customized) by Joost de Valk
Yoast SEO (v4.0.2) by Team Yoast
jQuery Pin It Button For Images (v2.1.2) by Marcin Skrzypiec

**Comment by aaemnnosttv** [comment]
To answer your questions:

> What are you replacing the S3 URL with?

URLs are filtered to their "local" non-S3 versions - the same as if URL rewriting was disabled.

> If an image was not included as an attachment (but merely added to the post via a url like: `<img src="https://images.pinkcakebox.com/first-birthday-creative-cakes-950x633.jpg" alt="Creative 1st Birthday Cakes " width="950" height="633" class="aligncenter size-large wp-image-6650" />`) will it upgrade these as well?

Yes. The filtering is smart enough to identify images which are attachments by URL only as well :)

I'm going to close this out due to it's age, but for anyone else coming here for a similar problem, please see our document about background processes stalling here: https://deliciousbrains.com/wp-offload-s3/doc/background-processes-not-completing/
