### ISSUE TITLE
1.1 removes the "s3 and cloudfront' menu item

### ISSUE THREAD

**Issue by davecarlson** [deliciousbrains/wp-amazon-s3-and-cloudfront#343]
Upon upgrading to 1.1, I no longer have the option to edit the settings. All I see now is access tokens & addons. 

I have confirmed this on 2 websites.

**Comment by A5hleyRich** [comment]
Hi @davecarlson 

This usually happens when the Amazon Web Services plugin hasn't been updated. Can you confirm the version?

**Comment by davecarlson** [comment]
Ah yes, it was on 0.3.7 ( but wasn't offering an upgrade to 1.0 ). 

I've updated and now this works - thanks.
