### ISSUE TITLE
AWS URL reverting to domain URL on Update

### ISSUE THREAD

**Issue by cejayassoc** [deliciousbrains/wp-amazon-s3-and-cloudfront#345]
Hello, we've just updated the plugins Amazon Web Service to 1.0 and WP Offload S3 Lite to version 1.1 (the most recent update.)  Now, when we embed an image it shows the cloudfront URL, but when we preview/update the post/page, the URL reverts to the URL of the domain.

WordPress Version 4.6.1
Our Theme is Divi, which was just updated to 3.0.13

Other plugins we are using include (ones in Bold were updated at the same time)

- Content Views and Content Views Pro (by PT Guy)
-  Duplicate Post
**- Enhanced Media Library**
- Facet WP by Facet WP, LLC
**- iTHemes  Security by iTHemes**
**- Jetpack (enabled modules: Site Stats, Sharing, Tiled Galleries, amd Extra Sidebar Widgets)**
**- MasterSlider Pro by Averta**
**- Ninja Forms** 
- Page Links to (by Mark Jaquith)
- UpdraftPlus by UpdraftPlus.com
**- UserRole Editor by Vladimir Garagulya**
**- WP All Import by Soflyy**
**- WP Smush by WPMU DEV**
- WP-Optimize by Ruhani Rabin

**Comment by A5hleyRich** [comment]
I'm unable to replicate this with Divi. Can you provide the exact steps to replicate the issue?

**Comment by cejayassoc** [comment]
I can reproduce this in more than one way:

1.       In a Divi text module, click the “Add Media” button to add an image.  

a.       Choose an image in the library or upload an image already there

b.       In the text view of the module the cloudfront domain is shown

c.       Click “Save & Close” on the Module

d.       Click Preview…image broken in preview

e.       Edit the text module and notice URL has been re-written to www.harborstyle.com <http://www.harborstyle.com>  and is no longer the cloudfront url

2.       In the media library, copy the url of the image (which does have the cloudfront domain)

a.       In the text module, text view, replace the harborstyle.com url with the cloudfront url

b.       Click “Save & Close” on the Module

c.       Click Preview…image broken in preview

d.       Edit the text module and notice URL has been re-written to www.harborstyle.com <http://www.harborstyle.com>  and is no longer the cloudfront url

 

Sincerely,

 

Lisa Baird

Developer

CeJay Associates, LLC

PH:  941.916.2555

 <http://www.cejayassoc.com/> www.CeJayAssoc.com

Website Development & Internet Marketing

**Comment by A5hleyRich** [comment]
I'm still not seeing this behavior with the steps outlined.

Image added to test widget and page saved. Database content:

```
[et_pb_section admin_label="section"][et_pb_row admin_label="row"][et_pb_column type="4_4"][et_pb_text admin_label="Text" background_layout="light" text_orientation="left" use_border_color="off" border_color="#ffffff" border_style="solid"]

<a href="http://wordpress.dev/wp-content/uploads/2016/10/0480_wESKMSgZJDo.jpeg"><img src="http://wordpress.dev/wp-content/uploads/2016/10/0480_wESKMSgZJDo-1024x577.jpeg" alt="0480_weskmsgzjdo" width="1024" height="577" class="alignnone size-large wp-image-42" /></a>

[/et_pb_text][/et_pb_column][/et_pb_row][/et_pb_section]
```

<img width="1552" alt="edit page wordpress wordpress" src="https://cloud.githubusercontent.com/assets/1422996/19431628/270c8b8c-9451-11e6-85e1-2026970018c3.png">

<img width="1552" alt="edit page wordpress wordpress" src="https://cloud.githubusercontent.com/assets/1422996/19431632/29450d2a-9451-11e6-81cb-c81b5b55b3e1.png">

Please can you confirm your custom domain settings?

**Comment by cejayassoc** [comment]
I have just updated WP Offload S3 Lite to version 1.1.1 and re-tested.  It is working fine now.  Thanks!
