### ISSUE TITLE
Error fetching buckets — Internal Server Error

### ISSUE THREAD

**Issue by AndrewNMathews** [deliciousbrains/wp-amazon-s3-and-cloudfront#346]
site_url(): http://jottergo.com
home_url(): http://jottergo.com
Database Name: wordpress
Table Prefix: wp_
WordPress: 4.6.1
Web Server: Apache/2.4.18 (Ubuntu)
PHP: 7.0.8-0ubuntu0.16.04.3
MySQL: 5.7.15
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 4 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 16 MB
PHP Time Limit: 60
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2g  1 Mar 2016
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 244
Media Files on S3: 0
Number of Image Sizes: 12

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1000x450)
shop_thumbnail (250x188)
shop_catalog (400x300)
shop_single (800x600)
post-thumbnail (none)
hosthubs-thumb-masonry-square (600x600)
hosthubs-thumb-masonry-84 (800x400)
hosthubs-thumb-masonry-48 (400x800)
hosthubs-thumb-86 (800x600)

WP_CONTENT_DIR: /var/www/html/wp-content
WP_CONTENT_URL: http://jottergo.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_PLUGIN_URL: http://jottergo.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: 
Region: 
Copy Files to S3: Off
Rewrite File URLs: Off

Local URL:
http://jottergo.com/wp‑content/uploads/2016/10/photo.jpg
S3 URL:
http://s3.amazonaws.com//wp‑content/uploads/2016/10/22035925/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: WP Hosthubs
Active Theme Folder: wp-hosthubs

Active Plugins:
Amazon Web Services (v1.0) by Delicious Brains
Cmssuperheroes (v1.0.9.2) by Luan Nguyen, Cong Nguyen
Contact Form 7 (v4.5.1) by Takayuki Miyoshi
Custom Post Type UI (v1.4.3) by WebDevStudios
EF3 Import And Export (v1.1.3) by FOX
EF3-Framework (v1.0.4) by FOX
News Twitter (v1.0.5) by FOX
Newsletter (v4.6.7) by Stefano Lissa & The Newsletter Team
Slider Revolution (v5.2.6) by ThemePunch
VC Bootstrap Tabs (v1.0.0) by FOX
WHMCS Bridge (v3.7.4) by globalprogramming
WP Offload S3 Lite (v1.1.1) by Delicious Brains
WPBakery Visual Composer (v4.12.1) by Michael M - WPBakery.com
WooCommerce (v2.6.6) by WooThemes

Must-use Plugins:
WP fail2ban (v3.5.3) by Charles Lecklider

**Comment by A5hleyRich** [comment]
An internal server error will generate an error message. Can you try editing your wp-config.php file to replace this line - 

`define( 'WP_DEBUG', false );`

With these lines - 

```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false); 
```

This means that any errors are logged to `/wp-content/debug.log`, because some errors are not visible on screen. More details about that at http://codex.wordpress.org/Editing_wp-config.php#Debug

**Comment by rafaelsigues** [comment]
I switched hosting and now I'm seeing this error as well. I already activated debug.log and the error logging is this below. Please, could you help me?

[13-Feb-2018 15:36:52 UTC] PHP Fatal error:  Uncaught Error: Class 'SimpleXMLElement' not found in /var/www/html/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Message/Response.php:886
Stack trace:
#0 /var/www/html/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/LocationVisitor/Response/XmlVisitor.php(17): Guzzle\Http\Message\Response->xml()
#1 /var/www/html/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/OperationResponseParser.php(134): Guzzle\Service\Command\LocationVisitor\Response\XmlVisitor->before(Object(Aws\S3\Command\S3Command), Array)
#2 /var/www/html/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/OperationResponseParser.php(86): Guzzle\Service\Command\OperationResponseParser->visitResult(Object(Guzzle\Service\Description\Parameter), Object(Aws\S3\Command\S3Command), Object(Guzzle\Http\Message\Response))
#3 /var/www/html/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/DefaultResponseParser.php(39): Guzzle\Service\Command\Operatio in /var/www/html/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Message/Response.php on line 886

**Comment by A5hleyRich** [comment]
Looks like the XML PHP module isn't installed. You'll need to speak to your hosting provider about this.

**Comment by r4f43ls1gu3s** [comment]
solved the problem: `apt-get install php7.0-xml` AND `service apache2 restart`
