### ISSUE TITLE
Issue with Divi theme relative to the Divi global libraries

### ISSUE THREAD

**Issue by fidjius** [deliciousbrains/wp-amazon-s3-and-cloudfront#348]
Hello,
I am using WP Offload S3 Pro 1.2.1 with an active 500k licence and 102,000 media files on S3. Every media is uploaded to S3, nothing is kept on the web server.
I am using latest Divi theme 3.0.16.

In my Wordpress site, I used to create many global libraries with Divi that I can reuse on different pages.

The issue occurs when there is an image in a Divi global library. The S3 link of the image is stored in the library, that is OK.

But when I import this **global** library in a page, this is not the S3 link of the image that is displayed anymore but the URL of the image on the website. And that makes a broken image link on the website.

When the Divi library is not set as global, there is no problem.

Please help! Thank you in advance.

Best regards

**Comment by lakewoodmedia** [comment]
We are still experiencing this issue with Divi and global modules.

**Comment by aaemnnosttv** [comment]
For Offload S3 license holders, please send us a support request by visiting the Help tab of your install and using the support form.

We are currently working with Divi to resolve conflicts with the theme.
