### ISSUE TITLE
After upgrade from 1.1.1 to 1.1.2 getting "Running 1.2 Upgrade (0% Complete)" message in Admin page

### ISSUE THREAD

**Issue by decarvalhoaa** [deliciousbrains/wp-amazon-s3-and-cloudfront#351]
I have just upgraded Offload S3 **Lite** from 1.1.1 to 1.1.2 and I'm seeing the following message on the top of the plugin's admin page.

> **Running 1.2 Upgrade (0% Complete)**
> A find & replace is running in the background to update URLs in your content. See our documentation for details on why we’re doing this, why it runs slowly, and how to make it run faster. Pause Update

Please note that the find & replace process has already finished successfully after the upgrade to 1.1.1.

I suspect that some Offload S3 version 1.2 made it to the master of the Offload S3 Lite 1.1.2 release.

**Comment by A5hleyRich** [comment]
Hi,

Can you post the contents of your `tantan_wordpress_s3` option from the wp_options table?

> I suspect that some Offload S3 version 1.2 made it to the master of the Offload S3 Lite 1.1.2 release.

The upgrade routines are shared across the two plugins, so that's not the issue. It's more likely that the notice is stuck if the upgrade has already completed.

**Comment by decarvalhoaa** [comment]
Here you go

> a:13:{s:17:"post_meta_version";i:5;s:6:"bucket";s:18:"thelittlecraft-dev";s:6:"region";s:12:"eu-central-1";s:6:"domain";s:10:"cloudfront";s:10:"cloudfront";s:0:"";s:13:"object-prefix";s:0:"";s:10:"copy-to-s3";s:1:"1";s:13:"serve-from-s3";s:1:"1";s:17:"remove-local-file";s:1:"0";s:17:"object-versioning";s:1:"1";s:21:"use-yearmonth-folders";s:1:"1";s:20:"enable-object-prefix";s:1:"1";s:11:"force-https";b:0;}

Regarding

> The upgrade routines are shared across the two plugins, so that's not the issue. It's more likely that the notice is stuck if the upgrade has already completed.

well when I upgraded to 1.1.1, the message was Running 1.1.1 Upgrade indicating the right version. If the upgrade code is shared, it would be best to indicate the correct version of the plugin, i guess.

**Comment by A5hleyRich** [comment]
Your `tantan_wordpress_s3` option shows that the upgrade has completed. Can you try removing any occurrences of the `as3cf_notices` from both the wp_options and wp_usermeta tables. That should remove the notice.

**Comment by decarvalhoaa** [comment]
I don't have any `as3cf_notices` in neither of the wp_options nor wp_usermeta tables.

Just for curiosity, how to you know the upgrade process as completed from the content of `tantan_wordpress_s3`? is it the `post_meta_version`?

**Comment by decarvalhoaa** [comment]
I just try upgrading my pre-prod environment that is a near replica of production and didn't get the notice issue I got in the development environment. Below you can find the content of `tantan_wordpress_s3` in the pre-prod environment. 

I notice that in the dev environment I turned ON the `CloudFront or Custom Domain` feature but left the field blank, where in the pre-prod env this was properly configured. Is this different/the Cloudfront domain field relevant for the Upgrade process?

`a:13:{s:17:"post_meta_version";i:5;s:6:"bucket";s:22:"thelittlecraft-preprod";s:6:"region";s:12:"eu-central-1";s:6:"domain";s:10:"cloudfront";s:10:"cloudfront";s:32:"media-preprod.thelittlecraft.com";s:13:"object-prefix";s:19:"wp-content/uploads/";s:10:"copy-to-s3";s:1:"1";s:13:"serve-from-s3";s:1:"1";s:17:"remove-local-file";s:1:"0";s:11:"force-https";s:1:"0";s:17:"object-versioning";s:1:"1";s:21:"use-yearmonth-folders";s:1:"1";s:20:"enable-object-prefix";s:1:"0";}`

**Comment by ianmjones** [comment]
It's possible that that blank CloudFront domain is causing you issues.

Can you check the raw `post_content` field in a few posts to determine whether they still hold S3 URLs? If they do, make sure your WP Offload S3 settings match their configuration, e.g. set the CloudFront domain or turn off that setting, and then "Save Changes".

Then update the `tantan_wordpress_s3` setting to so that "post_meta_version" has a value of 3 rather than 5.

**Comment by decarvalhoaa** [comment]
Seems that the empty CloudFront domain did create the issue. I guess that a is input empty validation will help preventing problems going forward.

Although there were no S3 urls in the posts, the progress is no longer stuck and at some point ended and the notice was removed. The message nonetheless, was referring Release 1.2 and I'm not using that release - I'm using the Lite version. A minor issue but perhaps you guys want to check that out.

**Comment by ianmjones** [comment]
Thanks @decarvalhoaa.
