### ISSUE TITLE
After update to v1.1.3 media-permissions in amazon s3 not working

### ISSUE THREAD

**Issue by spreadmind-anke** [deliciousbrains/wp-amazon-s3-and-cloudfront#355]
Hi there,

after updating WP Offload S3 to v1.1.3 I got the following issue: 

My media files are uploaded to amazon s3. But the permission for the files says: 

**Grantee: "Me" – Open/Download (checked); View Permissions (checked); Edit Permissions (checked)**

But this permission is _completely_ missing: 

**Grantee: "Everyone" – Open/Download (checked); View Permissions (unchecked); Edit Permissions (unchecked)**

So that means that in my wordpress media I cannot see the uploaded image and the amazon-s3-upload-URL is also not working. I'm getting an error: "Access denied". Therefor I'm not able to use them. 

Best, Anke

**Comment by spreadmind-anke** [comment]
Some more informations regarding this problem: 

It seems that it's only not working with images which size is smaller than 400 x 400 px or 300 x 300 px. In Amazon S3 the 300x300 thumbnail is not being created. 

With an larger image (e.g. 1200px x 1800px) it is working fine.

**Comment by ianmjones** [comment]
@spreadmind-anke Please could you post your Diagnostic Info from the Support tab of WP Offload S3 Lite.

**Comment by spreadmind-anke** [comment]
Sorry -- here you go @ianmjones : 

site_url(): https://spreadmind.de
home_url(): https://spreadmind.de
Database Name: c10_spreadmind
Table Prefix: s8h32_
WordPress: 4.6.1 Multisite
Multisite Site Count: 95
Web Server: nginx/1.10.2
PHP: 7.0.13-1~dotdeb+8.1
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 196M
WP Memory Limit: 196M
Memory Usage: 2 MB
Blocked External HTTP Requests: None
WP Locale: de_DE
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 244 MB
PHP Time Limit: 300
PHP Error Log: 
WP Cron: Disabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1t  3 May 2016
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 5.440
Media Files on S3: 4.812
Number of Image Sizes: 4

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)

WP_CONTENT_DIR: /var/www/clients/client10/web485/web/wp-content
WP_CONTENT_URL: https://spreadmind.de/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/clients/client10/web485/web/wp-content/plugins
WP_PLUGIN_URL: https://spreadmind.de/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: spreadmind
Region: eu-central-1
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
https://spreadmind.de/wp‑content/uploads/2016/12/photo.jpg
S3 URL:
https://s3‑eu‑central‑1.amazonaws.com/spreadmind/wp‑content/uploads/2016/12/08115947/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: On
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Headway Base
Active Theme Folder: headway

Active Plugins:
Admin Menu Editor Pro (v2.4.2) by Janis Elsts
Amazon Web Services (v1.0) by Delicious Brains
Domain Mapping (v4.4.2.4) by WPMU DEV
EDD-NBT-Creator-AddOn (v1.2.0) by WebDevDesign by André Schneider
Multisite Plugin Manager (v3.1.5) by Aaron Edwards
Multisite Privacy (v1.1.8.6) by WPMU DEV
New Blog Templates (v2.8.3) by WPMU DEV
Spreadmind Customization (v1.2) by Jan Thiel
Spreadmind Earnings EDD-Widget (v1.0.2) by WebDevDesign by André Schneider
Ultimate Branding (v1.8.2) by WPMU DEV
Unfiltered MU (v1.3.1) by Automattic
WP Offload S3 Lite (v1.1.3) by Delicious Brains
WP Smush Pro (v2.5.2) by WPMU DEV
WP fail2ban (v3.5.3) by Charles Lecklider
WP-Piwik (v1.0.14) by André Bräkling
WPMU DEV Dashboard (v4.2) by WPMU DEV
iThemes Security (v5.8.0) by iThemes

**Comment by ianmjones** [comment]
Do you have anything in your functions.php file that might be changing the ACL for uploaded files?

Or do you have any policies on your bucket that might be enforcing an ACL?

**Comment by spreadmind-anke** [comment]
Thanks for your response. 

No we do not have anything changed in the functions.php file. Nor any policies on our bucket.

**Comment by spreadmind-anke** [comment]
Are there any updates related to my issues? It's still not working.

**Comment by ianmjones** [comment]
Hi @spreadmind-anke, we can't think of anything that'll have that kind of effect other than implementing one of our `upload_acl` filters in one of your plugins, theme, or the functions.php file, or by setting a policy in AWS, most likely on the bucket.

If it's definitely nothing set in AWS, then you could try searching your site's code for the "as3cf_upload_acl" filter to see if something is overriding the ACL when WP Offload S3 Lite uploads to S3.

**Comment by spreadmind-anke** [comment]
Hi @ianmjones, I think we found the problem. As soon as we deactivated the plugin "WP Smush Pro" the images do get the missing permission "Grantee: Everyone – [yes] Open/Download". 

Thank you for your help though, really appreciated it.

**Comment by ianmjones** [comment]
Thanks for letting us know @spreadmind-anke, we'll keep an eye out for WP Smush Pro if anyone else has similar problems.
