### ISSUE TITLE
Copy local WordPress folder structure to S3?

### ISSUE THREAD

**Issue by xjlin0** [deliciousbrains/wp-amazon-s3-and-cloudfront#359]
Hi there,

First, thanks for all the efforts and it's such a great work!

I am wondering when uploading files in folders on the WordPress site, will this plugin create and maintain the same folder structure on S3 buckets (custom folders, other then year/month)?  I tried but the custom folder structure in WordPress side are not replicated on the S3 buckets, browsed in AWS management console.

Thanks again and have a wonderful one!

**Comment by ianmjones** [comment]
Hi @xjlin0,

No, WP Offload S3 creates specific file paths on S3 based on the options you select in its settings, such as using a custom path prefix, using year/month, and using an object version prefix.
