### ISSUE TITLE
amazonS3_cache exploding in size

### ISSUE THREAD

**Issue by achbed** [deliciousbrains/wp-amazon-s3-and-cloudfront#360]
We support a moderately large site with thousands of posts and assets. We have started to see the amazonS3_cache entries in the wp_postmeta table explode in size.  The cache data arrays are between 400 and 900 items, and now consume about 1GB of storage in the database.  This seems a little excessive.

Can we (a) turn this off, and/or (b) identify a better way to manage these cached values?  Larger operations use Redis and other static caches - perhaps that would be a better place to store cached values such as these.

**Comment by achbed** [comment]
Diagnostic info:

site_url(): https://www.indagare.com
home_url(): https://www.indagare.com
Database Name: indagarewp
Table Prefix: wp_
WordPress: 4.6.1
Web Server: Apache
PHP: 5.5.9-1ubuntu4.20
MySQL: 5.5.53
ext/mysqli: yes
PHP Memory Limit: 512M
WP Memory Limit: 512M
Memory Usage: 17 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Disabled
WP_DEBUG: No
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 96 MB
PHP Time Limit: 90
PHP Error Log: /var/log/php/php_errors.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 46,376
Media Files on S3: 46,375
Number of Image Sizes: 11

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
hero-full (940x460)
hero-medium (620x300)
hero-review (620x413)
thumb-large (300x200)
thumb-feature (450x375)
thumb-medium (220x146)
thumb-small (140x95)

WP_CONTENT_DIR: /var/www/indagare.com/public_html/wp-content
WP_CONTENT_URL: https://www.indagare.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/indagare.com/public_html/wp-content/plugins
WP_PLUGIN_URL: https://www.indagare.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: images.indagare.com
Region: 
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
https://www.indagare.com/wp‑content/uploads/photo.jpg
S3 URL:
https://s3.amazonaws.com/images.indagare.com/wp‑content/uploads/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: Off
Force HTTPS: Off
Remove Files From Server: On
Object Versioning: Off

Active Theme Name: Indagare
Active Theme Folder: indagare
Parent Theme Folder: thematic

Active Plugins:
AJAX Thumbnail Rebuild (v1.12) by junkcoder
Adminimize (v1.11.2) by Frank Bültge
Advanced Custom Fields (v4.4.11) by Elliot Condon
Advanced Custom Fields - Location Field add-on (v1.0) by Julien Bechade
Advanced Custom Fields: Gallery Field (v1.1.1) by Elliot Condon
Advanced Custom Fields: Options Page (v1.2.0) by Elliot Condon
Advanced Custom Fields: Repeater Field (v1.1.1) by Elliot Condon
Advanced Custom Fields: WP WYSIWYG (v1.0.0) by Elliot Condon
Akismet (v3.2) by Automattic
Amazon Web Services (v1.0.1) by Delicious Brains
Back End Category Search (v0.2) by Jason Corradino
Bulk Password Reset (v1.3.3) by Ruben Woudsma
Contact Form 7 (v4.6) by Takayuki Miyoshi
Contact Form 7 - Dynamic Text Extension (v2.0.1) by Chris Mavricos, SevenSpark
Contact Form 7 Honeypot (v1.10) by Nocean
Custom Content Types - Indagare (v2.4.0) by Dennis Wallace
Custom Forgot Password Mail (v2.0) by Coral Web Design, whiteboardlabs.com
Custom Login (v3.2.5) by Austin Passy
Disable Emojis (v1.5.3) by Ryan Hellyer
Display PHP Version (v1.4) by David Gwyer
Enable Media Replace (v3.0.5) by Måns Jonasson
Exclude Pages from Navigation (v1.92) by Simon Wheatley
Favicon by RealFaviconGenerator (v1.3.9) by Philippe Bernard
Google Analytics by MonsterInsights (v5.5.4) by MonsterInsights
HubSpot Tracking Code for WordPress (v1.1.0) by HubSpot
ManageWP - Worker (v4.2.16) by ManageWP
Media Library Assistant (v2.41) by David Lingren, Fair Trade Judaica
Multiple Post Thumbnails (v1.6.6) by Chris Scott
New RoyalSlider (v3.1.4) by Dmitry Semenov
Page Links To (v2.9.6) by Mark Jaquith
Post Duplicator (v2.19) by Metaphor Creations
Redirection (v2.5) by John Godley
Relevanssi Premium (v1.13.5) by Mikko Saari
Rename wp-login.php (v2.5.5) by Ella Iseulde Van Dorpe
SHR: Stop Emails (v1.0.0) by 
SSH SFTP Updater Support (v0.7.1) by TerraFrost
Salesforce Integration (v1.3.3) by SHR
Sucuri Security - Auditing, Malware Scanner and Hardening (v1.8.3) by Sucuri, Inc
User Role Editor (v4.31.1) by Vladimir Garagulya
WP Offload S3 Lite (v1.1.5) by Delicious Brains
WP-Mail-SMTP (v0.10.1) by Callum Macdonald
Yoast SEO (v4.0.2) by Team Yoast
cbnet Multi Author Comment Notification (v3.2) by chipbennett


Drop-ins:
object-cache.php - Memcached

**Comment by A5hleyRich** [comment]
Hi,

You can't disable this feature, because it greatly improves the performance of filtering URLs, which was introduced in WP Offload S3 1.2.

https://deliciousbrains.com/wp-offload-s3-1-2-released/

Each post should have a single `amazonS3_cache`, which maps attachment URLs to their ID. These postmeta entries should be fairly small in size. Is this not the case?

I agree that having the option to store these values in an external data store would be advantageous. I've raised an issue for the team to investigate.

**Comment by achbed** [comment]
The issue is one of scale. The pages/posts have links (and images) to relevant other content.  This changes all the time.  As a result, every post will eventually cache links for every image on the system.

Also, we went through a site transition from http to https.  It appears that all the old http urls are still cached even thought they aren't needed any more.  This probably also doubled the cache size overnight.

When you have a site that's about 13K posts and has 46K images, that starts to add up.  In the end, we have 13K database entries using up 962,634,630 bytes of string storage in the wp_postmeta table.  Some other way to store that data would be helpful (a separate table, an external cache mechanism) would be one idea.  Allowing cache entries to expire would be another.  I'm attaching one typical entry in our database.
[average amazonS3_cache entry.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/706046/average.amazonS3_cache.entry.txt)

**Comment by achbed** [comment]
I think I'm slowly coming around to what the underlying logic process is and the compromises made in the replacement of URLs. I believe the core of the issue ends up being that we can't use a single large data cache that contains all the urls used in the find/replace step because that gets too large too quickly. So, as a result, we need to segment that data set.  Storing them by post makes sense to reduce the number of calls to the database as this will logically group them into much smaller buckets, increasing efficiency and speed.

I'm leaning more towards a persistent cache (if present) by post_id being the best solution.  Yes, this adds some work on page load if the cache gets cleared, but we can recover from that fairly quickly.

**Comment by aaemnnosttv** [comment]
The handling of the `amazonS3_cache` has been greatly improved in v1.2. If you already had large entries, you should see these consolidate into much more reasonable values as the respective posts are accessed.
