### ISSUE TITLE
Unable to save bucket configuration

### ISSUE THREAD

**Issue by pramanikshreya** [deliciousbrains/wp-amazon-s3-and-cloudfront#362]
I just installed the latest plugin and activated them, then we tried to save the bucket name, the following was the error :
Error saving bucket — Error Getting Bucket Region —There was an error attempting to get the region of the bucket uemgroup: Missing required client configuration options: region: (string) A "region" configuration value is required for the "s3" service (e.g., "us-west-2"). A list of available public regions and endpoints can be found at http://docs.aws.amazon.com/general/latest/gr/rande.html. version: (string) A "version" configuration value is required. Specifying a version constraint ensures that your code will not be affected by a breaking change made to the service. For example, when using Amazon S3, you can lock your API version to "2006-03-01". Your build of the SDK has the following version(s) of "s3": * "2006-03-01" You may provide "latest" to the "version" configuration value to utilize the most recent available API version that your client's API provider can find. Note: Using 'latest' in a production application is not recommended. A list of available API versions can be found on each client's API documentation page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are unable to load a specific API version, then you may need to update your copy of the SDK.

Attached a debug log file:
[uem.edu_.in-diagnostic-log-20170128083319.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/736787/uem.edu_.in-diagnostic-log-20170128083319.txt)

**Comment by A5hleyRich** [comment]
This error usually occurs when you're using a different version of the AWS SDK. Please see https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/267
