### ISSUE TITLE
S3 Image URL Replacement fails with multiple local domains

### ISSUE THREAD

**Issue by PhilippHeuer** [deliciousbrains/wp-amazon-s3-and-cloudfront#363]
There is a bug when you can access wordpress from 2 domains.
- test.com
- test.de

The image links aren't correctly replaced with the s3 links.

If i insert the image using the control panel at test.com/wp-admin then the links are broken on test.de and vice versa.
It only works on domain i used when i inserted the image in the control panel.

By broken links i mean that wordpress searches for the files locally in wp-content/uploads and isn't using the s3/cloudfront urls.

**Comment by ianmjones** [comment]
@PhilippHeuer Are you using any domain mapping plugins?

Can you give us your Diagnostic Info from the Help tab?

**Comment by PhilippHeuer** [comment]
I am not using any domain mapping plugins.

## Diagnostic Info

site_url(): http://**domain**/wp
home_url(): http://**domain**
Database Name: t9c40zesgqlkkdl7
Table Prefix: wp_
WordPress: 4.7.2
Web Server: nginx/1.8.1

PHP: 7.1.1
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 2 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 32 MB
PHP Time Limit: 30
PHP Error Log: /tmp/heroku.php-fpm.www.46583.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled
PHP GD: Disabled
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 1
Media Files on S3: 1
Number of Image Sizes: 7

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
post-thumbnail (none)
large-feature (1000x288)
small-feature (500x300)

WP_CONTENT_DIR: /app/web/app
WP_CONTENT_URL: http://**domain**/app
UPLOADS: Not defined
WP_PLUGIN_DIR: /app/web/app/plugins
WP_PLUGIN_URL: http://**domain**/app/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: **bucketNameHidden**
Region: eu-central-1
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://**domain**/app/uploads/2017/01/photo.jpg
S3 URL:
https://s3‑eu‑central‑1.amazonaws.com/**bucketNameHidden**/app/uploads/2017/01/31102106/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: app/uploads/
Use Year/Month: On
Force HTTPS: On
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Twenty Eleven
Active Theme Folder: twentyeleven

Active Plugins:
Amazon Web Services (v1.0.1) by Delicious Brains
WP Offload S3 Lite (v1.1.5) by Delicious Brains

Must-use Plugins:
Bedrock Autoloader (v1.0.0) by Roots
Disallow Indexing (v1.0.0) by Roots
Register Theme Directory (v1.0.0) by Roots

**Comment by ianmjones** [comment]
How are you able to log into WP and upload media with the non-default domain?

For example, I can set up a site that uses test.com as its default domain, but view it as test.de too with no problems (including WP Offload S3 filtering to S3 URLs).

If I try and log in to test.de I will get re-directed to test.com, always.

This means I can only edit posts and upload media while on the default test.com domain, and even though I'm later viewing test.de WP Offload S3 will filter the local test.com URLs to S3 URLs.

Normally a site uses domain mapping or localization/translation plugins when setting up alternate domains, so that default domain URLs are filtered to match the accessing domain.

**Comment by PhilippHeuer** [comment]
Thats because your WP_HOME/WP_SITEURL are still set to the .com domain, if you change those to .de link-replacement will break for images you added while it was still set to .com.

To fix those login/link issues, i added the following code. This sets WP_HOME and WP_SITEURL and all other links correctly regardless of which domain is used to access it.
There are reasons that i need to do it like this ;)
```php
if (array_key_exists('HTTP_X_FORWARDED_PROTO', $_SERVER) && $_SERVER["HTTP_X_FORWARDED_PROTO"] == 'https') {
    $_SERVER['HTTPS'] = 'on';
}
$_http_host_schema = array_key_exists('HTTPS', $_SERVER) && $_SERVER['HTTPS'] == 'on' ? 'https' : 'http';
$_http_host_name = array_key_exists('HTTP_HOST', $_SERVER) ? $_SERVER['HTTP_HOST'] : 'localhost';
$_server_http_url = $_http_host_schema."://".$_http_host_name;

define('WP_HOME', env('WP_HOME') ?: $_server_http_url);
define('WP_SITEURL', env('WP_SITEURL') ?: $_server_http_url."/wp");
```

Im currently building a one-click-deploy wordpress package for Heroku and want to add this plugin by default, since heroku's local disk isn't persistent. (local media files are deleted anyway)
If you want to take a look at my source code you can click [here](https://github.com/philippheuer/wordpress-heroku).

**Comment by ianmjones** [comment]
WP Offload S3 uses the `wp_upload_dir()` function to get what WordPress considers to be the local paths and URLs, the most important for filtering being the returned `baseurl` component.

As long as the URLs saved to the content match what `wp_upload_dir()` provides, then WP Offload S3 will be able to find attachments based on URL matching if the `img` tag doesn't include the standard `wp-image-NNN` class that defines the attachment id.

If however you have switched the default URL without doing a find and replace of your existing content, or are inserting URLs for a number of aliased domains without mapping them back to the default domain on render, then WP Offload S3 has no chance of finding attachments by their local URL if saved with a different domain to the current default.

**Comment by PhilippHeuer** [comment]
Thanks for your fast responses. I set the default URL based on each visitor, so a find/replace isn't possible.

I can define a primary domain and use a domain mapping plugin to get this working, though i would prefer not to.

According to your answer, shouldn't the matching work based on the `wp-image-NNN` class even before url matching will be tried?
It does not right now, my images all have that class fe. `wp-image-11` in the `img` tag.

**Comment by ianmjones** [comment]
WP Offload S3 goes through each post being rendered and filters URLs based on their `wp-image-NNN` class, and if any URLs escape that then another attempt to match them with local media and therefore S3 URLs is made.

Can you give an example URL that isn't being matched?

**Comment by PhilippHeuer** [comment]
It's the url directly inserting using wordpress insert media button.

```html
<img src="https://SERVER/uploads/2017/01/1024x500.png" alt="" width="1024" height="500" class="alignnone size-full wp-image-18" />
```

**Comment by ianmjones** [comment]
WP Offload S3 Lite 1.3.2 was released a little while ago with the ability to filter the "local domains" to add additional domains that should be matched during URL rewriting.

Please see https://deliciousbrains.com/wp-offload-s3/doc/filtering-urls-for-multiple-domains/ for further details.
