### ISSUE TITLE
WP Image editing broken using s3 protocol

### ISSUE THREAD

**Issue by tdinatale** [deliciousbrains/wp-amazon-s3-and-cloudfront#364]
We are using version 1.1.5 of WP Offload S3 Lite.

When going into edit an image in WP the image is broken. When I inspect the broken image and go to the WP ajax request directly, I just see -1, which I know is some sort of WP permission error. After reverse engineering WP core code, I found that it is trying to load a valid image stored in S3 via s3://bncore/wp-content/uploads/2016/08/IMG_1017-1.jpg. This does not appear to be working. When I go to the https version of the URL for the same image, https://s3.amazonaws.com/bncore/wp-content/uploads/2016/08/IMG_1017-1.jpg, it works fine.

Also if I comment out line 16 in:
wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-stream-wrapper.php
stream_wrapper_register( $protocol, __CLASS__, STREAM_IS_URL );
The S3 protocol does not register and I am able to edit the image in WP.

We're using a multi site installation of WP and on a load balanced setup, if that helps.

It does not happen on all images. Is this tied to the upgrade procedure that is running?

It only happens when trying to edit an image. All other places the image displays fine.

Is there a way I can disable the use of the s3 protocol and just use the https protocol version of the image URL? Or is there something else I need to do for this part of WP to understand the S3 protocol?

Thank you for your help!

**Comment by A5hleyRich** [comment]
Could be related to https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/320

What PHP version are you using?

**Comment by aaemnnosttv** [comment]
Going to close this out for now as support for image editing has been enhanced in v1.2.

If this is still an issue for you after upgrading, please feel free to re-open.
