### ISSUE TITLE
Regular expression causing seg faults and pages to exceed max execution time

### ISSUE THREAD

**Issue by RTC1** [deliciousbrains/wp-amazon-s3-and-cloudfront#365]
```
[Mon Feb 06 19:32:34.648178 2017] [core:notice] [pid 4033] AH00052: child pid 20584 exit signal Segmentation fault (11)

[Mon Feb 06 19:33:04.213663 2017] [:error] [pid 20600] [client 172.31.2.129:29192] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /var/app/current/web/app/plugins/amazon-s3-and-cloudfront/classes/as3cf-filter.php on line 251
````

This is permanently an issue on certain pages of the site, but I'm unsure how they differ from the pages which load fine. 

The issue has only occurred since updating to 1.1.4/1.1.5 and upgrading the tables. 

Tried testing with XLARGE EC2 instance (vs Mid/Small), which had no effect.

**Comment by A5hleyRich** [comment]
How large are the pages that cause the issue? Generally, this regular expression should only happen once per post/page as the results are cached. Can you please also post your debug information from the Support tab?

**Comment by RTC1** [comment]
Figured it out, someone had put a loop in the wrong place in the theme template! Thanks.
