### ISSUE TITLE
AWS S3 Images

### ISSUE THREAD

**Issue by chaitu1124** [deliciousbrains/wp-amazon-s3-and-cloudfront#366]
Hi All,

I have created a wordpress website in AWS(LAMP Server) and installed the following plugins.

->amazon web services
->amazon-s3-and-cloudfront

When I add images to page/post in media library the URL is pointing to S3 but in Data base wp-posts table it is pointing to local server.

In the website I clicked inspect and checked there also image URL pointing to S3. 

Images are loading properly in S3 bucket. From wordpress website it is clearly showing Image URL is pointing to S3 but when I checked in Database it is pointing to Local Server.

Please let me know how to fix this. In Database also the URL need to point to S3 URL.

Thanks,

**Comment by A5hleyRich** [comment]
This is intentional. The reasons are explained in this blog post:

https://deliciousbrains.com/wp-offload-s3-1-2-released/

**Comment by chaitu1124** [comment]
Hi, 

I am new to Wrodpress. May be this is a dump question. 

I am not using "WP Offload S3" plugin. I am using following plugins. 

->amazon web services
->**WP Offload S3 lite** 

Not sure "WP Offload S3" and "WP Offload S3 lite" are same. 

I have gone through the link which you post. I have a question on Migration, Suppose I am migrating a site from AWS S3 to Azure Blob, that time I need to replace the local site URL with Azure Blob site URL where ever attachment is there. am I right?

Thanks,

**Comment by ianmjones** [comment]
If the site's URL is changing when you migrate from one server to another, then yes, you need to update the URLs in your content and settings.

If you're continuing to use the same S3 objects then there is nothing to change for your S3 settings.

If you're intending to use a different bucket for the site on the new server, then you'll want to re-upload from the new site, so be sure to migrate your media too.

There's a [really nice plugin](https://deliciousbrains.com/wp-migrate-db-pro/) for migrating your site's database to a new server! 😉
