### ISSUE TITLE
Cant turn off Rewrite File URLs option

### ISSUE THREAD

**Issue by dking3876** [deliciousbrains/wp-amazon-s3-and-cloudfront#367]
the option will not save to not rewrite file urls on multiple sites and enviorments

**Comment by ianmjones** [comment]
@dking3876 Just a tiny bit more information might help us debug this. 😉 

Can you post diagnostic info from the the support tab?

Can you try turning on WP_DEBUG and WP_DEBUG_LOG to see what gets logged to wp-content/debug.log when you try the process again?

Can you check out the browser console to see if there are any errors there when you try the process again?

**Comment by aaemnnosttv** [comment]
Closing for now due to no response.
