### ISSUE TITLE
This item has not been copied to S3 yet.

### ISSUE THREAD

**Issue by data-compute-geek** [deliciousbrains/wp-amazon-s3-and-cloudfront#368]
I upload an image to the media library, but it is not uploaded to s3. When I got to the image details, a note says "This item has not been copied to S3 yet." and the file URL still points to my wordpress path, not an s3 path.

I double checked my AWS key and secret key in wp-config.php, and they are both correct.

Anyone has any idea?

**Comment by ianmjones** [comment]
Please enable WP_DEBUG, WP_DEBUG_LOG and turn off WP_DEBUG_DISPLAY and try the process again. Then please post wp-content/debug.log.
Please also post your Diagnostic Info from the help tab.

**Comment by data-compute-geek** [comment]
wp-content/debug.log

[14-Feb-2017 17:28:36 UTC] WPOS3: Error uploading /home3/happynut/public_html/wp-content/uploads/2017/02/s-l1600-2.jpg to S3: [curl] 77:  [url] https://seanlog.s3.amazonaws.com/wp-content/uploads/2017/02/14092836/s-l1600-2.jpg

Diagnostic Info
site_url(): http://seanlog.com
home_url(): http://seanlog.com
Database Name: happynut_wrdp1
Table Prefix: wp_
WordPress: 4.7.2
Web Server: Apache
PHP: 5.4.45
MySQL: 5.5.51
ext/mysqli: no
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 33 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 64 MB
PHP Time Limit: 30
PHP Error Log: /home3/happynut/public_html/wp-content/debug.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 38
Media Files on S3: 0
Number of Image Sizes: 6

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
post-thumbnail (none)
twentyfourteen-full-width (1038x576)

WP_CONTENT_DIR: /home3/happynut/public_html/wp-content
WP_CONTENT_URL: http://seanlog.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /home3/happynut/public_html/wp-content/plugins
WP_PLUGIN_URL: http://seanlog.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: seanlog
Region: 
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://seanlog.com/wp‑content/uploads/2017/02/photo.jpg
S3 URL:
https://s3.amazonaws.com/seanlog/wp‑content/uploads/2017/02/14093011/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: On
Remove Files From Server: On
Object Versioning: On

Active Theme Name: 2014 Child
Active Theme Folder: twentyfourteen-child
Parent Theme Folder: twentyfourteen

Active Plugins:
Amazon Web Services (v1.0.1) by Delicious Brains
Disqus Comment System (v2.86) by Disqus 
JW Player Plugin (v1.6.0) by JW Player
Jetpack by WordPress.com (v4.6) by Automattic
Limit Login Attempts (v1.7.1) by Johan Eenfeldt
Simple Custom CSS (v3.3) by John Regan, Danny Van Kooten
WP Add Custom CSS (v1.0.0) by Daniele De Santis
WP Offload S3 Lite (v1.1.5) by Delicious Brains
WP Super Cache (v1.4.9) by Automattic
Yoast SEO (v4.2.1) by Team Yoast


Drop-ins:
advanced-cache.php - advanced-cache.php

**Comment by ianmjones** [comment]
Do you have any policies added to the bucket?

If you didn't use the "Browse" method to select your bucket, In WP Offload S3 Lite's settings, can "Chang Bucket" and use the "Browse" method. Do you see your bucket and can you click it OK?

**Comment by data-compute-geek** [comment]
No policy.  Plus the user with the KeyID and secret key has policy AdministratorAccess, which is very liberal.

**Comment by A5hleyRich** [comment]
cURL 77 errors usually indicate an issue with your CA cert file.

http://unix.stackexchange.com/questions/269614/curl-77-pbm-with-the-ssl-ca-cert-path-access-rights

**Comment by data-compute-geek** [comment]
Thank you. That is very possible. I use the Hatchling plan from Hostgator.com, and the plan does not support a private SSL.  

If that is the case, any idea what to do to solve the issue?

Thanks a lot.

**Comment by A5hleyRich** [comment]
The CA file should still be present even on the Hatchling plan, as it's not used to provide private SSL, but rather validate third party SSL certs. You should contact Hostgator support, they may be able to resolve the issue for you.

**Comment by data-compute-geek** [comment]
Thank you so much. I will reach out to Hostgator regarding it.
