### ISSUE TITLE
connection error between wordpress and  s3,cloudfront, aws

### ISSUE THREAD

**Issue by geat83** [deliciousbrains/wp-amazon-s3-and-cloudfront#369]
Is  there any other ppl who know this error?

I can't find at all.ㅠㅠㅠ

I set the all access key etc. but it doesn't work..
 
It should be move form
Local URL:
http://tourmatekorea.kr/wp‑content/uploads/2017/03/photo.jpg
to S3 URL:
http://d3neclua0tlheq.cloudfront.net/wp‑content/uploads/2017/03/13185625/photo.jpg
 

Please check this out and diagnose
 --------here is our site condition-----------

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: www.tourmatekorea.kr.seoul
Region: ap-northeast-2
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://tourmatekorea.kr/wp‑content/uploads/2017/03/photo.jpg
S3 URL:
http://d3neclua0tlheq.cloudfront.net/wp‑content/uploads/2017/03/13185625/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: Startuply WP
Active Theme Folder: startuply

Active Plugins:
Akismet Anti-Spam (v3.3) by Automattic
Amazon Web Services (v1.0.1) by Delicious Brains
Circle Image Slider With Lightbox (v1.0.2) by I Thirteen Web Solution
Custom Post Type UI (v1.4.3) by WebDevStudios
Duplicate Post (v3.1.2) by Enrico Battocchi
Envato WordPress Toolkit (v1.7.3) by Envato
Instagram Feed (v1.4.8) by Smash Balloon
Q2W3 Fixed Widget (v5.0.4) by Max Bond
Related Posts (v5.12.68) by iLen
Simple Vertical Timeline (v0.1) by Alessandro Staniscia
Templatera (v1.1.1) by WPBakery
UpdraftPlus - Backup/Restore (v1.12.34) by UpdraftPlus.Com, DavidAnderson
Use Any Font (v4.6) by Dinesh Karki
WP Offload S3 Lite (v1.1.5) by Delicious Brains
WP RSS Aggregator (v4.10) by RebelCode
WPBakery Visual Composer (v5.0.1) by Michael M - WPBakery.com
WordPress Importer (v0.6.3) by wordpressdotorg
Yoast SEO Premium (v4.4) by Team Yoast

**Comment by A5hleyRich** [comment]
What exactly is the error you're receiving?

**Comment by aaemnnosttv** [comment]
Closing for now after no response.
