### ISSUE TITLE
Error Updating Attachments

### ISSUE THREAD

**Issue by cgidds** [deliciousbrains/wp-amazon-s3-and-cloudfront#372]
Running Offload S3 Lite, v1.1.6

The number of queries being executed on any given page in wp-admin is roughly 8k, and in the debug, it shows all these queries to be similar to: 
SELECT post_id, meta_key, meta_value
FROM wp_postmeta
WHERE post_id IN (5375)
ORDER BY meta_id ASC

In S3 Lite, there's an error stating:
Error Updating Attachments — We ran into some errors attempting to update the attachments for all your Media Library items that have been uploaded to S3. Please check your error log for details. (#2)

Yet the only error in debug.log is this:
[29-Mar-2017 20:09:24 UTC] WPOS3: Total file size for the attachment is 0: 1061
[29-Mar-2017 20:09:24 UTC] WPOS3: Total file size for the attachment is 0: 5313

When I force an update, the number of queries drops dramatically back down to 80 per page; however, that "fix" is only temporary (i.e. about 2 minutes).

Here's the debug information:
site_url(): http://staging.hillsong.com
home_url(): http://staging.hillsong.com
Database Name: wordpress_staging
Table Prefix: wp_
WordPress: 4.7.3
Web Server: Apache
PHP: 7.0.10
MySQL: 5.6.10
ext/mysqli: yes
PHP Memory Limit: -1
WP Memory Limit: 40M
Memory Usage: 13 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 2 GB
PHP Time Limit: 300
PHP Error Log: /var/app/current/wp-content/debug.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1k-fips 8 Jan 2015
cURL: Enabled
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 269,349
Media Files on S3: 29,463
Number of Image Sizes: 15

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
unlimited-card (700x700)
unlimited-subject (568x268)
header (1440x450)
header-large (1500x1000)
header-default (1500x1000)
hillsong-medium (700x0)
hillsong-large (1200x0)
contributor-avatar (150x150)
contributor-card (220x285)
card (700x0)
podcast (1400x0)

WP_CONTENT_DIR: /var/app/current/wp-content
WP_CONTENT_URL: http://staging.hillsong.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/app/current/wp-content/plugins
WP_PLUGIN_URL: http://staging.hillsong.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: pagely-media
Region: 
Copy Files to S3: On
Rewrite File URLs: On

Domain: cloudfront
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Hillsong
Active Theme Folder: hillsong

Active Plugins:
404page (v9.1.4 // Edited by Hillsong to prevent auto-update, actually version 1.4) by smartware.cc
Advanced Custom Fields PRO (v5.5.0) by Elliot Condon
Advanced Custom Fields: Gravity Forms Field (v1.0.0) by @adam_pope of @stormuk
Advanced Custom Fields: Link Picker (v1.1.1) by 
Advanced Database Cleaner (v2.0.0) by Younes JFR.
Amazon Web Services (v1.0.1) by Delicious Brains
Custom Post Type UI (v1.4.3) by WebDevStudios
Duplicate Post (v3.1.2) by Enrico Battocchi
Enable Media Replace (v3.0.5) by Måns Jonasson
Enhanced Media Library (v2.3.5) by wpUXsolutions
Facebook Instant Articles & Google AMP Pages by PageFrog (v1.0.9) by PageFrog Team
Filenames for WooCommerce Virtual Product Downloads (v0.1) by gplclub.org
Gravity Forms (v1.9.16) by rocketgenius
Gravity Forms User Registration Add-On (v3.1) by rocketgenius
Groups (v1.13.1) by itthinx
Groups 404 Redirect (v1.2.4) by itthinx
Posts 2 Posts (v1.6.5) by scribu
Query Monitor (v2.13.2) by John Blackbourn
Quick Page/Post Redirect Plugin (v5.1.8) by anadnet
Regenerate Thumbnails (v2.2.6) by Alex Mills (Viper007Bond)
User Meta Display (v1.2.2) by Myles McNamara
WP Google Analytics Events (v2.3) by Yuval Oren
WP Offload S3 Lite (v1.1.6) by Delicious Brains
WP Rocket (v2.6.12) by WP Rocket
WPML Media (v2.1.19) by OnTheGoSystems
WPML Multilingual CMS (v3.3.6) by OnTheGoSystems
WPML String Translation (v2.3.6.1) by OnTheGoSystems
WPML Translation Management (v2.1.5) by OnTheGoSystems

**Comment by ianmjones** [comment]
@cgidds We're working on a fix for a many queries issue with the upgrade routine when run on a multisite with a lot of subsites, but have not see the problem on a single site install like this.

Please can you detail your server setup, how many web servers are there and is there just one database backing them?

If there are multiple servers, have you disabled WP-Cron on all but the server you posted the diagnostics from?

What version of the plugin were you running before upgrading to v1.1.6?

The secondary problem of errors with 0 length attachments sounds like either a possible race condition with a couple of servers trying to download and generate the meta data for the same file and then removing the local version (one wins), or having a Media Library record for a file that has been removed. Please check the referenced attachments.

**Comment by cgidds** [comment]
There are 5 EC2 instances running the WP code, with auto-scaling of the environment based on various performance metrics. From a database perspective, there's 1 aurora cluster with 1 RDS instance behind it.

The EC2 instances are configured the same so WP-Cron is not "sticky" on any particular server. Do you have a reference as to how to do that?

We're currently running v1.1.4 in production, though we tested v1.1.6 in staging (it was also on v1.1.4 before upgrading) and still received the same error.

**Comment by ianmjones** [comment]
Although WordPress tries to ensure there is just one cron process running at any one time, and at most once per minute, I expect 5 servers all trying to start wp-cron at the same time might occasionally let 1 or 2 extras start up. Especially with a remote db with write latency (an options table transient is used for the lockout).

Might be worth disabling WP-Cron and using a single external cron that ticks over once per minute.

https://deliciousbrains.com/wp-offload-s3/doc/cron-setup/

**Comment by cgidds** [comment]
Thanks for the link. We followed the instructions and added it directly to crontab on a management server that has access to the EC2 instances. However, we're still seeing the update_meta_cache being queried for every resource every time the admin page loads.  Here's the stack trace for update_meta_cache:

get_metadata
get_post_meta
get_attached_file
AS3CF_Upgrade_File_Sizes->get_attachments_removed_from_server
AS3CF_Upgrade_File_Sizes->count_items_to_process
AS3CF_Upgrade->maybe_init
AS3CF_Upgrade->__construct
Amazon_S3_And_CloudFront->init
Amazon_S3_And_CloudFront->__construct
as3cf_init
call_user_func_array
WP_Hook->apply_filters
WP_Hook->do_action
do_action('aws_init')
Amazon_Web_Services->__construct
amazon_web_services_init
call_user_func_array
WP_Hook->apply_filters
WP_Hook->do_action
do_action('init')
require_once('wp-settings.php')
require_once('wp-config.php')
require_once('wp-load.php')
require_once('wp-admin/admin.php')

**Comment by cgidds** [comment]
Can I have an update on this please?

**Comment by aaemnnosttv** [comment]
Hi there. I've pushed a temporary fix to a new branch here which should fix things for you until the next release: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/tree/temp-fix-big-queries-before-upgrades

Let us know how that works out for you.

**Comment by aaemnnosttv** [comment]
This should be resolved now as of the latest release v1.2.

If you're still seeing performance problems after upgrading please let us know.
