### ISSUE TITLE
 resizing the image using WordPress' built in image editor (i.e. crop) does not upload the changed images to S3

### ISSUE THREAD

**Issue by tabakade** [deliciousbrains/wp-amazon-s3-and-cloudfront#375]
The initial image upload and transfer to S3 works well. However, resizing the image using WordPress' built in image editor (i.e. crop) does not upload the changed images to S3

**Comment by A5hleyRich** [comment]
Hi,

WP Offload S3 works fine with the WordPress built-in image editor, even when the local files have been removed. Do you have any third party plugins installed which could be causing conflicts?

**Comment by xoref** [comment]
Sorry to hijack this thread, but we are facing the same issue using a third party plugin called [Manual Image Crop](https://wordpress.org/plugins/manual-image-crop/). 

Is it possible to trigger an action hook or filter so that the image does get updated? If so, which one would that be? Thanks!

**Comment by aaemnnosttv** [comment]
Closing this for now as support for editing images with the native WordPress image editor has been improved in the latest release v1.2.

If this is still an issue, please re-open.

@xoref Supporting compatibility with individual plugins is beyond the scope of the issues on this free plugin which are primarily for bug reports. For awesome personalized support, please upgrade to Offload S3 pro, and send us an email 😎
