### ISSUE TITLE
Url utf8

### ISSUE THREAD

**Issue by dsalcedo** [deliciousbrains/wp-amazon-s3-and-cloudfront#377]
I upload a image with the name like: “a-nueva-poesía-mexicana.jpg”
In AWS S3 I see the link Link	***/la-nueva-poesi%CC%81a-mexicana.jpg
The plugin print the url: “***/la-nueva-poesía-mexicana.jpg”

Result:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

Some suggest?

**Comment by ianmjones** [comment]
What version of WP Offload S3 Lite are you using?

There were improvements to non-ascii character handling in later versions.

**Comment by dsalcedo** [comment]
Versión 1.1.6 |

**Comment by aaemnnosttv** [comment]
I uploaded a file using the file name you provided and see the same values for the URL, but the image loads just fine for me using the same version of the plugin:

![image](https://cloud.githubusercontent.com/assets/1621608/26559641/8835248c-44b9-11e7-8f21-1b5270aaf525.png)

Would you mind sharing the exact URL you're using that is giving you the error message?

**Comment by danieluyo** [comment]
hmmmmm

I upload many images to S3 using aws-cli (25GB of data t.t) and then I install the plugin. Now the images with UTF8 chars its not loading :'(
Some idea if is the plugin or something like that?

**Comment by aaemnnosttv** [comment]
The plugin does not interact with media in the bucket that it does not upload itself.

I was not able to replicate the issue with the plugin so it sounds like this may be a limitation of the aws-cli.
