### ISSUE TITLE
unable to upload with server under corporate proxy

### ISSUE THREAD

**Issue by ad34** [deliciousbrains/wp-amazon-s3-and-cloudfront#380]
I can't get the plugin to work . the website is hosted on a server where all web trafic must be routed throught a proxy server. this server is defined in wp-config.php  ( WP_PROXY_HOST / WP_PROXY_PORT) but for some reason I get the following error after editing configuration in the wordpress backoffice

There was an error attempting to check the permissions of the bucket xxx: [curl] 7: Failed connect to xxx.s3.amazonaws.com:443; No route to host [url] https://xxx.s3.amazonaws.com/path/wp-content/uploads/as3cf-permission-check.txt 

if there customs settings I have to use for the proxy ? 

diagnostic info  (sorry I have to anonymize some data) 

site_url(): http://xxx
home_url(): http://xxx
Database Name: wp_xxx
Table Prefix: wp_
WordPress: 4.7.5
Web Server: Apache
PHP: 5.6.21
MySQL: 5.5.35
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 40 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 2 MB
PHP Time Limit: 30
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Disabled
OpenSSL: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1
Imagick: Disabled
Basic Auth: Disabled
Proxy: Enabled

Media Files: 23
Media Files on S3: 3
Number of Image Sizes: 9

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
thumb-featured (940x480)
thumb-blog (460x200)
thumb-single (940x480)
badge (500x500)
banner (1440x539)

WP_CONTENT_DIR: /var/www2/xxxx.com/wp-content
WP_CONTENT_URL: http://xxx.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www2/xxx.com/wp-content/plugins
WP_PLUGIN_URL: http://xxx.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: xxx
Region: 
Copy Files to S3: On
Rewrite File URLs: On

Local URL:
http://xxxx.com/wp‑content/uploads/2017/06/photo.jpg
S3 URL:
https://xxxxx.cloudfront.net/xxxx/wp‑content/uploads/2017/06/15082033/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: xxx/wp-content/uploads/
Use Year/Month: On
Force HTTPS: On
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: xxx
Active Theme Folder: xxx

Active Plugins:
Advanced Custom Fields PRO (v5.5.14) by Elliot Condon
Amazon Web Services (v1.0.2) by Delicious Brains
Jetpack by WordPress.com (v4.9) by Automattic
TotalPoll Pro (v3.2.42) by MisqTech
WP Offload S3 Lite (v1.1.6) by Delicious Brains
WPML Multilingual CMS (v3.3.8) by OnTheGoSystems

**Comment by aaemnnosttv** [comment]
The `WP_PROXY_*` constants only affect http requests dispatched through WordPress's `WP_HTTP` class.  The AWS SDK used by the plugin uses the Guzzle http client internally, which of course has no idea about these WP constants for the proxy.

You'll need to configure the S3 client to use your proxy as outlined in the SDK docs here: http://docs.aws.amazon.com/aws-sdk-php/v2/guide/configuration.html?highlight=proxy#using-a-proxy

To modify the arguments used for the client, you can use the `aws_get_client_args` filter ([source](https://github.com/deliciousbrains/wp-amazon-web-services/blob/0b64dc5ec5582378b948c48d02817dd2079f6562/classes/amazon-web-services.php#L311)).

I'll raise an issue with the team to consider configuring the client automatically to use a proxy if the WP constants are set.

**Comment by ad34** [comment]
@aaemnnosttv thanks.

adding 

$args['request.options']  =
			[
				'proxy' => WP_PROXY_HOST.':'.WP_PROXY_PORT
			];

fix the issue.

is there a way to force the upload of all previous assets which are still linked to the local webserver?

**Comment by aaemnnosttv** [comment]
Fantastic, great to hear and yes! That is one of the key features of the pro version: https://deliciousbrains.com/wp-offload-s3/#media-library-upload
