### ISSUE TITLE
Default URL Format Changed

### ISSUE THREAD

**Issue by allynbeth** [deliciousbrains/wp-amazon-s3-and-cloudfront#382]
According to the documentation (https://deliciousbrains.com/wp-offload-s3/doc/settings/) the url format should be similar to the following: https://s3.amazonaws.com...

Our url format used to match that format:
https://s3********.amazonaws.com/bucketname/filepath/filename

When we upgraded to the latest version 1.1.6 from version 1.1.3 the default url format changed to the following:
https://bucketname.s3********.amazonaws.com/filepath/filename

Is there a reason the format has changed and the documentation isn't updated? and is there a way we can get the old format to work? We are running into issues with the new url format as it appears to be pointing to a different endpoint in AWS.

**Comment by ianmjones** [comment]
@allynbeth Have you definitely got "CloudFront or Custom Domain" turned off in the settings?

If it's turned on, but nothing entered for the domain, then the URL format switches to bucket in domain format.

**Comment by allynbeth** [comment]
Yes it's turned off.


- -

<http://artispassion.com/>ALLYN BETH BROWN
beth@artispassion.com
facebook.com/artispassion
www.artispassion.com

**Comment by allynbeth** [comment]
The bucket is private. I have the same plugin installed on another site and
the bucket is public. It looks like the issue only happens with the private
bucket. I also noticed all of the media assets have signed urls now. Is
this configurable at all?


- -

<http://artispassion.com/>ALLYN BETH BROWN
beth@artispassion.com
facebook.com/artispassion
www.artispassion.com

**Comment by aaemnnosttv** [comment]
To my knowledge, buckets are not private or public by themselves, only objects are private or public. Can you elaborate on what you mean by a private bucket? Private objects will have signed URLs from Offload S3 otherwise they would be inaccessible.

If you enable the Force HTTPS setting you should find that the URL uses the bucket-in-path format. It looks like you're using https anyways, so give this a try and see if that fixes things for you.

**Comment by aaemnnosttv** [comment]
Going to close this one out for now as it's been a while since we've heard from you. If you're still having a problem and you believe this may be a bug, please provide us with your diagnostic information from the Support tab.
