### ISSUE TITLE
[Q] Does the plugin work with Php7?

### ISSUE THREAD

**Issue by MansoorMajeed** [deliciousbrains/wp-amazon-s3-and-cloudfront#384]
I was having some issues with php7 and the s3 plugin. Before continuing the debugging somewhere, just wanted to confirm, does the plugin work with php7? I saw this in the error log

```
"NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mysql_get_server_info() in /app/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php:2144"
```

**Comment by ianmjones** [comment]
WP Offload S3 Lite definitely supports PHP 7.

However, your error message doesn't match up with the current version of the plugin, maybe you're using an older version?

**Comment by MansoorMajeed** [comment]
I will try with the latest version and will get back :) Thank you very much.
