### ISSUE TITLE
URLs being mangled on rewrite into DB

### ISSUE THREAD

**Issue by potato12345678** [deliciousbrains/wp-amazon-s3-and-cloudfront#385]
Hi,

I have the following settings in `wp-config.php`:

    define('WPOS3_SETTINGS', serialize([
        'region' => 'ap-southeast-2',
        'bucket' => 'uploads.example.org',
        'copy-to-s3' => true,
        'serve-from-s3' => true,
        'domain' => 'cloudfront',
        'cloudfront' => 'uploads.example.org',
        'enable-object-prefix' => false,
        'use-yearmonth-folders' => false,
        'force-https' => false,
        'remove-local-file' => true,
        'object-versioning' => false
    ]));

Uploads are moving over to S3 OK, and when adding an image to a post, the URL is rewritten correctly so that the S3 image is used in the WYSIWYG editor.

But when saving, the URL in the DB is changed back to: `http:/content/uploads/foo.png` - notice it is quite mangled.

I'm not sure if this is because I set the following constants in `wp-config.php` so I can have the `wp-content` dir outside the main WP install:

    define('WP_CONTENT_DIR', __DIR__ . '/content');
    define('WP_CONTENT_URL', '/content');

 - Is the URL meant to be rewritten when saving, even though the image is deleted locally?
 - Is the issue that it's just not being rewritten back to the S3 URL because it's mangled?

Diagnostic info [here](https://pastebin.com/raw/NUaM0tGw).

**Comment by ianmjones** [comment]
If you're overriding `WP_CONTENT_URL`, it should be a full URL.

See https://codex.wordpress.org/Determining_Plugin_and_Content_Directories#Constants

**Comment by aaemnnosttv** [comment]
Regarding the URL rewriting you're seeing, URLs are intentionally rewritten to a local URL on save since version version 1.1 [See here for more info](https://deliciousbrains.com/wp-offload-s3/doc/content-filtering-upgrade/).

**Comment by potato12345678** [comment]
Looks like that's the trick @ianmjones - thanks!
@aaemnnosttv good post, makes sense. Cheers.
