### ISSUE TITLE
S3 image replace heavy Database CPU

### ISSUE THREAD

**Issue by ryurock** [deliciousbrains/wp-amazon-s3-and-cloudfront#387]
Version: 1.2

Executed in wp-cron.php
Apply_filter ('as3cf_cron_update_replace_s 3 _urls')
It is very processing load that the database load is tremendously heavy.

see SQL Query log

```
UPDATE wp_posts SET `post_content` = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(post_content, '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-768x512.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-768x512.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-730x306.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-730x306.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-640x320.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-640x320.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-480x320.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-480x320.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-480x480.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-480x480.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-180x180.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-180x180.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-135x135.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-135x135.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-90x90.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-90x90.jpg'), '//ddmxdtm74ysa7.cloudfront.net/uploads/2017/02/13131910/112f31450f956723434f7e59a6ea08e5_1486991950-150x150.jpg', '//192.168.59.111/wp/wp-content/uploads/2017/02/112f31450f956723434f7e59a6ea08e5_1486991950-150x150.jpg') WHERE `ID` IN(37349,37516,37518)
```

**Comment by A5hleyRich** [comment]
This query is part of the upgrade routine which goes through your database and replaces S3 URLs with local URLs. You can read more about why we do this here:

https://deliciousbrains.com/wp-offload-s3-1-2-released/

 How many posts and attachments does the site have?

**Comment by ianmjones** [comment]
@ryurock Please also double check that your `wp_posts` table still has its unique primary key index on `ID` intact.

**Comment by ryurock** [comment]
@A5hleyRich 

thank you.
I did not understand the reasons for the change and I was just in trouble.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/387#issuecomment-312213479

**Comment by ryurock** [comment]
please tell me.
I'd like to bulk up the process of replacing cloudfront's URL with local URL.
Is there a way

**Comment by ianmjones** [comment]
@ryurock Can you explain what you're trying to do?

Sounds like you've updated to the current version and some of your S3/CloudFront URLs did not get migrated to local server URLs in your database content, correct?

**Comment by ryurock** [comment]
Not Exactly.
We upgraded Wp-amazon-s3-and-cloudfront from 1.0.4 to 1.2

Current problem is the process of replacing the URLs of S3 with the local URLs is too heavy.
I would like to replace data in a batch process.

Do you have any ways to replace whole data?
Or can we avoid the replacing process in some way?

**Comment by ryurock** [comment]
@ianmjones 
Not Exactly.
We upgraded Wp-amazon-s3-and-cloudfront from 1.0.4 to 1.2

Current problem is the process of replacing the URLs of S3 with the local URLs is too heavy.
I would like to replace data in a batch process.

Do you have any ways to replace whole data?
Or can we avoid the replacing process in some way?

**Comment by ryurock** [comment]
I found a way to bulk replace localURL.

```
wp_config_path={wp current path}
for event_name in "as3cf_cron_update_replace_s3_urls" "as3cf_cron_update_replace_edd_urls" "as3cf_cron_update_filter_post_excerpt"
do
    while :
    do
        wp_cron_event_list=$(wp cron event list --fields=hook --path="$wp_config_path" | grep "$event_name")
        [ "$wp_cron_event_list" = "" ] && break
        wp cron event run $event_name --path="$wp_config_path"
        sleep 5
    done
done
```

**Comment by ryurock** [comment]
@ianmjones 
@A5hleyRich 

thanks you.
