### ISSUE TITLE
Bucket sharing 

### ISSUE THREAD

**Issue by Paul008** [deliciousbrains/wp-amazon-s3-and-cloudfront#389]
I have several sites sharing the same bucket assets, after the upgrade i have broken links, if I search the image in the media library on the first site where the image was uploaded too it returns the image when I search the image on the sister sites it returns a broken link or no image found?, This is a problem as these assets are part of a custom post product catalogue page where their is templated cron exports for updates.

**Comment by aaemnnosttv** [comment]
These issues are primarily for bug reports, not support. Please see our response to your email. Thank you!
