### ISSUE TITLE
Can't access S3 buckets

### ISSUE THREAD

**Issue by kmgsoftware** [deliciousbrains/wp-amazon-s3-and-cloudfront#390]
I followed all the instructions in the getting started guide - created a new IAM user, gave it the necessary S3 permissions explicitly copied and pasted from the guide, added the access key and secret key to wp-config.php. However, when I try to list my S3 buckets or define which one I want to use, I get this error:

```
Error saving bucket — Error Getting Bucket Region —There was an error attempting to get the region of the bucket arn:aws:s3:::kincaid-galleries-media: Missing required client configuration options: region: (string) A "region" configuration value is required for the "s3" service (e.g., "us-west-2"). A list of available public regions and endpoints can be found at http://docs.aws.amazon.com/general/latest/gr/rande.html.
```

I can't see anywhere to configure the region - any ideas?

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please using the "License & Support" tab in the plugin.
