### ISSUE TITLE
Settings not retrieved when activated on multiple networks.

### ISSUE THREAD

**Issue by AmibeWebsites** [deliciousbrains/wp-amazon-s3-and-cloudfront#392]
Hi, I'm receiving the following message:

> There was an error attempting to check the permissions of the bucket rssa-website-files: Error retrieving credentials from the instance profile metadata server. (Client error: `GET http://169.254.169.254/latest/meta-data/iam/security-credentials/` resulted in a `404 Not Found` response: not found )

This is a **Multinetwork** environment using WordPress 4.8, Amazon Web Services 1.0.3 and WP Offload S3 Lite 1.2. The multinetwork capability is supported by WP Multi-Network 2.1.0; the mutlisite setup is sub-domain.

I created a 2nd network where I activated and configured everything as per https://deliciousbrains.com/wp-offload-s3/doc/quick-start-guide/ and it is working perfectly - no issue there.

I then activated on the primary network using the exact same settings as with the secondary network and get the message above when going to the Offload S3 Lite Media Library settings.

If I try and change the bucket I receive this message:

> Error fetching buckets — Missing required client configuration options: region: (string) A "region" configuration value is required for the "s3" service (e.g., "us-west-2").

When I return to the settings for the 2nd Network (the one that did work) I'm now getting a message about the endpoint being incorrect. It appears to have not loaded the correct region - and if I save the settings I see that it changes from the region from 'eu-west-2' (which is correct) to 'us-east-2' (which is incorrect). The 2nd network is now no longer uploading images to S3.

Deactivate and remove the settings (in the site meta table) for the primary network and the secondary is working again with no error messages.

So it seems that the settings aren't loaded correctly when activated on more than one network.

Would I be able to use the filters to overcome this on a per network basis? as3cf_setting_bucket, as3cf_setting_region, as3cf_setting_domain, etc?

**Comment by ianmjones** [comment]
We don't currently test on or support multi-network setups. However, I'd eradicate all of the as3cf/wpos3/tantan_s3 settings from your site options and then try setting up purely using the settings constants - https://deliciousbrains.com/wp-offload-s3/doc/settings-constants/

However, please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "License & Support" tab in the plugin.
