### ISSUE TITLE
How to change Custom Domain in function.php?

### ISSUE THREAD

**Issue by shangdev** [deliciousbrains/wp-amazon-s3-and-cloudfront#393]
I used a multi-site netword plugins, and now i want to do Custom Domain under each topic's function.php, how do i do it?
Now, when I use apply_filter ('post_thumbnail_html', '') on each topic, WP Offload S3 will stop working as soon as I run a website based on that topic
Please tell me some of the solutions.
Thanks.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "License & Support" tab in the plugin.
