### ISSUE TITLE
Not working when attachment added through code

### ISSUE THREAD

**Issue by harish-php** [deliciousbrains/wp-amazon-s3-and-cloudfront#394]
I am adding attchment using code using wordpress functions "wp_insert_attachment()" 
My attachment not uploaded to s3
When i do same using wordpress dashboard it works.

**Comment by aaemnnosttv** [comment]
[`wp_insert_attachment`](https://developer.wordpress.org/reference/functions/wp_insert_attachment/) is only a simple wrapper for `wp_insert_post`, it does not trigger the same actions as adding a _file_ to the media library. To add a file to the media library which will also trigger an upload to S3, use [`media_handle_sideload`](https://developer.wordpress.org/reference/functions/media_handle_sideload/).
