### ISSUE TITLE
Unable to sync custom directory structure inside wp_contents/uploads/ to S3

### ISSUE THREAD

**Issue by harish-php** [deliciousbrains/wp-amazon-s3-and-cloudfront#398]
I am addinf atatchments to wordpress, I am creating custom directory heirarchy inside wp-contents/uploads/2017/08/test/test1/test34/filename.png
But on s3 its gets added as
wp-contents/uploads/2017/08/filename.png

$uploadfile = ABSOLUTE_PATH.'wp-contents/uploads/2017/08/test/test1/test34/filename.png';
global $as3cf;
$res = $as3cf->upload_attachment_to_s3($attach_id, NULL, $uploadfile);

**Comment by aaemnnosttv** [comment]
The path on S3 does not mirror the path on the local file system, but is based on the Path related settings.

If you would like support for WP Offload S3 Lite, you can open a thread on the WordPress.org support forum here: https://wordpress.org/support/plugin/amazon-s3-and-cloudfront.  If you are a WP Offload S3 license holder, you can always reach us through the support tab of the plugin.
