### ISSUE TITLE
AWS GovCloud region support?

### ISSUE THREAD

**Issue by gboone** [deliciousbrains/wp-amazon-s3-and-cloudfront#399]
I've been working on setting up a WordPress site inside of AWS's `us-gov-west-1` region and using this plugin to push WordPress assets to an S3 bucket upon upload.

I'm seeing an error and trying to troubleshoot. When I set up the plugin with my S3 credentials I get the following error:
> *Error fetching buckets* — The AWS Access Key Id you provided does not exist in our records.

Double checking my credentials, I think I have the plugin configured properly. When I use the same credentials with the AWS CLI, it works as expected. Is it possible this plugin does not support the `us-gov-west-1` region?

**Comment by A5hleyRich** [comment]
This should work if you manually provide the region to the AWS client. You can use the `aws_get_client_args` filter, which is demonstrated here:

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/master/amazon-s3-and-cloudfront-tweaks.php#L326

**Comment by gboone** [comment]
So, it's not enough to put `define( 'AS3CF_REGION', 'us-gov-west-1' );` in `wp-config`? Instead, I should install that other plugin and enable that filter. Is that correct?

**Comment by aaemnnosttv** [comment]
The `AS3CF_REGION` constant only enforces the region used for creating new buckets through the plugin interface. You do not need to install that other plugin (although you could), it only shows an example of how to use the filter.
