### ISSUE TITLE
AS3CF_S3_To_Local is constantly looking to replace S3 urls with local ones

### ISSUE THREAD

**Issue by JoshShashaty** [deliciousbrains/wp-amazon-s3-and-cloudfront#402]
`AS3CF_S3_To_Local` on post save kicks off `filter_post` from it's base class `AS3CF_Filter`, finds any potential urls in the content, then sends that list of urls back through `AS3CF_S3_To_Local`'s `url_needs_replacing()` ... each of those urls have it's path taken, searches through postmeta to find the right attachment ID.

The problem for us is that we don't want any S3 urls being replaced with local ones, we fully want S3 urls to be uploaded and remain as S3 urls in the content.   This results in searching a huge postmeta table with an attachment path, of which takes sometimes 70 seconds, and ultimately times out on each post save because there's lots of URLs to try and find attachment ID's for.

Here's a NewRelic screenshot that shows how long finding the attachment ID's can take: https://i.imgur.com/VUBJnu7.png

My question is, why is the class trying to replace S3 (remote urls) with local urls on every post save?  I might need some clarification/understanding on it's purpose.  But currently, it just seems like it's needlessly running and causing timeouts when saving posts that have a lot of remote urls to process.

Here's the method below that determines whether the URL should be replaced or not. It's basically doing the logic on which URLs should be searched in the database for whether it's an S3 url or not (which I understand you have to do because all S3 urls could be different, cloudfront, etc.) 

```	/**
	 * Does URL need replacing?
	 *
	 * @param string $url
	 *
	 * @return bool
	 */
	protected function url_needs_replacing( $url ) {
		$uploads  = wp_upload_dir();
		$base_url = AS3CF_Utils::remove_scheme( $uploads['baseurl'] );

		if ( false !== strpos( $url, $base_url ) ) {
			// Local URL, no replacement needed
			return false;
		}

		// Remote URL, perform replacement
		return true;
	}
```

**Comment by aaemnnosttv** [comment]
Please see the [1.2 release post](https://deliciousbrains.com/wp-offload-s3-1-2-released/) (pro version) on our blog which explains the change.

To your point about the performance issue, we cache the results which greatly improves the performance, but it shouldn't take that long. Can you attach your diagnostic information here for us to see?

**Comment by JoshShashaty** [comment]
I did read that article a couple weeks ago to see if there was a connection.  And after your comment, I think that's the case here.  The upgrade has already been performed by there's still posts with S3 urls in them.  So, if we replace those S3 urls with their server counterpart, then we shouldn't be hitting timeouts because those urls won't get added to list to be found in the database through AS3CF_S3_To_Local ... is my thinking right there?

I did check out the caching method Offload S3 uses, it just seems like for some posts that Offload S3 is never really able to fully replace urls on post content and then save it again before the post save times out.

**Comment by ianmjones** [comment]
Hey @JoshShashaty, did you fix your URLs in the database and did that fix the problem?

**Comment by JoshShashaty** [comment]
Hey @ianmjones , thanks for following up :) what we ended up doing was removing the filter (`remove_filter()`) for `AS3CF_S3_To_Local` ... it was only really affecting some posts that had a lot of images and hadn't had all of the urls replaced, and those posts were hitting timeouts.  Most posts are fine and they actually use Envira, so not URLs to process in those posts.   I'm assuming this is an issue you don't see often because most sites have gone through a successful upgrade.  I am curious as to if that process should run through background processing to calculate time left in the execution and amount of memory, too.

**Comment by ianmjones** [comment]
Definitely sounds like the upgrade had issues. I would suggest setting the 'postmeta_version' field of the 'tantan_wordpress_s3' options record to "3" (it's likely currently set to "6"). That will kick off a suite of upgrades that will run in the background over time.
