### ISSUE TITLE
Plugin requires an older version of composer/installers

### ISSUE THREAD

**Issue by markorapaic** [deliciousbrains/wp-amazon-s3-and-cloudfront#406]
Looks like version 1.2 of the plugin still requires that an older version of composer be used? My current composer version is `1.5.2`

```
Problem 1
    - Installation request for deliciousbrains/wp-amazon-s3-and-cloudfront ^1.2 -> satisfiable by deliciousbrains/wp-amazon-s3-and-cloudfront[1.2].
    - deliciousbrains/wp-amazon-s3-and-cloudfront 1.2 requires composer/installers ~1.0.6 -> satisfiable by composer/installers[1.0.x-dev, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.17, v1.0.18, v1.0.19, v1.0.20, v1.0.21, v1.0.22, v1.0.23, v1.0.24, v1.0.25, v1.0.6, v1.0.7, v1.0.8, v1.0.9] but these conflict with your requirements or minimum-stability.
```

**Comment by aaemnnosttv** [comment]
This is not about the version of Composer but a conflict in the required version of the `composer/installers` package which is needed to install WordPress plugins and themes via Composer.

It looks like we're using an overly restrictive version constraint on this package in our `composer.json`. 

Are you manually requiring `composer/installers` in your root `composer.json`? If so, you should be able to just remove that. If not, you could try running `composer why composer/installers` and see what comes up there.

**Comment by aaemnnosttv** [comment]
Alternatively, you can always install the plugin from `wpackagist-plugin/amazon-s3-and-cloudfront` which has a looser requirement for the installers package.

**Comment by ianmjones** [comment]
WP Offload S3 Lite 1.3.2 was released a while ago with relaxed version requirements:

`"composer/installers": "^1.0"`
