### ISSUE TITLE
PDF URLs in custom posts are changed to local path, when copied from object storage media library

### ISSUE THREAD

**Issue by sldgs** [deliciousbrains/wp-amazon-s3-and-cloudfront#410]
We experience a strange issues, PDFs are uploaded to media library and the object storage URL is taken from their to a custom post type. After several hours the link is nevertheless changed - how can we prevent this to happen? Our settings page does not display any cronjob for migration going on anymore, and also the setting is clearly set to sue object storage files.

Right now ONLY the pdf urls are breaking all the time.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "License & Support" tab in the plugin.
