### ISSUE TITLE
array_keys() expects parameter 1 to be array in /classes/as3cf-filter.php on line 853

### ISSUE THREAD

**Issue by rrecurse** [deliciousbrains/wp-amazon-s3-and-cloudfront#413]
Some new PHP warnings cropping up today. Not sure anyone else is experiencing the same. I believe it's the scheduled job that runs via the WP Cron that's triggering this.

Here is a full list of new warnings with their offending lines:

PHP Warning:  array_keys() expects parameter 1 to be array, string given in /amazon-s3-and-cloudfront/classes/as3cf-filter.php on line 853

PHP Warning:  array_map(): Argument #2 should be an array in /amazon-s3-and-cloudfront/classes/as3cf-filter.php on line 853, 

`$post_cache_keys = array_map( 'AS3CF_Utils::reduce_url', array_keys( $existing_cache ) );`

PHP Warning:  array_combine() expects parameter 1 to be array, null given in /amazon-s3-and-cloudfront/classes/as3cf-filter.php on line 854

`$existing_cache  = array_combine( $post_cache_keys, $existing_cache );`

PHP Warning:  array_merge(): Argument #1 is not an array in /amazon-s3-and-cloudfront/classes/as3cf-filter.php on line 862

`return array_merge( $existing_cache, $merge_cache );`

**Comment by ianmjones** [comment]
These errors seem to be related to an older version of WP Offload S3 Lite as those line numbers do not match up with the current release.

@rrecurse Do you still have the same problem with the latest version?
