### ISSUE TITLE
PLease help me with minor error 

### ISSUE THREAD

**Issue by izremote** [deliciousbrains/wp-amazon-s3-and-cloudfront#414]
After installing plugin received this error :: ****_Warning: preg_match() expects parameter 2 to be string, array given in /home/vitami26/public_html/fragranceflask.com/wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-utils.php on line 200_****

This is the code for as3cf-utils.php

	**public static function is_url( $string ) {
			if ( preg_match( '@^(?:https?:)?\/\/[a-zA-Z0-9\-]{3,}@', $string ) ) {
				return true;
			}

			return false;
		}**

Please advise 

Thank you .

IZ

**Comment by ianmjones** [comment]
@izremote Please post your diagnostic info from the Help tab of WP Offload S3 Lite.

**Comment by izremote** [comment]
Attached please find diagnostic file .

Thank you 
IZ
[www.fragranceflask.com-diagnostic-log-20171114191857.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/1472207/www.fragranceflask.com-diagnostic-log-20171114191857.txt)

**Comment by ianmjones** [comment]
@izremote Do you still have the same problem with the latest version?
