### ISSUE TITLE
Image is renamed with an unknown variable after the upload.

### ISSUE THREAD

**Issue by romanturbo** [deliciousbrains/wp-amazon-s3-and-cloudfront#416]
Afer uploading an image I have an unknown variable which I cant manage to find where is it coming from. Example:
http://exa-assets.s3.amazonaws.com/section/section1/201710/20171019-section1-01_uyt900.jpg
http://exa-assets.s3.amazonaws.com/section/section1/201710/20171019-section1-01_uyt888.jpg

What is that uyt900 / uyt888 variable? Seems to be radom and its conflicting with one of my plugins, since I cant determine what generates it. It started to appear recently, so far all my links where like this:

http://exa-assets.s3.amazonaws.com/section/section1/201710/20171019-section1-01.jpg
http://exa-assets.s3.amazonaws.com/section/section1/201710/20171019-section1-02.jpg
.
.
.
etc
Seems like it started to ocurr in september. Is there any update?

**Comment by aaemnnosttv** [comment]
This isn't something that we do with WP Offload S3. It's likely something that your theme or another plugin is doing.

These issues are just for bug reports. You might try posting about it on the [plugin's forum](https://wordpress.org/support/plugin/amazon-s3-and-cloudfront) to see if anyone else from the community has had a similar issue. If you're a license holder, you're always welcome to send us an email through the support tab of the plugin, and we can take a closer look.
