### ISSUE TITLE
Offload S3 Lite - error attempting to check the permissions of the bucket

### ISSUE THREAD

**Issue by aludayanan** [deliciousbrains/wp-amazon-s3-and-cloudfront#417]
Hi,

We have a site hosted on AWS EC2 and we're using s3 to host our media files. When AWS s3-and-cloudfront installed last June 2017 it was working perfectly until I've found out 2 days ago that uploading of images was not copied to S3. 

When i check the plugin AWS s3-and-cloudfront it gives me this error "**There was an error attempting to check the permissions of the bucket : The difference between the request time and the current time is too large.**"

Just to let you know that there's no changes in regards to the setting when i first installed the plugins.

Does anyone here have any ideas on how to solve the issue?

Thank you and looking forward for an answer.

**Comment by aaemnnosttv** [comment]
This error indicates that the server's time is out of sync.
