### ISSUE TITLE
URL filename encode issues

### ISSUE THREAD

**Issue by superjunky** [deliciousbrains/wp-amazon-s3-and-cloudfront#418]
To generate the s3 URL, `rawurlencode` is used for the filename. This causes my @2x images to load as %402x in the filename.
The images load correct, but other retina scripts are depending on those @2x tags un-encoded.

Is this something that can be fixed?

Edit. Perhaps it's better to use filter `as3cf_get_attachment_url` ;)

**Comment by ianmjones** [comment]
It's important that URLs are properly encoded otherwise bad things can happen!

What kinds of scripts are you talking about, JavaScript, or plugins that could hook in earlier to do their thing?

**Comment by superjunky** [comment]
JavaScipt.

I understand.
I will filter the '@' for now, and will add a better solution later. Need to get rid of some of those scripts anyway.
