### ISSUE TITLE
wp_generate_attachment_metadata Not Working

### ISSUE THREAD

**Issue by jbakerpixelstrike** [deliciousbrains/wp-amazon-s3-and-cloudfront#419]
Hello All,

Was wondering if anyone else had run into this with a file management plugin. I found the one issue card about needing the wp_generate_attachment_metadata hook (https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/340). For whatever reason, the hook isn't working for me (All the files are staying local and not going to S3). I can confirm that the normal upload is working fine. I wasn't sure if it's a placement issue in the code or I'm missing something:

`public function upload_media_store($filename, $mime)
    {
    	//error_reporting(1);
    		require_once( ABSPATH . 'wp-admin/includes/image.php' );
			require_once( ABSPATH . 'wp-admin/includes/file.php' );
			require_once( ABSPATH . 'wp-admin/includes/media.php' );
        $filename = str_replace('\\', '/', $filename);
        $wp_filetype = wp_check_filetype($filename, null );
          $attachment = array(
             'guid' 			=> $filename ,
             'post_mime_type'	=> $wp_filetype['type'],
             'post_title' 		=> preg_replace( '/\.[^.]+$/', '', basename( $filename ) ),
             'post_content' 	=> '',
             'post_status' 		=> 'inherit',
             'post_date'        => date('Y-m-d H:i:s')
          );
          //hook to disable image risizes:
          add_filter( 'intermediate_image_sizes', 'red_empty_hook', 99 );

          $attach_id = wp_insert_attachment( $attachment, $filename, 0);      
	  $attach_data = wp_generate_attachment_metadata( $attach_id, $filename );
          wp_update_attachment_metadata( $attach_id, $attach_data );

          //dont need the filter anymore
         remove_filter( 'intermediate_image_sizes', 'red_empty_hook', 99 );
          $temp_data = wp_generate_attachment_metadata( $attach_id, $filename );
          wp_update_attachment_metadata( 0, $temp_data );
          wp_update_attachment_metadata( 0, $attachment );
    }

    function red_empty_hook(){
    	$abc = array();
    	return $abc;
    }`

**Comment by dtqdtq** [comment]
Hello, is there any update on this issue?

**Comment by ianmjones** [comment]
As far as we can tell there is nothing wrong with WP Offload S3 (Lite), it's likely the 3rd party plugin isn't putting data in the right place. We did some experiments with the file management plugin (via a support request) and determined that it was always using local files and didn't use the WordPress API properly to retrieve and interact with files whether local or remote.

It should also be noted that the above sample code is broken, the `wp_update_attachment_metadata` calls are passing in `0` instead of the expected `$attach_id`.
