### ISSUE TITLE
1.0.4 Image Path Bug

### ISSUE THREAD

**Issue by jlucero-contentad** [deliciousbrains/wp-amazon-s3-and-cloudfront#420]
When I upgraded from 1.0.3 to 1.0.4, image paths including Featured Images and in article image paths failed to include the full file path to the image on S3. The Plugin creates a folder with what appears to be a random number and uploads the images to that folder. When I upgraded to 1.0.4, the random number folder no longer appears in the file path to Featured and in article images. 

Is there a work-around for this problem?

**Comment by ianmjones** [comment]
@jlucero-contentad Can you post your diagnostic info please?

**Comment by jlucero-contentad** [comment]
How do I do that @ianmjones?

**Comment by ianmjones** [comment]
@jlucero-contentad You can download the diagnostic info from the Support tab of WP Offload S3 Lite.

**Comment by jlucero-contentad** [comment]
Thank you @ianmjones. I see the data now. 

I don't feel comfortable posting details about my server and server settings in a public forum. Would it be possible for you to specify only the exact information you need to debug the issue, as well as a private way to provide that information?

In the mean time, I have added the update back to our test site. Please take a look. Notice that images (as of 12/6/17) in the slideshow and in the columns below that were uploaded with your plugin are not displaying correctly. You can see the 403 (Forbidden) error messages in the browser console since the images do not exist at that file path. Images like the test image listed below do not contain the random number folder name that your plugin added when uploading the files to S3. But the production file path without your plugin update work just fine.

Test Site Data:
https://test.firsttoknow.com/
WordPress v4.9.1
Amazon Web Services v1.0.4
WP Offload v1.1.4

Test Site Image Path using AWS plugin v1.0.3
http://firsttoknow-cdn.s3.amazonaws.com/wp-content/uploads/2017/11/ajit-pai-1068x580.jpg

Production Site Image Path using AWS plugin v1.0.4
https://s3-us-west-2.amazonaws.com/firsttoknow-cdn/wp-content/uploads/2017/11/28151339/ajit-pai-1068x580.jpg

I received the following notice when I updated the AWS plugin to v1.04, but there is no update available for WP Offload S3 v1.1.4
> WP Offload S3 has been disabled because it will not work with the version of the Amazon Web Services plugin installed. WP Offload S3 1.5.1 or later is required. Update WP Offload S3 to the latest version. You can deactivate the WP Offload S3 plugin to get rid of this notice.

**Comment by ianmjones** [comment]
Hey @jlucero-contentad, looks like you're using WP Offload S3, not WP Offload S3 Lite. As such you should contact us directly for support, the best way is to submit a support request through the Support tab of the plugin as that will send us the diagnostic info we need by default too.

If you need a quick fix while we try and help, please revert to AWS 1.0.3.
