### ISSUE TITLE
URL set back to local

### ISSUE THREAD

**Issue by webtent** [deliciousbrains/wp-amazon-s3-and-cloudfront#421]
We use CloudFront with the Remove Files From Server option enabled. Sometime in the last week all or a lot of URLs reverted to the local domain path to the uploads folder and the subject files are not found locally or on S3, lost. Has anyone seen this behavior or know the cause? We also use a Media Library plugin called WP Media Folder and suspect it may have happened when someone was moving files into different folders, but not sure yet.

**Comment by ianmjones** [comment]
We've yet to see a "Media Manager" style plugin that does the right thing when it comes to using the WordPress API.

You can check the `amazonS3_info` postmeta records for where WP Offload S3 Lite expects to find the files on S3, unless of course something has removed them.
