### ISSUE TITLE
urls for images hosted on third party servers get rewritten

### ISSUE THREAD

**Issue by oweuxllc** [deliciousbrains/wp-amazon-s3-and-cloudfront#423]
This happened to us when using an image hosted on another server.

Here's the Scenario:

The image's name is favicon.ico and each website has one such file on the same location.

When using  src="https://otherdomain.com/favicon.ico" the image loaded corresponded to the version for the local favicon. Loading the developer tools revealed that the url was re-written to match that of the local favicon file (hosted on the s3 Service).

We understand that adding to your code is not recommended because the next update will delete our changes but in the meantime we edited 'as3cf-filter.php' to include a check to compare host names and skip images hosted on other servers. Here is a simplified version that I hope helps me explain how we corrected it so the problem becomes more clear. I am sure you have a better way of resolving the issue.

    protected function should_process_host($url_found, $url_wp){

        $src_host_names = explode(".", parse_url($url_found, PHP_URL_HOST));

        $src_host_names = array_slice($src_host_names, -2);//adjust for depth comparison

        $src_host_names = implode('.', $src_host_names);

        $wp_host_name = explode(".", parse_url($url_wp, PHP_URL_HOST));

        $wp_host_name = array_slice($wp_host_name, -2);//adjust for depth comparison

        $wp_host_name = implode('.', $wp_host_name);

        if (strpos($wp_host_name, $src_host_names) === false) {

            return false;

        }

    }

then added 

            if (!$this->should_process_host($url, get_site_url())) {
                // URL is foreign, skip
                continue;
            }

under 'get_urls_from_img_src' inside of 'foreach ($matches as $image)'

and 

 'get_urls_from_content' inside of ' foreach ($matches as $url)

**Comment by ianmjones** [comment]
Please can you give us an example of the configured Site URL and the link that is incorrectly filtered?

Also, are the two sites separate single site installs of WordPress, or part of the same multisite install?

**Comment by oweuxllc** [comment]
One of the two websites is not wordpress, just a plain html website. This plain website hosts the file:

https://oweux.com/favicon.ico

I have disabled our edits to the file 'as3cf-filter.php' so you can see the issue. 

I entered the new post page and entered the URL above, gave the page a title and pressed Publish. That generated this link:

https://www.match.cat/favico-issue/

When the page reloaded after saving

https://oweux.com/favicon.ico

got converted to:

https://images.match.cat/wp-content/uploads/2018/01/05114948/favicon.ico

Visiting the page as a guest also displays the modified URL

**Comment by ianmjones** [comment]
Hmm, interesting. If you look in the database at the `post_content` for that new example post, what do you see?

And do you have a "favicon.ico" in your Media Library?

**Comment by oweuxllc** [comment]
I do have a favicon.ico on the media library under this url:

https://images.match.cat/wp-content/uploads/2018/01/05114948/favicon.ico


If I look at the post_content with: 
SELECT * FROM `wp_posts` WHERE `ID` = 19061 OR `post_parent` = 19061

all relevant versions of the post have:

https://www.match.cat/wp-content/uploads/2018/01/favicon.ico

Both the editor and the LIVE version of the page show the s3 version of the link

As a test I added the URL (https://oweux.com/favicon.ico) as a second line using the editor on the same post and it gets switched again when stored to the DB to the 'local url' and displayed as the s3 version of the link.

If I edit the post directly on the DB and enter the URL (https://oweux.com/favicon.ico) it remains unmodified and is displayed correctly on both editor and LIVE page.

BUT after pressing update on the editor to save the document, the URL gets re-written to  https://www.match.cat/wp-content/uploads/2018/01/favicon.ico and displayed from its s3 location on the editor and LIVE.

**Comment by ianmjones** [comment]
@oweuxllc I can't reproduce this.

Have you by chance got some rewrite rules or code that uses that Media Library version of the favicon as the site's own favicon?

**Comment by oweuxllc** [comment]
@ianmjones I have disabled all plugins except:

Amazon Web Services
WP Offload S3 Lite

 I am using the theme:

twentyfifteen

.htaccess is the one that comes with WP server has no directive to add/remove www prefix.

https://oweux.com/favicon.ico still gets re-written when the post is saved.

Adding the code on the original post fixes the issue. At run-time the URL reaches your plugin unmodified. That is an another way, IMHO, your plugin is the one responsible; in enters OK but exits re-written.

I have added https://oweux.com/favicon.ico to a post o another website and it does not happen. Not sure why a site that is clean as can be has the issue while another one with 20+ plugins and customizations works fine.

I deleted the file: 

https://www.match.cat/wp-content/uploads/2018/01/favicon.ico

from the library and the problem went away. Maybe there is an issue when handling file names that already exist on the library. Weird that my code would fix this issue, maybe your 'url cache' is finding the favicon file and assumes it already knows the link and bypasses other parts of your code.

**Comment by ianmjones** [comment]
Good call about the URL cache, maybe an incorrect entry got created at some point that linked that external url with the Media Library ID. Although that shouldn't happen for new posts if the OS3/AWS plugins are all that's active.

Can you delete all 'amazonS3_cache' keyed postmeta records, then try the experiment again with only the WP Offload S3/AWS plugins active and favicon.ico back in the Media Library. It that doesn't show the error then it'll be time to hunt down the plugin that interfered.

**Comment by oweuxllc** [comment]
I am going to proceed as requested. Here are the contents of the 'amazonS3_cache' record on the 'post_meta' table prior to deletion -- just in case they are useful to you.

a:3:{
s:23:"//oweux.com/favicon.ico";
s:5:"16219";
s:54:"//www.match.cat/wp-content/uploads/2018/01/favicon.ico";
s:5:"16219";
s:66:"//images.match.cat/wp-content/uploads/2018/01/05114948/favicon.ico";
s:5:"16219";
}

**Comment by oweuxllc** [comment]
Issue remains with only these two plugins activated:

Amazon Web Services
WP Offload S3 Lite

After adding and pressing UPDATE

https://oweux.com/favicon.ico 

got changed to:

https://images.match.cat/wp-content/uploads/2018/01/11101542/favicon.ico

All URLs on the same document got changed to the above --- even those that linked to the the now dead URL:  https://images.match.cat/wp-content/uploads/2018/01/05114948/favicon.ico

Then... added this two dummy URLs (and pressing update)

https://blalasdada.com/favicon.ico
http://blalasdada.com/favicon.ico

yielded the same results. They got changed respectively to:

https://images.match.cat/wp-content/uploads/2018/01/11101542/favicon.ico
http://images.match.cat/wp-content/uploads/2018/01/11101542/favicon.ico

This is the current entry for 'amazonS3_cache': 

a:4:{
  s:54:"//www.match.cat/wp-content/uploads/2018/01/favicon.ico";
  s:5:"24811";
  s:66:"//images.match.cat/wp-content/uploads/2018/01/11101542/favicon.ico";
  s:5:"24811";
  s:23:"//oweux.com/favicon.ico";
  s:5:"24811";
  s:28:"//blalasdada.com/favicon.ico";
  s:5:"24811";
}

**Comment by ianmjones** [comment]
@oweuxllc If you haven't already, can you add the following image to your Media Library...

https://oweux.com/images/iconHouseLogo.png

Then update that post where you're seeing the conversion of https://oweux.com/favicon.ico to the library/S3 version to add another line with "https://oweux.com/images/iconHouseLogo.png".

After save does the post now display https://oweux.com/images/iconHouseLogo.png or the library/S3 version?

**Comment by oweuxllc** [comment]
@ianmjones 
I did as requested as follows:

1) saved https://oweux.com/images/iconHouseLogo.png to my local hard drive
2) +media and uploaded the file by drag and drop
3) pressed edit on the test page.
4) inserted https://oweux.com/images/iconHouseLogo.png and updated post

URL got changed to s3 url for the file uploaded on step 2: 
https://images.match.cat/wp-content/uploads/2018/01/12153758/iconHouseLogo.png

I also created a clean post and pasted the URL. same result after pressing publish.

**Comment by ianmjones** [comment]
I see that www.match.cat is routed through CloudFlare but oweux.com is not. Are they actually on the same server though?

If so, do you have anything in the wp-config.php for www.match.cat that deals with domains?

We still can't reproduce this at all without using rewrite rules in the web server though.

**Comment by oweuxllc** [comment]
www.match.cat has no redirects other than those in 'WordPress Address' and 'Site Address'. Both set to:
https://www.match.cat

They are both on the same Plesk on an AWS instance and they both have their DB on the same RDS instance -- with credentials that cannot write  to or read from each other's DB.

wp-config.php has nothing outside of the 'stock' options...

I could reinstall WP and see what happens but the way I was able to work around this issue is by adding the code that checks the origin domain on the URL against the local URL.

I just tested on another website using your plugin:


https://oweux.com/favicon.ico

got converted to:

https://imagenes.iberoeconomia.es/wp-content/uploads/2018/01/15145742/favicon.ico

on https://iberoeconomia.es


I added 'favicon.ico' to the library on that site. Then the following links on a page:

https://oweux.com/favicon.abc (does not exist)
https://oweux.com/favicon.ico (exists) +IN MEDIA LIBRARY
https://oweux.com/favicon.abc (does not exist)
https://oweux.com/favicon.jpg (does not exist)
https://oweux.com/favicon.png (does not exist)
https://oweux.com/ (exists)
https://oweux.com/images/iconHouseLogo.png (exists) NOT ON MEDIA LIBRARY


only https://oweux.com/favicon.ico was converted, all others remain unmodified.


After this I added iconHouseLogo.png to the media library - saving the document did not re-write the URL. Seems like the issue only occurs if the image exists on the media library prior to using it in a document. I added a second  https://oweux.com/favicon.ico and it still got modified.

**Comment by A5hleyRich** [comment]
The `url_needs_replacing` method in `AS3CF_Local_To_S3` should already ensure remote URLs are not replaced, so it's strange that your modification fixes the issue. The main difference I can see is that you're using `PHP_URL_HOST` where as we use `wp_upload_dir()`. Are you able to `print_r()` the return of `wp_upload_dir()` and `$base_url` from within that function?

**Comment by oweuxllc** [comment]
This is the output requested. It was generated when adding 'https://oweux.com/favicon.ico' to the document and pressing update. (URL gets re-written).

Array
(
    [base_url] => https://www.match.cat/wp-content/uploads
    [wp_upload_dir] => Array
        (
            [path] => /var/www/vhosts/match.cat/httpdocs/wp-content/uploads/2018/01
            [url] => https://www.match.cat/wp-content/uploads/2018/01
            [subdir] => /2018/01
            [basedir] => /var/www/vhosts/match.cat/httpdocs/wp-content/uploads
            [baseurl] => https://www.match.cat/wp-content/uploads
            [error] => 
        )

)

**Comment by oweuxllc** [comment]
I added $url to the output of url_needs_replacing( $url )

Array
(
    [url] => https://www.match.cat/wp-content/uploads/2018/01/favicon.ico
    [base_url] => https://www.match.cat/wp-content/uploads
    [wp_upload_dir] => Array
        (
            [path] => /var/www/vhosts/match.cat/httpdocs/wp-content/uploads/2018/01
            [url] => https://www.match.cat/wp-content/uploads/2018/01
            [subdir] => /2018/01
            [basedir] => /var/www/vhosts/match.cat/httpdocs/wp-content/uploads
            [baseurl] => https://www.match.cat/wp-content/uploads
            [error] => 
        )

)

You can see '$url' is 'https://www.match.cat/wp-content/uploads/2018/01/favicon.ico'
but what I entered on the post is 'https://oweux.com/favicon.ico'

It gets changed before it reaches this point in your code.

**Comment by oweuxllc** [comment]
Have you had any chance to review further? I do not mean to bother. Thank you for all of your help and investment of time on this issue.

**Comment by ianmjones** [comment]
We simply can't reproduce this problem at the moment. The only way we can get close is if we configure our web server with rules that first match on the "external" site (that is actually on same server) before falling through to the site that has a matching media library item.

**Comment by itcakm** [comment]
I am facing the same issue with a slight difference on the URL.
The images has successfully uploaded to S3. I can even check the file manually and it is there. However, after using Domain Mapping the image URLs change to files/revslider/home slider/banner2.jpg
it is not linking the image to S3.

**Comment by ianmjones** [comment]
@oweuxllc WP Offload Media (Lite) 2.3.2 includes some changes to filtering that may have resolved your issue (which we still can't reproduce by the way).

Please let us know whether this recent release fixed things up for you.

**Comment by ianmjones** [comment]
With the help of a customer we found the cause of this, now fixed in WP Offload Media (Lite) 2.4! 🎉

**Comment by oweuxllc** [comment]
Great! I am sorry for not replying to your latest question directed at me, not sure what happened there. I hope this finally resolves this issue.
