### ISSUE TITLE
Clone bucket to new environment breaks all media links

### ISSUE THREAD

**Issue by Jakst** [deliciousbrains/wp-amazon-s3-and-cloudfront#425]
I have copied all content from my production bucket (**content-production**) to my staging bucket (**content-staging**). I have the exact same code running in both environments and have cloned the database. I can access all the content from both buckets publicly, and the only difference in the URI's to access them is replacing **content-production** with **content-staging**.

Despite this, doing a search and replace from **content-production** to **content-staging** in the database breaks all media in the staging environment. However, creating new media works and is correctly uploaded to **content-staging**.

Any idea why a search and replace breaks all links?

**Comment by aaemnnosttv** [comment]
What method are you using for the search and replace? It sounds like you might be doing it in a way which is not safe for serialized data.

**Comment by Jakst** [comment]
@aaemnnosttv You are completely correct. I forgot to correct the string length in my search and replace. Closing this issue.
