### ISSUE TITLE
New Feature: Support S3 Pre-Signed URLs

### ISSUE THREAD

**Issue by bminer** [deliciousbrains/wp-amazon-s3-and-cloudfront#427]
It would be really cool (i.e. cool enough for me to buy the Pro version) if pre-signed URLs were supported by this plugin.  For example, I might want WordPress to generate a pre-signed URL with a time limit on it (maybe 60 seconds or so).  That way, S3 Objects would not be publicly accessible, but they could still be served to end-users.

https://docs.aws.amazon.com/aws-sdk-php/v3/guide/service/s3-presigned-url.html

Thoughts?

**Comment by A5hleyRich** [comment]
Signed URLs are already supported. You can use the `as3cf_upload_acl ` filter as shown in our tweaks plugin:

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/master/amazon-s3-and-cloudfront-tweaks.php#L30

Alternatively, the Pro version has a toggle button in the Media Library: 

https://deliciousbrains.com/wp-offload-1-1-released/

**Comment by bminer** [comment]
@A5hleyRich - I know you can save as private/public by changing the ACLs.  But, it would be cool if the plug-in could support pre-signed URLs (with a timeout) to retrieve the resource.  How would you do that with the tweaks?

**Comment by A5hleyRich** [comment]
When an object has private permissions, WP Offload S3 will automatically generate a signed URL. By default they expire after 15 minutes, but you can use the `as3cf_expires` filter to adjust the duration.

**Comment by bminer** [comment]
Very cool and good to know.  Thanks!

**Comment by karuppasamy-rajaguru** [comment]
Hi, I have the object with private permission still my image path is generated as common not signed URL

**Comment by ianmjones** [comment]
@karuppasamy-rajaguru For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
