### ISSUE TITLE
Error fetching buckets — Internal Server Error

### ISSUE THREAD

**Issue by ivoryhands** [deliciousbrains/wp-amazon-s3-and-cloudfront#428]
Site was using S3 Offload fine, until suddenly I got this error.

Export:

site_url(): https://alpha2.com
home_url(): http://alpha2.com
Database Name: alpha2
Table Prefix: wp_
WordPress: 4.9.2
Web Server: Apache/2.4.18 (Ubuntu)
PHP: 5.6.30-10+deb.sury.org~xenial+2
MySQL: 5.7.21
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 17 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 32 MB
PHP Time Limit: 300
PHP Error Log: /var/www/html/alpha2/wp-content/debug.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2k  26 Jan 2017
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.2.3
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 3,314
Media Files on S3: 166
Number of Image Sizes: 8

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
large (1024x1024)
medium-large (450x0)
medium (300x300)
small (120x0)

WP_CONTENT_DIR: /var/www/html/alpha2/wp-content
WP_CONTENT_URL: http://alpha2.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/html/alpha2/wp-content/plugins
WP_PLUGIN_URL: http://alpha2.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: alpha2
Region: ca-central-1
Copy Files to S3: On
Rewrite File URLs: On

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: alpha2
Active Theme Folder: alpha2
Parent Theme Folder: base-theme

Active Plugins:
Advanced Ads (v1.8.21) by Thomas Maier
Advanced Custom Fields PRO (v5.6.7) by Elliot Condon
Amazon Web Services (v1.0.4) by Delicious Brains
Campaign Monitor (v2.6.1) by Campaign Monitor
EWWW Image Optimizer (v4.0.6) by Shane Bishop
Enhanced Media Library (v2.4.5) by wpUXsolutions
Gravity Forms (v2.2.4) by rocketgenius
Gravity Forms Campaign Monitor Add-On (v3.5) by rocketgenius
Nested Pages (v2.0.4) by Kyle Phillips
SearchWP (v2.8.7) by SearchWP, LLC
ShiftNav Pro - Responsive Mobile Menu (v1.5.1) by Chris Mavricos, SevenSpark
Simple Sitemap (v2.4) by David Gwyer
Super Socializer (v7.9.6) by Team Heateor
WP Offload S3 Lite (v1.2.1) by Delicious Brains
Wordpress File Upload (v4.2.0) by Nickolas Bossinas

**Comment by ivoryhands** [comment]
Found this in the debug log: 

PHP Fatal error:  Class 'SimpleXMLElement' not found.

Am currently investigating.

**Comment by ianmjones** [comment]
Sounds like someone updated your PHP and forgot that WordPress needs the SimpleXMLElement library.
