### ISSUE TITLE
PHP Fatal error:  Call to undefined function wp_using_ext_object_cache()

### ISSUE THREAD

**Issue by ssant0s** [deliciousbrains/wp-amazon-s3-and-cloudfront#429]

**Comment by ssant0s** [comment]
After installing plugin received this error:: PHP Fatal error: Call to undefined function wp_using_ext_object_cache() and home goes page blank.

**Comment by A5hleyRich** [comment]
What version of WordPress are you using? `wp_using_ext_object_cache()` is a WordPress core function.
