### ISSUE TITLE
Get the files back from S3 to local

### ISSUE THREAD

**Issue by edubuc** [deliciousbrains/wp-amazon-s3-and-cloudfront#430]
Hi,
I used the plugin for a client of mine to speed up his site, the local files were deleted. 
Now he want to leave us and want his site back, how can I easily get the images back from S3 to local?

**Comment by ianmjones** [comment]
You can either download them via the **AWS Console** or **awscli** and place them back in the correct place, or if you have a WP Offload S3 license it has a tool on the settings page to "**Remove all files from S3**" which will download anything that isn't on the local filesystem and then remove it from the S3 bucket. WP Offload S3 also has a "**Download all files from S3 to server**" tool should you wish to leave the files in the bucket for the time being.

**Comment by edubuc** [comment]
Hi,
The biggest issue with w3 licence is that it’s limited to a number of media file (I don’t understand why whereas the free plugin isn’t limited to a numbers of files, it seems they want you to pay to get less)

Is the « Download all files from S3 to server » a part of the free version?

The issue with downloading from s3 is that all folder are prefixed with a number

**Comment by ianmjones** [comment]
> Is the « Download all files from S3 to server » a part of the free version?

No, it's in the Pro version only.

> The issue with downloading from s3 is that all folder are prefixed with a number

Yes, if you've been using the Object Versioning (recommended) then you will need to move the files out of those numeric folders after manually downloading. This isn't a problem when using the "Download all files from S3 to server" tool in the Pro plugin, it downloads to the file's original local folder, saving a lot of time/hassle.
