### ISSUE TITLE
SQL synatx error when using `attachment_url_to_postid`

### ISSUE THREAD

**Issue by mpgo13** [deliciousbrains/wp-amazon-s3-and-cloudfront#431]
Call WP's `attachment_url_to_postid('Bill\'s-letter.jpg')`

Expected result: No SQL error
Actual result: `WordPress database error You have an error in your SQL syntax;...`

**Comment by ianmjones** [comment]
Thanks for the bug report and PR @mpgo13.

**Comment by banago** [comment]
Same issue here.

**Comment by ianmjones** [comment]
Fixed in [release 1.4](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/releases/tag/1.4)

Thanks for raising this and the PR @mpgo13.
