### ISSUE TITLE
Image don't upload to s3 if using the function "get image from url" from 3rd party plugin

### ISSUE THREAD

**Issue by kid1810** [deliciousbrains/wp-amazon-s3-and-cloudfront#433]
I used AWS + WP OFFLOAD S3 plugin, and Zombify plugin & Boombox theme.

I have problem as below.

1- When I used get img in the front end from this url: https://scontent.fsgn5-2.fna.fbcdn.net/v/t1.0-9/27657228_3930381430623945_1127970149838751021_n.jpg?oh=36a1a2d9a62c954bbc14df86e06445df&oe=5AD846D3

The image get downloaded to local storage and was not uploaded to amazon s3

Same thing happened with this url: https://i.redditmedia.com/BQJuIw4tno7w0y4xuiFp2FiKgWPdSJZZ-JhaIGo-Ss0.jpg?w=1024&s=0400def0488a680de4cb5dde6aa5a402

However, with this url: https://i.imgur.com/SXebxRf.jpg

Everything worked fine.

2- So I try to download & upload the 2 pics from facebook & reddit links above, and I keep the same file name. When upload at backend admin, the 2 images were upload to s3 successfully.

So there must be something wrong when s3 plugin decided to upload and don't upload.

Can you advice?

Thanks

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "License & Support" tab in the plugin.
