### ISSUE TITLE
Error fetching buckets 

### ISSUE THREAD

**Issue by GinnyHung69** [deliciousbrains/wp-amazon-s3-and-cloudfront#435]
Hi, I have some problem can't use WP offload S3 on AWS Linux2 EC2 instance.
Could you help me, please?! Thanks!

site_url(): https://yiginny.com
home_url(): https://yiginny.com
Database Name: ginnyblog
Table Prefix: wp_
WordPress: 4.9.4
Web Server: Apache/2.4.6 (Amazon Linux 2) PHP/7.2.0
PHP: 7.2.0
MySQL: 5.6.37
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 4 MB
Blocked External HTTP Requests: None
WP Locale: zh_TW
Organize uploads by month/year: Disabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 2 MB
PHP Time Limit: 30
PHP Error Log: /var/www/html/wp-content/debug.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2k-fips  26 Jan 2017
cURL: Enabled
Zlib Compression: Enabled
PHP GD: Disabled
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 0
Media Files on S3: 0
Number of Image Sizes: 5

Names and Dimensions of Image Sizes: 
thumbnail (none)
medium (none)
large (none)
post-thumbnail (none)

WP_CONTENT_DIR: /var/www/html/wp-content
WP_CONTENT_URL: https://yiginny.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_PLUGIN_URL: https://yiginny.com/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: 
Region: 
Copy Files to S3: Off
Rewrite File URLs: Off

Local URL:
https://yiginny.com/wp‑content/uploads/photo.jpg
S3 URL:
https://s3.amazonaws.com//wp‑content/uploads/20180213150104/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: Off
Force HTTPS: Off
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: Twenty Sixteen
Active Theme Folder: twentysixteen

Active Plugins:
Amazon Web Services (v1.0.4) by Delicious Brains
WP Offload S3 Lite (v1.2.1) by Delicious Brains

and this is mysite log : https://yiginny.com/wp-content/debug.log

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "License & Support" tab in the plugin.
