### ISSUE TITLE
Medialibrary dont show any images

### ISSUE THREAD

**Issue by elastic2ls-awiechert** [deliciousbrains/wp-amazon-s3-and-cloudfront#436]
Hi,

after I've installed Offload S3 the images stored localy in the WP folder are not shown anymore. Also the upload function does not work anymore.
--Alex

![bildschirmfoto 2018-02-27 um 20 55 31](https://user-images.githubusercontent.com/11214152/36751469-9287a99a-1c00-11e8-81f5-e44d7c263d91.png)
![bildschirmfoto 2018-02-27 um 20 55 20](https://user-images.githubusercontent.com/11214152/36751470-92b8ac0c-1c00-11e8-89e2-1859a636f0a8.png)

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "License & Support" tab in the plugin.
