### ISSUE TITLE
Media download

### ISSUE THREAD

**Issue by ChrisButterworth** [deliciousbrains/wp-amazon-s3-and-cloudfront#437]
Is there a way to download all the imagery into the local directory?
AWS is getting a little bit too expensive for the client so looking to move away from the plugin.

**Comment by ianmjones** [comment]
WP Offload S3 has a "Download all files from S3 to server" tool.

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.

**Comment by ChrisButterworth** [comment]
Where is that tool??

**Comment by ChrisButterworth** [comment]
Thanks will sort out a license to do this
