### ISSUE TITLE
There was an error attempting to check the permissions of the bucket cdn. Access Denied

### ISSUE THREAD

**Issue by GLOBALcloud** [deliciousbrains/wp-amazon-s3-and-cloudfront#438]
The below bucket policy is used to protect files from being downloaded from url gives this error in > Settings > Offload S3 :

There was an error attempting to check the permissions of the bucket cdn.sample.com: Access Denied

I cannot upload to S3 but if the policy is removed the plugin works just fine, wonder how to make the plugin compatible with this policy?

> {

    "Version": "2012-10-17",
    "Id": "http referer policy example",
    "Statement": [
        {
            "Sid": "Allow get requests referred by www.sample.com and sample.com.",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::cdn.sample.com/*",
            "Condition": {
                "StringLike": {
                    "aws:Referer": [
                        "https://www.sample.com/*",
                        "https://sample.com/*"
                    ]
                }
            }
        },
        {
            "Sid": "Explicit deny to ensure requests are allowed only from specific referer.",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::cdn.sample.com/*",
            "Condition": {
                "StringNotLike": {
                    "aws:Referer": [
                        "https://www.sample.com/*",
                        "https://sample.com/*"
                    ]
                }
            }
        }
    ]
}

>

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
