### ISSUE TITLE
get_avatar() problem

### ISSUE THREAD

**Issue by n0madic** [deliciousbrains/wp-amazon-s3-and-cloudfront#439]
When I try to get a link to the author's avatar using the standard function [get_avatar()](https://developer.wordpress.org/reference/functions/get_avatar/), the link to "s3://" is returned
```php
echo get_avatar($tw_author_email, $size = '120');
```
s3://bucketname/wp-content/uploads/2017/11/unnamed-120x120.png

P.S. WordPress v4.9.4, WP Offload S3 Lite v1.3.2

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
