### ISSUE TITLE
Function to upload Old Images in Bulk

### ISSUE THREAD

**Issue by eanbowman** [deliciousbrains/wp-amazon-s3-and-cloudfront#44]
Instead of having to manually re-upload old images, some way to bulk send the old ones to S3. This is almost a deal breaker really.

**Comment by tomasdev** [comment]
:+1:  I think this is partially done.

I think it was moving a couple old images in my case (or at least some that weren't in S3) and it had the warning "we're uploading in background every 10 mins... in small batches" but it disappeared before uploading all images (i have around 30k images)

**Comment by A5hleyRich** [comment]
@tomasdev Those notices wouldn't have come from WP Offload S3, as this functionality it not part of the free plugin.

The only process performed in the background is the update of meta data, which does not upload any files to S3.

**Comment by tomasdev** [comment]
@A5hleyRich then I found a bug hard to reproduce (I wasn't able to do that again) - it uploaded about 7-10 images

**Comment by sandys** [comment]
running `aws s3 --profile YOUR_PROFILE_NAME_HERE sync /path/to/your/local/content s3://YOUR_BUCKET_NAME_HERE --cache-control "max-age=315576000"` works very well to upload existing images to s3. I typically upload the entire `wp-content` directory to  `<MY_BUCKET>/wp_content`

is there a way to rewrite the image paths in the database to use the new route ?

I know there is a way to use .htaccess

`RewriteEngine On
RewriteRule ^/wp-content/uploads/(.*)$	http://MY-BUCKET.s3.amazonaws.com/$1 [L]`

but will this work for the new images going forward as well ? (as well as a situation when we have a feature to directly upload images to s3)

**Comment by polevaultweb** [comment]
Existing image upload is coming in the Pro version, which is being released soon. The CLI method doesn't connect the attachment metadata with the S3 upload so URL rewriting isn't possible with the plugin as is.

**Comment by A5hleyRich** [comment]
Feature available in the Pro version. Closing

https://deliciousbrains.com/wp-offload-s3/
