### ISSUE TITLE
Pre signed url not generated in other croped images

### ISSUE THREAD

**Issue by karuppasamy-rajaguru** [deliciousbrains/wp-amazon-s3-and-cloudfront#441]
Pre signed url not generated in other croped images like thumbnail and medium size images

**Comment by ianmjones** [comment]
If you're using the `as3cf_upload_acl` filter to set uploaded objects as private on S3, you can also use the `as3cf_upload_acl_sizes` filter in the same way for image thumbnails etc.

See the example in the Tweaks plugin:-

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/3e83234e96f67b823ae94d27385cf9603d149c0b/amazon-s3-and-cloudfront-tweaks.php#L131
