### ISSUE TITLE
S3 image upload by particular post types

### ISSUE THREAD

**Issue by karuppasamy-rajaguru** [deliciousbrains/wp-amazon-s3-and-cloudfront#442]
Any hook available to upload image to s3 for the particular post types

**Comment by ianmjones** [comment]
Check out the [Tweaks](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/master/amazon-s3-and-cloudfront-tweaks.php) plugin.

You can use the `as3cf_pre_update_attachment_metadata` filter to determine whether an item should be offloaded, you could likely query through to the attachment's parent post.

The `as3cf_object_meta` filter is great for altering where in the bucket an item goes should you need that.
