### ISSUE TITLE
images not visible in editor while uploaded onsame path

### ISSUE THREAD

**Issue by sangeeta18995** [deliciousbrains/wp-amazon-s3-and-cloudfront#443]
hi,
i have an issue that my default path is set up like https://hindi.mapsofindia.com/wp‑content/uploads/2018/03/photo.jpg  and because of this my images are visible in backend editor while they are visible on frontend and when i attach a image to a post its url looks like https://hindi.mapsofindia.com/wp‑content/uploads/2018/03/photo.jpg thats a wrong beacuase no file uploaded at this location it should be ashttps://images.mapsofindia.com/hindimoi/2018/03/photo.jpg kindly provide me its solution.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
