### ISSUE TITLE
WP_sitemeta thousands of 'as3cf_constant_WPOS3_SETTINGS' rows

### ISSUE THREAD

**Issue by brandtparker** [deliciousbrains/wp-amazon-s3-and-cloudfront#446]
v1.3.2

I've been running into a server issue, seeing sluggishness and 500 errors due to memory exhaustion, due to long queries to `wp_sitemeta`. Upon investigation found there are hundreds of thousands of `as3cf_constant_WPOS3_SETTINGS` rows in our LIVE db. Is this expected? Why would there be so many, and how can I reduce this?

For full context, we entered all our site content on our TEST environment and copied that over to LIVE at launch, which was 1 week ago. The TEST DB `wp_sitemeta` table has 49 rows. LIVE has 633k, with the vast majority for the `as3cf_constant_WPOS3_SETTINGS` key.

**Comment by ianmjones** [comment]
This issue is now being handled via support, looks to be an issue related to the site not handling `update_site_option()` calls correctly.
