### ISSUE TITLE
CDN S3 Media srcset attribut is empty

### ISSUE THREAD

**Issue by khalidahmada** [deliciousbrains/wp-amazon-s3-and-cloudfront#447]
Hi, I have an issue is about srcset when i activate your plugin for Media CDN AWS S3 every thing works just fine. except i have no responsive image srcset become empty ( it's work fine ) before install AWS S3.....

**Comment by ianmjones** [comment]
Hi @khalidahmada, this isn't a support forum, please submit a support request via WP Offload S3's built in support tab.

If you don't have a license then you could try the [community support forum](https://wordpress.org/support/plugin/amazon-s3-and-cloudfront).

You'll need to supply some information and what you've done so far to debug it in order for anyone to be able to try and help you. Diagnostic Info and debug.log files are also helpful.
