### ISSUE TITLE
Setting secure keys in .env file

### ISSUE THREAD

**Issue by kaldimar** [deliciousbrains/wp-amazon-s3-and-cloudfront#448]
When using an `.env` file to keep secure credentials separated per environment, for example while using `phpdotenv`, the AWS key id and secret cannot be set through the .env file.

If I add these debugs inside your `as3cf_init()` function after setting up the environment variables, I get the following:

    var_dump( $_SERVER['AS3CF_AWS_ACCESS_KEY_ID'] );  // string 'ASDFGHJKLZXCVBNMQWER' (length=20)
    var_dump( $_ENV['AS3CF_AWS_ACCESS_KEY_ID'] );  // string 'ASDFGHJKLZXCVBNMQWER' (length=20)
    var_dump( getenv( 'AS3CF_AWS_ACCESS_KEY_ID' ) );  // string 'ASDFGHJKLZXCVBNMQWER' (length=20)
    var_dump( defined( 'AS3CF_AWS_ACCESS_KEY_ID' ) );  // boolean false
    var_dump( DeliciousBrains\WP_Offload_S3\Amazon_Web_Services::access_key_id_constant( 'AS3CF_AWS_ACCESS_KEY_ID' ) );  // boolean false

**Comment by ianmjones** [comment]
@kaldimar WP Offload S3 does not inherently support `.env` files or do anything to stop them working via something like `phpdotenv`.

However, you will need to convert either of those `getenv` or `$_SERVER` entries to `define` values in your wp-config.php one way or another for WP Offload S3 to be able to use them.

**Comment by kaldimar** [comment]
Well many Wordpress distributions like the one provided by Roots (Bedrock + Sage) are becoming more and more popular every day. What if instead of closing this issue, which basically forces us to not use Offload S3 in our projects, you guys take a PR to update the plugin and allow `getenv()` compatibility? Wordpress setups relying on `composer` and a build process don't allow manual editing of the `wp-config.php` file.

**Comment by aaemnnosttv** [comment]
As Ian said, _nothing is stopping you from using phpdotenv to set these values from environment variables_. The plugin allows these to be set via constants. If you want to set them with environment variables defined in `.env`, all you need to do is add the constant definitions which are defined by the environment variable values. In Bedrock, this is as simple as adding a few lines to your `config/application.php` file, and is the exact same thing the framework does internally.

https://github.com/roots/bedrock/blob/31c638fe5a33d9e40a5c9eee07a94deb9cb76adc/config/application.php#L71-L77

**Comment by kaldimar** [comment]
Thanks for the hint, I didn't consider that option before!
