### ISSUE TITLE
Regenerate Thubnails

### ISSUE THREAD

**Issue by Conehard** [deliciousbrains/wp-amazon-s3-and-cloudfront#452]
Hi,
I saw in another issue that the plugin is compatible with the "Regenerate Thumbnails" plugin, if I use the lite version of WPSO, the plugin will download the images that are in S3 to do the regeneration?

**Comment by ianmjones** [comment]
Yes.

**Comment by Conehard** [comment]
When I try to regenerate my thumbnails, the image files weren't found. "Rewrite File URLs" and "Remove Files From Server" options are enabled.
When the image file, is in "local server/elastic beanstalk" works. 

Can you help me with it?

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
