### ISSUE TITLE
 Error executing "PutObject" on ...permission-check.txt

### ISSUE THREAD

**Issue by shareandlookhomes** [deliciousbrains/wp-amazon-s3-and-cloudfront#455]
Hi,
i am having several issues to configure Amazon S3 on my wordpress blog. I don't know if it's a bug or not but I have tried everything and also talked with Amazon Support.

I have all the information in my wp-config.php, as also tells the Diagnostic Info page but my files are not uploaded to my S3 bucket when I try to do so (obviously the button to upload is ON)... 

On the Media Library page It shows this error:

There was an error attempting to check the permissions of the bucket sharelookhomes: Error executing "PutObject" on "xxxxxxxxxxxxxxxx/as3cf-permission-check.txt"; AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

From the Diagnostic page, the only thing I see in blank is the region, but it should work...:
....
AS3CF_REGION: eu-central-1
Bucket: xxxxxxxxxxxx
Region:
...

My page is: https://www.shareandlookhomes.com/
Many thanks

**Comment by ianmjones** [comment]
This looks like a problem with your server's setup, in particular cURL isn't able to verify the AWS certificate because it is missing some local libraries maybe?

What happens if you run the following command from the server?

```
curl -I https://aws.amazon.com/
```

**Comment by shareandlookhomes** [comment]
Hi,

I bought the full version and it worked! There's something different
between your free plugin version and the full version...

Now it's ok.

Thanks.

2018-06-21 11:09 GMT+02:00 Ian M. Jones <notifications@github.com>:

**Comment by ianmjones** [comment]
Haven't heard anything more about this, no further information supplied.

Will reopen if more information and steps to replicate provided.

**Comment by shareandlookhomes** [comment]
Hi,

I made the request from the wordpress directly.

2018-06-26 17:17 GMT+02:00 Ian M. Jones <notifications@github.com>:

**Comment by maximilliangeorge** [comment]
> This looks like a problem with your server's setup, in particular cURL isn't able to verify the AWS certificate because it is missing some local libraries maybe?
> 
> What happens if you run the following command from the server?
> 
> ```
> curl -I https://aws.amazon.com/
> ```

This gives me the following error:

```
curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs
```

I'm using the latest official Wordpress docker image (`wordpress:latest`)
