### ISSUE TITLE
Fatal error: Class not found 

### ISSUE THREAD

**Issue by banago** [deliciousbrains/wp-amazon-s3-and-cloudfront#457]
Hi guys,

What seems to be the issue here? Thanks!

`Warning:  include(): Failed opening '/var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws2/vendor/composer/../../aws/aws-sdk-php/src/Aws/Common/Aws.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws2/vendor/composer/ClassLoader.php on line 440`

`Fatal error:  Uncaught Error: Class 'DeliciousBrains\\WP_Offload_S3\\Aws2\\Aws\\Common\\Aws' not found in /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-web-services.php:162\nStack trace:\n#0 /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php(2590): DeliciousBrains\\WP_Offload_S3\\Amazon_Web_Services->get_client()\n#1 /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-plugin-compatibility.php(605): Amazon_S3_And_CloudFront->get_s3client('', true)\n#2 /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-plugin-compatibility.php(661): AS3CF_Plugin_Compatibility->register_stream_wrapper('')\n#3 /var/www/html/wp-includes/class-wp-hook.php(286): AS3CF_Plugin_Compatibility->get_stream_wrapper_file('http://s3.amazo...', '/var/www/html/w...', 231025, Array)\n#4 /var/www/html/wp-includes/plugin.php(203): WP_Hook->apply_filters('http://s3.amazo...', Array)\n#5 /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and in /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-web-services.php on line 162`

**Comment by ianmjones** [comment]
Looks like you have an issue with your install of an earlier version of WP Offload S3 Lite, I'd try deleting it and installing the latest version.

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.

**Comment by banago** [comment]
Thanks @ianmjones
