### ISSUE TITLE
This query is killing my database

### ISSUE THREAD

**Issue by banago** [deliciousbrains/wp-amazon-s3-and-cloudfront#458]
Hi guys,

I see this query through mysql `show full processlist` and it's keeping the CPU of my database at 100% non stop:

    SELECT `post_id`
        FROM `wp_postmeta`
        WHERE `wp_postmeta`.`meta_key` = 'amazonS3_info'
        AND ( `wp_postmeta`.`meta_value` LIKE '%s:3:\"key\";s:49:\"wp-content/uploads/2013/04/image-name.jpg\";%'
        OR `wp_postmeta`.`meta_value` LIKE '%s:3:\"key\";s:38:\"uploads/2013/04/image-name.jpg\";%' )

I see this is coming from [this function](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/357c07bbbc20fa1340993c6ad4af44f025176f39/classes/as3cf-plugin-compatibility.php#L507): [customizer_background_image], if I'm not wrong: `customizer_background_image`. I cannot figure out why this is running non stop. 

Through query monitor plugin I see this function running 10-30+ times for each page load: `update_meta_cache()`. I suspect these two issues are related.

Please help

**Comment by ianmjones** [comment]
I suspect you're not using the latest version of WP Offload S3 Lite, there's a fix in it related to the `attachment_url_to_postid()` function that'll likely help.

**Comment by banago** [comment]
I'm on 1.4.1, which is the latest version. What I'm going to do now is comment [this line](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/357c07bbbc20fa1340993c6ad4af44f025176f39/classes/as3cf-plugin-compatibility.php#L65), since this seems to run non-stop: 

    add_filter( 'attachment_url_to_postid', array( $this, 'customizer_background_image' ), 10, 2 );

Let's see what happens.

**Comment by banago** [comment]
@ianmjones, yes commenting that line out solved the problem. The CPU load has gone to minimum. Can you please explain to me if that line is supposed to run on for every image on each page load? Is this a bug, or there is something wrong with my setup? Thanks.

**Comment by scarstens** [comment]
bump
