### ISSUE TITLE
On Divi builder in visual builder mode the images are pointing to local url

### ISSUE THREAD

**Issue by laxmikanta415** [deliciousbrains/wp-amazon-s3-and-cloudfront#459]
Hi,

In Divi builder in visual builder mode the images are pointing to local url, rather than s3 url , Is there any fix for this

**Comment by ianmjones** [comment]
WP Offload S3 1.7 introduced an integration for Divi Builder.

https://deliciousbrains.com/wp-offload-s3/doc/divi-builder-integration/

**Comment by ianmjones** [comment]
Because of the amount of work it takes to support and test an integration with a premium theme like Divi and its Divi Builder, we can only support it in WP Offload S3, not WP Offload S3 Lite.

You read more about WP Offload S3 and purchase a license at https://deliciousbrains.com/wp-offload-s3/
