### ISSUE TITLE
wp_postmeta amazonS3_info not updated on RESTORE ORIGINAL IMAGE when IMAGE_EDIT_OVERWRITE == false

### ISSUE THREAD

**Issue by georgekaz** [deliciousbrains/wp-amazon-s3-and-cloudfront#461]
**Setup**
WP Offload S3 Lite: Version 1.4.2
Amazon Web Services: Version 1.0.5
Wordpress: Version 4.9.7
PHP 7.2 fpm
All other plugins disabled.

**WP Offload S3 Lite Settings**
Copy Files to S3: on
Rewrite File URLs: on 
Custom Domain: my s3 domain (no cloudfront)
Path: on : wp-content/uploads/
Year/Month: off
Force HTTPS: off
Remove Files From Server: on
Object Versioning: off

**Steps to reproduce**
1. Add image to Media Library
2. Edit image
3. Crop image and save
4. Return to Media Library and see new cropped image
5. Edit image
6. Restore Original Image

**Expected behaviour**
Image should be restored to original

**Actual Behaviour**
Image is not restored to original

**What's happened?**
In the database the amazonS3_info metadata still contains a reference to the modified version

**A fix/workaround**
define('IMAGE_EDIT_OVERWRITE', true);

**Downside of the workaround**
If you wanted to keep all the edited versions you can't

**Comment by ianmjones** [comment]
Thanks for the bug report @georgekaz.

Question, when you do the restore, do you see anything in the debug log?

**Comment by ianmjones** [comment]
Thanks for the info, very helpful, we'll look into it.

**Comment by georgekaz** [comment]
No problem.

Looks like the problem is line 315 of
wp-content/plugins/amazon-s3-and-cloudfront/classes/as3cf-plugin-compatibility.php

which returns before the update_post_meta on line 326. It seems as though the function is slightly mis-ordered and should be more along the lines of:

```
public function image_editor_remove_files( $pre, $post_id, $data ) {
		if ( ! isset( $_POST['do'] ) || 'restore' !== $_POST['do'] ) {
			return $pre;
		}

		$s3object = $this->as3cf->get_attachment_s3_info( $post_id );

		// Update object key with original filename
		$restored_filename = wp_basename( $data['file'] );
		$old_filename      = wp_basename( $s3object['key'] );
		$s3object['key']   = str_replace( $old_filename, $restored_filename, $s3object['key'] );
		update_post_meta( $post_id, 'amazonS3_info', $s3object );

		if ( ! defined( 'IMAGE_EDIT_OVERWRITE' ) || ! IMAGE_EDIT_OVERWRITE ) {
			$this->remove_edited_image_files( $post_id, $s3object );
		}

		return true;
	}
```

Anyway, I'll leave it to you. Thanks

**Comment by ianmjones** [comment]
@georgekaz Does this still happen with WP Offload Media Lite 2.5.3?
