### ISSUE TITLE
Not fully working on all wordpress 

### ISSUE THREAD

**Issue by crossing1** [deliciousbrains/wp-amazon-s3-and-cloudfront#462]
Hello,

After install I have noticed that plugin have effect only on pages/posts. I’m using a freelancer WordPress template so the employer/freelancer are able to upload their files on website. I have noticed that the files are uploaded to Amazon S3 only if they are jpg, pdf, etc , I need to it to work with zip, rar files.

Another issue is that the download link on website is from Wordpress upload folder instead of Amazon S3. I have also enabled “Remove Files From Server”, they are sent to Amazon S3 and they can be deleted from the upload folder by selecting proper delete option on website, while the download link remains the same to my server upload folder so when the client click on it they get error page (because I have enabled "Remove Files From Server". I need to solve this problems.

So the problems are:

1. How to allow zip/rar to be uploaded on Amazon S3 because right now works only with media.

2. Why the download link when files are uploaded on website is from upload folder instead of Amazon S3 link.

I have looked over the https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks but I don't really know what to enable there to solve my problem. Actually I uncommented this line with no effect

`//add_filter( 'as3cf_wp_get_attachment_url', array( $this, 'wp_get_attachment_url' ), 10, 2 );`

The strange thing is that deleted option deletes the file from Amazon S3 (even if its not present on my server).

This is thecode that generates the download link:

`   echo '<a href="' . $value->guid . '" target="_blank"><i class="fa fa-cloud-download" aria-hidden="true"></i></a>'; `

Extracted from here, you can also see delete code that does the proper job deleting the file from Amazon even if not present on my server:

`  <?php 

							            if ( $post->post_status == 'close' && $value->post_author == $user_ID && ! $value->post_parent && ( fre_share_role() || ae_user_role() == FREELANCER ) ) {

								            echo '<a href="' . $value->guid . '" target="_blank"><i class="fa fa-cloud-download" aria-hidden="true"></i></a>';
								            if ( $lock_file != 'lock' ) {
									            echo '<a href="#" data-post-id="' . $value->ID . '" data-project-id="' . $post->ID . '" data-file-name="' . $value->post_title . '" class="delete-attach-file"><i class="fa fa-times" aria-hidden="true" data-post-id="' . $value->ID . '" data-project-id="' . $post->ID . '" data-file-name="' . $value->post_title . '"></i></a>';
								            }
							            } else {
								            echo '<a href="' . $value->guid . '" target="_blank"><i class="fa fa-cloud-download" aria-hidden="true"></i></a>';
							            }
							            ?>`

Can you please alter the proper line to actually download the file from Amazon instead on Wordpress upload folder ?

Thank you

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
