### ISSUE TITLE
Closed issue not solved

### ISSUE THREAD

**Issue by crossing1** [deliciousbrains/wp-amazon-s3-and-cloudfront#466]
Can you please check this issue because its still there https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/464#issuecomment-409872535

Is there any chance to fix the issue, I' really need to use the plugin but not with this problem.

**Comment by crossing1** [comment]
I have this issue only on profile avatar image. What's happening is when I upload the image the initial big size image is loaded properly on amazon s3 / cloudfront , only the second cropped image link its screwed like this https://mysite.net/wp-content/uploads/s3eucentral1://evaluari/private/uploads/2018/08/08190833/cropped-1.jpg ,

Altering the code would solve my problem, if not, at least to disable that file to be processed by amazon s3 offload using tweaks plugin but I don't know how to do that. File name is modal-upload-avatar.php with this content , 

`<?php
global $user_ID;

$avatar_id = get_user_meta($user_ID,'et_avatar',true);
$avatar_url = get_user_meta($user_ID,'et_avatar_url',true);

$avatar_data = wp_get_attachment_image_url($avatar_id,'full');
?>
<style>
	#md_user_avatar_thumbnail img{
		max-width: 100%;
		margin: 0 auto;
	}
    #container_crop_avatar > img {
        max-width: 100%;
    }
</style>
<div class="modal fade" id="uploadAvatar">
	<div class="modal-dialog">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
                <i class="fa fa-times"></i>
            </button>
            <h4 class="modal-title"><?php _e("Upload profile picture", ET_DOMAIN) ?></h4>
        </div>
		<div class="modal-content">
			<div class="modal-body">
				<form class="form-save-avatar" data-processing = 'no'>
					<div class="fre-input-field text-center">

                        <div class="preview-image" id="container_crop_avatar" data-is_crop="false">
							<?php if(!empty($avatar_data)){ ?>
                                <img src="<?php echo $avatar_data ?>" class="avatar photo avatar-default">
							<?php }else{ ?>
								<?php echo get_avatar( $user_ID, 150 ) ?>
							<?php } ?>
                        </div>

						<div class="" style="margin-top: 50px">
							<button type="submit" class="fre-normal-btn fre-submit-portfolio">
								<?php _e('Save profile picture', ET_DOMAIN) ?>
							</button><br><br>

                            <div  id="md_user_avatar_container" data-avatar_id="<?php echo $avatar_id ?>">
                                <a class="fre-form-close" href="#" id="md_user_avatar_browse_button" style="margin-left: 0">
		                            <?php _e( 'Change picture', ET_DOMAIN ) ?>
                                </a>
                                <span class="et_ajaxnonce hidden" id="<?php echo de_create_nonce( 'md_user_avatar_et_uploader' ); ?>"></span>
                            </div>
						</div>

					</div>
				</form>
			</div>
		</div>
	</div>
</div>`

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.
