### ISSUE TITLE
Customizer data with WPMU Domain Mapping Plugin Active

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#467]
So...finally have isolated the issue with customizer css paths.

When this very popular  and important plugin is active: https://premium.wpmudev.org/project/domain-mapping/ and a domain is added for mappping.

In the customizer css if user enters amazon s3 path that is part of their image library, for some reason either your plugin gets confused (or something else happens) and it rewrites the remote path to the local image file location instead of keeping the s3 location. If a remote file from some where else is there then no re-writing occur. So the re-write could only be done by your plugin.

Everything else seems pretty great..minus this scenario. It happens in all themes and only in customizer css and I think customizer conrols css.

IE if a theme has an image selector (ie background) the user uses the customizer to select the image and then save. It will appear fine but after saving with domain mapping active during the save and visiting the mapped domain location, it will also show the local broken path (i have the s3 setting to remove local files)

Disabling the domain mapping plugin, then re-saving and then revisiting the page shows the customizer css paths working without issue. So the issue only happens when domain mapping is active and after something gets saved and then viewed on the mapped domain.

So there the problem is isolated and confirmed. Everything else works without issue. Please reach out if you are having trouble duplicating and I can walk you through it.

Thanks for the great work hopefully we can end this mystery its been going on for a while but i wasn't sure how to figure out the cause.

Thanks!

**Comment by ianmjones** [comment]
You probably need to tell WP Offload S3 that the site has more than one domain.

https://deliciousbrains.com/wp-offload-s3/doc/filtering-urls-for-multiple-domains/

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload S3 license please use the "Support" tab in the plugin.

**Comment by mrbm** [comment]
@ianmjones 

Thanks for the quick response, appreciate all your work in this amazing plugin

>> You probably need to tell WP Offload S3 that the site has more than one domain.

If that were true...then the the s3 swap wouldn't be working everywhere else on the site...but it does! Its only when the customizer generates css from controls and css manually entered in the customizer only. Everywhere else the swaps are working great for me.

I think the wpmudev plugin is messing things up when it does its own "mapped domain" swapping of urls that's somehow interfering with your swapping process. 

The reason why your plugin is swapping the remote path to the local path of items in its media libraras the final output I don't quite understand, but it is indeed a function that could only be done by your plugin. If there was an option to "leave customizer css along" that would be a quick fix!
