### ISSUE TITLE
Updating plugin via filesystem does not run metadata update

### ISSUE THREAD

**Issue by lurchpop** [deliciousbrains/wp-amazon-s3-and-cloudfront#469]
Not everyone can update via the WP UI because the files aren't sitting on a single server.  

We update our plugins on a development server, verify nothing broke, commit the new plugin version and deploy to a cluster.  When updating this way the metadata update procedure never runs? 

How do you trigger the metadata update procedure to run?

**Comment by ianmjones** [comment]
The metadata update is triggered by WP-Cron, a health check job runs regularly and notices that the settings version is "old", does the required upgrades, and updates the settings version as it completes each upgrade.

In your scenario of a cluster, presumably you have disabled WP-Cron but set a manual cron to fire on a specific node to ensure WordPress's required cron jobs fire regularly but without conflicts across the cluster?

**Comment by lurchpop** [comment]
> 
> In your scenario of a cluster, presumably you have disabled WP-Cron but set a manual cron to fire on a specific node to ensure WordPress's required cron jobs fire regularly but without conflicts across the cluster?

The cron jobs are not touched. I think the issue is that I updated the plugin outside the context of clicking "upgrade." I updated it on a dev server, committed the code, then deployed it. Does the upgrade cron job only run when the plugin runs the update procedure?

**Comment by ianmjones** [comment]
@lurchpop No, the meta data upgrades are not triggered by the WordPress plugin upgrade routines, that wouldn't work for people using composer, git or other methods for deploying new versions.

The plugin checks its settings version each time its loaded by WordPress, if the settings need updating then each of the required upgrade routines are added to the WP-Cron schedule.

If your `tantan_wordpress_s3` options record already has a `post_meta_version` of 7, then its settings are up to date (with WP Offload Media v2.0).

If for whatever reason you think the upgrade routines need to be run, you can set that value back to an earlier number like 6 (which has been the most up to date version for a good few releases now), and WP Offload Media will recognize that it needs to run metadata upgrade.
