### ISSUE TITLE
majority of images doesn't take s3 path.

### ISSUE THREAD

**Issue by bhaktvanti** [deliciousbrains/wp-amazon-s3-and-cloudfront#471]
I recently upgraded plugin from WP Offload S3 to WP Offload Media Lite. It has not converted all images to s3 paths. Please help. Thanks!

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
