### ISSUE TITLE
Suspicious code message from Vaultpress

### ISSUE THREAD

**Issue by hellopath** [deliciousbrains/wp-amazon-s3-and-cloudfront#472]
Hi there,

I have your last version installed on my wordpress (Version 2.0) and it's been a day that I receive a message about suspicious code coming from your plugin. 

The message came from the [Vaultpress](https://wordpress.org/plugins/vaultpress/), a plugin that I use for backup and security scanning.

I attach the exact message below
![screen shot 2018-10-03 at 09 43 36](https://user-images.githubusercontent.com/550356/46396898-f8989500-c6f0-11e8-9e9d-69088b83ff30.png)
![screen shot 2018-10-03 at 09 46 57](https://user-images.githubusercontent.com/550356/46397018-562ce180-c6f1-11e8-8d58-c19f04c229c7.png)
![screen shot 2018-10-03 at 09 47 08](https://user-images.githubusercontent.com/550356/46397021-588f3b80-c6f1-11e8-98bf-8239423ee37f.png)

Do I have to worry?
Anyway I just wanted to let you know. 

Thanks

**Comment by ianmjones** [comment]
@hellopath Please contact VaultPress support and ask them to address this false positive.
