### ISSUE TITLE
Querying for content out of our domain.

### ISSUE THREAD

**Issue by pinheiroalexandre2** [deliciousbrains/wp-amazon-s3-and-cloudfront#473]
Hello, 

In our site, we have wp-amazon-s3-and-cloudfront plugin that moves the uploaded images to S3.
  
But when we have some external images in post content, like on [this](https://observador.pt/2018/10/04/cativaram-mas-nao-surpreenderam-analise-ao-iphone-xs-e-xs-max-em-10-gifs/) article, the plugin runs [this query](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/e9d4432d43a25d4188e02e42910d9c9589ac3dae/classes/filters/as3cf-s3-to-local.php#L133) for every external image links.. 

This queries are very CPU intensive and are locking our database. 
We have more than 1M images and 14M of metafields in our database :(  

Here are some examples of SQL:

## Expected behavior with our content:

```
SELECT * FROM wp_postmeta
WHERE meta_key = 'amazonS3_info'
AND meta_value LIKE '%uiC29DpVkY1Dt66yUx/giphy.gif%
```

## Unexpected behavior with external links.

```
SELECT * FROM wp_postmeta
WHERE meta_key = 'amazonS3_info'
AND meta_value LIKE '%uiC29DpVkY1Dt66yUx/giphy.gif%'

SELECT * FROM wp_postmeta
WHERE meta_key = 'amazonS3_info'
AND meta_value LIKE '%2018/10/procuradoria-investiga-guru-de-bolsonaro-sob-suspeita-de-fraude.shtml%'

SELECT * FROM wp_postmeta
WHERE meta_key = 'amazonS3_info'
AND meta_value LIKE '%2wXzEaj50H35Cslgq8/giphy.gif%'

SELECT * FROM wp_postmeta
WHERE meta_key = 'amazonS3_info'
AND meta_value LIKE '%10/10/health/south-africa-hiv-liver-transplant-intl/index.html%'
```

Shouldn't the plugin only query for links in our domain? 
Is there any way to restrict plugin to query urls that don't belong to our domains?

### Our  Diagnostic info

site_url(): https://observador.pt
home_url(): https://observador.pt
Database Name: 
Table Prefix: wp_
WordPress: 4.9.8 Multisite (subdomain)
Multisite Site Count: 4
Domain Mapping: Disabled
Web Server: nginx/1.14.0
PHP: 7.0.32-0ubuntu0.16.04.1
MySQL: 5.6.10
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 64M
Memory Usage: 6 MB
Blocked External HTTP Requests: None
WP Locale: pt_PT
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 8 MB
PHP Time Limit: 1000
PHP Error Log: /var/log/php_errors.log
WP Cron: Disabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2g  1 Mar 2016
cURL: 7.47.0
Zlib Compression: Enabled
PHP GD: 2.1.1
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 1.002.676
Offloaded Media Files: 1.002.205
Number of Image Sizes: 4

Names and Dimensions of Image Sizes: 
thumbnail (200x200)
medium (none)
large (2000x2000)

WP_CONTENT_DIR: /opt/observador/wordpress/releases/1a4685de9f3f1c7e79d3773c55fb6298be733963/wp-content
WP_CONTENT_URL: https://observador.pt/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /opt/observador/wordpress/releases/1a4685de9f3f1c7e79d3773c55fb6298be733963/wp-content/plugins
WP_PLUGIN_URL: https://observador.pt/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: s3.observador.pt
Region: eu-west-1
Copy Files to Bucket: On
Rewrite File URLs: On

Local URL:
https://observador.pt/wp‑content/uploads/2018/10/photo.jpg
Offload URL:
https://s3.observador.pt/wp‑content/uploads/2018/10/10153518/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: On
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: Observador
Active Theme Version: 1.0.0
Active Theme Folder: observador

Active Plugins:
Redis Object Cache (v1.3.8) by Till Krüss
WP Offload Media Lite (v2.0) by Delicious Brains

Drop-ins:
db.php - HyperDB
object-cache.php - Redis Object Cache Drop-In

## UPDATE

I Just found that the plugin is analyzing `<a>` tag for external domains and that are not links to "offloadable" content.
Here's an example query of this behavior:

```
SELECT * FROM wp_postmeta
WHERE meta_key = 'amazonS3_info'
AND meta_value LIKE '%information/index.html%'
```

**Comment by ianmjones** [comment]
@pinheiroalexandre2 Please can you give me an example of the `src` attribute in the `img` tag that is getting analysed by WP Offload Media when it shouldn't be?

For example, I see on that example page you gave that there is an `img` tag with the following `src` attribute value: `https://bordalo.observador.pt/400x,q80/https://www.contasconnosco.pt/img/md/assets/images/articles/lisboa-viva-go-viaja-primeiro-paga-depois-5c589a31509d7.jpg`

Is it images like that that are getting analysed, or other formats?

**Comment by pinheiroalexandre2** [comment]
@ianmjones Imagine the following example:

I have a post that has the following urls and images:

- **urls**:
  - https://www.aljazeera.com/news/2019/03/algeria-190312143022460.html (**link to external page**)
  - https://observador.pt/wp-content/themes/magg/anuncie/exemplos/resizer_formatos_mobile.html (**I own this**)

- **images**
  - https://media.giphy.com/media/1n83GppSeTZcXcb5BY/giphy.gif (**link to external image**)
  - https://bordalo.observador.pt/2600x,q85/https://s3.observador.pt/wp-content/uploads/2019/03/14205345/GettyImages-1130400161_1280x720_acf_cropped.jpg (**I own this**)
  - https://s3.observador.pt/wp-content/uploads/2019/03/15092637/image3_770x433_acf_cropped.jpg (**I own this**)

So, the plugin should have a setting where I define which are the domains that should be offloaded. Otherwise, if I have one article with 20 urls that I don't own or that should not be on S3 the plugin will hammer our database more than needed. :)

**Comment by ianmjones** [comment]
WP Offload Media Lite 2.1.1 has been released with support for the WordPress MU Domain Mapping plugin and other bug fixes for filtering content.
