### ISSUE TITLE
get_plugin_sdks_dir_path() sometimes returning path without plugin name

### ISSUE THREAD

**Issue by orjhor** [deliciousbrains/wp-amazon-s3-and-cloudfront#475]
Since 2.0 I've experienced that get_plugin_sdks_dir_path() will return a path that is missing the plugin name.

E.g. when updating a Woocommerce product, and hit "Publish" I will get:

> Warning: require_once(/home/qwertyj27/public_html/wp-content/plugins/vendor/Aws3/aws-autoloader.php): failed to open stream: No such file or directory in /home/qwertyj27/public_html/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/providers/aws-provider.php on line 152
> 
> Fatal error: require_once(): Failed opening required '/home/qwertyj27/public_html/wp-content/plugins/vendor/Aws3/aws-autoloader.php' (include_path='.:/usr/local/php70/pear') in /home/qwertyj27/public_html/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/providers/aws-provider.php on line 152

Notice that "amazon-s3-and-cloudfront-pro" is missing from the path in the error-messages.

I've created a temp workaround for now that inserts the plugin directory if missing:

```
	public function __construct( \AS3CF_Plugin_Base $as3cf ) {
		parent::__construct( $as3cf );

		// Autoloader.				
		$autoloader_path = $as3cf->get_plugin_sdks_dir_path() . '/Aws3/aws-autoloader.php';
		if (strpos($autoloader_path, '/amazon-s3-and-cloudfront-pro/vendor/') !== false) {
			
		} else {
			$autoloader_path = str_replace('/vendor/', '/amazon-s3-and-cloudfront-pro/vendor/', $autoloader_path);
		}
		require_once $autoloader_path;
	}
```

**Comment by ianmjones** [comment]
This is an unsupported usage of WP Offload Media Lite's bundled AWS PHP SDK, and reaching inside a plugin  to use it's functions that aren't specifically exported as part of a public API is never a good idea.

You'd be much better off using the filters that WP Offload Media exposes.

**Comment by orjhor** [comment]
`This is an unsupported usage of WP Offload Media Lite's bundled AWS PHP SDK`
If you mean my workaround then yes. Please note that the snippet was not what was causing the issue, it was just something thrown together to fix a production site.

But it seems you closed the ticket because of my temporary workaround, and not the actual issue description?

**Comment by ianmjones** [comment]
@orjhor Yes, that function only works in the context of the plugin itself, it's not intended for use outside of WP Offload Media, it won't have the correct env to be used by outside code.
