### ISSUE TITLE
Issue without elastic IP

### ISSUE THREAD

**Issue by Lucpica** [deliciousbrains/wp-amazon-s3-and-cloudfront#477]
Hello,

I have configured an EC2 with bitnami AMI for wordpress. I put the EC2 behind ELB.
If I remove elastic ip from EC2 and use the public one from ELB it works fine BUT I got some error with the plugin.
If I put an elastic ip on my EC2 plugin works fine.
I don't understand what is the issue. Do we have to configure something on the plugin ? It's like the plugin tries to connect on internet and do not resolve something...

you can find some issue log here 
https://community.bitnami.com/t/issue-with-plugin-option/61986

do you already had this issue ?

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
