### ISSUE TITLE
Media library image thumbnails are missing when using Csutom 

### ISSUE THREAD

**Issue by mlangone** [deliciousbrains/wp-amazon-s3-and-cloudfront#479]
We have setup the custom domain name process through AWS cloudfront. When ever the custom domain option is checked the media library images do not display, with it unchecked they do display.
Custom domain cname off
![screen shot 2018-11-09 at 12 25 43 pm](https://user-images.githubusercontent.com/4027703/48283758-b0b90c00-e41a-11e8-913e-5dcea3924645.png)

Cname on
![screen shot 2018-11-09 at 12 27 19 pm](https://user-images.githubusercontent.com/4027703/48283842-efe75d00-e41a-11e8-8c26-ce08033bd6d3.png)

**Comment by mlangone** [comment]
It appears that any thumbnails are throwing a 403 error , the original main image displays but the different image sizes that wp creates are not showing.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
