### ISSUE TITLE
Full size images aren't uploading

### ISSUE THREAD

**Issue by brianpiccione** [deliciousbrains/wp-amazon-s3-and-cloudfront#480]
Hello, first off, your plugin is great so thank you!! Second, I'm not sure if this is a bug or related to my settings or something else but only the resized images are being offloaded to S3 for our site. It seems that the full size image is not making it up to S3 for some reason. Here's some of the diagnostic information (I'd prefer not to share absolutely everything publicly so if you need more I can send it separately).

site_url(): https://considerable.com
home_url(): https://considerable.com
WordPress: 4.9.8
Web Server: Apache
PHP: 5.5.9-1ubuntu4.25
MySQL: 5.6.39
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 22 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 2 MB
PHP Time Limit: 30
PHP Error Log: 

Media Files: 1,608
Media Files on S3: 1,570
Number of Image Sizes: 19

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined

Copy Files to S3: On
Rewrite File URLs: On

Local URL:
https://considerable.com/wp‑content/uploads/2018/11/photo.jpg
S3 URL:
https://cdn1.considerable.com/wp‑content/uploads/2018/11/19134943/photo.jpg

Domain: cloudfront
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: On
Remove Files From Server: Off
Object Versioning: On

Active Theme Name: Considerable
Active Theme Version: 2.10.4
Active Theme Folder: Considerable

Active Plugins:
Amazon Web Services (v1.0.5) by Delicious Brains
Contact Form 7 (v5.0.3) by Takayuki Miyoshi
Gutenberg (v4.2.0) by Gutenberg Team
Redis Object Cache (v1.3.8) by Till Krüss
Regenerate Thumbnails (v3.0.2) by Alex Mills (Viper007Bond)
WP All Import - Yoast WordPress SEO Add-On (v1.1.7) by Soflyy
WP All Import Pro (v4.5.0) by Soflyy
WP Offload S3 Lite (v1.4.3) by Delicious Brains
WP Rocket (v3.1) by WP Media
WP SES (v0.8.1) by Delicious Brains Inc
WPBakery Page Builder (v5.5.2) by Michael M - WPBakery.com
Widget Context (v1.1.0) by Kaspars Dambis
Yoast SEO Premium (v7.6.1) by Team Yoast

Drop-ins:
advanced-cache.php - advanced-cache.php
object-cache.php - Redis Object Cache Drop-In

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
