### ISSUE TITLE
WP Offload Media Lite - Upload error 

### ISSUE THREAD

**Issue by williamsalt** [deliciousbrains/wp-amazon-s3-and-cloudfront#481]
Hi,

When I try to upload a gif through the media upload I keep getting HTTP error. When I try to upload Images through Media -> Add New ->  click upload, it will automatically throw an error msg. It will be great if someone know how to fix the error. Thanks

<img width="1255" alt="screenshot 2018-12-14 at 16 19 30" src="https://user-images.githubusercontent.com/45969925/50156765-83883500-02c7-11e9-9229-ebd774bd95d2.png">

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
