### ISSUE TITLE
Compatibility Issue WP 5.0

### ISSUE THREAD

**Issue by Danilka** [deliciousbrains/wp-amazon-s3-and-cloudfront#482]
With the AWS credentials saved in the database and bucket being visible through the plugin, it would still spit out an "Access Denied to Bucket" error.

WP 5.0
Plugin 2.0.1

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
