### ISSUE TITLE
RSS Feed Enclosure Links Broken

### ISSUE THREAD

**Issue by 2PersonGames** [deliciousbrains/wp-amazon-s3-and-cloudfront#484]
We're currently using this plugin, and unfortunately it's broken the enclosure links for our RSS feed - all other links work fine however. From playing around a little it looked like the fix might be to add `rss_enclosure` to the filters already being used in `./classes/filters/as3cf-local-to-s3.php`.

To recreate the issue try running curl on our RSS feed - [https://www.escapistmagazine.com/v2/tag/escapist-podcast-volume-two/feed/](https://www.escapistmagazine.com/v2/tag/escapist-podcast-volume-two/feed/) - and check our the Url within the enclosure tag, it should be from the site and not from Cloudfront, as every content related Url should be.

**Comment by ianmjones** [comment]
@2PersonGames Are you using a podcast or feed generator plugin?

**Comment by 2PersonGames** [comment]
@ianmjones From what I can see we don't have any plugins installed relating to a podcast or feed generator, we're just using what Wordpress supplies by default - I can provide a complete list of the plugins we have installed if that helps?

**Comment by 2PersonGames** [comment]
@ianmjones Is there any more information you need from me?

I've forked the repository and setup a pull request with what appears to fix it based on our testing.

**Comment by 2PersonGames** [comment]
@ianmjones Assuming you don't need any more information from me, are we okay to review that pull request for the fix? I'd really like to get this working for our sites.

**Comment by ianmjones** [comment]
Hey @2PersonGames,

We haven't been able to reproduce this, please can you give cast-iron steps on how you create the posts with mp3 enclosures?

We can't directly use PRs submitted to this repo as it's a mirror from a private repo, but we can certainly take the ideas from a PR and re-apply to our main repo if it solves the problem.

**Comment by ianmjones** [comment]
Oh, and Diagnostic Info from WP Offload Media's Support tab is always helpful.

**Comment by 2PersonGames** [comment]
Thanks for the responses, however we've decided to move away from using this plug-in for the time being.
