### ISSUE TITLE
 The difference between the request time and the current time is too large.

### ISSUE THREAD

**Issue by jayesh2509** [deliciousbrains/wp-amazon-s3-and-cloudfront#486]

**Comment by jayesh2509** [comment]
Issues is to bucket and my DIAGNOSTIC INFO error will this

Table Prefix: wp_
WordPress: 4.7.4
Web Server: Apache/2.4.7 (Ubuntu)
PHP: 5.5.9-1ubuntu4.22
MySQL: 5.5.57
ext/mysqli: yes
PHP Memory Limit: 268435456
WP Memory Limit: 64M
Memory Usage: 17 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize uploads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 1 GB
PHP Time Limit: 30
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.1f 6 Jan 2014
cURL: Enabled
Zlib Compression: Enabled
PHP GD: 2.1.1-dev
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 267
Media Files on S3: 228
Number of Image Sizes: 11

Names and Dimensions of Image Sizes: 
thumbnail (none)
medium (none)
large (none)
flipbokkimg (100x100)
shop_thumbnail (180x180)
shop_catalog (300x300)
shop_single (600x600)
post-thumbnail (none)
beetube-fslider (400x300)
beetube-movies (185x274)

WP_CONTENT_DIR: /var/www/html/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins

AWS_USE_EC2_IAM_ROLE: Not defined
AS3CF_BUCKET: Not defined
AS3CF_ASSETS_BUCKET: Not defined
AS3CF_REGION: Not defined

Bucket: yflive
Region: us-east-2
Copy Files to S3: On
Rewrite File URLs: On

S3 URL:
https://s3‑us‑east‑2.amazonaws.com/yflive/wp‑content/uploads/2019/02/13070706/photo.jpg

Domain: path
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Force HTTPS: Off
Remove Files From Server: On
Object Versioning: On

Active Theme Name: Betube Child
Active Theme Folder: betube-child
Parent Theme Folder: betube

Active Plugins:
Advanced Custom Fields PRO (v5.5.10) by Elliot Condon
Akismet Anti-Spam (v3.3) by Automattic
All In One SEO Pack (v2.3.13.2) by Michael Torbert
Amazon Web Services (v1.0.2) by Delicious Brains
Contact Form 7 (v4.7) by Takayuki Miyoshi
Easy HTTPS (SSL) Redirection (v1.6) by Tips and Tricks HQ
Font Awesome 4 Menus (v4.7.0) by New Nine Media
LayerSlider WP (v6.3.0) by Kreatura Media
PDF Image Generator (v1.5.6) by Mizuho Ogino
Real 3D Flipbook (v2.35) by creativeinteractivemedia
Redux Framework (v3.6.4) by Team Redux
Video Thumbnails (v2.12.3) by Sutherland Boswell
WP Offload S3 Lite (v1.1.6) by Delicious Brains
WP Statistics (v12.0.5) by Greg Ross & Mostafa Soufi
WP-Mail-SMTP (v0.10.1) by Callum Macdonald
WooCommerce (v3.0.8) by Automattic
WooCommerce PayPal Pro (v2.1) by wp.insider
beTube Ads (v1.0.1) by JoinWebs
beTube Helper (v1.2) by JoinWebs

**Comment by ianmjones** [comment]
Your server's time is too inaccurate, AWS doesn't like that.

**Comment by bstarr322** [comment]
@ianmjones We have the same issue.
We are running the site on AWS EC2 Instance which is based on US-east-1.
And S3 Bucket is on US-west-1. Do you think this would be the cause of this issue and we need to match the region to the same one?
