### ISSUE TITLE
Could not upload canvas image to cdn 

### ISSUE THREAD

**Issue by yonoyono** [deliciousbrains/wp-amazon-s3-and-cloudfront#488]
Need  information where, wp_insert_post function, sending image to CDN. because i want to remove one of my feature in web, when image upload via this task, itu store to my local server. 

Thanks U

**Comment by ianmjones** [comment]
Not sure I'm following what you're asking for, but for new Media Library items it's generally the `wp_update_attachment_metadata` filter that tells WP Offload Media Lite that there's possibly new files to be offloaded.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/9a12cc0709b06782f73b774fbe91417a616bf2d2/classes/amazon-s3-and-cloudfront.php#L191

Usually something like...

```
wp_update_attachment_metadata( $attachment->ID, wp_generate_attachment_metadata( $attachment->ID, $file ) );
```

Does that help?
