### ISSUE TITLE
WP Offload Media and GuzzleHTTP is breaking the WP Mail SMTP plugin

### ISSUE THREAD

**Issue by plenge** [deliciousbrains/wp-amazon-s3-and-cloudfront#490]
Hi,

I am using WP Offload Media to serve my images through Google Cloud Storage.
And I am using WP Mail SMTP to serve emails through GMail.
- https://github.com/awesomemotive/WP-Mail-SMTP

But WP Offload Media is breaking the WP Mail SMTP plugin when both plugins are active.
WP Offload works fine when WP Mail SMTP is active.

The problem seems to persist in GuzzleHTTP vendor files.

```
2019-03-26T16:20:04Z PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\Psr7\stream_for() in /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/guzzlehttp/psr7/src/Request.php:53
  Stack trace:
  #0 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/google/apiclient/src/Google/Service/Resource.php(201): GuzzleHttp\Psr7\Request->__construct('POST', Object(GuzzleHttp\Psr7\Uri), Array, '{"raw":"RGF0ZTo...')
  #1 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/google/apiclient-services/src/Google/Service/Gmail/Resource/UsersMessages.php(197): Google_Service_Resource->call('send', Array, 'Google_Service_...')
  #2 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/src/Providers/Gmail/Mailer.php(94): Google_Service_Gmail_Resource_UsersMessages->send('me', Object(Google_Service_Gmail_Message))
  #3 /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/src/MailCatcher.php(105): WPMailSMTP\Providers\Gmail\Mailer->send()
  #4 /srv/app/oakdigital/htdocs/www/wp/wp-includ in /srv/app/oakdigital/htdocs/www/wp-content/plugins/wp-mail-smtp/vendor/guzzlehttp/psr7/src/Request.php on line 53
```

I am unsure wether or not that is has something to do with Guzzle versioning or what could cause the issue.

I know you are not bound to fix it as it is a compatibility issue with another plugin, but I hope you could help me anyway.

Do you guys have any ideas as to how I might fix the issue? :) 

(I have posted this on the other plugin github aswell, as I am unsure where the compatibility issue could actually be fixed).

**Comment by ianmjones** [comment]
Hi @plenge,

WP Offload Media namespaces its versions of GuzzleHttp that are bundled with the plugin with a Delicious Brains / WP Offload Media specific namespace and only references those namespaced versions itself.

It looks like WP Mail SMTP does not give its bundled version of GuzzleHttp a uniquely scoped namespace and as such probably accidentally uses our version of the classes as they are presumably loaded first by WordPress.

The chances are the two plugins are using different versions of the `GuzzleHttp/Psr7/Request` class and WP Mail SMTP is expecting a function to exist that doesn't in our version of the class.

Hope that helps.
