### ISSUE TITLE
Changing expires and cache control header values

### ISSUE THREAD

**Issue by Ardakilic** [deliciousbrains/wp-amazon-s3-and-cloudfront#493]
Hello,

I want to change cache control and expires headers values from 365 days to something bigger, like 10 years, because when it touches my cdn, I never want to re-fetch the image from storage even after a year.

So, how's this possible? I'm using an S3 bucket and Cloudfront CDN.

Would it suffice to change these values manually? Or is there a setting to set these values?

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/ff028e5801489ed8fca5a12b4aae6a8d5636325d/classes/amazon-s3-and-cloudfront.php#L1146-L1153

Thanks in advance,

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

P.S. https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/cb7c645d84969d58b43dd43b918c6c5c75218099/amazon-s3-and-cloudfront-tweaks.php#L368

**Comment by Ardakilic** [comment]
@ianmjones Can this not be considered as feature request? Actually, I was asking how to achieve this, and if there was no way to do this for an end-user I'd consider this issue as feature request.

Thanks for the method link, I'll dig into it.

**Comment by ianmjones** [comment]
@Ardakilic It's not really something 99.999% of users are going to want to change, but if we hear enough requests for being able to change the default metadata for objects in the UI rather than via filters, we'll certainly consider it.
