### ISSUE TITLE
Error fetching buckets — Error executing "ListBuckets"

### ISSUE THREAD

**Issue by amarathota** [deliciousbrains/wp-amazon-s3-and-cloudfront#494]
Below is the DIAGNOSTIC info. Could someone please help?

site_url(): https://qa.coete.co
home_url(): https://qa.coete.co
Database Name: coete_qa_db
Table Prefix: wp_
WordPress: 5.0
Web Server: Apache
PHP: 7.2.13
MySQL: 5.6.40
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 14 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 2 MB
PHP Time Limit: 60
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2k  26 Jan 2017
cURL: 7.61.1
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 15
Offloaded Media Files: 0
Number of Image Sizes: 16

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
portfolio-square (570x570)
portfolio-portrait (600x800)
portfolio-landscape (800x600)
menu-featured-post (345x198)
qode-carousel_slider (400x260)
portfolio_slider (500x380)
portfolio_masonry_regular (500x500)
portfolio_masonry_wide (1000x500)
portfolio_masonry_tall (500x1000)
portfolio_masonry_large (1000x1000)
portfolio_masonry_with_space (700x0)
latest_post_boxes (539x303)

WP_CONTENT_DIR: /var/app/current/wp-content
WP_CONTENT_URL: https://qa.coete.co/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/app/current/wp-content/plugins
WP_PLUGIN_URL: https://qa.coete.co/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Defined
AS3CF_SETTINGS Keys: access-key-id, provider, secret-access-key

Local URL:
https://qa.coete.co/wp‑content/uploads/2019/04/photo.jpg
Offload URL:
https://s3.amazonaws.com/coetewp/wp‑content/uploads/2019/04/25144239/photo.jpg

Provider: Amazon Web Services
Use Server Role: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: coetewp
Region: 

Copy Files to Bucket: On
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Rewrite Media URLs: On
Enable Custom Domain (CDN): Off
Custom Domain (CDN): 
Force HTTPS: Off

Remove Files From Server: Off

Active Theme Name: Bridge Child
Active Theme Version: 1.0.0
Active Theme Folder: bridge-child
Parent Theme Name: Bridge
Parent Theme Version: 17.2
Parent Theme Folder: bridge

Active Plugins:
Blog Designer - Post and Widget (v1.6.2) by WP OnlineSupport
Classic Editor (v1.4) by WordPress Contributors
Conditional Menus (v1.1.1) by Themify
Contact Form 7 (v5.1.1) by Takayuki Miyoshi
Envato Market (v2.0.0) by Envato
Google Captcha (reCAPTCHA) by BestWebSoft (v1.43) by BestWebSoft
MailChimp for WordPress (v4.3.2) by ibericode
MemberPress Plus (v1.4.4) by Caseproof, LLC
Slider Revolution (v5.4.8) by ThemePunch
User Menus (v1.1.3) by Jungle Plugins
WP Mail SMTP (v1.4.1) by WPForms
WP Offload Media Lite (v2.1) by Delicious Brains
WPBakery Page Builder (v5.6) by Michael M - WPBakery.com
WPide (v2.4.0) by Simon @ WPsites
Zoho-Subscriptions (v2.0) by Zoho Subscriptions

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
