### ISSUE TITLE
S3-like compatibility

### ISSUE THREAD

**Issue by fnzv** [deliciousbrains/wp-amazon-s3-and-cloudfront#495]
Dear Developer,
I wanted to know if is there any possibility to have a S3-like compatibility with your plugin so any S3 compatible storage can connect to the plugin.

Example:
- Adding S3 server custom endpoint and provider on the settings

**Comment by fnzv** [comment]
This is a working example with compatible S3 endpoints:
- https://wordpress.org/plugins/ilab-media-tools/

**Comment by ianmjones** [comment]
It's your lucky day!

https://deliciousbrains.com/s3-compatible-storage-provider-minio/
