### ISSUE TITLE
New: Multisite domain mapping via WordPress MU Domain Mapping plugin is now supported

### ISSUE THREAD

**Issue by alexander-schneider** [deliciousbrains/wp-amazon-s3-and-cloudfront#498]
Where can I found the settings for each blog?

**Comment by ianmjones** [comment]
@alexander-schneider Sorry, I don't understand the question!

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
