### ISSUE TITLE
serving 2x for retina

### ISSUE THREAD

**Issue by tntmax-dev** [deliciousbrains/wp-amazon-s3-and-cloudfront#499]
We are trying to use this plugin along with WP Retina so we can show 2x images. 
Unfortunately it does not seem to be working. 

How are other people using this plugin while also showing 2x versions of images?
We realized we had object versioning turned on. Will turning it off fix this issue? And what can we do about files already there?

**Comment by ianmjones** [comment]
People tend to not use 2x files these days, but instead register different image sizes and use media breakpoints in CSS and the img tag's srcset to handle images responsively.

However, you could use WP Offload Media's `as3cf_attachment_file_paths` filter to add extra files that are not registered sizes to the list of files to be offloaded.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/24226e968349b5bb8e3033adc3aff2e85ea8845d/amazon-s3-and-cloudfront-tweaks.php#L532

**Comment by tntmax-dev** [comment]
Not use 2X?
So what are people doing about retina devices?

Based on my reading everyone still relies on Retina images.

https://premium.wpmudev.org/blog/make-images-retina-ready/
