### ISSUE TITLE
Multi Site Setup and Gutenburg Image Block

### ISSUE THREAD

**Issue by joeporterme** [deliciousbrains/wp-amazon-s3-and-cloudfront#500]
So, i have a Multi Site setup with S3 Offload Object Versioning turned on. (offload activated on all the sites, 5 sites total)  

I have the Main Blog (Blog ID: 1) copy posts to other sites based on the user input when creating the post on the blog.   Well if the person uses the Image Block, this image content is what is moved to the other sites in the post content table:

```
<!-- wp:image {"id":65984} -->
<figure class="wp-block-image"><img src="https://main.blog.com/wp-content/uploads/2019/06/image.jpg" alt="" class="wp-image-65984" /></figure>
<!-- /wp:image -->

```
On the Main Blog (ID 1) the image shows using the Amazon CDN:
`<figure class="wp-block-image"><img src="https://cdn.name.com/wp-content/uploads/2019/06/24140403/image" alt="" class="wp-image-65984"></figure>`

On child site (ID 2) the image does not show live and this is what is shown: 
`<figure class="wp-block-image"><img src="https://main.blog.com/wp-content/uploads/2019/06/image.jpg" alt="" class="wp-image-65984"></figure>`

do you have a suggestion on how to fix this?  The images and posts are always started and published from blog id: 1. 

Is there a hook we can include to make sure Offload "switch_to_blog(1)" while its processing images for displaying?  is there a another option?  Thanks for your help.

**Comment by ianmjones** [comment]
Short answer: Nope.

Slightly longer answer: Each subsite in a multisite network has its own Media Library, and WP Offload Media will only recognize Media Library items from the same site that a post is being rendered for.

So, on site2.blog.com it will only look for Media Library URLs that include site2.blog.com in their domain, those main.blog.com are external to the site and therefore will not be handled by WP Offload Media.

I believe there are plugins that allow you to share a Media Library across subsites, you might be able to get that to work and fool WP Offload Media into filtering those URLs, but frankly, you're working against the way WordPress handles media and are likely to find other issues.
