### ISSUE TITLE
While Woocommerce Marketplace installed - Out of memory error

### ISSUE THREAD

**Issue by fansollo22** [deliciousbrains/wp-amazon-s3-and-cloudfront#501]
While woocommerce marketplace is installed i get random out of memory exception on different files while uploading images. I tryied setting the plugin to keep the files on the local media aswell but to no success.

The errors look a bit like this :

Fatal error: Out of memory (allocated 88080384) (tried to allocate 1052672 bytes) in /home/www/swphdev.com/sandbox/casa-de-idei/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/GuzzleHttp/Psr7/Stream.php on line 178

Fatal error: Out of memory (allocated 41943040) (tried to allocate 20480 bytes) in /home/www/swphdev.com/sandbox/casa-de-idei/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/data/s3/2006-03-01/api-2.json.php on line 4

I've tryied to increase the memory to about 1GB and i still get these errors. Sometimes there are two errors with one saying out of memory in Unknown.

**Comment by ianmjones** [comment]
Sounds like WooCommerce's dynamic thumbnail generation is having problems with stream wrappers, please raise this with WooCommerce.
