### ISSUE TITLE
cdn rewrite path not using filesystem path

### ISSUE THREAD

**Issue by markyma** [deliciousbrains/wp-amazon-s3-and-cloudfront#502]
after installing the plugin, images are re-written to the CDN, however if the original image was at wp‑content/uploads/2018/07/photo.jpg the CDN image is at wp‑content/uploads/photo.jpg
(the entire wp-content folder has been uploaded to S3 using "aws s3 sync" and they have the same path as the file system.

**Comment by ianmjones** [comment]
The path used in the bucket is determined by the settings you use in WP Offload Media, it does not mirror the filesystem path.

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
