### ISSUE TITLE
Manually moved over entire existing media library, need to update paths

### ISSUE THREAD

**Issue by sethrubenstein** [deliciousbrains/wp-amazon-s3-and-cloudfront#51]
So I know alot of people have asked if this plugin can migrate their files over to S3 I'm not asking that. I've already done that by just manually downloading my entire wp-content/uploads directory then moving that to my S3 bucket. I've also gone in and changed all my meta values for posts that have wp-content/uploads to take into account my cloudfront address.

HOWEVER

I'd like all my existing images that I've now migrated over in the Media Library to point to S3 like new images do. 

Is there any way to go about this?

**Comment by cluber22** [comment]
@tmoitie your SQL worked a treat for me!

Just had to modify it slightly to include:

`s:6:"region";s:9:"eu-west-2"`
