### ISSUE TITLE
missing hook in Amazon_S3_And_CloudFront::get_setting to filter $region

### ISSUE THREAD

**Issue by lucymtc** [deliciousbrains/wp-amazon-s3-and-cloudfront#511]
There seems to be a filter hook missing here
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/6371429abc63935fe18b0c60f0abb85f7cb06056/classes/amazon-s3-and-cloudfront.php#L433 
to filter the region setting, the same way any other setting can be filtered further down 
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/6371429abc63935fe18b0c60f0abb85f7cb06056/classes/amazon-s3-and-cloudfront.php#L521

I believe the expected return should be 
`return apply_filters( 'as3cf_setting_region', $region );`
I'm happy to open a PR if you consider this is a bug. 
Thanks!

**Comment by ianmjones** [comment]
It's kinda intentional, the region is usually derived from the bucket.

Could you expand on the use case for setting the region manually?
