### ISSUE TITLE
SVG files are not being uploaded to AWS S3

### ISSUE THREAD

**Issue by Mikeg05** [deliciousbrains/wp-amazon-s3-and-cloudfront#513]
Hi
after the update the SVG files are not uploaded
the other extensions are uploaded (png, jpg, json, pptx.. etc)

**Comment by ianmjones** [comment]
WordPress does not support the SVG mime type to be uploaded to the Media Library, so WP Offload Media does not offload them either.

You'll need to enable uploading of SVGs to the Media Library, or tell WP Offload Media to offload them regardless.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/96d9fc03ffcfdc1d2e77b0a1a53891e6e1a76e30/amazon-s3-and-cloudfront-tweaks.php#L387

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

**Comment by Mikeg05** [comment]
Hi @ianmjones 

I had already enabled it to allow me to upload svg in WordPress.
and yesterday I configured the wp-amazon-s3-and-cloudfront-tweaks plugin. But it still doesn't work thats why I thinks is a bug

I configured the plugin this way
at amazon-s3-and-cloudfront-tweaks.php
first uncomment line 85
and second  on line 387 I added
```function allowed_mime_types ($ types) {
     $ types ['svg'] = 'image / svg + xml';
     $ types ['svgz'] = 'image / svg + xml';
     $ types ['doc'] = 'application / msword';
     $ types ['json'] = 'application / json';
return $ types;
}```

**Comment by ianmjones** [comment]
Does your code really have that all that whitespace, or is that just a problem resulting from copy and paste?

If your code really is as shown above, try this instead...

```
function allowed_mime_types( $types ) {
    $types['svg'] = 'image/svg+xml';
    $types['svgz'] = 'image/svg+xml';
    $types['doc'] = 'application/msword';
    $types['json'] = 'application/json';

    return $types;
}
```

Also, please confirm you uncommented the relevant `add_filter( 'as3cf_allowed_mime_types', ...` line in the `__construct` function, and activated the Tweaks plugin.

**Comment by Mikeg05** [comment]
![image](https://user-images.githubusercontent.com/39812823/69080417-cf1ff300-09f0-11ea-8685-fffdf7014c0a.png)
![image](https://user-images.githubusercontent.com/39812823/69080427-d47d3d80-09f0-11ea-9253-11a3d565e4e0.png)
![image](https://user-images.githubusercontent.com/39812823/69080459-e363f000-09f0-11ea-8530-2e18d0403f23.png)

Everything seems to be fine, but does not work.

**Comment by ianmjones** [comment]
Thanks for confirming that.

I believe this is related to #516, as SVGs don't get thumbnails it's tripping up on that same code.

There's a fix on the way, currently in test, should be out this week.

**Comment by ianmjones** [comment]
WP Offload Media Lite 2.3.1 has been released with the fix.

**Comment by Mikeg05** [comment]
Hi @ianmjones 

I'm still with the problem. 
![image](https://user-images.githubusercontent.com/39812823/69370185-499b7d80-0c52-11ea-9ae9-3df4b6369762.png)

**Comment by epoplive** [comment]
I also am having this issue

**Comment by simplenotezy** [comment]
@ianmjones Any updates on this? I tried adding this filter:

    function allow_svg_mime($mimes) {
        $mimes['svg'] = 'image/svg+xml';
        return $mimes;
    }

    add_filter('upload_mimes', __NAMESPACE__ . '\\allow_svg_mime');
    add_filter('as3cf_allowed_mime_types', __NAMESPACE__ . '\\allow_svg_mime');

But it doesn't seem to work.

Also prior to adding the filter, the file is actually uploaded, but if you go to the bucket link, it will complain:

![image](https://user-images.githubusercontent.com/3786627/143769481-4b97a3d1-e1c9-4666-a02b-4b5db3499c6d.png)
