### ISSUE TITLE
In 2.3: Media Library hosed with "Cannot use object of type DeliciousBrains\\WP_Offload_Media\\Items\\Media_Library_Item as array" in logs

### ISSUE THREAD

**Issue by davidknoll** [deliciousbrains/wp-amazon-s3-and-cloudfront#514]
We have our plugins updated automatically, and yesterday one of our users had trouble uploading files. I found that since updating to version 2.3 of this plugin, _the Media Library was completely broken_, can't upload or even list its contents. An AJAX call that happens when the Media Library page is refreshed was returning 500, and this was associated with the following frequent message in the Apache error log:
```
[Thu Nov 14 11:14:18.766712 2019] [:error] [pid 8748] [client CENSORED] PHP Fatal error:  Uncaught Error: Cannot use object of type DeliciousBrains\\WP_Offload_Media\\Items\\Media_Library_Item as array in /var/www/html/wp-includes/media.php:3433
Stack trace:
#0 [internal function]: wp_prepare_attachment_for_js(Object(WP_Post))
#1 /var/www/html/wp-admin/includes/ajax-actions.php(2965): array_map('wp_prepare_atta...', Array)
#2 /var/www/html/wp-includes/class-wp-hook.php(288): wp_ajax_query_attachments('')
#3 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /var/www/html/wp-admin/admin-ajax.php(175): do_action('wp_ajax_query-a...')
#6 {main}
  thrown in /var/www/html/wp-includes/media.php on line 3433, referer: https://CENSORED/wp-admin/upload.php
```
Server runs PHP 7.0, MySQL 5.7. Observed with WP 5.3 _and_ whatever the one right before that was. We have the free version of Smush installed, but temporarily removing Smush did not fix the issue. We also have the Amazon Web Services plugin but I didn't fiddle with that.

I note that something in this plugin that used to be an associative array is now an object. I was able to hack around this issue by adding
```
if ( ! is_array( $meta ) ) { $meta = array(); }
```
after `$meta` is fetched in `wp_prepare_attachment_for_js` in `wp-includes/media.php`.

**Comment by ianmjones** [comment]
Please remove Smush completely, and then check your `_wp_attachment_metadata` records for recent uploads.

We're not sure how, but we've just found out that Smush is incompatible with filter changes in WP Offload Media (Lite) 2.3 and may be accidentally saving offload data into `_wp_attachment_metadata` instead of the proper data.

This is unconfirmed, it might not be Smush, but so far all problems like yours have had Smush active at some point.

If just a few of your `_wp_attachment_metatdata` records are incorrect then you should be able to delete the associated Media Library item and re-upload.

If there's a lot of problems then you may need to restore the database from a backup taken before the WP Offload Media upgrade.

**Comment by ianmjones** [comment]
WP Offload Media Lite 2.3.1 has been released with code to help protect against this kind of thing happening again.

Smush have also released a new version of there plugin that hopefully fixes compatibility with WP Offload Media.

**Comment by davidknoll** [comment]
@ianmjones Both WP Offload Media Lite and Smush have been updated since this issue, and it is still apparent with no change of symptoms.

How do I identify corrupt Media Library items as your comment above suggests?

**Comment by ianmjones** [comment]
Smush was putting a variation of WP Offload Media's data that you see in its old "amazonS3_info" records into `_wp_attachment_metadata`, or a serialized version of the new `Media_Library_Item` class WP Offload Media now has.

So, searching for "bucket" and/or "region" might work as relatively distinct, or maybe your bucket name. You'll need to check that you don't accidentally pick up good data that just happens to have related words in the file name etc.
