### ISSUE TITLE
Uploading fails if thumbnails are turned off

### ISSUE THREAD

**Issue by tdennis** [deliciousbrains/wp-amazon-s3-and-cloudfront#516]
When using the plugin with a site that has thumbnail creation turned off via: `intermediate_image_sizes_advanced` 
This causes the upload never to occur if as this check always fails
`
if ( wp_attachment_is_image( $post_id ) && empty( $data['sizes'] ) ) {
			return $data;
		}
`
This is due to the sizes always being empty because there are no sizes. I removed the check for my code for now and it works. Not sure what change can be made to check this

**Comment by ianmjones** [comment]
Thanks for the bug report @tdennis.

**Comment by ianmjones** [comment]
WP Offload Media Lite 2.3.1 has been released with a fix.

**Comment by tdennis** [comment]
I'll deploy it with our thursday release, if any issues, I'll reopen.
