### ISSUE TITLE
Query takes a long time

### ISSUE THREAD

**Issue by Nunardas** [deliciousbrains/wp-amazon-s3-and-cloudfront#517]
Hi,
After updating to version 2.3 (and completing the migration process) I discovered that uploading images takes a lot more time, it now takes more than 20 seconds to upload a single image as before it took less than half of that. Keep in mind that this database has more than a million records.
After little bit of digging I found out that this type of query... : 
```
SELECT DISTINCT items.*
FROM wp_as3cf_items AS items
WHERE items.source_type = 'media-library'
AND items.source_id NOT IN (3571551) AND (items.source_path IN ("2019/12/13987091_1200x300_acf_cropped.jpg") OR items.original_source_path IN ("2019/12/13987091_1200x300_acf_cropped.jpg")) ORDER BY items.source_id LIMIT 1
```
... takes almost 15 seconds. 
Also I found out that removing or even changing the limit returns much better results.
I guess it might be related to indexes.

here is my diagnostic info:
```
site_url(): https://observador.pt
home_url(): https://observador.pt
Database Name: 
Table Prefix: wp_
WordPress: 5.2.4 Multisite (subdomain)
Multisite Site Count: 4
Domain Mapping: Disabled
Web Server: nginx/1.14.0
PHP: 7.1.33-1+ubuntu16.04.1+deb.sury.org+1
MySQL: 5.6.10
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 64M
Memory Usage: 10 MB
Blocked External HTTP Requests: None
WP Locale: pt_PT
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: No
SCRIPT_DEBUG: No
WP Max Upload Size: 8 MB
PHP Time Limit: 30
PHP Error Log: /var/log/php_errors.log
WP Cron: Disabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
cURL: 7.47.0
Zlib Compression: Enabled
PHP GD: 2.2.5
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 1.397.558 (paths 1.354.034)
Offloaded Media Files: 1.397.031 (paths 1.353.724)
Not Offloaded Media Files: 527 (paths 310)
Note: Approximate values, paths *try* and discard duplicates.

Number of Image Sizes: 4

Names and Dimensions of Image Sizes: 
thumbnail (200x200)
medium (none)
large (2000x2000)

WP_CONTENT_DIR: /opt/observador/wordpress/releases/9b84a21d66d7da3edec388f49234c1c41daed9ad/wp-content
WP_CONTENT_URL: https://observador.pt/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /opt/observador/wordpress/releases/9b84a21d66d7da3edec388f49234c1c41daed9ad/wp-content/plugins
WP_PLUGIN_URL: https://observador.pt/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://observador.pt/wp‑content/uploads/2019/12/photo.jpg
Offload URL:
https://s3.observador.pt/wp‑content/uploads/2019/12/04163901/photo.jpg

Provider: Amazon Web Services
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: AWS_ACCESS_KEY_ID
Secret Access Key Define: AWS_SECRET_ACCESS_KEY

Bucket: s3.observador.pt
Region: eu-west-1

Copy Files to Bucket: On
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Rewrite Media URLs: On
Enable Custom Domain (CDN): On
Custom Domain (CDN): s3.observador.pt
Force HTTPS: On

Remove Files From Server: Off

Active Theme Name: Observador Theme
Active Theme Version: 1.0.0
Active Theme Folder: observador-child
Parent Theme Name: Observador Main Theme
Parent Theme Version: 1.0
Parent Theme Folder: main

Active Plugins:
WP Offload Media Lite (v2.3.1) by Delicious Brains
```

Thank you in advance.

**Comment by leoxavier** [comment]
Literacy explaining this behavior:
https://stackoverflow.com/questions/31420780/limit-1-is-very-slow-for-specific-records-using-different-keys/31420906

After using EXPLAIN on the query mentioned on the issue, we see that MySQL does a suboptimal choice of indexes. We fixed this by adding the following line to the query in case it's a "$first_only" scenario:
`USE INDEX (uidx_source_path,uidx_original_source_path) `

Any idea how this can be fixed din a more permanent way?

**Comment by wywarren** [comment]
We are in a similar situation as we are using rest API to update our WooCommerce products and images from a remote system. Once we do use the batch products API, it has to process the provided images onto S3 and in building the response it calls the above query. We're profiling our MySQL DB using AWS RDS Performance Insights and is it one of the heavier queries. Our timeout is set at 60 seconds right now and every so often we get timed out API calls so we end up having to throttle our system to compensate for this.

**Comment by ianmjones** [comment]
Thanks for the bug report.

We've implemented various performance improvements in WP Offload Media (Lite) 2.4, hopefully you'll see a big improvement.
