### ISSUE TITLE
Bucket writability check needs to apply the as3cf_upload_acl filter

### ISSUE THREAD

**Issue by alexk-wb** [deliciousbrains/wp-amazon-s3-and-cloudfront#518]
Our bucket policy does not allow to upload publicly readable files. Therefore, we use as3cf_upload_acl filter to set ACL to 'private', which works great. However, the bucket writability tests fails, because it does not apply the same filer.

File: amazon-s3-and-cloudfront/classes/providers/aws-provider.php
Function: can_write

**Comment by ianmjones** [comment]
WP Offload Media (Lite) 2.4 now has support for **Block All Public Access to Bucket**. 🎉 

https://deliciousbrains.com/wp-offload-media/doc/block-all-public-access-to-bucket/
