### ISSUE TITLE
"This item has not been offloaded yet"

### ISSUE THREAD

**Issue by beaespi** [deliciousbrains/wp-amazon-s3-and-cloudfront#519]
Current version of the plugin is 2.3.1.... 
Stuck on the "Running Metadata Update (99.12% Complete)" for more than an hour now. All my new assets on the media library for wordpress is giving the status: This item has not been offloaded yet. Any news about this?

Help?

**Comment by beaespi** [comment]
downgraded to version 2.2.1.... it works there

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
