### ISSUE TITLE
Upgrade to 2.3.x broke all images due to incorrectly marked 'private sizes'

### ISSUE THREAD

**Issue by schoenkaft** [deliciousbrains/wp-amazon-s3-and-cloudfront#521]
The recent upgrade to 2.3.x broke all our images, resulting in privately signed images throughout all of our websites.

We think the issue is possibly caused by the conversion to the new format, where the old sizes from the `amazonS3_info` entries are incorrectly converted to `private_sizes` without checking if they are indeed 'private'. 

Possible cause: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/classes/items/media-library-item.php#L373

An example of an old `amazonS3_info` entry:

```
a:6:{s:8:"provider";s:3:"aws";s:6:"region";s:9:"eu-west-1";s:6:"bucket";s:26:"bucket.example.com";s:3:"key";s:79:"app/uploads/2019/10/lorem-ipsum-11.jpg";s:3:"acl";s:13:"aws-exec-read";s:5:"sizes";a:19:{s:9:"thumbnail";a:1:{s:3:"acl";s:13:"aws-exec-read";}s:6:"medium";a:1:{s:3:"acl";s:13:"aws-exec-read";}}}
```

The `is_private` column in the new table is correctly set tot `0`, as we use `aws-exec-read` to circumvent issues mentioned in #492. We do not used the pre-signed/private image feature at all. 

So all items were still 'public', but since every image size was in the the private sizes column, all images were served via `s3_client->createPresignedRequest()`.

The 'quick and dirty' solution was to completely delete all `extra_info` entries, so the `private_sizes` entry is cleared:

```mysql
UPDATE toc_as3cf_items
SET extra_info = NULL
WHERE extra_info is not null;
```

**Comment by ianmjones** [comment]
Hey @schoenkaft, appreciate you raising this issue and also submitting the PRs related to private buckets.

However, as you've probably figured out, the switch to the custom table gave us the opportunity to properly codify the fact WP Offload Media has only really ever supported the concept of objects being either "public" or "private", where "private" means needing a signed URL.

We no longer use the canned ACL strings in the stored metadata for offloaded Media Library items, just as part of the code for supported storage providers.

This is the first phase of supporting buckets where setting the ACL either makes no sense or isn't even allowed.

We're working on supporting those kinds of buckets where direct access isn't allowed, and "public" access is only provided via CDN.

**Comment by schoenkaft** [comment]
Hey @ianmjones, thanks for the quick response. 

We've upgrade a few of our other sites (we do this periodically since everything is managed by Composer), and did not encounter further issues. We only have two sites which require `private` buckets (sensitive data and content embargoes). So it appears the `sizes`-issue only happened during the migration of the our 'private' sites.

> This is the first phase of supporting buckets where setting the ACL either makes no sense or isn't even allowed.
>
> We're working on supporting those kinds of buckets where direct access isn't allowed, and "public" access is only provided via CDN.

Great, looking forward to it! Keep up the great work 👍 

I'll close this issue (might still help someone who hasn't upgraded yet and has the same setup).
