### ISSUE TITLE
 Refused to load the script because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.  2

### ISSUE THREAD

**Issue by rushang19** [deliciousbrains/wp-amazon-s3-and-cloudfront#522]
Unable to load images on my site with aws s3 bucket url

**Comment by ianmjones** [comment]
@rushang19 Going to need some more info here, never seen this before.

Please can you share example img tags that are suffering from this restriction.

Please also detail what version of what browser you're using on what OS, and what content and security settings you have enabled in the browser.

**Comment by rushang19** [comment]
It is due to https, I have selected Http, need to just select Https. and its worked
