### ISSUE TITLE
Efficient way to rewrite  filepath

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [deliciousbrains/wp-amazon-s3-and-cloudfront#524]
I realized that the plugin is adding a part to the uploaded files. I found that this is due to `Object Versioning` being enabled. I've disabled it now. Is there a way for me to remote this versioning from the path of the files that were uploaded earlier?

![image](https://user-images.githubusercontent.com/11808845/73456454-ee93ae80-4397-11ea-8d14-aa8cf53ab6cc.png)

**Comment by ianmjones** [comment]
You need to "Remove from Bucket" and re-offload with new settings so that the objects get new keys (paths).

WP Offload Media has Pro tools for bulk remove from bucket and re-offload.

https://deliciousbrains.com/wp-offload-media/
