### ISSUE TITLE
How to link with the subdomain with the google cloud store?

### ISSUE THREAD

**Issue by vituchito125** [deliciousbrains/wp-amazon-s3-and-cloudfront#525]
could you help me how to link the domain with the google store api?

I am new at this 🙁

**Comment by ianmjones** [comment]
We have a doc for that!

https://deliciousbrains.com/wp-offload-media/doc/google-cloud-storage-quick-start-guide/

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

**Comment by vituchito125** [comment]
I already did that and it is working that I know but I want to know how I want to change this for
https://storage.googleapis.com/uploadercodes/wp-content/contenido/subidast/wp-content/2020/01/31082901/figuras-8.jpg
by
my domain I saw a page that I did the same and it works normal

**Comment by vituchito125** [comment]
There is no manual on how to configure the Google Cloud cname and CND of them to link the domain with the Google Store api,
believe the CND Inside Dns and it didn't work the same way: "v

**Comment by vituchito125** [comment]
![image](https://user-images.githubusercontent.com/53723504/73543108-3b14d380-4404-11ea-88ea-739ba63c3d5d.png)
I want something like this linked: "v
