### ISSUE TITLE
Protect against updates of partially formed metadata since WordPress 5.3.

### ISSUE THREAD

**Issue by cocodelacueva** [deliciousbrains/wp-amazon-s3-and-cloudfront#526]
Hi, I install the lite, but i also have a question.
File: amazon-s3-and-cloudfront.php
Line 1064

// Protect against updates of partially formed metadata since WordPress 5.3.

If i deactive this, works fine. But if I keep it as it is, it doesn't work. And it does not generate an error in debug log either.

I activate the Twenty Twenty Theme and it does not work either. WP is not generating thumnails.

My question is, what I'm forgeting here?

Thanks.

**Comment by ianmjones** [comment]
If WP thinks there should be thumbnails generated, but they aren't being generated, then WP Offload Media isn't going to be able to offload the item as it'll see that as a failure and will avoid breaking things further.
