### ISSUE TITLE
 It does not show and does not change the url with S3 aws

### ISSUE THREAD

**Issue by vituchito125** [deliciousbrains/wp-amazon-s3-and-cloudfront#527]
When they switch from google cloud to aws they don't want to change anymore the url stays static with the original wordprees url
![123](https://user-images.githubusercontent.com/53723504/74988348-9cc8cc00-540b-11ea-9394-fd65954adab7.png)
![1234](https://user-images.githubusercontent.com/53723504/74988345-9a667200-540b-11ea-9505-4d81a2bad2f1.png)

site_url(): https://www.zonamixs.com
home_url(): https://www.zonamixs.com
Database Name: bitnami_wordpress
Table Prefix: wp_
WordPress: 5.3.2
Web Server: Apache
PHP: 7.3.13
MySQL: 8.0.18
ext/mysqli: yes
PHP Memory Limit: 512M
WP Memory Limit: 40M
Memory Usage: 10 MB
Blocked External HTTP Requests: None
WP Locale: es_ES
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 0 B
PHP Time Limit: 120
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
cURL: 7.67.0
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 0 (paths 0)
Offloaded Media Files: 0 (paths 0)
Not Offloaded Media Files: 0 (paths 0)
Note: Approximate values, paths *try* and discard duplicates.

Number of Image Sizes: 19

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
ct_actor_thumb (500x500)
videopro_misc_thumb_1 (50x50)
videopro_misc_thumb_2 (100x75)
videopro_misc_thumb_3 (205x115)
videopro_misc_thumb_4 (277x156)
videopro_misc_thumb_5 (298x298)
videopro_misc_thumb_6 (320x180)
videopro_misc_thumb_7 (407x229)
videopro_misc_thumb_8 (565x318)
videopro_misc_thumb_9 (636x358)
videopro_misc_thumb_10 (800x450)
videopro_misc_thumb_11 (1280x720)
tptn_thumbnail (250x250)

WP_CONTENT_DIR: /opt/bitnami/apps/wordpress/htdocs/wp-content
WP_CONTENT_URL: https://www.zonamixs.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins
WP_PLUGIN_URL: https://www.zonamixs.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Defined
AS3CF_SETTINGS Keys: access-key-id, provider, secret-access-key

Local URL:
https://www.zonamixs.com/wp‑content/uploads/2020/02/photo.jpg
Offload URL:
https://cloud.zonamixs.com/codes/contenido/subidas/wp‑content/2020/02/20230704/photo.jpg

Provider: Amazon Web Services
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: s3-zonamixs
Region: 

Copy Files to Bucket: On
Enable Path: On
Custom Path: codes/contenido/subidas/wp-content/
Use Year/Month: On
Object Versioning: On

Rewrite Media URLs: On
Enable Custom Domain (CDN): On
Custom Domain (CDN): cloud.zonamixs.com
Force HTTPS: On

Remove Files From Server: On

Active Theme Name: videopro
Active Theme Version: 2.3.6.7
Active Theme Folder: videopro

Active Plugins:
Advance Search Form (v1.4.9.9) by Cactusthemes
All In One SEO Pack (v3.3.5) by Michael Torbert
Analytics Dashboard Free (v6.0.1) by ZonaMixs
BuddyPress (v5.1.2) by La Comunidad de BuddyPress
Cactus Actor (v1.1.4.2) by CactusThemes
Cactus Ads (v2.5.5.5) by CactusThemes
Cactus Badges (v1.1) by Cactusthemes
Cactus Rating (v1.2.1.3) by Cactusthemes
Cactus Video (v2.3.6.6) by CactusThemes
Contact Form 7 (v5.1.6) by Takayuki Miyoshi
Easy Tab (v2.0.2) by CactusThemes
Imágenes Categorías (v2.5.4) by Muhammad Said El Zahlan
Loco Translate (v2.3.1) by Tim Whitlock
OptionTree (v2.7.3) by Derek Herman
Sassy Social Share (v3.3.8) by Team Heateor
Top 10 (v2.8.0) by Ajay D'Souza
UpdraftPlus - Backup/Restore (v1.16.21) by UpdraftPlus.Com, DavidAnderson
Video Thumbnails (v2.12.4) by Sutherland Boswell
VideoPro - Shortcodes (v1.3.4.7) by CactusThemes
VideoPro - Unyson Sample Data (v1.0.3) by CactusThemes
WP Mail SMTP (v1.8.1) by WPForms
WP Offload Media Lite (v2.3.2) by Delicious Brains
WP Super Cache (v1.7.1) by Automattic
WP-Optimize - Clean, Compress, Cache (v3.0.16) by David Anderson, Ruhani Rabin, Team Updraft
WPBakery Page Builder (v6.1) by Michael M - WPBakery.com
WTI Like Post (v1.4.4) by webtechideas
Widget Logic (v5.10.4) by WPChef
Wordfence Security (v7.4.6) by Wordfence
Youzer (v2.3.9) by Youssef Kaine
wpDiscuz (v5.3.5) by gVectors Team (A. Chakhoyan, G. Zakaryan, H. Martirosyan)

Drop-ins:
advanced-cache.php - advanced-cache.php

**Comment by vituchito125** [comment]
Practically if it goes up normal but the wordpres url does not change it stays pro default, with google cloud I had no problem

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
