### ISSUE TITLE
Looks like something’s gone wrong. Wait a couple seconds, and then try again.

### ISSUE THREAD

**Issue by vistarahuljaiswar** [deliciousbrains/wp-amazon-s3-and-cloudfront#528]
I Integrated my Wordpress Blog assets (images) to S3 using the Amazon AWS plugin 
and migrate my all blog assets to aws s3 using this plugins but i am facing issues with the logo of my blog and trying to replace the logo but when i upload the image it's giving me error 
Untitled-2-01.png : An error occurred in the upload. Please try again later.

and i am unable customize the page too it giving me error  Looks like something’s gone wrong. Wait a couple seconds, and then try again.

please help me with this issue

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
