### ISSUE TITLE
get_stream_wrapper_file make web slow

### ISSUE THREAD

**Issue by anhton** [deliciousbrains/wp-amazon-s3-and-cloudfront#530]
My site slowdown after install wp-amazon-s3-and-cloudfront plugin 
it take 1s to load homepage before install but it take 40s after install plugin 
my site have 9 image
I debug into plugin and find out this code make my site slow

file :amazon-s3-and-cloudfront/classes/as3cf-plugin-compatibility.php
function : compatibility_init_if_setup 
line 91 : 
`// Turn on stream wrapper S3 file`
`add_filter( 'as3cf_get_attached_file', array( $this, 'get_stream_wrapper_file' ), 20, 4 );`
After i remove this code line , my site  take 1s as before and plugin still ok 

hope you check and fix it soon

[maybeautyus.local-diagnostic-log-20200305105007.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/4297228/maybeautyus.local-diagnostic-log-20200305105007.txt)

**Comment by ianmjones** [comment]
You probably have a wayward dynamic cropping plugin, theme or custom code.

https://deliciousbrains.com/on-the-fly-image-processing/

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
