### ISSUE TITLE
Not able to regenerate thumbnails

### ISSUE THREAD

**Issue by RajeevRF** [deliciousbrains/wp-amazon-s3-and-cloudfront#533]
Hi,

I am not able to regenerate thumbnails for the images stored in S3.
I am getting the following error.

The fullsize image file cannot be found in your uploads directory at https://cdn.domain.com/wp-content/uploads/2020/03/filename.jpg. Without it, new thumbnail images can't be generated.

**Comment by ianmjones** [comment]
Unfortunately you have not provided enough information for us to reproduce the problem.

However, if you're using something other than the Regenerate Thumbnails plugin, please try that plugin first as we know it works well with WP Offload Media, including when you're using the "Remove Files From Server" option.

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

**Comment by RajeevRF** [comment]
Hi,

I am using the Regenerate Thumbnails plugin and the "Remove Files From Server" option is enabled. Whenever I try to regenerate thumbnail for an individual image or for all the images, I am getting the following error.

**The fullsize image file cannot be found in your uploads directory at https://cdn.domain.com/wp-content/uploads/2020/03/filename.jpg. Without it, new thumbnail images can't be generated.**
