### ISSUE TITLE
Renaming uploaded files in S3

### ISSUE THREAD

**Issue by pixelprogrammer** [deliciousbrains/wp-amazon-s3-and-cloudfront#534]
Would be great if there was a feature for renaming files with this plugin (let me know if it already exists).

Sometimes you need to go in and rename a file for SEO purposes.

**Comment by ianmjones** [comment]
WP Offload Media works well with the [Enable Media Replace](https://wordpress.org/plugins/enable-media-replace/) plugin, is that what you're looking for?
