### ISSUE TITLE
Update AWS SDK

### ISSUE THREAD

**Issue by pcfens** [deliciousbrains/wp-amazon-s3-and-cloudfront#536]
This is a duplicate of what's posted on the [WordPress support site](https://wordpress.org/support/topic/outdated-aws-library/).

I'm attempting to use IAM roles linked to a Kubernetes service account to grant access to S3 instead of giving the entire node an IAM role. Amazon's documentation says that version [3.110.7 or newer](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html) of the PHP SDK is required. There have been bugfixes since then, so an update to the latest PHP SDK would be appreciated.

Thanks!

**Comment by ianmjones** [comment]
Next version of WP Offload Media will be using AWS PHP SDK v3.133.40 or newer.

**Comment by ianmjones** [comment]
Fixed in WP Offload Media (Lite) 2.4 which includes a much newer version of the AWS PHP SDK v3.

**Comment by pcfens** [comment]
Thanks for the update on this - it looks like a few files required for assuming roles didn't make it in the update.

When I try running this from inside a container on Kubernetes I get the error that `amazon-s3-and-cloudfront/vendor/Aws3/Aws/Sts/StsClient.php` can't be found. I'm guessing that this will fail on EC2 instances too since the STS stuff is used there too.

Please let me know if you need any more info.

**Comment by ianmjones** [comment]
@pcfens Please create a new issue with details of what's missing for your use-case, including any relevant doc links etc.

**Comment by pcfens** [comment]
Thanks! This seems to have fixed the issues we were running in to.

For others that might find this, if you find yourself getting the error

`PHP Warning:  file_get_contents(/var/run/secrets/eks.amazonaws.com/serviceaccount/token): failed to open stream: Permission denied in /var/www/html/wp-content/plugins/amazon-s3-and-cloudfront/vendor/Aws3/Aws/Credentials/AssumeRoleWithWebIdentityCredentialProvider.php on line 75`

you'll also need to set a securityContext on your pods so that Apache will be able to read the token provided by AWS with
```yaml
securityContext:
  fsGroup: 33
```
in your deployment manifest (fsGroup is the group ID of the www-data user - 33 is the default in the "official" WordPress image).
