### ISSUE TITLE
updation of existing pages - doesn't place the CDN URL

### ISSUE THREAD

**Issue by kasivps** [deliciousbrains/wp-amazon-s3-and-cloudfront#538]
Hi Support, 

We are using wordpress Version 5.3.2
WP Offload Media Lite: Version 2.3.2

When our WordPress Developers, create a new Page and upload the files using the plugin, the URL gets reflected as the CDN URL provided, but when we make further changes to the same page and update, the Offload URL is getting replaced with the Local URL. 

This is causing our images to be loaded from the Web Server rather than from a CDN.

Please let us know what could cause the issue to happen only when the images/posts are updated. 

Modified the url to keep it as example urls. 
--

site_url(): https://write.example.org/in
home_url(): https://write.example.org/in
Database Name: xxx
Table Prefix: prod_
WordPress: 5.3.2
Web Server: nginx/1.12.2
PHP: 7.3.15
MySQL: 5.6.44
ext/mysqli: yes
PHP Memory Limit: 128M
WP Memory Limit: 40M
Memory Usage: 7 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 2 MB
PHP Time Limit: 30
PHP Error Log: /var/log/php-fpm/www-error.log
WP Cron: Disabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2k  26 Jan 2017
cURL: 7.61.1
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 529 (paths 529)
Offloaded Media Files: 270 (paths 270)
Not Offloaded Media Files: 259 (paths 259)
Note: Approximate values, paths *try* and discard duplicates.

Number of Image Sizes: 6

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)

WP_CONTENT_DIR: /var/www/html/in/wp-content/in/wp-content
WP_CONTENT_URL: https://write.example.org/in/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/html/in/wp-content/plugins
WP_PLUGIN_URL: https://write.example.org/in/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://write.example.org/in/wp‑content/uploads/2020/04/photo.jpg
Offload URL:
https://cdn-myweb.example.org/in/wp‑content/uploads/2020/04/20233305/photo.jpg

Provider: Amazon Web Services
Use Server Roles: On
Key File Path: N/A
Access Keys Set: No
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: xxx
Region: xx-xxxx-x

Copy Files to Bucket: On
Enable Path: On
Custom Path: in/wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Rewrite Media URLs: On
Enable Custom Domain (CDN): On
Custom Domain (CDN): cdn-myweb.example.org
Force HTTPS: On

Remove Files From Server: Off

Active Theme Name: dt-the7
Active Theme Version: 1.0.0
Active Theme Folder: dt-the7-child
Parent Theme Name: The7
Parent Theme Version: 8.4.1
Parent Theme Folder: dt-the7

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
