### ISSUE TITLE
Slow gallery after last update plugin

### ISSUE THREAD

**Issue by leonardop21** [deliciousbrains/wp-amazon-s3-and-cloudfront#539]
Hello,

A few days after updating the plugin to version 2.3.2 we noticed that our gallery is very slow to open, sometimes it takes more than 30 seconds to load the images, which are in Google Storage

Print: https://prnt.sc/s6wh5n

The wp version is 5.3

Anyone else facing this problem? Any idea how to solve it?

**Comment by arwinjp** [comment]
I have the same issue with DO Spaces. I have removed files from local server and the images are served from spaces. Image upload takes longer time than usual. Media search returns timeout error most of the time.
Plugin version: 2.3.2
WordPress version: 5.4.2

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
