### ISSUE TITLE
When Upload new Image to Media Library - thumbnails not generated and not uploaded to amazon s3 bucket

### ISSUE THREAD

**Issue by ranapiyush1986** [deliciousbrains/wp-amazon-s3-and-cloudfront#540]
Hello,
I am using Offload Media Lite - when i upload images in Media library on single image uploaded in s3 bucket , but as per WP Rule , when we upload any image WP will make 8-9 thumbnail different sizes, but when we using this plugin , there are no thumbnails in relevant bucket folder.
your help will be really appreciated.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
