### ISSUE TITLE
Errors getting bucket location

### ISSUE THREAD

**Issue by danjcarrington** [deliciousbrains/wp-amazon-s3-and-cloudfront#541]
I'm using an IAM role to provide access to the bucket and I have explicitly granted GetBucketLocation, but still getting an error that it's getting AccessDenied for getting the bucket location. I'll post below the Bucket Policy, the relevant code from wp-config.php and the error message:

Bucket Policy:
```
{
    "Version": "2012-10-17",
    "Id": "Policy1586199645769",
    "Statement": [
        {
            "Sid": "Stmt1586199560294",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::<account num>:role/my-ecs-service-role",
                    "arn:aws:iam::<account num>:role/my-ec2-role"
                ]
            },
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::mybucket"
        },
        {
            "Sid": "Stmt1586199642917",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::<account num>:role/my-ecs-service-role",
                    "arn:aws:iam::<account num>:role/my-ec2-role"
                ]
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::mybucket/*"
        }
    ]
}

```
From wp-config.php:
```
define( 'AS3CF_SETTINGS', serialize( array(
    'provider' => 'aws',
    'use-server-roles' => true,
) ) );
```

Error message:
```
Error Getting Bucket Region —There was an error attempting to get the region of the bucket mybucket: Error executing "GetBucketLocation" on "https://s3.amazonaws.com/mybucket?location"; AWS HTTP error: Client error: `GET https://s3.amazonaws.com/mybucket?location` resulted in a `403 Forbidden` response: AccessDeniedAccess DeniedB21964 (truncated...) AccessDenied (client): Access Denied - AccessDeniedAccess DeniedB219647EE6F7A213cpifEtGm/XzgjuWWSI/E/EDSpDnbZ0HYF0r3NHgYtVhMfOOk4OIc2dhFDEv41WkWpQiqpCRnWuU=
```

**Comment by danjcarrington** [comment]
I was able to resolve this by adding the AmazonS3FullAccess managed policy to the ec2 role and the ecs role. That is a bit too open for my taste, so I do plan on whittling that down to get the minimum permissions required. But, apparently, the bucket policy was not sufficient. There needs to be some level of S3 access specified for the IAM role.

The other thing I will have to narrow down is whether that S3 access needs to be specified for the ec2 role or the ecs role as I'm running this as a container in AWS ECS. Currently, it's set in both, but I suspect only one is actually required. I will update this once I am able to narrow it down and determine the minimum requirements.

**Comment by ianmjones** [comment]
We've just updated the following doc to match WP Offload Media 2.4 requirements, it now uses the most restrictive actions possible, no wildcard actions.

https://deliciousbrains.com/wp-offload-media/doc/custom-iam-policy-for-amazon-s3/
