### ISSUE TITLE
Stop serving images from S3

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [deliciousbrains/wp-amazon-s3-and-cloudfront#542]
Hey there,

I've deactivated the plugin but still, the images are loading from S3. How can I serve the images back from my main hosting and not S3?

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

**Comment by abhishek-pokhriyal** [comment]
Excellent!
