### ISSUE TITLE
Compatibility issue with Thrive Architect (v2.5.4.1) by Thrive Themes

### ISSUE THREAD

**Issue by lancedon** [deliciousbrains/wp-amazon-s3-and-cloudfront#543]
Hi,

I used here the "Offload Media Lite", works very well, but the marketing area trying start use the plugin "Thrive Architect" in some cases. We noted the follows problem:

![Screen Shot 2020-05-26 at 6 47 05 PM](https://user-images.githubusercontent.com/19196410/83033626-b9c5fa00-a00d-11ea-8955-6ec985da5413.png)

Appear the "Offload Media Lite" or the "Thrive Architect" trying host the images locally on the server and not send them to S3. 
Someone have any suggestion to help us here?

DIAGNOSTIC INFO
`site_url(): https://astrocentro.meupro.com.br/blog
home_url(): https://astrocentro.meupro.com.br/blog
Database Name: dev_wp_astrocentro
Table Prefix: wp_
WordPress: 5.4.1
Web Server: nginx/1.16.1
PHP: 7.1.33
MySQL: 5.7.28
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 46 MB
Blocked External HTTP Requests: None
WP Locale: pt_BR
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes	
SCRIPT_DEBUG: No
WP Max Upload Size: 64 MB
PHP Time Limit: 300
PHP Error Log: /var/log/php-fpm/7.1/www-error.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2k  26 Jan 2017
cURL: 7.61.1
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Disabled
Basic Auth: Enabled
Proxy: Disabled

Media Files: 6.636 (paths 6.635)
Offloaded Media Files: 6.629 (paths 6.628)
Not Offloaded Media Files: 7 (paths 7)
Note: Approximate values, paths *try* and discard duplicates.

Number of Image Sizes: 9

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
post-thumbs (142x80)
post-image (1074x725)
mobile (400x400)

WP_CONTENT_DIR: /var/www/html/blog_astrocentro/blog/wp-content
WP_CONTENT_URL: https://astrocentro.meupro.com.br/blog/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/html/blog_astrocentro/blog/wp-content/plugins
WP_PLUGIN_URL: https://astrocentro.meupro.com.br/blog/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://astrocentro.meupro.com.br/blog/wp-content/uploads/2020/05/photo.jpg
Offload URL:
https://cdn.astrocentro.com.br/blog/wp-content/uploads/2020/05/27111153/photo.jpg

Provider: Amazon Web Services
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: DBI_AWS_ACCESS_KEY_ID
Secret Access Key Define: DBI_AWS_SECRET_ACCESS_KEY

Bucket: uploads-astrocentro
Region: sa-east-1

Copy Files to Bucket: On
Enable Path: On
Custom Path: blog/wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Rewrite Media URLs: On
Enable Custom Domain (CDN): On
Custom Domain (CDN): cdn.astrocentro.com.br
Force HTTPS: On

Remove Files From Server: Off

Active Theme Name: Astrocentro
Active Theme Version: 2.3.0
Active Theme Folder: odin

Active Plugins:
301 Redirects (v2.45) by WebFactory Ltd
Advanced Custom Fields (v5.8.11) by Elliot Condon
Amazon Web Services (v1.0.5) by Delicious Brains
Audima (v1.10.0) by Audima
Custom Post Type Page Template (v1.1) by Hiroaki Miyashita
DFP - DoubleClick Ad Manager (v0.3.2) by Chris W. Gerber
Enhanced Category Pages (v2.3.0) by Ciprian Amariei, Diana Amitroaei
No Category Base (WPML) (v1.3) by Marios Alexandrou
The Official Facebook Chat Plugin (v1.5) by Facebook
Thrive Architect (v2.5.4.1) by Thrive Themes
Thrive Leads (v2.2.15.1) by Thrive Themes
Thrive Product Manager (v1.2.3) by Thrive Themes
Thrive Quiz Builder (v2.2.15.1) by Thrive Themes
User Role Editor (v4.54) by Vladimir Garagulya
WP Offload Media Lite (v2.3.2) by Delicious Brains
WordPress Zero Spam (v3.1.1) by Ben Marshall
Yoast SEO (v14.2) by Team Yoast
mobble (v1.6) by Scott Evans
`

**Comment by ianmjones** [comment]
We're keeping track of votes for integrating with page builders and other plugins that have custom content handling that does not use the standard WordPress functionality and therefore prevents WP Offload Media's URL rewriting hooks from firing.

However, because of the work involved in developing, testing and maintaining such integrations, we generally add such integrations to WP Offload Media rather than WP Offload Media Lite.
