### ISSUE TITLE
URL Incorrect if CDN points to a subfolder

### ISSUE THREAD

**Issue by Cutch** [deliciousbrains/wp-amazon-s3-and-cloudfront#544]
Great plugin, looks like its going to be everything we want however. It is not working because our AWS CDN points to a subfolder in the s3 bucket.
For example
bucket/cdn/wpcontent
cdn.website.com -> bucket/cdn
When the urls are generated they look like
cdn.website.com/cdn/wpcontent
However because our cdn is already pointing to a subfolder it does not work.
The goal would be to have the url look like 
cdn.website.com/wpcontent

It would be great if you could add a cdn base path in the settings and subtract that from the generated url.

**Comment by ianmjones** [comment]
Check out the `as3cf_cloudfront_path_parts` filter.

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/96d9fc03ffcfdc1d2e77b0a1a53891e6e1a76e30/amazon-s3-and-cloudfront-tweaks.php#L830
