### ISSUE TITLE
Cloudflare CDN

### ISSUE THREAD

**Issue by webtent** [deliciousbrains/wp-amazon-s3-and-cloudfront#546]
I am having an issue getting our Amazon S3 bucket set up with Cloudflare as a CDN. I believe the issue may be the bucket is not DNS-compliant. As an example, where the bucket name is 'bucket', the URL given by S3 when I enable Static website hosting is:

    http://bucket.s3-website-us-east-1.amazonaws.com/

The link works with access denied response as expected and all item URLs in our bucket work under that URL with 'Block all public access' set to 'Off'. However, when I set up in Cloudflare as a CNAME 'bucket' with the target as `bucket.s3-website-us-east-1.amazonaws.com`, the CNAME does not work and results in a 404 error not found:

    http://bucket.domain.tld

Other examples I've seen and instructions show the use of a DNS-compliant bucket name such as `cdn.domain.tld` so the URL becomes:

    http://cdn.domain.tld.s3-website-us-east-1.amazonaws.com/

Would this be the issue? And if so, could someone suggest the best way to convert a very large bucket to a DNS-compliant bucket?

**Comment by ianmjones** [comment]
Yes, Cloudflare requires that the bucket name match the subdomain you wish to use.

https://deliciousbrains.com/wp-offload-media/doc/cloudflare-setup/

WP Offload Media has the ability to create (or select) a new bucket with the correct name, and then copy the offloaded media bucket to bucket without downloading, which is pretty fast.

https://deliciousbrains.com/wp-offload-media/doc/how-to-copy-media-between-buckets/
