### ISSUE TITLE
is_readable(): open_basedir restriction in effect. File(...) is not within the allowed path(s)(...) in .../ConfigurationProvider.php

### ISSUE THREAD

**Issue by kagomemiao** [deliciousbrains/wp-amazon-s3-and-cloudfront#548]
There's nothing been changed on my site recently except new posts. I have tried to deactivate this plugin, and the problem solved.
So I suppose it is a plugin issue.

**Comment by ianmjones** [comment]
Thanks, we've had a couple of customers raise this issue and we're looking into a fix.

**Comment by ianmjones** [comment]
We've just released v2.4.1, please let us know if it fixes this problem for you @kagomemiao.

**Comment by kagomemiao** [comment]
yes, the problem is fixed, thanks a lot
