### ISSUE TITLE
Error Getting Bucket Region

### ISSUE THREAD

**Issue by singhdeepender891** [deliciousbrains/wp-amazon-s3-and-cloudfront#549]
After enter the name of bucket i am getting this error.

Error Getting Bucket Region —There was an error attempting to get the region of the bucket filmistory: Error executing "GetBucketLocation" on "https://filmistory.s3.amazonaws.com/?location"; AWS HTTP error: Client error: `GET https://filmistory.s3.amazonaws.com/?location` resulted in a `403 Forbidden` response: AccessDeniedAccess Denied7M2PBN (truncated...) AccessDenied (client): Access Denied - AccessDeniedAccess Denied7M2PBN3S0W8J0Q8POfIY7AwncWxpjVlInAImkYGXi4Si4h

**Comment by ianmjones** [comment]
Probably not a bug, you likely need to check your AWS Access Keys have been entered correctly or that the IAM User has the correct access.

https://deliciousbrains.com/wp-offload-media/doc/amazon-s3-quick-start-guide/

https://deliciousbrains.com/wp-offload-media/doc/custom-iam-policy-for-amazon-s3/

**Comment by singhdeepender891** [comment]
Great, Now its working
