### ISSUE TITLE
'Creating default object from empty value' in updates.php

### ISSUE THREAD

**Issue by mpemburn** [deliciousbrains/wp-amazon-s3-and-cloudfront#550]
We've been using WP Amazon S3 and Cloudfront Pro for some time, and this just cropped up in my dev environment.  I think it may be due to having upgraded to PHP 7.4.3 recently. The warning occurs in updates.php on line 154.

**Comment by ianmjones** [comment]
Can you give us a stack trace?

**Comment by ianmjones** [comment]
Oh, and Diagnostic Info from the Support tab?

**Comment by mpemburn** [comment]
Stack trace:

ErrorException: Creating default object from empty value in file /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/content/plugins/amazon-s3-and-cloudfront-pro/vendor/deliciousbrains/updates.php on line 154
  | Stack trace:
  | 1. ErrorException-&gt;() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/content/plugins/amazon-s3-and-cloudfront-pro/vendor/deliciousbrains/updates.php:154
  | 2. Themosis\Core\Bootstrap\ExceptionHandler-&gt;handleError() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/content/plugins/amazon-s3-and-cloudfront-pro/vendor/deliciousbrains/updates.php:154
  | 3. Delicious_Brains_API_Updates-&gt;site_transient_update_plugins() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/wp/wp-includes/class-wp-hook.php:289
  | 4. WP_Hook-&gt;apply_filters() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/wp/wp-includes/plugin.php:206
  | 5. apply_filters() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/wp/wp-includes/option.php:1801
  | 6. get_site_transient() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/wp/wp-includes/update.php:658
  | 7. wp_get_update_data() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/wp/wp-admin/menu.php:32
  | 8. require() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/wp/wp-admin/admin.php:153
  | 9. require_once() /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/wp/wp-admin/upload.php:10
  | 10. require() /Users/mpemburn/.composer/vendor/weprovide/valet-plus/server.php:131

**Comment by mpemburn** [comment]
site_url(): https://laruta.test/wp
home_url(): https://laruta.test
Database Name: laruta_dev_1_6_2020
Table Prefix: lrt_
WordPress: 5.4.1 Multisite (subdomain)
Multisite Site Count: 7
Domain Mapping: Enabled
Web Server: nginx/1.17.9
PHP: 7.4.3
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 2G
WP Memory Limit: 2000M
Memory Usage: 34 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: Yes
WP Max Upload Size: 24 GB
PHP Time Limit: 5000
PHP Error Log: /Users/mpemburn/.valet/Log/php.log
WP Cron: Disabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
cURL: 7.69.1
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 11,832 (paths 11,794)
Offloaded Media Files: 11,786 (paths 11,751)
Not Offloaded Media Files: 46 (paths 43)
Note: Approximate values, paths *try* and discard duplicates.

Number of Image Sizes: 13

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
themosis (200x150)
woocommerce_thumbnail (300x300)
woocommerce_single (600x0)
woocommerce_gallery_thumbnail (100x100)
shop_catalog (300x300)
shop_single (600x0)
shop_thumbnail (100x100)

WP_CONTENT_DIR: /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/content
WP_CONTENT_URL: https://laruta.test/content
UPLOADS: Not defined
WP_PLUGIN_DIR: /Users/mpemburn/Dev/laruta.io/laruta.io/site/htdocs/content/plugins
WP_PLUGIN_URL: https://laruta.test/content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://laruta.test/content/uploads/2020/07/photo.jpg
Offload URL:
https://cdn.laruta.io/app/uploads/2020/07/15093651/photo.jpg

Provider: Amazon Web Services
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: DBI_AWS_ACCESS_KEY_ID
Secret Access Key Define: DBI_AWS_SECRET_ACCESS_KEY

Bucket: laruta-cdn
Region: 

Copy Files to Bucket: On
Enable Path: On
Custom Path: app/uploads/
Use Year/Month: On
Object Versioning: On

Rewrite Media URLs: On
Enable Custom Domain (CDN): On
Custom Domain (CDN): cdn.laruta.io
Force HTTPS: On

Remove Files From Server: On

Posts Count: 1,092,013

Pro Upgrade: 
License Status: Valid
License Constant: Off

Host IP: 127.0.0.1
Background Jobs: 


Active Theme Name: Laruta for MACPA
Active Theme Version: 2.0
Active Theme Folder: laruta-macpa
Parent Theme Name: Laruta Parent Theme
Parent Theme Version: 1.1.4.0
Parent Theme Folder: laruta-themosis-parent

Active Plugins:
ACF Native Fields (v1.1.0) by Winter
ACF to REST API (v3.1.0) by Aires Gonçalves
Advanced Custom Fields PRO (v5.8.12) by Elliot Condon
Advanced Custom Fields: Unique ID Field (v1.0.0) by KLicheR
Classic Editor (v1.5) by WordPress Contributors
Cornerstone (v2.1.7) by Themeco
Enable Media Replace (v3.4.1) by ShortPixel
Gravity Forms (v2.4.18.7) by Gravity Forms
Gravity Forms CLI (v1.2) by Rocketgenius
Gravity Forms Survey Add-On (v3.5.1) by Gravity Forms
Gravity Forms User Registration Add-On (v4.5.3) by Gravity Forms
Imagify (v1.9.10) by WP Media
LH User Taxonomies (v1.56) by Peter Shaw
LaRuta Redis Object Cache (v1.0) by Blue Ocean Ideas, Pressjitsu, Inc. Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive
Manage Notification E-mails (v1.5.1) by Virgial Berveling
ModalBox for Cornerstone (v1.2) by MagniGenie
Query Monitor (v3.6.0) by John Blackbourn
Redirection (v4.8) by John Godley
SearchWP (v3.1.13) by SearchWP, LLC
SearchWP Exclude UI (v1.2.1) by SearchWP
SearchWP Metrics (v1.2.3) by SearchWP
The SEO Framework (v4.0.7) by The SEO Framework Team
User Role Editor Pro (v4.56.2) by Vladimir Garagulia
WP CLI Login Command Server (v1.2) by Evan Mattson
WP Crontrol (v1.8.5) by John Blackbourn & crontributors
WP Offload Media (v2.3.2) by Delicious Brains
WooCommerce (v4.2.0) by Automattic
WooCommerce Account Funds (v2.1.19) by WooCommerce
WooCommerce Box Office (lrt-mod) (v1.1.11) by WooCommerce
WooCommerce Memberships (v1.17.5) by SkyVerge
WooCommerce Name Your Price (v3.1.0) by Kathy Darling
WooCommerce Order Status Control (v1.12.3) by SkyVerge
WooCommerce Product Bundles (v6.2.5) by SomewhereWarm
WooCommerce Shop as Customer (BOI FORK) (v2.12) by cxThemes
WooCommerce Stripe Gateway (v4.5.0) by WooCommerce
WooCommerce Subscriptions (v3.0.4) by WooCommerce
WooCommerce Subscriptions Gifting (v2.1.1) by WooCommerce

Must-use Plugins:
Disallow Indexing (v1.0.0) by Roots
Network Admin URL Fix (v1.0) by Julien Lambé
Separate Blog User Tables (v0.1) by lightningspirit
Themosis Framework Loader (v1.4.0) by Julien Lambé
disable_localization.phpjQuery Light (v) by 
lrtConditionallyLoadPlugins.phplrtSetupMigrations.phplrt_acf_json.php

Drop-ins:
sunrise.php - sunrise.php

**Comment by ianmjones** [comment]
@mpemburn FYI, as you're using WP Offload Media and therefore presumably have a license, you could have submitted your support request through the "Support" tab of WP Offload Media for priority (private) support!

As you're using WP Offload Media 2.3.2 rather than the just released v2.4 that I thought you might be using, you might still want to submit a support request so that we can work with you to debug this properly, especially as we've not seen this error with anyone else using 2.3.2.

**Comment by mpemburn** [comment]
Thanks.  I'll talk to the dev-ops guy about updating.
