### ISSUE TITLE
Default to private media

### ISSUE THREAD

**Issue by ocasta** [deliciousbrains/wp-amazon-s3-and-cloudfront#552]
It's great to see all the Signed URL and private Media extensions in 2.4. We can nearly remove our custom hack. The one weakness that remains from an enterprise point of view is that it still requires the media to be set as Private when uploaded which is easily overlooked by users. It would be great to have an option to force all uploaded media to Private

**Comment by ianmjones** [comment]
Check out the `as3cf_upload_acl` and `as3cf_upload_acl_sizes` filters!

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront-tweaks/blob/96d9fc03ffcfdc1d2e77b0a1a53891e6e1a76e30/amazon-s3-and-cloudfront-tweaks.php#L514
