### ISSUE TITLE
Compatibility issue with Education WordPress Theme - Masterstudy

### ISSUE THREAD

**Issue by alexaung** [deliciousbrains/wp-amazon-s3-and-cloudfront#553]
Hi, I offload media to S3 with cloudfront. But most of my images does not show. I saw only one image is uploaded to S3. 

I would like to buy it but I want to know It's compatibility issue?

site_url(): https://www.etakatho.com
home_url(): https://www.etakatho.com
Database Name: etakatho
Table Prefix: wp_
WordPress: 5.4.2
Web Server: nginx/1.17.10
PHP: 7.3.16-1+ubuntu16.04.1+deb.sury.org+1
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 18 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 128 MB
PHP Time Limit: 300
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
cURL: 7.47.0
Zlib Compression: Enabled
PHP GD: 2.2.5
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 138
Offloaded Media Files: 6
Not Offloaded Media Files: 132

Number of Image Sizes: 26

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
img-1100-450 (1100x450)
img-1120-800 (1120x800)
img-870-440 (870x440)
img-850-600 (850x600)
img-480-380 (480x380)
img-300-225 (300x225)
img-75-75 (75x75)
img-840-400 (840x400)
img-270-283 (270x283)
img-270-180 (270x180)
img-270-153 (270x153)
img-129-129 (129x129)
img-122-120 (122x120)
img-69-69 (69x69)
img-63-50 (63x50)
img-50-56 (50x56)
img-1170-500 (1170x500)
img-840-430 (840x430)
img-770-300 (770x300)
img-370-193 (370x193)

WP_CONTENT_DIR: /www/etakatho_436/public/wp-content
WP_CONTENT_URL: https://www.etakatho.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /www/etakatho_436/public/wp-content/plugins
WP_PLUGIN_URL: https://www.etakatho.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Defined
AS3CF_SETTINGS Keys: access-key-id, provider, secret-access-key

Local URL:
https://www.etakatho.com/wp‑content/uploads/2020/07/photo.jpg
Offload URL:
https://cdn.etakatho.com/wp‑content/uploads/2020/07/15114417/photo.jpg

OME Metadata Version: 8

Storage Provider: Amazon S3
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: etakatho
Region: ap-southeast-1
Block All Public Access: Disabled

Copy Files to Bucket: On
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Delivery Provider: Amazon CloudFront
Rewrite Media URLs: On
Enable Custom Domain (CNAME): On
Custom Domain (CNAME): cdn.etakatho.com

Force HTTPS: On

Remove Files From Server: On

Active Theme Name: Master Study Child
Active Theme Version: 2.0
Active Theme Folder: masterstudy-child
Parent Theme Name: MasterStudy
Parent Theme Version: 3.5.1
Parent Theme Folder: masterstudy

Active Plugins:
Breadcrumb NavXT (v6.5.0) by John Havlik
BuddyPress (v6.1.0) by The BuddyPress Community
BuddyPress Multilingual (v1.6) by OnTheGoSystems
Contact Form 7 (v5.2) by Takayuki Miyoshi
Email Templates (v1.3.1.2) by Damian Logghe
GDPR Compliance & Cookie Consent (v1.5) by StylemixThemes
Google Analytics for WordPress by MonsterInsights (v7.11.0) by MonsterInsights
Mailgun (v1.7.1) by Mailgun
MasterStudy LMS Learning Management System PRO (v3.1.0) by StylemixThemes
MasterStudy LMS – WordPress Course Plugin (v2.1.3) by StylemixThemes
STM Configurations (v4.1.0) by StylemixThemes
Slider Revolution (v6.2.6) by ThemePunch
WP Offload Media Lite (v2.4) by Delicious Brains
WPBakery Page Builder (v6.2.0) by Michael M - WPBakery.com
WPForms Lite (v1.6.1) by WPForms
WPML Media (v2.5.5) by OnTheGoSystems
WPML Multilingual CMS (v4.3.12) by OnTheGoSystems
WPML String Translation (v3.0.9) by OnTheGoSystems
WPML Translation Management (v2.9.6) by OnTheGoSystems
Yoast SEO (v14.5) by Team Yoast

Must-use Plugins:
Kinsta Must-use Plugins (v2.3.3) by Kinsta Team

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
