### ISSUE TITLE
IAMS3FullAcces cURL error 28

### ISSUE THREAD

**Issue by W1sm3rill** [deliciousbrains/wp-amazon-s3-and-cloudfront#554]
Hello,

Since the 2.4 update I can't access S3 anymore, I get the error: "
[ITCO-WebSer-Y87T12M95E5U-596469962.eu-west-3.elb_.amazonaws.com-diagnostic-log-20200717115146.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/4937619/ITCO-WebSer-Y87T12M95E5U-596469962.eu-west-3.elb_.amazonaws.com-diagnostic-log-20200717115146.txt)
Error fetching buckets — Error retrieving credentials from the instance profile metadata service. (cURL error 28: Operation timed out after 1000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html))
".

I followed all the recommendations to access S3 via IAM, before this update no problem.

Thank you for this update.

**Comment by ianmjones** [comment]
Try with 2.4.2, but please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

**Comment by dawidroz** [comment]
Hi, the problem still exists in 2.4.4 version -> https://wordpress.org/support/topic/s3-error-with-iam-roles/
