### ISSUE TITLE
Running Attachments Update seems to hang

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#555]
Stuck on both my multi-sites:

Running Attachments Update (80.75% Complete) — We’re going through all the offloaded Media Library items and updating the metadata with the sizes of files that have been removed from the server. This will allow us to serve the correct size for media items and the total space used in Multisite subsites. This will be done quietly in the background, processing a small batch of Media Library items every 2 minutes. There should be no noticeable impact on your server’s performance

Is there a command line i could run to push this all through at once? Have gone through all the debugging tips and restarted process and it always seems to get stuck on the same completed % amount. Thanks guys!

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
