### ISSUE TITLE
wp_get_attachment_image_attributes might be need to be more sturdy?

### ISSUE THREAD

**Issue by mrbm** [deliciousbrains/wp-amazon-s3-and-cloudfront#556]
Getting this error in my logs:
```
[19-Jul-2020 18:18:55 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Amazon_S3_And_CloudFront::wp_get_attachment_image_attributes(), 2 passed in /somepath/wp-includes/class-wp-hook.php on line 287 and exactly 3 expected in /somepath/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php:2504
Stack trace:
#0 /somepath/wp-includes/class-wp-hook.php(287): Amazon_S3_And_CloudFront->wp_get_attachment_image_attributes(Array, Object(WP_Post))
#1 /somepath/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#2 /somepath/wp-content/plugins/fancy-gallery-pro/class.core.php(439): apply_filters('wp_get_attachme...', Array, Object(WP_Post))
#3 /somepath/wp-content/plugins/fancy-gallery-pro/class.core.php(484): WordPress\Plugin\Fancy_Gallery\Core->Build_Gallery(Array, Array)
#4 /somepath/wp-content/plugins/amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php on line 2504
```
checking amazon-s3-and-cloudfront/classes/amazon-s3-and-cloudfront.php line 2505 reveals

`public function wp_get_attachment_image_attributes( $attr, $attachment, $size ) {`

and digging into /somepath/wp-content/plugins/fancy-gallery-pro/class.core.php line 439 reveals
```
      $image->attributes = Apply_Filters('wp_get_attachment_image_attributes', Array(
        'src'    => $image->src,
        'width'  => $image->width,
        'height' => $image->height,
        'class'  => $image->class,
        'alt'    => $image->title,
        'title'  => $image->title
      ), $image );
```

fancy-gallery-pro is a crap old non updated plugin...that said is this error revealing an issue that should be dealt with, ie if filesize isn't set...set it it to full size?

Thoughts?

**Comment by mrbm** [comment]
Reviewing you code I see this wp_get_attachment_image_attributes function is newly added. Love to hear your thoughts on this new function and its compatibility and if you can thing of a possible hot fix I could make. its created an issue for all the sites in my multisite that have this gallery...so they are all done in that regards to their gallery.

Any thoughts would be appreciated, thanks guys!

**Comment by ianmjones** [comment]
> fancy-gallery-pro is a crap old non updated plugin

Umm, that kinda says it all really! 😂 

It should not be applying that `wp_get_attachment_image_attributes` filter itself, and certainly not with the incorrect number of arguments.

WordPress Core is responsible for that filter being applied in the `wp_get_attachment_image` function, with the following args...

`$attr = apply_filters( 'wp_get_attachment_image_attributes', $attr, $attachment, $size );`
