### ISSUE TITLE
Stuck at Metadata update

### ISSUE THREAD

**Issue by ocasta** [deliciousbrains/wp-amazon-s3-and-cloudfront#557]
I've updated the plugin on one of our instances and the Metadata upload never ends. The logs show this

`NOTICE: PHP message: WordPress database error Duplicate entry 'as3cf_tool_errors_uploader' for key 'option_name' for query UPDATE `wp_options` SET `option_name` = 'as3cf_tool_errors_uploader' WHERE `option_name` = 'wpos3_tool_errors_uploader' made by do_action_ref_array('as3cf_cron_update_wpos3_to_as3cf'), WP_Hook->do_action, WP_Hook->apply_filters, DeliciousBrains\WP_Offload_Media\Upgrades\Upgrade->do_upgrade, DeliciousBrains\WP_Offload_Media\Upgrades\Upgrade->run_upgrade, DeliciousBrains\WP_Offload_Media\Upgrades\Upgrade->upgrade_blog, DeliciousBrains\WP_Offload_Media\Upgrades\Upgrade_WPOS3_To_AS3CF->upgrade_item, wpdb->update, wpdb->print_error`

Even after deleting the key as3cf_tool_errors_uploader it still refuses to finish.
There are not Media items on this WP instance

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
