### ISSUE TITLE
Issue with filter_post_data & Advanced Custom Fields

### ISSUE THREAD

**Issue by thetoine** [deliciousbrains/wp-amazon-s3-and-cloudfront#558]
Hi,

We detected an issue with a certain type of ACF fields when used with _WP Offload Media Lite_.

### Quick intro 

ACF comes with a feature where you can set relation between a page/post (included CPT). A good exemple is a FAQ post type, I could create a WP page that include multiple "FAQ" through that relationship ACF field. Then on the page themplate, we loop each attached FAQ, where the filter "the_content" is applied for each linked posts.

### Issue

When _WP Offload Media Lite_ is activated, any nested post through relationship ACF field will herit the same _the_content_ filter from its "parent" page.

The exemple below is using Twig/Timber, but should have the same effect with regular PHP templates :

```twig
<h2>{{ page.title }}</h2>
{{ page.content }}

{% for faq in page.get_field("faqs") %}        
   <h2>{{ faq.title }}</h2>
   {# this FAQ content will display page.content and skipping its actual content #}
   {{ faq.content }}        
{% endfor %}
```

This is linked to the global $pages in the filter :

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/6096efe110a87358b1d6ed762a580cc7a1df0913/classes/filters/as3cf-local-to-s3.php#L64

The filter grabs the global $pages from the parent page when looping each ``` {{ faq.content }}```, resulting all FAQs content with the same parent page content.

Not sure how this could be fixed efficiently, we hot patched our production by removing the ```global $pages``` in ```as3cf-local-to-s3.php```.  ACF is a very popular plugin though and the filter should be compatible with that specific use case I think.

Best regards, thank you!

**Comment by ianmjones** [comment]
WP Offload Media has compatibility with ACF, WP Offload Media Lite does not.

**Comment by thetoine** [comment]
@ianmjones I actually bought the plugin after posting this issue, and I had the same issue with it.

**Comment by ianmjones** [comment]
@thetoine Great, please contact us with more details via the plugin's "Support" tab and we'll look into it with you.
