### ISSUE TITLE
AWS SDK reads outside of open_basedir paths

### ISSUE THREAD

**Issue by piscis** [deliciousbrains/wp-amazon-s3-and-cloudfront#559]
Hi, I think one of the BugFixs for 2.4.1 actually causes server logs to receive warnings when ever a user interacts with wp-offload (eg. uploads media / saves settings). 

**Changeset:** https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/commit/6096efe110a87358b1d6ed762a580cc7a1df0913#diff-f34d4fe7aaf53c38d45bd994bb40f605L216-L226

I think the reason is that the AWS SDK currently searches for a config file in the basedir + /.aws/config of the php process. If a  hoster turned basedir restrictions on it leads to the following error:

**Example error:**
```text
"PHP message: PHP Warning: is_readable(): open_basedir restriction in effect. File(/www/XXXXX/YYY/.aws/config) is not within the allowed path(s):
```

**Workaround:**
Adding this filter, disables the warnings caused by wp-offload + aws sdk.
Found a possible workaround in this issue: https://github.com/aws/aws-sdk-php/issues/1931#issuecomment-641698551

```php
// Workaround for: https://github.com/aws/aws-sdk-php/issues/1931#issuecomment-641698551
add_filter('as3cf_disable_aws_csm', function($disabled) {
  if($disabled) {
   putenv('AWS_CONFIG_FILE='.__DIR__.'/does_not_exist.ini');
  }
 return $disabled;
}, 10, 1);
```

**Comment by ianmjones** [comment]
Should be fixed in 2.4.2.
