### ISSUE TITLE
New function in 2.4 "set_url_scheme" randomly causes internal loop with Polylang Pro when site has different domains for different languages.

### ISSUE THREAD

**Issue by frcade** [deliciousbrains/wp-amazon-s3-and-cloudfront#561]
Following problem finally causes Memory exhaustion on first load (xdebug limit 256). Error after updating from 2.3.2 to 2.4.1. Polylang Pro version 2.7.3 (latest working with wp-amazon-s3-and-cloudfront 2.3.2)

5:24:21 PM web.1 |  [14-Aug-2020 14:24:21 UTC] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /Users/ahti/www/xxx/web/app/plugins/polylang-pro/include/functions.php:96
5:24:21 PM web.1 |  Stack trace:
5:24:21 PM web.1 |  #0 /Users/ahti/www/xxx/web/app/plugins/polylang-pro/include/links-abstract-domain.php(40): pll_get_requested_url()
5:24:21 PM web.1 |  #1 /Users/ahti/www/xxx/web/app/plugins/polylang-pro/include/links-abstract-domain.php(82): PLL_Links_Abstract_Domain->get_language_from_url()
5:24:21 PM web.1 |  #2 /Users/ahti/www/xxx/web/wp/wp-includes/class-wp-hook.php(287): PLL_Links_Abstract_Domain->upload_dir(Array)
5:24:21 PM web.1 |  #3 /Users/ahti/www/xxx/web/wp/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
5:24:21 PM web.1 |  #4 /Users/ahti/www/xxx/web/wp/wp-includes/functions.php(2306): apply_filters('upload_dir', Array)
5:24:21 PM web.1 |  #5 /Users/ahti/www/xxx/web/app/plugins/amazon-s3-and-cloudfront/classes/filters/as3cf-local-to-s3.php(142): wp_upload_dir()
5:24:21 PM web.1 |  #6 /Users/ahti/xxx/metsateollisuus2/web/app/plugins/amazon-s3-and-cloudfront/class in /Users/ahti/www/xxx/web/app/plugins/polylang-pro/include/functions.php on line 96

**Comment by ianmjones** [comment]
The description of the issue here doesn't directly match up with the given stack trace, however, from looking at the stack trace I think you may find that v2.4.2 fixes your issue.

If not, please give further details of the problem, such as why `set_url_scheme` is at the root of the problem, and also pass on anything you learned from Polylang when you raised the issue with them.
