### ISSUE TITLE
Still got Class 'DeliciousBrains\WP_Offload_Media\Aws3\Symfony\Polyfill\Intl\Idn\Idn' not found in 2.4.3

### ISSUE THREAD

**Issue by Boronare** [deliciousbrains/wp-amazon-s3-and-cloudfront#566]
the problem is as title.

I found namespace path is different to autoloader, so I changed code of aws-autoloader.php
'DeliciousBrains\\\\WP_Offload_Media\\\\Aws3\\\\Symfony\\\\Polyfill\\\\**IntlIdn**\\\\Idn' => \_\_DIR\_\_ . '/Symfony/Polyfill/IntlIdn/Idn.php'
to
'DeliciousBrains\\\\WP_Offload_Media\\\\Aws3\\\\Symfony\\\\Polyfill\\\\**Intl\\\\Idn**\\\\Idn' => \_\_DIR\_\_ . '/Symfony/Polyfill/IntlIdn/Idn.php'
and others like that so.

and it works.
+I got Normalizer not found error, so I installed php7.2-intl.

**Comment by ianmjones** [comment]
Fixed in 2.4.4.
