### ISSUE TITLE
GCP Storage URLs safety warnings in Chrome

### ISSUE THREAD

**Issue by lars190090** [deliciousbrains/wp-amazon-s3-and-cloudfront#567]
Chrome has an experimental flag "Navigation Suggestions for Lookalike URLs" which is set to ENABLE by default with version 84.x.x.

**GCP Storage URLs will trigger the safety warning:**
_Did you mean example.com?
The site you just tried to visit looks fake. Attackers sometimes mimic sites by making small, hard-to-see changes to the URL._

This will happen if the storage bucket is named similarly to the domain name of the host.

**URL that triggers the warning:**
https://example-com.storage.googleapis.com/wp-content/uploads/2020/09/example.jpg

**URL that does not trigger the warning:**
https://storage.googleapis.com/example-com/wp-content/uploads/2020/09/example.jpg

**Comment by ianmjones** [comment]
This is not something we can avoid in WP Offload Media. Best bet is to use a custom domain.

https://deliciousbrains.com/wp-offload-media/doc/how-to-set-up-a-custom-domain-cdn-for-google-cloud-storage/
