### ISSUE TITLE
.Gifs not being offloaded to s3

### ISSUE THREAD

**Issue by Sparlix** [deliciousbrains/wp-amazon-s3-and-cloudfront#568]
hello, it seems gifs are not being offloaded to my s3. I tested this a few updates back and it worked and seems to not work now. 

site_url(): hidden
home_url(): hidden
Database Name: hidden
Table Prefix: wp_
WordPress: 5.5.1
Web Server: Apache
PHP: 7.4.10
MySQL: 5.7.29
ext/mysqli: yes
PHP Memory Limit: 512M
WP Memory Limit: 40M
Memory Usage: 2 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 50 MB
PHP Time Limit: 3600
PHP Error Log: /var/log/apache2/hidden.error.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1  11 Sep 2018
cURL: 7.58.0
Zlib Compression: Enabled
PHP GD: 2.2.5
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 1,048
Offloaded Media Files: 1,043
Not Offloaded Media Files: 5

Number of Image Sizes: 6

Names and Dimensions of Image Sizes: 
thumbnail (600x600)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)

WP_CONTENT_DIR: /nas/content/live/hidden/wp-content
WP_CONTENT_URL: https://hidden.wpengine.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /nas/content/live/hidden/wp-content/plugins
WP_PLUGIN_URL: https://hidden.wpengine.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Defined
AS3CF_SETTINGS Keys: access-key-id, provider, secret-access-key

Local URL:
https://hidden.wpengine.com/wp‑content/uploads/2020/09/photo.jpg
Offload URL:
https://cdn.hidden.com/wordpress/2020/09/24161517/photo.jpg

OME Metadata Version: 8

Storage Provider: Amazon S3
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: hidden-cdn
Region: (empty)
Block All Public Access: Disabled

Copy Files to Bucket: On
Enable Path: On
Custom Path: wordpress/
Use Year/Month: On
Object Versioning: On

Delivery Provider: Cloudflare
Rewrite Media URLs: On
Enable Custom Domain (CNAME): On
Custom Domain (CNAME): cdn.hidden.com

Force HTTPS: On

Remove Files From Server: On

Active Theme Name: 
Active Theme Version: 
Active Theme Folder: hidden

Active Plugins:
All-in-One WP Migration (v7.27) by ServMask
All-in-One WP Migration Unlimited Extension (v2.37) by ServMask
Application Passwords (v0.1.2) by George Stephanis
Classic Editor (v1.6) by WordPress Contributors
EWWW Image Optimizer (v5.7.0) by Exactly WWW
List category posts (v0.83.1) by Fernando Briano
LuckyWP Table of Contents (v2.1.4) by LuckyWP
Mammoth .docx converter (v1.16.0) by Michael Williamson
Ninja Forms (v3.4.27) by Saturday Drive
Ninja Forms - File Uploads (v3.3.7) by The WP Ninjas
Ninja Forms - Google Spreadsheet (v3.4) by Webholics
Page-list (v5.2) by webvitaly
WP Offload Media Lite (v2.4.4) by Delicious Brains
Yoast SEO Premium (v14.9) by Team Yoast

Must-use Plugins:
Force Strong Passwords - WPE Edition (v1.6.4) by Jason Cosper
WP Engine Seamless Login Plugin (v1.5.5) by WP Engine
WP Engine Security Auditor (v1.0.9) by wpengine
WP Engine System (v4.0.0) by WP Engine
password-protected.php

Drop-ins:
advanced-cache.php - advanced-cache.php
object-cache.php - Memcached Redux

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
