### ISSUE TITLE
Cannot access EC2 metadata from ECS

### ISSUE THREAD

**Issue by mims92** [deliciousbrains/wp-amazon-s3-and-cloudfront#569]
Hello,

I am using the latest version of Offload Media Lite on:
- Wordpress 5.5.1
- PHP 7.3.23

Wordpress is running on ECS (non Fargate).
The wp-config.php configuration looks like this:
```
define('AS3CF_AWS_USE_EC2_IAM_ROLE', true);
define('WPOS3_SETTINGS', serialize([
    'bucket' => '°BUCKET_NAME°',
    'region' => '°AWS_REGION°',
    'copy-to-s3' => true,
    'serve-from-s3' => false,
    'enable-object-prefix' => true,
    'object-prefix' => 'wp-content/uploads/',
    'use-yearmonth-folders' => true,
    'remove-local-file' => true,
    'domain' => 'cloudfront',
    'cloudfront' => '°CLOUDFRONT_URL°',
    'object-versioning' => false
]));
```

The issue is:

```
There was an error attempting to check the permissions of the bucket BUCKET: Error retrieving credentials from the instance profile metadata service. (cURL error 28: Operation timed out after 1001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html))
```

When connecting directly in the container, a curl call to the instance metadata works perfectly.

**Comment by eremitis** [comment]
Same problem here. In AWS calls from docker container to http://169.254.169.254/latest/api/token endpoint are not allowed due default settings of IMDSv2 policy.

Unfortunately WP Offload Media Lite plugin doesn't handle that situation well and I believe because of a bug doesn't gracefully switch to IMDSv1. I think there is a typo in https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/master/vendor/Aws3/Aws/Credentials/InstanceProfileProvider.php#L143, I think that line should be changed to
```
            if ($reason instanceof RequestException) {
                throw $reason;
            }
```

**Comment by ianmjones** [comment]
@eremitis Thanks!

While your fix isn't quite right (not correctly namespaced), you have pointed out a potential problem in our automatic namespacing of the embedded AWS PHP SDK.

It's too late for us to do anything about this for the next release, but I'll see if we can investigate and fix this for a follow-on release.

**Comment by eremitis** [comment]
Thanks @ianmjones , I'm looking forward for the proper fix.

As a temporary solution, for people that experiencing that issue, I suggest to downgrade to 2.3.2 version if possible. On that version you shouldn't have that problem.

**Comment by mims92** [comment]
Thanks for the piece of advice :) I have used IAM credentials as a workaround but will look at downgrading the library!

Looking forward the fix ;)

**Comment by ianmjones** [comment]
Should have been fixed quite a while ago, certainly by https://deliciousbrains.com/wp-offload-media/whats-new/#dec-14-2020

If not, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
