### ISSUE TITLE
Not able to stop offloading specific file type to S3

### ISSUE THREAD

**Issue by RajeevRF** [deliciousbrains/wp-amazon-s3-and-cloudfront#571]
Hi,
I am using this plugin on my website to offload the uploads to S3. I don’t want CSV files alone offloaded to S3. I want all other file types to be offloaded to S3. I went through a few support threads(https://wordpress.org/support/topic/feature-questions-9/) and found the below code to do this job. But when I use this code, all types of files are uploaded to the UPLOADS folder. But it is supposed to do this only for CSV file types.

`function pre_upload_attachment( $abort, $post_id, $metadata ) {
		// Example stops csv from being offloaded.
		$file      = get_post_meta( $post_id, '_wp_attached_file', true );
		$extension = is_string( $file ) ? pathinfo( $file, PATHINFO_EXTENSION ) : false;
		if ( is_string( $extension ) && in_array( $extension, array( 'csv' ) ) ) {
			$abort = true; // abort the upload
		}

		// Example helps bulk offload tool on severely resource restricted shared hosting.
		// WARNING: Do not uncomment the following code unless you're on shared hosting and getting "too many open files" errors
		// as <code>gc_collect_cycles()</code> could potentially impact performance of the bulk offload and WordPress.
		/*
		if ( false === $abort ) {
			gc_collect_cycles();
		}
		*/

		return $abort;
	}
	
add_filter( 'as3cf_pre_upload_attachment', array( $this, 'pre_upload_attachment' ), 10, 3 );`

I also tried the “as3cf_allowed_mime_types” function as well. But the same result.

These functions are disabling the offload option for all filetypes irrespective of what we provide in the code.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
