### ISSUE TITLE
Cannot access Settings page

### ISSUE THREAD

**Issue by anteksiler** [deliciousbrains/wp-amazon-s3-and-cloudfront#572]
We are using Offload S3 plugin (v1.4.4) on 1 corporate client (https://www.premiumbeat.com/blog) which stopped working suddenly.

We tried changing to Offload Media Lite, it can be activated, but the Settings page won’t open, resulting in 503 error page. It just times out without any issues.

We are thinking of upgrading to Pro, but can not test if Offload Media Lite is working first.

There are 32k media files that are already on AWS, and the uploads are not working since the last week. 

AWS keys are verified.

Best,

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
