### ISSUE TITLE
Images disappeared after turning "Rewrite Media URl " setting on.

### ISSUE THREAD

**Issue by uc-sja** [deliciousbrains/wp-amazon-s3-and-cloudfront#575]
There is a very critical issue that I am facing. 

I had successfully offloaded all my images to s3 bucket and my future posts are also being offloaded with the help of WP Offlite Media Lite plugin. The settings were : https://prnt.sc/wnxi6a

Everything seemed to be working fine.
But as recommended by WP Offlite Media Lite,  I used the eWWW plugin to compress my images in the s3 bucket. But it not working and showing error. After thorough discussion with eWWW they are recommending me to switch on the "Rewrite Media URLs" setting on in the WP Offlite Media Lite settings.

But turning that on resulted in almost 50% of the images from my whole website getting disappeared. Even after I switched back off, the images. have not been restored.

This is a very critical issue. The eWWW team has asked to contact WP Offlite Media Lite in finding out why this is happenning. My website is dev.mishry.com

Since the issue is very critical to me and I need my problem to be resolved as soon as possible.

Please look into the issue with utmost priority.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
