### ISSUE TITLE
ACF Pro + WP Offload Media Pro = Slow

### ISSUE THREAD

**Issue by bare-david** [deliciousbrains/wp-amazon-s3-and-cloudfront#577]
Hi there,

I have narrowed down an issue when using ACF Pro image fields with WP Offload Media Pro. We are using version 2.5.2 of WP Offload Media Pro, and ACF Pro 5.9.2. For some reason, the file size of the images isn't being saved to the metadata when it is uploaded, which causes a massive performance hit on this block in ACF:

includes/api/api-helpers.php:3154
```
	if( isset($meta['filesize']) ) {
		$response['filesize'] = $meta['filesize'];
	} elseif( file_exists($attached_file) ) { <--- This block
		$response['filesize'] = filesize( $attached_file );
	}
```

What this block does is check to see if the `filesize` key of the metdata exists, if it doesn't it tries to fetch the image (which is using an `s3apsoutheast2://{bucket}/{path}/{filename}.jpg` format URL) and get its size. This takes quite a few seconds and has ground our website to a halt.

I've tried using the "add metadata tool" by enabling `define( 'AS3CF_SHOW_ADD_METADATA_TOOL', true );`, but this has had no effect.

**Comment by ianmjones** [comment]
Please submit a support request through WP Offload Media's "Support" tab if you haven't already, and we'll look into it with you.
