### ISSUE TITLE
 fopen(https://nocomp......./12/cat2-3-100x100.png): failed to open stream: HTTP wrapper does not support writeable connections in /var/www/vhosts/nocompre.com/httpdocs/demo2/wp-includes/class-wp-image-editor.php on line 494 on uploading images programattically

### ISSUE THREAD

**Issue by hvignesh18197** [deliciousbrains/wp-amazon-s3-and-cloudfront#578]
fopen(https://nocompre.com/wp-content/uploads/2015/12/cat2-3-100x100.png): failed to open stream: HTTP wrapper does not support writeable connections in /var/www/vhosts/nocompre.com/httpdocs/demo2/wp-includes/class-wp-image-editor.php on line 494 
 
 This was logged when uploading images programmatically use offload media plugin

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
