### ISSUE TITLE
srcset not working for scaled and edited images

### ISSUE THREAD

**Issue by lee-peuker** [deliciousbrains/wp-amazon-s3-and-cloudfront#579]
Hey guys,

images, which are saved scaled or edited, will create an entry in the wp_as3cf_items table with a `-scaled` or `-eUNIXTIMESAMP` suffix in the "path" column. 
Every image which has such a suffix will not get a "srcset" in the frontend anymore, because the filename with the suffix is not matching the original filename anymore (see the `wp_calculate_image_srcset_meta` filter in the `as3cf-plugin-compatibility.php`, line 865).

I can recreate this behaviour/bug in an fresh wordpress installation.

------

Example: 

Post content:
```
<img src="https://cdn.XXX.org/img/pretty-big-test-image-225x300.jpg" alt="" width="225" height="300" class="alignnone size-medium wp-image-26" />
```

Rendered content in api response:
```
"<p><img loading=\"lazy\" src=\"https://cdn.XXX.org/img/pretty-big-test-image-225x300.jpg\" alt=\"\" width=\"225\" height=\"300\" class=\"alignnone size-medium wp-image-26\" /></p>\n"
```

Path of image in `wp_as3cf_items`: `img/pretty-big-test-image-scaled.jpg`

If I upload the same image in smaller, the path value in `wp_as3cf_items` will have the same filename as the original and srcset attribute will exist in the rendered content.

**Comment by alexander-schneider** [comment]
@ianmjones do you have an answer for us?

**Comment by ianmjones** [comment]
Please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
