### ISSUE TITLE
Table columns missing in plugin update from v2.4.4 to v2.5.3

### ISSUE THREAD

**Issue by RobWiddick** [deliciousbrains/wp-amazon-s3-and-cloudfront#580]
We have a client who updated their WP Offload Media Lite plugin from 2.4.4 to 2.5.3. When this update completed, the offload stopped working. After digging into the debug, we've discovered that somewhere during the update, there were two table columns that were not added to the `wp_as3cf_items` table: `is_verified` and `originator`.

When I added these columns (`tinyint(1)` and `varchar(255)`, respectively), the S3 offloads after uploads started working again and debug errors stopped getting logged.

Example debug log errors:

1. WordPress database error Unknown column 'originator' in 'field list' for query INSERT INTO `wp_as3cf_items` [truncated]
2. WordPress database error Unknown column 'is_verified' in 'field list' for query INSERT INTO `wp_as3cf_items` [truncated]

**Comment by ianmjones** [comment]
Thanks, not seen anyone else have this issue, so likely a blip during the upgrade.

If we see anyone else raise the same problem via https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or a support request raised via the "Support" tab in the plugin, we'll take a closer look.

**Comment by montchr** [comment]
I can also confirm encountering this issue.  In my case, it affected the database for a multisite instance that had been stuck on an old version of the plugin until recently.

The significant result is that these columns seem to be necessary for following the process described in the documentation article "[Add Metadata Tool: For When Your Media is Already in a Bucket](https://deliciousbrains.com/wp-offload-media/doc/add-metadata-tool/)".  I was not able to use that feature until adding the columns to the database.  

I also should note that the schema is slightly different from the description in the original comment.  I made a fresh WordPress installation with the latest version of the plugin to compare.  These SQL queries worked for my case:

```sql
ALTER TABLE `wp_as3cf_items` ADD `originator` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' AFTER `extra_info`;
ALTER TABLE `wp_as3cf_items` ADD `is_verified` TINYINT(1) NOT NULL DEFAULT '1' AFTER `originator`;
```
