### ISSUE TITLE
S3 bucket images dissapeared suddenly

### ISSUE THREAD

**Issue by maruf-cefalo** [deliciousbrains/wp-amazon-s3-and-cloudfront#581]
I have used this plugin for many years, suddenly all of my images in s3 buckets seem to be gone. Any scripts that can do this from your plugin?

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
