### ISSUE TITLE
Extra files not deleted when using the Regenerate Thumbnails plugin

### ISSUE THREAD

**Issue by incentfit** [deliciousbrains/wp-amazon-s3-and-cloudfront#582]
The [Regenerate Thumbnails plugin](https://wordpress.org/plugins/regenerate-thumbnails/) is supposed to work.  That plugin has a checkbox to "Delete thumbnail files for old unregistered sizes in order to free up server space."  Clicking that button does not delete unregistered sizes in S3.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
