### ISSUE TITLE
Updating from 1.2 to 1.x fatal error cant find class

### ISSUE THREAD

**Issue by mrhn** [deliciousbrains/wp-amazon-s3-and-cloudfront#583]
Get the following error when upgrading an old wp site.

PHP 7.0.17
WP 4.7

Class 'AS3CF_Plugin_Base' not found amazon-s3-and-cloudfront.php on line 31

Have another package that require AWS 3.x or higher that seems to be the conflict and the reasoning for upgrading offload.

Forums etc. seems very sparse on this error, would be nice if anyone could guide me in the right direction.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
