### ISSUE TITLE
Warning Block All Public Access is Enabled Still Visible even with CloudFront as Delivery

### ISSUE THREAD

**Issue by JulienHe** [deliciousbrains/wp-amazon-s3-and-cloudfront#585]
### What?
The Warning message is still visible even tho I already setup Cloudfront in the admin
![CleanShot 2021-06-27 at 22 15 02@2x](https://user-images.githubusercontent.com/718868/123569867-240f1800-d795-11eb-9b1b-47fe2a8114ab.jpg)

![CleanShot 2021-06-27 at 22 16 52@2x](https://user-images.githubusercontent.com/718868/123570065-7cdeb080-d795-11eb-91e4-867d8e66708f.jpg)

#### Diagnostic Info
```
site_url(): https://webapi.itsnemesis.com
home_url(): https://webapi.itsnemesis.com
Database Name: webapinemesis
Table Prefix: wp_
WordPress: 5.7.2
Web Server: Apache/2.4.41 (Ubuntu)
PHP: 7.4.3
MySQL: 8.0.23
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 40M
Memory Usage: 2 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Disabled
WP_DEBUG: Yes
WP_DEBUG_LOG: Yes
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 16 MB
PHP Time Limit: 30
PHP Error Log: /var/www/webapi.itsnemesis.com/wp-content/debug.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
cURL: 7.68.0
Zlib Compression: Enabled
PHP GD: Disabled
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 2
Offloaded Media Files: 0
Not Offloaded Media Files: 2

Number of Image Sizes: 7

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
post-thumbnail (none)

WP_CONTENT_DIR: /var/www/webapi.itsnemesis.com/wp-content
WP_CONTENT_URL: https://webapi.itsnemesis.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/webapi.itsnemesis.com/wp-content/plugins
WP_PLUGIN_URL: https://webapi.itsnemesis.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://webapi.itsnemesis.com/wp-content/uploads/photo.jpg
Offload URL:
https://static.itsnemesis.com/20210628021753/photo.jpg

OME Metadata Version: 8

Custom tables:
wp_as3cf_items: Ok

Storage Provider: Amazon S3
Use Server Roles: On
Key File Path: N/A
Access Keys Set: No
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: nemesiswebapi
Region: eu-west-1
Block All Public Access: Enabled

Copy Files to Bucket: On
Enable Path: Off
Custom Path: (none)
Use Year/Month: Off
Object Versioning: On

Delivery Provider: Amazon CloudFront
Rewrite Media URLs: On
Enable Custom Domain (CNAME): On
Custom Domain (CNAME): static.itsnemesis.com

Force HTTPS: On

Remove Files From Server: Off

Active Theme Name: Twenty Twenty-One
Active Theme Version: 1.3
Active Theme Folder: twentytwentyone

Active Plugins:
Advanced Custom Fields PRO (v5.9.7) by Delicious Brains
SVG Support (v2.3.18) by Benbodhi
WP GraphQL (v1.4.3) by WPGraphQL
WP Offload Media Lite (v2.5.3) by Delicious Brains
```

### Issue
I followed the steps that are visible [here](https://deliciousbrains.com/wp-offload-media/doc/cloudfront-setup/) I double check to make sure everything was setup right but seems like the warning is still there, on top of that the upload is not even happening. I also debug the wordpress installation but nothing seems to be visible and no error on the EC2 instance either.

##### IAM Role
![CleanShot 2021-06-27 at 22 23 58@2x](https://user-images.githubusercontent.com/718868/123570567-7ac92180-d796-11eb-9770-916bc1e608ff.jpg)

##### S3 Policy
![screencapture-s3-console-aws-amazon-s3-buckets-nemesiswebapi-2021-06-27-22_27_12](https://user-images.githubusercontent.com/718868/123570856-10fd4780-d797-11eb-8409-bd378e584db5.png)

##### Cloudfront
![CleanShot 2021-06-27 at 22 29 42@2x](https://user-images.githubusercontent.com/718868/123570956-3ee28c00-d797-11eb-9ca0-378efb23f18f.jpg)
![CleanShot 2021-06-27 at 22 31 35@2x](https://user-images.githubusercontent.com/718868/123571092-7fdaa080-d797-11eb-8d75-ee1deef1deed.jpg)

Did I miss something?

**Comment by ianmjones** [comment]
That's a strange one!

However, the Bucket Policy looks weird, it's missing its "Principal" details.

https://deliciousbrains.com/wp-offload-media/doc/cloudfront-setup/#block-public-access

Might be worth making sure that "Grant Read Permissions on Bucket" entry when editing the CloudFront Origin is still set to "Yes, Update Bucket Policy", and then saving the Origin again. That might fix up the policy.

Otherwise, for support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
