### ISSUE TITLE
After uploading media files S3 Url's not generationg.

### ISSUE THREAD

**Issue by purnima-python** [deliciousbrains/wp-amazon-s3-and-cloudfront#586]
<img width="698" alt="Screen Shot 2021-06-28 at 12 27 54 PM" src="https://user-images.githubusercontent.com/64583417/123593587-4e4fec80-d80c-11eb-8c8d-c15f1c67440c.png">
<img width="338" alt="Screen Shot 2021-06-28 at 12 28 53 PM" src="https://user-images.githubusercontent.com/64583417/123593698-73dcf600-d80c-11eb-9492-1b25e57bdc77.png">
I have installed the WP Offload S3 Lite for my wordpress site to coply the images to s3 bucket but unfortunately it stop generating the s3 url. Its picking the local urls.
Attached the screenshots for the same.
Can you please help me out because I could not able to find the logs as well?

Regards,
Purnima Singh

**Comment by ianmjones** [comment]
For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
