### ISSUE TITLE
Bug: Multiple DB queries firing when using plugins causing large perormance hit

### ISSUE THREAD

**Issue by Zxurian** [deliciousbrains/wp-amazon-s3-and-cloudfront#589]
**Describe the bug**
WP Offload Media Lite v2.5.5
Multiple Duplicate DB Query calls being made by plugin, exponentially increasing site load time / memory. We had a page with a larger than usual number of images attached via ACF Pro. The page originally was returning a 500 error due to memory requirements. After increasing the amount of memory, page finally loaded, so tried to isolate what would cause this specific post to require so much more, and nothing out of ordinary except a few more images attached via ACF Pro.

Using Query Monitor, identified a long list of duplicate queries
![image](https://user-images.githubusercontent.com/573371/136091533-692b67bd-53c1-4855-a818-c392cdee3bab.png)

You can see the scroll bar on the right to get an indication of how many duplicate queries there were, as well as the amount of times they were being called (184 for some?)

After disabling WP Offload Media Lite, page load time was miniscule (option to leave files locally checked), so for now I'm going to have to disable it until this can be resolved, as with each new image attached, it seems to be making 

**To Reproduce**
Enable WPOML, multiple duplicate queries being fired, page is slow to load.

**Expected behavior**
single query per request, results stored and then used instead of firing multiple duplicate queries.

**Screenshots**
See above in description

**debug.log**
none - can attempt to capture specific if necessary.

**Diagnostic Info (from plugin's "Support" tab):**
```
site_url(): https://unikavaev.com
home_url(): https://unikavaev.com
Database Name: wordpress
Table Prefix: wp_
WordPress: 5.8.1
Web Server: Apache/2.4.46 (codeit) OpenSSL/1.1.1k PHP/7.2.34
PHP: 7.2.34
MySQL: 5.7.33
ext/mysqli: yes
PHP Memory Limit: 2G
WP Memory Limit: 40M
Memory Usage: 2 MB
Blocked External HTTP Requests: None
WP Locale: en_US
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 30 MB
PHP Time Limit: 30
PHP Error Log: /var/log/php-fpm/www-error.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.0.2k  26 Jan 2017
cURL: 7.29.0
Zlib Compression: Enabled
PHP GD: Disabled
Imagick: Disabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 12,314
Offloaded Media Files: 1,305
Not Offloaded Media Files: 11,009

Number of Image Sizes: 13

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
hero (1280x700)
category-hero (1280x320)
home-thumbnail (625x236)
news-thumbnail (411x274)
product-thumbnail (200x200)
colorway-thumbnail (200x200)
home-page-carousel (839x783)

WP_CONTENT_DIR: /var/www/unikavaev.com/html/wp-content
WP_CONTENT_URL: https://unikavaev.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/unikavaev.com/html/wp-content/plugins
WP_PLUGIN_URL: https://unikavaev.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://unikavaev.com/wp‑content/uploads/2021/10/photo.jpg
Offload URL:
https://content.unikavaev.com/wp‑content/uploads/2021/10/05193100/photo.jpg

OME Metadata Version: 8

Custom tables:
wp_as3cf_items: Ok

Storage Provider: Amazon S3
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: DBI_AWS_ACCESS_KEY_ID
Secret Access Key Define: DBI_AWS_SECRET_ACCESS_KEY

Bucket: unikavaev-com
Region: (empty)
Block All Public Access: Disabled

Copy Files to Bucket: On
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Delivery Provider: Other
Rewrite Media URLs: On
Enable Custom Domain (CNAME): On
Custom Domain (CNAME): content.unikavaev.com

Force HTTPS: On

Remove Files From Server: Off

Active Theme Name: Unikavaev
Active Theme Version: 2.0
Active Theme Folder: unikavaev-wp-theme

Active Plugins:
ACF: Better Search (v4.0.0) by Mateusz Gbiorczyk
Advanced Custom Fields PRO (v5.10.2) by Delicious Brains
Async JavaScript (v2.21.08.31) by Frank Goossens (futtta)
Category Order and Taxonomy Terms Order (v1.5.7.7) by Nsp-Code
Classic Editor (v1.6.2) by WordPress Contributors
Contact Form 7 (v5.4.2) by Takayuki Miyoshi
Custom Post Type Permalinks (v3.4.5) by Toro_Unit
Disable Author Pages (v1.1.0) by LittleBizzy
Disable Comments (v2.2.2) by WPDeveloper
Enable Media Replace (v3.5.0) by ShortPixel
Google Analytics Dashboard for WP (GADWP) (v7.1.0) by ExactMetrics
ICF Group (v1.2) by rgoodrow
Kraken Image Optimizer (v2.6.5) by Karim Salman
LiveChat (v4.4.10) by LiveChat
Query Monitor (v3.7.1) by John Blackbourn
Redirection (v5.1.3) by John Godley
Regenerate Thumbnails (v3.1.5) by Alex Mills (Viper007Bond)
SVG Support (v2.3.19) by Benbodhi
WP Activity Log (v4.3.2) by WP White Security
WP File Download (v5.1.3) by Joomunited
WP Offload Media Lite (v2.5.5) by Delicious Brains
WP Offload SES Lite (v1.4.6) by Delicious Brains
WP Rollback (v1.7.1) by Impress.org
WP Session Manager (v4.2.0) by Eric Mann
WP-SCSS (v2.3.5) by Connect Think
WordPress Importer (v0.7) by wordpressdotorg
Yoast Duplicate Post (v4.1.2) by Enrico Battocchi & Team Yoast
Yoast SEO (v17.3) by Team Yoast


Drop-ins:
advanced-cache.php - advanced-cache.php
db.php - Query Monitor Database Class

```

**Additional context**

**Comment by ianmjones** [comment]
@Zxurian Thanks for the bug report.

There's a couple of potential issues here ...

1. WP Offload Media Lite does not support ACF, but WP Offload Media does. As such, there's a very good chance the issues you're seeing would be solved by upgrading to WP Offload Media. However, at present WP Offload Media officially supports ACF rather than ACF Pro, there may be a feature of ACF Pro you're using that OME might still trip up on. We have it on our todo list to review ACF and ACF Pro support in WP Offload Media now that Delicious Brains owns ACF, I'll also pass on your feature request that Lite should support ACF too.
2. When we see multiple SQL hits for the same Media Library item it usually suggest that there's an issue with the site's object cache config as normally the first hit's result gets stuffed into the cache and used from there onwards, never hitting the db again.
