### ISSUE TITLE
Bug: Website don't upload a homepage when I enable - Rewrite Media URLs button pls check

### ISSUE THREAD

**Issue by rememberkz** [deliciousbrains/wp-amazon-s3-and-cloudfront#590]
site_url(): https://chilys.club
home_url(): https://chilys.club
Database Name: wp590
Table Prefix: wpfa_
WordPress: 5.8.1
Web Server: Apache/2.4.6 () OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.4.16
PHP: 7.3.30
MySQL: 5.5.68
ext/mysqli: yes
PHP Memory Limit: 1024M
WP Memory Limit: 1024M
Memory Usage: 24 МБ
Blocked External HTTP Requests: None
WP Locale: ru_RU
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 1 ГБ
PHP Time Limit: 60
PHP Error Log: 
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1d  10 Sep 2019
cURL: 7.71.0
Zlib Compression: Enabled
PHP GD: bundled (2.1.0 compatible)
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Media Files: 480
Offloaded Media Files: 33
Not Offloaded Media Files: 447

Number of Image Sizes: 26

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
img-1100-450 (1100x450)
img-1120-800 (1120x800)
img-870-440 (870x440)
img-850-600 (850x600)
img-480-380 (480x380)
img-300-225 (300x225)
img-75-75 (75x75)
img-840-400 (840x400)
img-270-283 (270x283)
img-270-180 (270x180)
img-270-153 (270x153)
img-129-129 (129x129)
img-122-120 (122x120)
img-69-69 (69x69)
img-63-50 (63x50)
img-50-56 (50x56)
img-1170-500 (1170x500)
img-840-430 (840x430)
img-770-300 (770x300)
img-370-193 (370x193)

WP_CONTENT_DIR: /var/www/user353402/data/www/chilys.club/wp-content
WP_CONTENT_URL: https://chilys.club/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/user353402/data/www/chilys.club/wp-content/plugins
WP_PLUGIN_URL: https://chilys.club/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Not defined

Local URL:
https://chilys.club/wp‑content/uploads/2021/10/photo.jpg
Offload URL:
https://chilys.s3.us‑east‑2.amazonaws.com/wp‑content/uploads/2021/10/09123726/photo.jpg

OME Metadata Version: 8

Custom tables:
wpfa_as3cf_items: Ok

Storage Provider: Amazon S3
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: AS3CF_AWS_ACCESS_KEY_ID
Secret Access Key Define: AS3CF_AWS_SECRET_ACCESS_KEY

Bucket: chilys
Region: us-east-2
Block All Public Access: Disabled

Copy Files to Bucket: On
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: On
Object Versioning: On

Delivery Provider: Amazon S3
Rewrite Media URLs: On

Force HTTPS: Off

Remove Files From Server: On

Active Theme Name: MasterStudy
Active Theme Version: 4.3.8
Active Theme Folder: masterstudy

Active Plugins:
AddToAny Share Buttons (v1.7.44) by СоцЗакладки
Breadcrumb NavXT (v6.6.0) by John Havlik
Contact Form 7 (v5.4) by Takayuki Miyoshi
Creative Mail by Constant Contact (v1.3.5) by Constant Contact
Loco Translate (v2.5.1) by Тим Уитлок (Tim Whitlock)
MasterStudy LMS - плагин для курсов WordPress (v2.6.7) by StylemixThemes
MasterStudy LMS Learning Management System API (v1.1.4) by StylemixThemes
PHP Settings (v1.0.6) by Askupa Software
Paid Memberships Pro (v2.6.1.1) by Stranger Studios
Post SMTP (v2.0.22) by Yehuda Hassine
STM Configurations (v4.2.9) by StylemixThemes
Slider Revolution (v6.4.6) by ThemePunch
WP Content Copy Protection & No Right Click (v3.4.1) by wp-buy
WP Offload Media Lite (v2.5.5) by Delicious Brains
WPBakery Page Builder (v6.6.0) by Michael M - WPBakery.com
Система управления обучением MasterStudy LMS PRO (v3.6.0) by StylemixThemes

Drop-ins:
advanced-cache.php - advanced-cache.php

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
