### ISSUE TITLE
Bug: wp_as3cf_items created even before WP installation started

### ISSUE THREAD

**Issue by furai** [deliciousbrains/wp-amazon-s3-and-cloudfront#592]
**Describe the bug**
`wp_as3cf_items` created even before WP installation started

**To Reproduce**
1. Go to clean wordpress without before installation.
2. Refresh install page.
3. Check database.
4. `wp_as3cf_items` table got created and no other tables are there.

**Expected behavior**
Table shouldn't get created before installation.

**Comment by ianmjones** [comment]
@furai not sure I fully understand what you're seeing here. To clarify, is this what you've done ...

1. Created new database.
2. Installed clean version of WP using that new database.
3. Installed WP Offload Media, but did not activate it.
4. Saw `wp_as3cf_items` table created even though WP Offload Media has not ever been activated yet?

Or, did you did something else?

From your description it sounds like you have the `wp_as3cf_items` table in the database but none of the usual tables such as `wp_posts`, `wp_options` etc. Is that what you're saying?

**Comment by furai** [comment]
I have only added credentials to the database via wp-config.php. Didn't trigger install itself, only visited it and for whatever reason an empty table `wp_as3cf_items` was created. If you can't reproduce feel free to close, it's not like something breaking. Maybe something that happened once for whatever reason on my setup and won't ever happen again. I just feel that there shouldn't be any table created until I actually install the wordpress itself.

**Comment by ianmjones** [comment]
Ok, if you're able to reproduce please let us know the steps to reproduce and we'll re-open.
