### ISSUE TITLE
Bug: Offloads not working. Stuck at "This item has not been offloaded yet". How to force offloads?

### ISSUE THREAD

**Issue by Danrancan** [deliciousbrains/wp-amazon-s3-and-cloudfront#594]
**Describe the bug**
After configuring the wp amazon offload plugin giving full administrative access to my S3 drive, the uploaded wordpress media files DO NOT offload when uploading a media file to wordpress.

**To Reproduce**
1. Upload any media (.mp4 .mov .webP etc.) file to your wordpress installation under the media directory.
2. Click on the media file.
3. Scroll down to the bottom right of the page where the "Offload" box appears.
4. See error "This item has not been offloaded yet." no matter how long you wait after the media file has been uploaded to wordpress. 

QUESTION: Are the offloads supposed to take place automatically? I am assuming so, and that the offloads are not properly working.

**Expected behavior**
I expect to see my file in my S3 Bucket, and the Offload plugin to indicate that the media file has been properly offloaded.

**Screenshots**
<img width="288" alt="WP Offload Plugin — This item has not been offloaded yet  Stuck  WordPress 2022-01-03 22-23-19" src="https://user-images.githubusercontent.com/30222551/148009676-301976bb-4bc4-4195-aca2-54f05939015d.png">

**debug.log**
```
[04-Jan-2022 04:52:38 UTC] AS3CF: Error offloading /var/www/mcmo.is/wp-content/uploads/2022/01/www.McMo_.is-landing-page-video-background-UHD-30fps-Shortented.m4v to provider: Error executing "PutObject" on "https://myvideostorage-s3-bucket.s3.us-east-2.amazonaws.com/wp-content/uploads/2022/01/03225237/www.McMo_.is-landing-page-video-background-UHD-30fps-Shortented.m4v"; AWS HTTP error: Client error: `PUT https://myvideostorage-s3-bucket.s3.us-east-2.amazonaws.com/wp-content/uploads/2022/01/03225237/www.McMo_.is-landing-page-video-background-UHD-30fps-Shortented.m4v` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessControlListNotSupported</Code><Message>The bucket does not all (truncated...)
 AccessControlListNotSupported (client): The bucket does not allow ACLs - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessControlListNotSupported</Code><Message>The bucket does not allow ACLs</Message><RequestId>3GMWC852C208YTJ9</RequestId><HostId>43tODY4U6d5OPazlRY8VoGBLPoJXx0zrLB64vJlssn+xSzOjqYsXXLwlTpgSg7pOjjAEZjV7ITs=</HostId></Error>
```

https://deliciousbrains.com/why-use-wp-debug-log-wordpress-development/

**Diagnostic Info (from plugin's "Support" tab):**
[www.mcmo_.is-diagnostic-log-20220104033812.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/7805323/www.mcmo_.is-diagnostic-log-20220104033812.txt)

**Additional context**
Please help me solve this error so I can offload properly. Thank you!

**Comment by ianmjones** [comment]
See https://wordpress.org/support/topic/files-not-uploading-to-s3/#post-15235089
