### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by marcoriosp** [deliciousbrains/wp-amazon-s3-and-cloudfront#595]
Hey!!, 

I'm having the following problem:

SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data

I've follow all the instructions, but no solution so far, what could be?

**Comment by ianmjones** [comment]
See https://wordpress.org/support/topic/syntaxerror-json-parse-unexpected-non-whitespace-character-after-json-data-at/#post-15263517
