### ISSUE TITLE
Post Thumbnails don't work with custom sizes since 2.6.0 

### ISSUE THREAD

**Issue by mike-healy** [deliciousbrains/wp-amazon-s3-and-cloudfront#599]
**Describe the bug**
My theme registered a custom thumbnail size, and then uses it by calling `get_the_post_thumbnail()` in the template.
This produces img src urls linking to that thumbnail resolution. (e.g. `https://d3lelize76uef8.cloudfront.net/content/2019/08/V60-coffee-beasts-960x600.jpg`)

After updating to 2.6.0 that function returns a generic, uncropped image size which breaks the page layout.
(e.g. `https://d3lelize76uef8.cloudfront.net/content/2019/08/V60-coffee-beasts.jpg`)

**To Reproduce**
1. Register a custom thumbnail size, e.g. `add_image_size('hiresthumb', 960, 600, true);`
2. Render it from a template file `get_the_post_thumbnail(null, 'hiresthumb')`
3. With 2.5.5 you should see image URLs with that size modifier
4. Since 2.6.0 the base uncropped image URL is returned

**Expected behavior**
The -960x600.jpg type URL is expected instead of the original image URL
(The URL is correctly pointing to Cloudfront, it's the size that's incorrect).

**Diagnostic Info (from plugin's "Support" tab):**
[www.ultravulture.xyz-diagnostic-log-20220315060007.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/8250573/www.ultravulture.xyz-diagnostic-log-20220315060007.txt)

**Comment by jmerilainen** [comment]
Can confirm that image sizes doesn't work anymore. Using the AWS S3 as provider as well. Works alright with version 2.5.5.

If this helps: I did quick drilling and found out that eventually the method `$as3cf_item->path($size)` (where $size is for example 'hiresthumb') is called but the item's `$objects` is empty and therefore it returns the default path which is the original size.  

https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/2.6.0/classes/items/item.php#L906-L917

**Comment by ianmjones** [comment]
@mike-healy your "OME Metadata Version" is "3", which is incorrect even for v2.5.5 that is installed in the site's diagnostics you shared, it should be "8". And after upgrading to v2.6.0 a couple of upgrades should run that bring that up to "10".

Please check your site health and ensure cron is working properly.

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.

@jmerilainen what is the "OME Metadata Version" in your diagnostic info? (that's in the support tab)

**Comment by mike-healy** [comment]
Thanks @ianmjones 
I don't know what OME Metadata is. My site health looks good, no errors reported.
Cron jobs seem to work because my scheduled backups run as expected.  Is there some way to update OME Metadata beside having that happen automatically via cron?

**Comment by jmerilainen** [comment]
Hi @ianmjones, the OME Metadata Version is 10.

**Comment by jmerilainen** [comment]
Quick follow up before moving to WP support forum. 

I did some more digging and noticed that in the table `as3cf_items` the column `extra_info` is invalid in most cases. Some rows has the correct data with sizes included etc. but there are quite many with data being just `a:2:{s:7:"objects";a:0:{}s:14:"private_prefix";s:0:"";}`. So it seems that the update has run but not correctly. This has happened in multiple site where the plugin is in use.

**Comment by ianmjones** [comment]
@mike-healy please re-submit via Lite support, there's something up with your site that means the upgrades haven't run for a while.

@jmerilainen thanks for the extra info :wink:, but yes, please re-submit via Lite support so we can better dig into it.
