### ISSUE TITLE
WebP Image Format doesn't upload on AWS S3 bucket

### ISSUE THREAD

**Issue by Pramodranpariya** [deliciousbrains/wp-amazon-s3-and-cloudfront#603]
Hello,

WebP Image Format doesn't upload on AWS S3 bucket.
Please give us proper solution.

Thanks

**Comment by ianmjones** [comment]
WP Offload Media can offload WebP images already.

Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
