### ISSUE TITLE
Feature Request: Ability to set a file private or public in Google Storage

### ISSUE THREAD

**Issue by Nomafin** [deliciousbrains/wp-amazon-s3-and-cloudfront#604]
**Is your feature request related to a problem? Please describe.**
Would be great if it was possible to set a file to be public or private in Google Storage. A simple toggle switch in the attachment edit page would do it. That way we can set up a proxy script with authentication for the private files.

**Describe the solution you'd like**
A simple toggle switch in the attachment edit page to set a file public or private. Filters with attachment ID, mime type, etc. to be able to set the private/public status automatically based on some conditions.

**Describe alternatives you've considered**
At minimum we'd need filters/actions in suitable places of the code to be able to set the private/public status ourselves.

**Comment by ianmjones** [comment]
Hey @Nomafin, thanks for the feature request, but WP Offload Media (not Lite) already has this feature!

https://deliciousbrains.com/wp-offload-media/doc/how-to-restrict-access-to-offloaded-media/#media-actions
