### ISSUE TITLE
All the settings are configured for GCP bucket but offload to bucket is not happening

### ISSUE THREAD

**Issue by rekha-dyooti** [deliciousbrains/wp-amazon-s3-and-cloudfront#607]
Hi Team,

We are using this plugin in our Wordpress(V5.9.3) site. The integration is done and all success. But when I try to upload any image from admin panel, then the image is still storing in the application path but not in the cloud. 

There is no error shown while saving the settings or uploading an image. We have given relevant permissions to bucket too. Kindly help us to know where we have went wrong.

Thanks.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
