### ISSUE TITLE
Bug: Offload Media Lite - Website get blank after updating the plugin

### ISSUE THREAD

**Issue by IMaisela** [deliciousbrains/wp-amazon-s3-and-cloudfront#608]
**Describe the bug**

**To Reproduce**
1. Go to 'I went to the backend of the website.'
2. Click on 'plugins updated the 'Offload Media Lite' plugin'
3. Open the frontend after the updates are finished to.
4. See a half blank page, no content not loading

**Expected behavior**
I expected to see a full Home page of the website from the website but after updating the plugin, the page gets half blank.

**Screenshots**
![FinGlobal-Financial-Emigration-Transfer-Funds-From-South-Africa](https://user-images.githubusercontent.com/41296216/170004363-2978e77b-bef8-4a1f-a819-cad397d9bc59.png)

**debug.log**
Capturing errors to debug.log and attaching to this issue will help immensely!
[www.finglobal.com-diagnostic-log-20220524094724.txt](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/files/8761543/www.finglobal.com-diagnostic-log-20220524094724.txt)
https://deliciousbrains.com/why-use-wp-debug-log-wordpress-development/

**Diagnostic Info (from plugin's "Support" tab):**
Attach file to issue (preferred) or paste here.

**Additional context**

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
