### ISSUE TITLE
Bug: BuddyBoss Integration Appears to be Broken

### ISSUE THREAD

**Issue by Wasca** [deliciousbrains/wp-amazon-s3-and-cloudfront#610]
**Describe the bug**
As per your documentation on this page (https://deliciousbrains.com/wp-offload-media/doc/buddyboss-integration/) this plugin is meant to be integrated to work with BuddyBoss user Avatars.

`uploads/avatars/{USER ID}`

However in the latest version of BuddyBoss (v2.07) When creating a cropped avatar image the resultant image is not sent to the s3 bucket or referenced by the the custom domain setting (cname) when rendered to the webpage.

**To Reproduce**
1. In the front end User menu of BuddyBoss go to Profile => Profile Photo
2. Click on select your file, upload a new profile image.
3. Crop the image to size. 
4. Now check your S3 bucket for the new avatar image, you will notice it is not uploaded.

**Expected behavior**
I was expecting the cropped avatar image to be uploaded to the S3 Bucket and referenced by the CNAME domain setting.

**Screenshots**
<img width="491" alt="image" src="https://user-images.githubusercontent.com/869112/184585468-1c3ddef1-71eb-430b-871c-3057bf5d660f.png">

![image](https://user-images.githubusercontent.com/869112/184585545-0c09e263-c9fd-43fc-a97f-50446a6e96fd.png)

![Screen Shot 2022-08-15 at 4 29 55 pm](https://user-images.githubusercontent.com/869112/184587561-8496ac17-4ac8-4615-9b3b-7eb621a1a7ff.png)

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/869112/184586166-f29801f7-94d9-4242-926d-d2ceecc8315f.png">

**debug.log**
N/A

**Diagnostic Info (from plugin's "Support" tab):**
`site_url(): https://mydomain.com
home_url(): https://mydomain.com
Database Name: XXXX
Table Prefix: wp_
WordPress: 6.0.1
Web Server: nginx/1.22.0
PHP: 8.0.21
MySQL: 8.0.30
ext/mysqli: yes
PHP Memory Limit: 256M
WP Memory Limit: 256M
Memory Usage: 46 MB
Blocked External HTTP Requests: None
WP Locale: en_AU
Organize offloads by month/year: Disabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 256 MB
PHP Time Limit: 300
PHP Error Log: /var/log/php/php_fpm_errors.log
WP Cron: Enabled
fsockopen: Enabled
allow_url_fopen: Enabled
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
cURL: 7.68.0
Zlib Compression: Enabled
PHP GD: 2.3.3
Imagick: Enabled
Basic Auth: Enabled
Proxy: Disabled

Media Files: 561
Offloaded Media Files: 561
Not Offloaded Media Files: 0

Number of Image Sizes: 7

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)
post-thumbnail (none)

WP_CONTENT_DIR: /var/www/mydomain.com/wp-content
WP_CONTENT_URL: https://mydomain.com/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /var/www/mydomain.com/wp-content/plugins
WP_PLUGIN_URL: https://mydomain.com/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Defined
AS3CF_SETTINGS Keys: access-key-id, provider, secret-access-key

Local URL:
https://mydomain.com/wp‑content/uploads/photo.jpg
Offload URL:
https://cdn.mydomain.com/wp‑content/uploads/photo.jpg

OME Metadata Version: 12

Custom tables:
wp_as3cf_items: Ok

Storage Provider: Amazon S3
Use Server Roles: Off
Key File Path: N/A
Access Keys Set: Yes
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: XXXXXX
Region: ap-southeast-1
Block All Public Access: Enabled

Copy Files to Bucket: On
Enable Path: On
Custom Path: wp-content/uploads/
Use Year/Month: Off
Object Versioning: Off

Delivery Provider: Amazon CloudFront
Rewrite Media URLs: On
Enable Custom Domain (CNAME): On
Custom Domain (CNAME): cdn.mydomain.com

Force HTTPS: On

Remove Files From Server: Off

Active Theme Name: BuddyBoss Child
Active Theme Version: 1.0.0
Active Theme Folder: buddyboss-theme-child
Parent Theme Name: BuddyBoss Theme
Parent Theme Version: 2.0.7
Parent Theme Folder: buddyboss-theme

Active Plugins:
BuddyBoss App (v1.5.5.1) by BuddyBoss
BuddyBoss Platform (v2.0.7) by BuddyBoss
BuddyBoss Platform Pro (v2.1.0.2) by BuddyBoss
Code Syntax Block (v3.1.1) by Marcus Kazmierczak
Custom Post Type UI (v1.12.1) by WebDevStudios
Duplicate Page (v4.4.9) by mndpsingh287
Elementor (v3.7.0) by Elementor.com
Enable Media Replace (v3.6.3) by ShortPixel
Formidable Forms (v5.4.3) by Strategy11
Formidable Forms Pro (v5.4.3) by Strategy11
Formidable Locations (v2.02) by Strategy11
Formidable Visual Views (v5.3) by Strategy11
GDPR Cookie Consent (v2.1.2) by WebToffee
Groups (v2.16.2) by itthinx
Groups File Access (v2.1.0) by itthinx
Groups Restrict Categories (v2.4.0) by itthinx
Itthinx Updates (v1.4.0) by itthinx
JSM's Show User Metadata (v3.0.4) by JS Morisset
LearnDash HUB (v1.0.0) by LearnDash
LearnDash LMS (v4.3.0.2) by LearnDash
LearnDash LMS - Certificate Builder (v1.0.3) by LearnDash
LearnDash LMS - Course Grid (v2.0.6) by LearnDash
LearnDash LMS - Notifications (v1.5.3) by LearnDash
LearnDash LMS - ProPanel (v2.1.4.1) by LearnDash
LearnDash LMS - Stripe Integration (v1.9.3) by LearnDash
LearnDash Progress Reset (v2.0.0) by WooNinjas
Maintenance (v4.06) by WebFactory Ltd
Nginx Cache (v1.0.5) by Till Krüss
Optuma LearnDash (v1.0.0) by KiYoung
PDF viewer for Elementor (v2.9.3) by RedLettuce Plugins
PowerPack for LearnDash (v1.3.1) by HonorsWP
Redirection (v5.3.2) by John Godley
Redis Object Cache (v2.1.6) by Till Krüss
SEOPress (v5.8.0.5) by SEOPress
Safe SVG (v2.0.2) by 10up
Simple Revisions Delete by bweb (v1.5.1) by Brice CAPOBIANCO
TinyPNG - JPEG, PNG & WebP image compression (v3.4) by TinyPNG
Ultimate Addons for Gutenberg (v1.25.6) by Brainstorm Force
User Activity Tracking and Log (v3.3.17) by Moove Agency
User Activity Tracking and Log - Premium Features (v3.2.7) by Moove Agency
User Menus (v1.2.9) by Code Atlantic
User Switching (v1.7.0) by John Blackbourn & contributors
VdoCipher (v1.27) by VdoCipher
W3 Total Cache (v2.2.4) by BoldGrid
WP Add Mime Types (v3.0.3) by Kimiya Kitani
WP Offload Media Lite (v2.6.2) by Delicious Brains
WP Offload SES Lite (v1.4.6) by Delicious Brains
WP Rollback (v1.7.1) by impress.org
Widget Options (v3.8.5) by Widget Options Team
Woody code snippets (PHP snippets | Insert PHP) (v2.4.6) by Creative Motion, Will Bontrager Software, LLC 
Wordfence Security (v7.6.0) by Wordfence
wpDataTables - Tables & Table Charts (v2.1.37) by TMS-Plugins

Must-use Plugins:
BuddyBoss API Caching (v1.0.1) by BuddyBoss
Elementor Safe Mode (v1.0.0) by Elementor.com
LearnDash LMS Multisite (v1.0.0) by LearnDash

Drop-ins:
advanced-cache.php - advanced-cache.php
object-cache.php - Redis Object Cache Drop-In
`

**Additional context**
I'm using the BuddyBoss Version 2.0 Theme Styling

![image](https://user-images.githubusercontent.com/869112/184586793-a67a92d4-eed0-49a4-9ee4-3810e46a6d54.png)

**Comment by ianmjones** [comment]
WP Offload Media Lite does not support BuddyBoss, that integration is in WP Offload Media.

**Comment by Wasca** [comment]
@ianmjones I could have sworn the lite version used to handle this. Did it change recently?

**Comment by ianmjones** [comment]
Nope, BuddyBoss integration was introduced with WP Offload Media 2.6.

https://deliciousbrains.com/wp-offload-media/whats-new/#mar-09-2022

WP Offload Media Lite has never had integration with BuddyBoss.

https://wordpress.org/plugins/amazon-s3-and-cloudfront/#developers
