### ISSUE TITLE
Problem with uploading cropped images to the Amazon server

### ISSUE THREAD

**Issue by jesders** [deliciousbrains/wp-amazon-s3-and-cloudfront#611]
When our client uploaded an image that they cropped in photoshop, and reuploaded, the image says it is the correct dimensions, but it is not. If you put the url directly to the s3 link it provides the uncropped version. However, wordpress says otherwise. Also, if you go into crop the image the size seems to be correct.

I have also noticed that when trying to crop the image, the thumbnail image is broken and you can’t actually crop the image. It fails. When you try to upload the image to a post, and refresh the page after updating, the image also appears broken.

Note that we do have the current version of the plugin as well and wordpress is on 6.0.0 currently. Happy to provide any other details as well.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
