### ISSUE TITLE
Editing the upload path for this plugin

### ISSUE THREAD

**Issue by lvollmer** [deliciousbrains/wp-amazon-s3-and-cloudfront#62]
It looks like by default, this plugin uploads images to objectpath: (user defined)wp-content/uploads/YYYY/MM.

The YYYY/MM is hardcoded into the settings of the plugin:
https://www.dropbox.com/s/m3ug7sshyjwkepr/Screenshot%202014-05-12%2014.13.30.png

Wouldn't it make sense to remove the YYYY/MM so that plugins that create directories within the uploads directory can also have images sent to s3? IE: NextGEN gallery

**Comment by A5hleyRich** [comment]
Paths are already customisable. Supporting NextGen requires a lot more work than removing the YYYY/MM prefix.

We do have a compatibility addon planned for NextGen, but no ETA just yet.
