### ISSUE TITLE
Bug: Plugin not deleting files from server after s3 bucket upload

### ISSUE THREAD

**Issue by khushboog-WAL** [deliciousbrains/wp-amazon-s3-and-cloudfront#620]
Hi team, we have free version of this plugin and we have enable the setting "Remove Local Media" but when we are uploading any media then it is getting upload on s3 bucket but after that it is not deleted from server...please let us know why???

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
