### ISSUE TITLE
Uncaught Error: Class 'AS3CF_Utils' not found in classes/pro/as3cf-pro-plugin-installer.php:136

### ISSUE THREAD

**Issue by Tsandberg97** [deliciousbrains/wp-amazon-s3-and-cloudfront#622]
**Describe the bug**
Downloaded 3.10.0 to install in our new WP staging site. Receive this error when I try to Activate:
An error of type E_ERROR was caused in line 136 of the file /var/www/html/galendata/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/pro/as3cf-pro-plugin-installer.php. Error message: Uncaught Error: Class 'AS3CF_Utils' not found in /var/www/html/galendata/wp-content/plugins/amazon-s3-and-cloudfront-pro/classes/pro/as3cf-pro-plugin-installer.php:136 Stack trace: #0 /var/www/html/galendata/wp-includes/class-wp-hook.php(308): AS3CF_Pro_Plugin_Installer->maybe_install_plugins('') #1 /var/www/html/galendata/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #2 /var/www/html/galendata/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /var/www/html/galendata/wp-admin/admin.php(175): do_action('admin_init') #4 /var/www/html/galendata/wp-admin/index.php(10): require_once('/var/www/html/g...') #5 {main} thrown

**Comment by ianmjones** [comment]
@Tsandberg97 looks like you have an issue with your zip file, or how you uploaded it to your site.

Please re-download from My Account and try again.

If you continue to have issues please contact support via the "Support" tab for your license in [My Account](https://deliciousbrains.com/my-account/licenses/).

**Comment by alexdlaird** [comment]
I'm experiencing the same issue on my installation. Worked fine for about a week, then started receiving this error. As suggested, downloaded the latest version again and re-installed it twice. The moment I activated it both times, this error is being thrown again and the site goes down.

**Comment by ianmjones** [comment]
@alexdlaird If you haven't already, please contact WP Offload Media Support via the plugin's "Support" tab, or via the support email address you see when viewing your license in our site's "My Account" page.

**Comment by atnjqt** [comment]
In my case, I was missing some PHP dependencies that weren't entirely obvious, such as php-xml and php-curl.

```bash
sudo apt-get install php-xml php-curl
```
