### ISSUE TITLE
Bug: Wipe/Reset the setting

### ISSUE THREAD

**Issue by alexlii1971** [deliciousbrains/wp-amazon-s3-and-cloudfront#623]
Hello,

I used these two plugin to optimize database:
https://wordpress.org/plugins/wp-sweep/
https://wordpress.org/plugins/wp-optimize/

After optimizing, it show:

WP Offload Media Lite:
Missing Table — One or more required database tables are missing, please check the Diagnostic Info in the Support tab for details. [More info

Here is a screenshot:
https://prnt.sc/J3s-76wjntPG

So, maybe some related database was removed?
I am trying to reset the WP Offload Media Lite, but I did not find a button to trigger reset.

So, is there any way to Wipe/Reset the setting, please?

**Comment by ianmjones** [comment]
We have an uninstall doc that details all the settings and data that can be manually removed.

https://deliciousbrains.com/wp-offload-media/doc/uninstall/
