### ISSUE TITLE
Bug: Buddyboss Video Offloaded To Amazon S3 Will Not Play In Chrome - Works In Firefox Perfectly

### ISSUE THREAD

**Issue by grpetz** [deliciousbrains/wp-amazon-s3-and-cloudfront#631]
**Describe the bug**
After uploading the video in Buddyboss it will not play unless you use ctrl + shift + r  to force refresh the Chrome browser to ignore cache.

**To Reproduce**
1. Upload video
2. Try to play video after uploading
3. Only plays in Chrome after using ctrl + shift + r

**Expected behavior**
Video should play right away as expected.

**Screenshots**
See screenshot here https://prnt.sc/uAyPFvjTIFFf

**Additional context**
I am not a developer, just trying to figure this out. Is this a Buddyboss plugin issue or your plugin not working correctly? In the Chrome inspector I watched the network activity for the media as it attempts to load  the amazon s3 video and I noticed it says "cancelled" whenever it attempts to load the video off of Amazon. If I just refresh ctrl + r it will not work, until I use ctrl + shift + r

**Comment by ianmjones** [comment]
Unfortunately we are unable to help you as media related functionality in BuddyBoss is developed and supported by [BuddyBoss](https://www.buddyboss.com/).
