### ISSUE TITLE
Feature Request: Apply as3cf_object_meta filter to settings checks

### ISSUE THREAD

**Issue by ska-kialo** [deliciousbrains/wp-amazon-s3-and-cloudfront#632]
**Is your feature request related to a problem? Please describe.**
I have an S3 bucket which requires object uploads to specify server-side encryption. I managed to use the `as3cf_object_meta` filter to add the required parameter to the S3 request when uploading media which works as expected. However now the plugin settings show an error as the implementation of `AWS_Provider->can_write` does not use this filter and the upload used to check the writeability fails.

**Describe the solution you'd like**
Either one of:
1. Provider write/upload checks use the `as3cf_object_meta` filter to allow extending the arguments.
2. A separate filter is provided for extending the arguments used for the write/upload checks. 

**Describe alternatives you've considered**
Just accepting that there's an error on the settings page. Not ideal as it may raise concerns and also hides any actual issues.

**Comment by ianmjones** [comment]
This was addressed in v3.2.7.

Thanks for the feature request.
