### ISSUE TITLE
Bug: The difference between the request time and the current time is too large.

### ISSUE THREAD

**Issue by bstarr322** [deliciousbrains/wp-amazon-s3-and-cloudfront#634]
### Describe the bug
- We got this message in the plugin admin page.
`There was an error attempting to check the permissions of the bucket whotels-prod: The difference between the request time and the current time is too large.
`
- Because of this timezone issue, this plugin doesn't fetch the bucket connected now.
- And it doesn't letting us to upload the medias to S3 Bucket.

### Expected behavior
- We should not see this error message and media upload to S3 bucket should work as expected.

### Screenshots
![image](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/assets/15979250/92a0217a-5364-4107-9466-7fcb6a535f80)

### Additional context
- Currently the site is running on AWS EC2 Instance, it's region is us-east-1 (N. Virginia), Estern Timezone.
- S3 Bucket connected is based on the region - us-west-1 (Losangles), Western Timezone.
- But this connection did work until last June.

**Comment by ianmjones** [comment]
Please only create issues for bug reports or feature requests on this repo.

For support, please raise a request at https://wordpress.org/support/plugin/amazon-s3-and-cloudfront or if you have a WP Offload Media license please use the "Support" tab in the plugin.
