### ISSUE TITLE
Feature Request: A lot of errors like [AS3CF: Could not get Block All Public Access status: Error executing "GetPublicAccessBlock"] are logged.

### ISSUE THREAD

**Issue by mt8** [deliciousbrains/wp-amazon-s3-and-cloudfront#635]
**Is your feature request related to a problem? Please describe.**

I am offloading images to S3. The entire bucket is made "private" and direct access is prohibited. 
All images are assumed to be delivered from CloudFront.

In such a case, the below error will keep getting logged in the server's PHP log.

```
[31-Oct-2023 11:50:21 UTC] AS3CF: Could not get Block All Public Access status: Error executing "GetPublicAccessBlock" on "https://example.s3.ap-northeast-1.amazonaws.com/?publicAccessBlock"; AWS HTTP error: Client error: `GET https://example.s3.ap-northeast-1.amazonaws.com/?publicAccessBlock` resulted in a `403 Forbidden` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>XXXXXX (truncated...)
</Error>
```

**Describe the solution you'd like**
Is it possible to stop this warning error when delivering images from CloudFront?

**Describe alternatives you've considered**
Nothing

**Additional context**

The relevant code seems to be around here.
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/blob/a39fe91633a2bd424a53daab2ae9841534424401/classes/providers/storage/aws-provider.php#L498-L509

**Comment by mt8** [comment]
@ianmjones Hi,
Could you please review this pull request?
https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/pull/636

**Comment by ianmjones** [comment]
Sounds like you're using a custom IAM policy and haven't added the required `GetBucketPublicAccessBlock` and `GetBucketOwnershipControls` actions.

https://deliciousbrains.com/wp-offload-media/doc/custom-iam-policy-for-amazon-s3/#bucket-restrictions

If you have any further support requests, please post them here: https://wordpress.org/support/plugin/amazon-s3-and-cloudfront/

**Comment by mt8** [comment]
@ianmjones 

Thanks for you reply

> Sounds like you're using a custom IAM policy and haven't added the required GetBucketPublicAccessBlock and GetBucketOwnershipControls actions.

Yes, that's right.

But, There's a reason for that, I offload media to S3 and only deliver from Cloudfront.
Distribution from S3 domains is prohibited by policy.
In such cases, CloudWatch Logs will be filled with this error log.

**Comment by ianmjones** [comment]
> Yes, that's right.
> 
> But, There's a reason for that, I offload media to S3 and only deliver from Cloudfront. Distribution from S3 domains is prohibited by policy. In such cases, CloudWatch Logs will be filled with this error log.

That shouldn't stop your user from being able to check the status of Block All Public Access. It's also super important to WP Offload Media that it knows whether Block All Public Access is set or not so that it correctly handles ACLs, or rather does not use them if they are not relevant.

**Comment by harai** [comment]
Allowing unnecessary API call is against Principle of Least Privilege which AWS recommends.  In this case, calling GetPublicAccessBlock is not a requirement since user knows the result.  There should be a filter that bypasses the unnecessary check.
