### ISSUE TITLE
Feature Request: Session tokens

### ISSUE THREAD

**Issue by furai** [deliciousbrains/wp-amazon-s3-and-cloudfront#639]
Hello,

The programmatic access we've got from our company requires us to use session tokens. Without them it's not possible to connect to s3 buckets.

So I'd love to request session tokens support for authentication.

I've checked docs and plugin's code and I haven't seen anything about session token based authentication.

Cheers,
Furai

**Comment by ianmjones** [comment]
@furai is your site hosted on an EC2 instance?

Do you use federated users?

**Comment by ianmjones** [comment]
No response, closing.

**Comment by furai** [comment]
Didn't notice first reply, got lost somewhere. 

It's mostly for when I'm developing locally. We're getting from our company access keys: key, secret and token. Credentials gets refreshed every 12h or so and currently plugin doesn't support authenticating with tokens. Just with key and secret.

**Comment by ianmjones** [comment]
Ah, that's interesting you're needing it for local dev.

I'll add this back on to the todo list then.

There's been quite a few changes in recent years in what's available in AWS/S3/CloudFront and the SDK for doing authentication etc, we need to do a round of updates to add some capabilities for sure.

Thanks for the feature request.
