### ISSUE TITLE
Bug: Error Getting Buckets — Error executing "ListBuckets" on "https://s3.amazonaws.com/"; AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3.amazonaws.com/

### ISSUE THREAD

**Issue by Ryan-Kevin** [deliciousbrains/wp-amazon-s3-and-cloudfront#640]
Error Getting Buckets — Error executing "ListBuckets" on "https://s3.amazonaws.com/"; AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3.amazonaws.com/

**Comment by ncdfilho** [comment]
Same error here. And it's not only this. Even if I add my aws credentials through database, it does not connect to aws. My IAM has full access to my bycket, but the plugin can't connect

**Comment by ianmjones** [comment]
Please post support requests to https://wordpress.org/support/plugin/amazon-s3-and-cloudfront/, or if you have a WP Offload Media license, please submit a support request via the Support tab in the plugin.
