### ISSUE TITLE
Bug: Unreasonably high resource usage when WP Offload Media Lite is enabled.

### ISSUE THREAD

**Issue by NerdvanaNC** [deliciousbrains/wp-amazon-s3-and-cloudfront#644]
**Describe the bug**
When enabled, this plugin makes an inordinately high number of DB queries and increases the server's RAM usage.

Using Query Monitor, I observed 556 DB Queries (from which many are duplicate) and upto 14 MB RAM added with WP Offload Media Lite enabled.

Even on pages where there are NO OFFLOADED MEDIA ITEMS, I am seeing about 200 DB queries and 5-6 MB of extra RAM used.

If the URL to the media item is re-written upon its transfer to the S3 bucket, what's the use for so many queries?

_How I tested these findings:_

1. 2 Different Pages.
    One with offloaded media, and one with locally stored (default) media.
2. Activated/Deactivated Plugin.
    I activated and deactivated the WP Offload Media plugin each time.
3. 10 Times.
    Each of the 2 different page types were loaded 5 times with the plugin enabled, and 5 times with the plugin disabled; this makes a total of 10 page loads.

**To Reproduce**
1. Enable the plugin.
2. Use Query Monitor to observe resource usage.
3. Disabling the plugin fixes the issue.

**Expected behavior**
A few extra queries and _some_ extra RAM usage might be expected from a plugin, but I wouldn't expect ANY extra resource usage on front-end page loads due to this plugin (because the image's URL is re-written to be served from Amazon S3).

**Screenshots**
_Plugin DISABLED_
![image](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/assets/13850325/4cbb446c-f143-4818-9759-08be95f365be)

_Plugin ENABLED_
![image](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/assets/13850325/75b524b4-1e72-4d89-ac2a-62dc037a08fb)

**debug.log**
N/A

https://deliciousbrains.com/why-use-wp-debug-log-wordpress-development/

**Additional context**
I have also created a support request on the free plugin's Wordpress.org page, but since that is not for reporting bugs per se, I have created an issue here as well.

**Comment by ianmjones** [comment]
This is being handled as a support request here: https://wordpress.org/support/topic/556-db-queries-14-mb-ram-added-when-plugin-is-enabled/
