### ISSUE TITLE
When I enable the block public access setting for the bucket, I can see all images on the WordPress site. However, when I disable the block public access setting, I am unable to see the images in WordPress. My requirement is to keep the bucket private and still have the images available in WordPress. What should I do to achieve this?

### ISSUE THREAD

**Issue by saraswathirs** [deliciousbrains/wp-amazon-s3-and-cloudfront#646]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**debug.log**
Capturing errors to debug.log and attaching to this issue will help immensely!

https://deliciousbrains.com/why-use-wp-debug-log-wordpress-development/

**Diagnostic Info (from plugin's "Support" tab):**
Attach file to issue (preferred) or paste here.

**Additional context**

**Comment by ianmjones** [comment]
Please ask your support question in the Lite plugin's support forum: https://wordpress.org/support/plugin/amazon-s3-and-cloudfront/

If you have a license for WP Offload Media, please ask your question via the Support tab of the plugin and our support staff will help you with your issue.
