### ISSUE TITLE
Uploads' Size Not Logging

### ISSUE THREAD

**Issue by sicknickel** [deliciousbrains/wp-amazon-s3-and-cloudfront#65]
Hello,

The files stored on Amazon S3 report 0 kb taken up within the media library.

This is not good, as I have a limit to the amount a user can upload; however, if it's not tracking the file sizes - users can upload unlimited amounts.

Is there a way to log file sizes?

**Comment by A5hleyRich** [comment]
Bug resolved in version 0.9.7.
