### ISSUE TITLE
Image upload succeeds, but full S3 URL is missing

### ISSUE THREAD

**Issue by virtualandy** [deliciousbrains/wp-amazon-s3-and-cloudfront#69]
Uploaded an image into WordPress, it sync'd to the S3 folder I defined in this plugins' settings. Awesome!

But when I load the page, the link to the image is something like ```http://s3_bucket/blog/uploads/9/14/...``` where 's3_bucket' is literally just the bucket name and not bucket_name.s3.amazonaws.com. 

Any ideas? Probably something stupid I forgot to configure. Thanks!

**Comment by A5hleyRich** [comment]
The virtual host option isn't very useful to be completely honest, but it was implemented prior to us taking over the plugin, hence why it's there.

In a future version that option will be removed in favour of using a custom domain.
