### ISSUE TITLE
Ability to for other plugins to upload files using AS3CF functions

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/wp-amazon-s3-and-cloudfront#94]
Ability to upload _any_ files by calling plugin methods in external code. Then other plugins can be written to extend the functionality of this one and add support for other file uploads, like BuddyPress avatars described in #39.

**Comment by quinngoldwin** [comment]
please add this feature! I havent found a solution to host avatars or profile photos on buddypress on amazon s3. 

This is huge because most of these managed wordpress hosting companies like wp-engine, pagely, and flywheel have restrictions on diskspace once they started providing SSD storage.

**Comment by A5hleyRich** [comment]
BuddyPress and bbPress compatibility are planned for a future release. No ETA just yet.

**Comment by aaemnnosttv** [comment]
Closing this as the issue has moved to the main repo.
